### ISSUE TITLE
Could you provide screenshots or a video in the README?

### ISSUE THREAD

**Issue by Dima-369** [manateelazycat/lsp-bridge#1]
> Provide modern UI: we use Qt technology build completion UI, to provide fantastic icon, both-end text alignment, web document preview, etc.

This sounds quite interesting!

In my environment I am apparently unable to test this out myself, but I would love to see some visual demonstration :)

**Comment by manateelazycat** [comment]
still in work process. ;)

**Comment by manateelazycat** [comment]
@Dima-369 You can use lsp-bridge now.
