### ISSUE TITLE
[Feature-Request]/Question: Tree-like view of symbols from lsp-bridge

### ISSUE THREAD

**Issue by krshrimali** [manateelazycat/lsp-bridge#1012]
Hi!

Thank you for your work with lsp-bridge. Really appreciate the contribution.

I've been using `lsp-treemacs-symbols` for some time: https://github.com/emacs-lsp/lsp-treemacs, and it gives a very useful feature: `lsp-treemacs-symbols` which helps navigate through symbols in the current buffer.

Please see the gif here from lsp-treemacs README: https://raw.githubusercontent.com/emacs-lsp/lsp-treemacs/master/screenshots/symbols-list.gif.

From what I understand (please correct me if I'm wrong), `lsp-treemacs` does not support `lsp-bridge` right now. Is there a plan to either integrate lsp-bridge into lsp-treemacs (probably worth creating an issue there in that case) _or_ have an inhouse feature for something similar to this in lsp-bridge?

Thanks!

**Comment by manateelazycat** [comment]
Sorry， I'm not treeemacs user, no plan to do this.

Any PR are welcome, I like to merge it.

**Comment by krshrimali** [comment]
> Sorry， I'm not treeemacs user, no plan to do this.
> 
> Any PR are welcome, I like to merge it.

I'll try to take a look at the code-base and see if I can get a similar feature in. Just to understand, there's no alternate way to get a symbols outline view with lsp-bridge in the current state, right? Want to make sure that I'm not duplicating any efforts.

Thanks!

**Comment by manateelazycat** [comment]
lsp-bridge-workspace-list-symbols
