### ISSUE TITLE
vscode-html-language-server日志返回candidates为0

### ISSUE THREAD

**Issue by SpiritHolly** [manateelazycat/lsp-bridge#1013]
vscode-html-language-server日志返回candidates为0
![image](https://github.com/user-attachments/assets/1f26ca5d-3d6b-4bbe-b0d0-709341a8385a)
任意html文件

**Comment by manateelazycat** [comment]
![截图 2024-08-10 10-41-12](https://github.com/user-attachments/assets/a04d2214-e9e0-436b-a0b3-17b40155dfc7)

我刚刚测试了， 是可以补全的。

**Comment by SpiritHolly** [comment]
会不会和node版本啥有关系node18,node20都不行，我切换node16，一直卡住
<img width="666" alt="image" src="https://github.com/user-attachments/assets/73fdd65d-9dea-4fe2-a829-fc8ebb142805">
<img width="998" alt="image" src="https://github.com/user-attachments/assets/094943b6-80b8-458a-8265-26e6a5ee0637">

**Comment by manateelazycat** [comment]
能给一个完整的日志吗？最好是开启 log 选项后的日志

**Comment by SpiritHolly** [comment]
iShot_2024-08-11_09.57.35.mp4

**Comment by manateelazycat** [comment]
能把日志做为附件给一下吗？ 日志在视频里面我无法看清楚

**Comment by SpiritHolly** [comment]
[lsp-bridge-log.txt](https://github.com/user-attachments/files/16571353/lsp-bridge-log.txt)

**Comment by manateelazycat** [comment]
我看了日志， 你的 LSP Server 没问题。

1. 确保选项是关闭的： (setq lsp-bridge-enable-log nil) 这个选项会影响性能
2. html补全一般是跟在 < 后面的，我刚刚又测试一遍没问题， 我的 node 版本是 v22.6.0
3. 测试之前， 用 emacs -Q 只加载 lsp-bridge 来测试， 避免其他插件影响 lsp-bridge

**Comment by SpiritHolly** [comment]
好的，谢谢，已解决， 之前这个关了也不行，现在(setq lsp-bridge-enable-log nil) 这个关了就好了
