### ISSUE TITLE
diagnostic功能无法显示整个project的异常

### ISSUE THREAD

**Issue by DanielLiuCD** [manateelazycat/lsp-bridge#1014]
我已经使用lsp-bridge进行flutter项目的开发两周了，期间一切都很流畅，但最近有个问题非常困扰我。
我调整了项目的目录结构，导致dart的import语句大量报错。但由于没法显示整个项目的全部异常，之能通过
编译运行才能发现一些较深路径下的import错误，这个过程非常地耗费时间。希望能够加入显示全项目异常的功能。

**Comment by manateelazycat** [comment]
能给一下测试代码吗？

**Comment by DanielLiuCD** [comment]
> 能给一下测试代码吗？

这是测试代码，我将里面的res和routes目录移动到新的x目录下了，里面所有导入的这两个目录的地方均在报错。在我们的真实
项目中有几百个import报错。
[social_flutter_app.zip](https://github.com/user-attachments/files/16567937/social_flutter_app.zip)

**Comment by manateelazycat** [comment]
LSP 3.17 协议的 [Workspace Diagnostics](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_diagnostic) 应该是想要找的功能， 我晚上也推送了一个补丁 

https://github.com/manateelazycat/lsp-bridge/commit/ccf6d1fbe9e1fbd19451b98f626b094051f4a6f4

当我用 lsp-bridge-workspace-diagnostic-list 命令来测试的时候， 我发现 Dart 的LSP Server还不支持 3.17 这个特性。

如果哪天 Dart 支持这个特性以后， lsp-bridge 很容易实现你想要的功能。
