### ISSUE TITLE
在启用auto-insert-mode之后，在打开新.sh文件时会出错

### ISSUE THREAD

**Issue by ipyffor** [manateelazycat/lsp-bridge#1016]
emacs 29.2

步骤：
emacs -q -l .emacs.d/mini-init.el
M-x find-file test.sh
![image](https://github.com/user-attachments/assets/52d8ba3d-e759-4b46-9a01-71e3902622ac)
配置：
链接: https://pan.baidu.com/s/1jc7D6lFKRY-6vQvJqEmG9A?pwd=zdyg 提取码: zdyg 
--来自百度网盘超级会员v6的分享

**Comment by manateelazycat** [comment]
不用auto-insert-mode，欢迎pr
