### ISSUE TITLE
auto-completed content comes to end of the line

### ISSUE THREAD

**Issue by yjloong** [manateelazycat/lsp-bridge#1022]
What I want is 'X[start]'. But it gives me 'X[st]art'.
I think the reason is that ']' is also completed automatically and the latency of lsp-bridge.
'()' also will produce the case.

acm-terminal in terminal.
GNU Emacs 29.3. 
lsp-bridge was pulled down 2 months ago.

**Comment by manateelazycat** [comment]
Can you give me test code?

**Comment by yjloong** [comment]
[emacs.d-master.zip](https://github.com/user-attachments/files/16694899/emacs.d-master.zip)

uname -a:
Linux OwO 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

The zip contains all my configuration. I only use cmd 'emacsclient -a "" -t -s uuid' to open emacs in terminal and no gui.

**Comment by yjloong** [comment]
And sometimes it will be act like this picture if I type too quick.
![image](https://github.com/user-attachments/assets/87e32d30-b753-46ed-b589-03ca493601a3)

**Comment by yjloong** [comment]
![image](https://github.com/user-attachments/assets/ada5f33a-e693-40eb-9954-9550ad78f9b8)

type too quick...

**Comment by yjloong** [comment]
When I typing 'rightness' at beginning...
![image](https://github.com/user-attachments/assets/567911f8-dc85-4277-98b2-680fa71333d2)

**Comment by manateelazycat** [comment]
You should send issue to acm-terminal

**Comment by manateelazycat** [comment]
Please compile emacs with tty-child-frames branch, this issue will fix.
