### ISSUE TITLE
本地文件跳转报错： Forbidden reentrant call of Tramp

### ISSUE THREAD

**Issue by getong** [manateelazycat/lsp-bridge#1024]
```
--- [14:44:26.951521] Record diagnostics from 'rust-analyzer' for file filename.rs
ERROR:epc:ReturnError([Symbol('remote-file-error'), 'Forbidden reentrant call of Tramp'])
```
是本地文件，不是远程文件。
而且是第一次使用lsp-bridge-find-ref命令跳转才会出现，第二次就可以正常跳转了。

**Comment by manateelazycat** [comment]
这个看起来和 tramp 相关啊。

**Comment by getong** [comment]
我本地打开了文件，远程sshx tramp也打开了文件，会不会这两部分文件记录混用在一起了呢？

**Comment by manateelazycat** [comment]
> 我本地打开了文件，远程sshx tramp也打开了文件，这两部分文件项目是相同的，会不会这两部分文件记录混用在一起了呢？

不晓得哇， 我很少用 tramp, 可以 git blame 看看是哪位代码提交的补丁， 可以@他讨论一下。
