### ISSUE TITLE
在补全rust的时候，回车选中候选词后，当前行会自动跳成第一行

### ISSUE THREAD

**Issue by C-Entropy** [manateelazycat/lsp-bridge#1029]
在补全rust的时候，在回车选中候选词后，当前行会自动跳成第一行。

比如，一开始是这样

![2](https://github.com/user-attachments/assets/3d77260f-fba0-4b62-be50-691a62466274)

在回车选中补全后成了这样子

![1](https://github.com/user-attachments/assets/33773fe0-9b10-4738-a0d3-c00c01610ec0)

3在.el文件中补全则不会出现这种情况。

我希望在回车后文档不会上移，请问这个要怎么处理呢？

https://github.com/user-attachments/assets/fd42a0b3-8fcc-4817-92f1-e465fb8bd1ca

**Comment by smallzhan** [comment]
@C-Entropy  试试把 https://github.com/manateelazycat/lsp-bridge/blob/0c02dc44f9bdf86f93ee3a5fbe624bf5a556b807/lsp-bridge-inlay-hint.el#L93 注释掉。或者关掉 inlay-hint

**Comment by manateelazycat** [comment]
下面是修复逻辑：
1. 因为 window-start 这个函数有bug， 如果在 window-start 之前不调用 redisplay ， window-start 就不会返回窗口起始位置
2. 但是调用 redisplay 又会有其他奇奇怪怪的问题， 比如当前这个issue

好的是 window-end 的函数没有这个影响， 所以这个补丁的修复方法是：
1. 直接去掉 redisplay ， 避免这些奇奇怪怪的问题
2. 给 LSP Server 发送 inlay hint 请求的时候直接请求 point-min/point-max, 这样永远都不会出错
3. 因为 lsp-bridge-inlay-hint-cache 先天就做了缓存对比的， 所以 point-min/point-max 发送也不会导致重复的 inlay 来闪动屏幕
