### ISSUE TITLE
连续快速输入，最新一次补全结果还没有更新 capf 的时候，选中的补全结果还是之前旧的内容

### ISSUE THREAD

**Issue by jadestrong** [manateelazycat/lsp-bridge#103]
1. 连续输入触发请求，得到服务器响应结果，执行 lsp-bridge-record-completion-items 后，去触发 corfu 补全接着执行 lsp-bridge-capf ；
2. 存在一种情况是，当最近的一次输入得到了服务器最新的响应结果，但是 lsp-bridge-capf 还没执行，这时候里面的 candidates 还是旧的，而这时侯选中并补全的内容就是旧的了
这种情况下，因为有了新的输入内容，用旧的补全就有可能出现非预期的结果
![image](https://user-images.githubusercontent.com/18475217/168987708-bfbdbbac-bd2b-4857-b1a9-6bbf95cba67c.png)
比如这个图中，最新返回的 insertText 已经是 name 了，但是因为 lsp-bridge-capf 还没执行，所以最终拿到的那个 item 的 insertText 还是 this.name ，所以最后出现了 this.this.name 的情况

**Comment by manateelazycat** [comment]
已经修复了，感谢反馈
