### ISSUE TITLE
Manually close LSP

### ISSUE THREAD

**Issue by wokring** [manateelazycat/lsp-bridge#1030]
Is it possible to manually shutdown the LSP?

**Comment by manateelazycat** [comment]
Maybe you need lsp-bridge-complete-manually and lsp-bridge-popup-complete-menu?

**Comment by wokring** [comment]
Was thinking if there was a function similar to `lsp-bridge-restart-process` but just stopping the process rather than restarting.

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/lsp-bridge/commit/8d0e32effab5a4fee2c7d76886cd4a62bad96449
