### ISSUE TITLE
Duplicate inlay hints after executing command revert-buffer-quick or revert-buffer.

### ISSUE THREAD

**Issue by biplabswain** [manateelazycat/lsp-bridge#1031]
Hi,

I've been using lsp-bridge for the past couple of days and so far I'am very happy with it. I stumbled upon an issue wherein duplicate inlay hints are displayed whenever the command revert-buffer-quick or revert-buffer is executed. Every time I execute the said command, new inlay hints are displayed alongside previously displayed hints. I'm attaching the screencast of the problem. The screencast shows the issue in a C project(the Linux kernel source in this case). I was able to reproduce the issue in a Java project as well.

I'm using Emacs 29.4 running on Fedora Linux 40 (Workstation Edition). Linux 6.10.6-200.fc40.x86_64. lsp-bridge version - pulled as of today

Thank you.

https://github.com/user-attachments/assets/fba02d58-0fba-4e09-8487-22214c2b565d

**Comment by manateelazycat** [comment]
I just push https://github.com/manateelazycat/lsp-bridge/commit/58da5923ec9251d617f2bda29dfa9484fa332ea7

Can you help test it ?

**Comment by biplabswain** [comment]
I've tested the fix and I am no longer able to reproduce the issue. This is great.

Thanks for the quick response.
