### ISSUE TITLE
Frame doesn't regain focus after using the lsp-bridge-code-action pop up menu.

### ISSUE THREAD

**Issue by biplabswain** [manateelazycat/lsp-bridge#1033]
Attached is the screencast of the issue. The frame doesn't respond to keyboard inputs after accepting any change suggested by the code action pop up menu. I can edit the buffer only after creating a new frame by using the menu bar.

I really like how the code action popup show what changes will be made.

Thank you.

https://github.com/user-attachments/assets/8b2b5f88-7d89-4d22-a704-1e4d76e68ad8

**Comment by manateelazycat** [comment]
please use emacs -Q test

**Comment by biplabswain** [comment]
Hi,

I did test with Emacs -Q before reporting the issue. To be exact, I used the following command to test
`emacs -Q -l /path/to/mardown-mode.el -l /path/to/yasnippet.el -l /path/to/my-lsp-bridge.el
`

I was setting some variables specific to lsp-bridge and acm in my-lsp-bridge.el so I removed those and now its content is as follows:

```
(add-to-list 'load-path (expand-file-name "~/lsp-bridge"))
(use-package lsp-bridge
  :config
  (global-lsp-bridge-mode))
```

I'm still able to reproduce the issue with the above configuration.

Thank you.

**Comment by manateelazycat** [comment]
Sorry, I can't reproduce your problem

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/0983d5300cd82f9d49dce23718a581db8219ed44

Has fixed

**Comment by biplabswain** [comment]
Hi,

From commit  [54d7bd0](https://github.com/manateelazycat/lsp-bridge/commit/54d7bd0d871bd7dd12fac6e48e193a5e506ef447 ) onwards executing lsp-bridge-code-action didn't provide any popup menu at all. It did start working from the commit you've mentioned above. However, the original issue is still always reproducible, i.e., the frame doesn't repond to any keyboard input after selecting any option from the popup menu lsp-bridge-code-action provides. If I set lsp-bridge-code-action-enable-popup-menu to nil, then I can use the code action from the minibuffer without any issue.

Thank you.
