### ISSUE TITLE
lsp-bridge-code-action 不能去掉多余的import

### ISSUE THREAD

**Issue by kapmix** [manateelazycat/lsp-bridge#1034]
lsp-bridge日志：

Eval in Emacs: (lsp-bridge-diagnostic--render '"/Users/kuga/work/Repo/GITRepo/src/bmtapi/app/main.py" '"" '((:range (:start (:line 9 :character 7) :end (:line 9 :character 14)) :message "`pymysql` imported but unused" :severity 2 :code "F401" :codeDescription (:href "https://docs.astral.sh/ruff/rules/unused-import") :source "Ruff" :tags (1) :data (:fix (:applicability "safe" :edits ((:content "" :end_location (:column 0 :row 11) :location (:column 0 :row 10))) :message "Remove unused import: `pymysql`") :noqa_row 10 :cell ()) :server-name "ruff") (:range (:start (:line 10 :character 17) :end (:line 10 :character 19)) :message "`pandas` imported but unused" :severity 2 :code "F401" :codeDescription (:href "https://docs.astral.sh/ruff/rules/unused-import") :source "Ruff" :tags (1) :data (:fix (:applicability "safe" :edits ((:content "" :end_location (:column 0 :row 12) :location (:column 0 :row 11))) :message "Remove unused import: `pandas`") :noqa_row 11 :cell ()) :server-name "ruff")) '2)
python代码：

import logging

from fastapi import FastAPI, Request
from fastapi.logger import logger
from fastapi.responses import HTMLResponse, ORJSONResponse, RedirectResponse
from fastapi.exceptions import HTTPException

from app.api import api

import pymysql
import pandas as pd

经测试：

commit 58da5923ec9251d617f2bda29dfa9484fa332ea7 code action能用。

commit 54d7bd0d871bd7dd12fac6e48e193a5e506ef447 开始code action不能用。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/0983d5300cd82f9d49dce23718a581db8219ed44

不好意思， 已经修复了， 感谢反馈。
