### ISSUE TITLE
Cannot be used along with Helm's `display-buffer-in-own-frame` feature

### ISSUE THREAD

**Issue by hexclover** [manateelazycat/lsp-bridge#1035]
I use Emacs 29.4 (PGTK variant) under Plasma Wayland on NixOS (will try to reproduce on other distros when I have time). When I load both Helm and lsp-bridge, Helm's `helm-display-buffer-in-own-frame` (which pops up a new frame to ask for completion) cannot work, but produces an error: `Wrong type argument: window-live-p, nil`:

![image](https://github.com/user-attachments/assets/883827cf-8d63-4883-9540-7041021bc031)

This is the normal behavior (can be reproduced by not loading `lsp-bridge` in the attached `init.el`):

![image](https://github.com/user-attachments/assets/86763678-c0a4-415c-b9c3-31dbff563b2c)

`flake.nix`:

```nix
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  };

  outputs =
    { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in
    { 
      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [
          ((emacsPackagesFor emacs29-pgtk).emacsWithPackages (epkgs: with epkgs; [ helm lsp-bridge ]))

        ];
      };
    };
}
```

`init.el`:

```elisp
(package-initialize)

(use-package helm
  :ensure t
  :bind (("M-x" . helm-M-x))
  :custom
  (helm-mode t)
  :config
  (setq helm-display-function 'helm-display-buffer-in-own-frame))

(use-package lsp-bridge)
```

**Comment by manateelazycat** [comment]
I don't use helm, can't help you.
