### ISSUE TITLE
在rust中use新的crate后，需要重启lsp-bridge才可以正常使用新包的内容

### ISSUE THREAD

**Issue by C-Entropy** [manateelazycat/lsp-bridge#1039]
如题，在rust中use新的crate后，需要重启lsp-bridge才可以正常使用新包的内容。
大佬能否实现自动更新呢？

**Comment by manateelazycat** [comment]
使用了新的 crate 后， 项目中什么文件会发生变化呢？

**Comment by C-Entropy** [comment]
> 使用了新的 crate 后， 项目中什么文件会发生变化呢？

rust里的crate相当于第三方库，引用新的crate会引入新的函数、宏、结构等内容。

rust的逻辑是需要先编译程序一次，在这个过程中才会编译第一次use的crate。

在编译完成后，补全内容和错误检测都应该能自动读取到新的函数、宏、结构等内容。

但现在需要先重启lsp-bridge才能读取到这些新的内容。

**Comment by manateelazycat** [comment]
我的意思是引入第三方库， 需要写什么配置依赖吗？ 还是直接修改源代码就可以引入第三方库？

**Comment by C-Entropy** [comment]
有两个地方

1.在项目文件的根目录的cargo.toml声明需要的第三方库名称、版本和特性
2.在代码文件（.rs）里use 库

在第一步后第三方库还后没有被编译加载

在第二步后编译一次，第三方库就会被加载

**Comment by manateelazycat** [comment]
@C-Entropy 我早上研究了一下 rust-analyzer 的 issue https://github.com/rust-lang/rust-analyzer/issues/15554#issuecomment-1738710847

你尝试把下面的内容替换 /home/andy/lazycat-emacs/site-lisp/extensions/lspbridge/langserver/rust-analyzer.json 后再重启 lsp-bridge 试一下？

```json
{
  "name": "rust-analyzer",
  "languageId": "rust",
  "command": ["rust-analyzer"],
  "settings": {},
  "capabilities": {
    "textDocument": {
      "hover": {
        "contentFormat": ["markdown"]
      }
    }
  },
  "initializationOptions": {
    "enableExperimental": false,
    "diagnostics": {
      "enable": true
    },
    "files": {
      "watcher": "server"
    },
    "cargo": {
      "features": "all",
      "noDefaultFeatures": false,
      "runBuildScripts": true,
      "loadOutDirsFromCheck": true,
      "useRustcWrapperForBuildScripts": true,
      "autoreload": false,
      "buildScripts": {
        "enable": true,
        "rebuildOnSave": false,
        "invocationLocation": "root",
        "invocationStrategy": "once",
        "overrideCommand": null
        }
      },
    "checkOnSave": {
      "enable": false,
      "allTargets": true,
      "features": "all",
      "invocationLocation": "root",
      "invocationStrategy": "once"
    },
    "completion": {
      "addCallParenthesis": true,
      "addCallArgumentSnippets": false,
      "postfix": {
        "enable": false
      },
      "autoimport": {
        "enable": true
      }
    },
    "procMacro": {
      "enable": true
    },
    "lens": {
      "enable": false
    }
  }
}
```

上面的配置加入了
```json
    "files": {
      "watcher": "server"
    },
```

这个配置的意思是让  rust-analyzer 来监控项目文件的变动， 而不是让 client 来监听文件变动。

**Comment by C-Entropy** [comment]
@manateelazycat ,感谢大佬。
我试用了新的配置，然后重启了emacs，在第二步后还是需要重启lsp-bridge才能有相应的补全。

**Comment by manateelazycat** [comment]
嗯， 你json配置只保留 files.watcher 那一段呢？

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/0411c2402b4ff0af05cda9740c387c8576c4a5e3/langserver/rust-analyzer.json#L24

这里的 autoreload 也改成 true 来试一下

**Comment by manateelazycat** [comment]
我推送一个新的补丁 https://github.com/manateelazycat/lsp-bridge/commit/74f2e64552385a0290d0e329c1063e2033a4c464

当你写完 use 语句以后， 你手动执行一下 lsp-bridge-rust-reload-workspace 看看有没有效果？

如果这个命令有效果， 我可以尝试在 lsp-bridge 补全 use 语句的时候， 能否自动调用 lsp-bridge-rust-reload-workspace 这个命令。

**Comment by C-Entropy** [comment]
报错了
```
[LSP-Bridge] Failed to deserialize rust-analyzer/reloadWorkspace: invalid type: map, expected unit; {"textDocument":{"uri":"file:///home/nil/projects/learnrust/command-line/chapter2/echo1/src/main.rs"}} [2 times]
```

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/6362ae4ede8ebfe3fbdef99007574b5dd86f0ee7

@C-Entropy 更新了， 再试一下

**Comment by C-Entropy** [comment]
大佬，还是报错：
`[LSP-Bridge] Failed to deserialize rust-analyzer/reloadWorkspace: invalid type: map, expected unit; {} [2 times]
`

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/b2345a2af84e2c6079001687d3b8d9e8db210b3d

再更新一下

**Comment by C-Entropy** [comment]
感谢大佬更新。
能正常调用了，但还是不会更新内容。
我现在先自动在编译后restart lsp-bridge。

**Comment by manateelazycat** [comment]
也就是说 reload workspace 没用， 是必须 restart lsp-bridge 才行？

**Comment by C-Entropy** [comment]
> 也就是说 reload workspace 没用， 是必须 restart lsp-bridge 才行？

现在测试下来是这样的

**Comment by fuyu0425** [comment]
我打开 vscode 的 lsp trace log 观察到了了几件事

1. 在 vscode 里面 edit Cargo.toml 会 trigger rust-analyzer 的 didSave
```
[Trace - 上午1:28:21] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "xxxxx/Cargo.toml"
    }
}
```
不太清楚 vscode 的 lsp client 实现 但目前 lsp-bridge 不会 send didSave 因为 toml 不会连接 rust-analyzer

2. 在 vscode 外面 edit Cargo.toml 会 trigger workspace/didChangeWatchedFiles 例如
```
[Trace - 上午1:29:14] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///xxxxx/Cargo.toml",
            "type": 1
        }
    ]
}
```
我看了一下 lsp-bridge 还没有实现 file watch 
这个 vscode 的 example request
```
[Trace - 上午1:28:22] Received request 'client/registerCapability - (39)'.
Params: {
    "registrations": [
        {
            "id": "workspace/didChangeWatchedFiles",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": {
                            "baseUri": "file:///xxxxxxxx",
                            "pattern": "**/*.rs"
                        }
                    },
                    {
                        "globPattern": {
                            "baseUri": "file:///xxxxxxxx",
                            "pattern": "**/Cargo.{lock,toml}"
                        }
                    },
                    {
                        "globPattern": {
                            "baseUri": "file:///xxxxxxxx",
                            "pattern": "**/rust-analyzer.toml"
                        }
                    },
                    {
                        "globPattern": "/Users/fuyu0425/Library/Application Support/rust-analyzer/rust-analyzer.toml"
                    },
                    {
                        "globPattern": "/xxxxxxxx/Cargo.toml"
                    }
                ]
            }
        }
    ]
}
```
lsp-mode 有实现 file watch 但 也有一些问题，貌似 kqueue used by filenotify.el 不能 support edit files under watched folders. 但用 python + fsevent 应该不是问题

https://github.com/emacs-lsp/lsp-mode/issues/3370
https://github.com/emacs-lsp/lsp-mode/issues/3296

感觉工作量蛮大的

**Comment by manateelazycat** [comment]
方便给一个最小的测试代码仓库吗？我这几天有空看一下怎么加watch files

**Comment by fuyu0425** [comment]
`cargo new helloworld` 就可以

**Comment by manateelazycat** [comment]
> workspace/didChangeWatchedFiles

先用 pip 安装 watchdog 这个包的依赖， 再更新到最新版 https://github.com/manateelazycat/lsp-bridge/commit/f7c37f583bd3fc9ec5010532c226edb17f32f438

现在修改 toml 文件会给 LSP server 发送 workspace/didChangeWatchedFiles notification.

**Comment by fuyu0425** [comment]
测试 会work
但 restart 会有 exception
```
Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/Users/fuyu0425/Library/Python/3.11/lib/python/site-packages/watchdog/observers/fsevents.py", line 307, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path='/Users/fuyu0425/test/helloworld', is_recursive=False> - it is already scheduled
```

**Comment by fuyu0425** [comment]
exception 没了 
发现会重复送 Send workspace/didChangeWatchedFiles
似乎每改一次 Cargo.toml 就多一次 

每次改时 server 都会在 push 一个 client/registerCapability 导致 handle_register_capability_message 一直加 watcher?

**Comment by manateelazycat** [comment]
> exception 没了 发现会重复送 Send workspace/didChangeWatchedFiles 似乎每改一次 Cargo.toml 就多一次
> 
> 每次改时 server 都会在 push 一个 client/registerCapability 导致 handle_register_capability_message 一直加 watcher?

陪领导逛街，晚上回去看看

**Comment by manateelazycat** [comment]
> exception 没了 发现会重复送 Send workspace/didChangeWatchedFiles 似乎每改一次 Cargo.toml 就多一次
> 
> 每次改时 server 都会在 push 一个 client/registerCapability 导致 handle_register_capability_message 一直加 watcher?

https://github.com/manateelazycat/lsp-bridge/commit/d6b54fe9ae6b9e2e5a9f56f8dfd9390095f1b8ec 再测试一下最新版吧， 上一版确实会多次探测相同的目录。

**Comment by manateelazycat** [comment]
还有问题请重新打开这个issue
