### ISSUE TITLE
swift文件显示不出来diagnostic，之前可以显示，后面swift的lsp支持background indexing后就显示不出来了。但是用eglot和vscode可以正常显示。

### ISSUE THREAD

**Issue by happyo** [manateelazycat/lsp-bridge#1040]
我这边记录了lsp-bridge和eglot的日志，发现eglot收到textDocument/publishDiagnostics然后显示就是这个，和vscode显示的一样。但是lsp-bridge的日志中没有收到textDocument/publishDiagnostics这个。具体log如下：
[eglotLog.txt](https://github.com/user-attachments/files/17054446/eglotLog.txt)
[lsplog.txt](https://github.com/user-attachments/files/17054447/lsplog.txt)

**Comment by happyo** [comment]
> 有测试代码吗？

应该任何有编译错误的swift文件都行。

复现步骤：

首先安装好swift环境后，按照 [开启background indexing](https://github.com/swiftlang/sourcekit-lsp/blob/main/Documentation/Enable%20Experimental%20Background%20Indexing.md) 上面的方法打开background indexing。

先创建一个文件夹LSPTest，cd进去后使用`swift package init --type library --name LSPTest`创建一个package。

然后运行`swift build`，可以看到编译成功。再打开LSPTest.swift文件，输入如下内容：
`
import SwiftUI

fun
`

保存后再执行`swift build`，可以看到会显示编译报错。

使用lsp-bridge打开这个文件后，打印日志没有显示diagnotics。然后再使用eglot打开这个文件，能正常显示diagnotics。

我的emacs配置如下：

`
;; (use-package lsp-bridge
;;   :demand t
;;   :ensure nil
;;   :bind (
;;          ("M-." . lsp-bridge-find-def)
;;          ("M-," . lsp-bridge-find-def-return)
;;          ("M-[" . lsp-bridge-code-format)
;;          )
;;   :load-path "~/.emacs.d/site-lisp/lsp-bridge"
;;   :config
;;   (setq lsp-bridge-python-command (pythonPath))
;;   ;; (setq acm-enable-tempel nil)
;;   ;; (setq acm-enable-citre t)
;;   (setq lsp-bridge-enable-log t)
;;   ;; (setq lsp-bridge-enable-signature-help t)
;;   (setq acm-enable-tabnine nil)
;;   (setq acm-enable-codeium nil)
;;   (setq acm-enable-copilot nil)
;;   (setq lsp-bridge-enable-org-babel t)
;;   (setq lsp-bridge-enable-hover-diagnostic t)
;;   (setq lsp-bridge-diagnostic-fetch-idle 0.2)
;;   (setq lsp-bridge-enable-completion-in-minibuffer t)
;;   (setq lsp-bridge-find-def-fallback-function 'xref-find-definitions)
;;   (setq lsp-bridge-find-def-return-fallback-function 'xref-pop-marker-stack)
;;   (setq acm-backend-lsp-match-mode "prefix")
;;   (setq acm-enable-capf t)
;;   ;; (define-key my-custom-minor-mode-map (kbd "M-.") 'my-custom-m-dot-function)
;;   ;; (define-key my-custom-minor-mode-map (kbd "M-,") 'lsp-bridge-find-def-return)
;;   ;; (define-key my-custom-minor-mode-map (kbd "M-]") 'lsp-bridge-code-format)
;;   (global-lsp-bridge-mode)
;;   )

(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
    '(swift-ts-mode . ("xcrun" "sourcekit-lsp"))))
`

我lsp-bridge里的配置增加了swift-ts-mode的支持，之前没开启background indexing时候是可以显示diagnotics的。开启background indexing成功后，在LSPTest的根目录下会出现`.index-build/`文件夹。

**Comment by manateelazycat** [comment]
Swift 在Linux下可以安装测试吗？

**Comment by happyo** [comment]
应该是可以的，[官网提供下载](https://www.swift.org/install/linux/ubuntu/#versions)，安装配置环境可以参考[linux配置swift环境](https://fatbobman.com/zh/posts/swift-in-linux/)

**Comment by manateelazycat** [comment]
大佬先把 https://github.com/manateelazycat/lsp-bridge/blob/fb64891c2585f9fc0b7f2062cc2b98321aa4e4ca/core/lspserver.py#L397

换成 

"publishDiagnostics":{"relatedInformation":False,"codeDescriptionSupport":False,"tagSupport":{"valueSet":[1,2]}}

试一下

**Comment by happyo** [comment]
> 周末看一下哈， 最近太忙了。

哈哈，没事。



> 大佬先把
> 
> https://github.com/manateelazycat/lsp-bridge/blob/fb64891c2585f9fc0b7f2062cc2b98321aa4e4ca/core/lspserver.py#L397
> 
> 换成
> 
> "publishDiagnostics":{"relatedInformation":False,"codeDescriptionSupport":False,"tagSupport":{"valueSet":[1,2]}}
> 
> 试一下

这个我试了下好像还是不行，等大佬空的时候再看吧。

**Comment by happyo** [comment]
刚顺着你这个思路我问了下ChatGPT，回答如下
`根据您提供的 **Eglot** 和 **lsp-bridge** 的初始化日志，我们可以分析它们之间的区别，找出导致 Eglot 可以收到诊断通知，而 lsp-bridge 没有收到的原因。

---

## **1. 比较初始化请求中的客户端能力（Client Capabilities）**

### **Eglot 的初始化请求**

```json
{
  "method": "initialize",
  "params": {
    "capabilities": {
      "textDocument": {
        "publishDiagnostics": {
          "relatedInformation": false,
          "codeDescriptionSupport": false,
          "tagSupport": {
            "valueSet": [1, 2]
          }
        },
        ...
      },
      ...
    },
    ...
  },
  ...
}
```

- **关键点**：
  - **Eglot** 在 `textDocument` 下声明了 **`publishDiagnostics`** 能力。
  - **`publishDiagnostics`** 是传统的推送式诊断机制，服务器通过该通知主动向客户端发送诊断信息。

### **lsp-bridge 的初始化请求**

```json
{
  "method": "initialize",
  "params": {
    "capabilities": {
      "textDocument": {
        "diagnostic": {
          "dynamicRegistration": true,
          "relatedDocumentSupport": true
        },
        "publishDiagnostics": {
          "relatedInformation": true,
          "tagSupport": {
            "valueSet": [1, 2]
          },
          "versionSupport": true,
          "codeDescriptionSupport": true,
          "dataSupport": true
        },
        ...
      },
      ...
    },
    ...
  },
  ...
}
```

- **关键点**：
  - **lsp-bridge** 同时声明了 **`diagnostic`** 和 **`publishDiagnostics`** 能力。
  - **`diagnostic`** 能力属于 **LSP 3.17** 引入的 **拉取式诊断（Pull-based Diagnostics）**，客户端主动请求诊断信息。
  - **`publishDiagnostics`** 也是声明了，但需要进一步检查 lsp-bridge 是否正确处理了该通知。

---

## **2. 服务器响应中的能力（Server Capabilities）**

### **Eglot 的服务器响应**

```json
{
  "result": {
    "capabilities": {
      "textDocumentSync": { ... },
      "completionProvider": { ... },
      "publishDiagnostics": { ... },
      ...
    }
  },
  ...
}
```

- **Eglot** 的服务器响应中，服务器支持传统的 **`textDocument/publishDiagnostics`** 机制。

### **lsp-bridge 的服务器响应**

```json
{
  "result": {
    "capabilities": {
      "textDocumentSync": { ... },
      "completionProvider": { ... },
      "semanticTokensProvider": { ... },
      ...
    }
  },
  ...
}
```

- **lsp-bridge** 的服务器响应中，没有提到 **`diagnosticProvider`** 或 **`textDocument/diagnostic`** 能力。
- 这表明服务器不支持 **拉取式诊断**，只支持传统的 **`publishDiagnostics`** 通知。

---

## **3. 问题分析**

### **可能的原因**

1. **lsp-bridge 依赖拉取式诊断，但服务器不支持**

   - **lsp-bridge** 声明了 **`diagnostic`** 能力，期望服务器支持 **拉取式诊断**。
   - **sourcekit-lsp**（服务器）并未在响应中声明支持 **`diagnosticProvider`**，意味着它不支持拉取式诊断。

2. **lsp-bridge 对 `publishDiagnostics` 通知的处理有问题**

   - 虽然 **lsp-bridge** 也声明了 **`publishDiagnostics`** 能力，但可能内部未正确处理该通知。
   - 在 **lsp-bridge** 的 Handlers 列表中，没有看到专门处理 **`publishDiagnostics`** 通知的处理器。

### **对比 Eglot 和 lsp-bridge**

- **Eglot**：
  - 明确声明并处理 **`publishDiagnostics`** 通知。
  - 在初始化请求和内部实现中，都正确地设置了对诊断通知的支持。

- **lsp-bridge**：
  - 声明了 **`diagnostic`** 和 **`publishDiagnostics`** 能力，但可能在内部实现上只处理了拉取式诊断。
  - 由于服务器不支持拉取式诊断，导致 lsp-bridge 未能收到诊断信息。

---

## **4. 解决方案**

### **检查 lsp-bridge 的诊断处理**

1. **确认 lsp-bridge 是否支持 `publishDiagnostics` 通知**

   - 查看 **lsp-bridge** 的源码，确认是否有处理 **`textDocument/publishDiagnostics`** 通知的逻辑。
   - 如果没有，需要在 lsp-bridge 中添加对 **`publishDiagnostics`** 通知的支持。

2. **修改 lsp-bridge 的客户端能力声明**

   - 在初始化请求中，去掉 **`diagnostic`** 能力的声明，避免服务器误解。
   - 保留并正确配置 **`publishDiagnostics`** 能力。

3. **更新 lsp-bridge 或服务器**

   - 如果 **lsp-bridge** 版本较旧，可能未完全支持 **`publishDiagnostics`** 通知，需要更新到最新版本。
   - 如果可能，使用支持 **拉取式诊断** 的语言服务器。

### **示例修改**

- **修改初始化请求的客户端能力**：

  ```json
  "capabilities": {
    "textDocument": {
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [1, 2]
        },
        "versionSupport": true,
        "codeDescriptionSupport": true,
        "dataSupport": true
      },
      ...
    },
    ...
  }
  ```

- **确保 lsp-bridge 内部实现对 `publishDiagnostics` 的处理**：

  - 添加或启用处理 **`textDocument/publishDiagnostics`** 通知的处理器。
  - 确保该处理器能够解析诊断信息，并在 Emacs 中正确显示。

---

## **5. 验证与测试**

1. **重启 lsp-bridge**

   - 在修改配置或源码后，重启 lsp-bridge，让更改生效。

2. **观察诊断信息**

   - 打开包含错误的代码文件，查看是否能收到并显示诊断信息。

3. **查看日志**

   - 检查 lsp-bridge 的日志，确认是否收到了 **`textDocument/publishDiagnostics`** 通知。

---

## **6. 总结**

- **问题原因**：
  - **lsp-bridge** 可能主要依赖 **拉取式诊断**，而 **sourcekit-lsp** 不支持该机制，导致未收到诊断信息。
  - **Eglot** 使用了传统的 **推送式诊断**（`publishDiagnostics` 通知），并正确处理，因而能够收到诊断信息。

- **解决方法**：
  - **修改 lsp-bridge** 的客户端能力声明，确保与服务器的能力匹配。
  - **添加或修正** 对 **`publishDiagnostics`** 通知的处理，使 lsp-bridge 能够接收并显示诊断信息。

- **建议**：
  - **查看 lsp-bridge 的文档或源码**，了解其诊断机制。
  - **更新 lsp-bridge** 到最新版本，获取最新的功能和修复。
  - **联系 lsp-bridge 的维护者或社区**，寻求进一步的支持。

---

## **附加信息**

- **LSP 协议中的诊断机制**

  - **推送式诊断**（Publish Diagnostics）：
    - 服务器通过 **`textDocument/publishDiagnostics`** 通知，将诊断信息发送给客户端。
    - 这是 LSP 协议中最初的诊断方式，大多数语言服务器都支持。

  - **拉取式诊断**（Pull-based Diagnostics）：
    - 在 **LSP 3.17** 中引入，客户端通过 **`textDocument/diagnostic`** 请求，主动从服务器获取诊断信息。
    - 需要服务器和客户端都支持该机制。

- **sourcekit-lsp 的诊断支持**

  - **sourcekit-lsp** 目前主要支持 **推送式诊断**。
  - 不支持 **拉取式诊断**，因此客户端需要正确处理 **`publishDiagnostics`** 通知。

---

希望以上分析能够帮助您理解为什么 **Eglot** 能够收到诊断通知，而 **lsp-bridge** 没有收到，并指导您解决问题。`

然后我将
`   "diagnostic": {
                    "dynamicRegistration": True,
                    "relatedDocumentSupport": True
                }`

删除了后就可以正常显示diagnostic了，后续大佬看下如何进行兼容。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/fd4a5e4379ec93465e413b06ff850b2935793185

已经修复

这个问题是尝试支持 https://github.com/manateelazycat/lsp-bridge/issues/1014 这个问题引入的。
