### ISSUE TITLE
能否加入对自定义大模型代码补全的支持

### ISSUE THREAD

**Issue by zxcwindy** [manateelazycat/lsp-bridge#1042]
你好，除了tabnine、codeium、copilot之外，目前还有deepseek-coder、codellama、qwen2.5-coder、sqlcoder、codegeex4、codegemma可以通过ollama以及各种OpenAI-API-compatible风格的平台部署。能否提供基于OpenAI-API-compatible或者Ollama的自动化补全呢？

现在找到相关的插件库有
[starhugger](https://gitlab.com/daanturo/starhugger.el)：Hugging Face/AI-powered text & code completion client (unofficial).Also supports using [Ollama](https://github.com/ollama/ollama) as a completion backend.Also supports using [Ollama](https://github.com/ollama/ollama) as a completion backend.
[ellama](https://github.com/s-kostyaev/ellama)：Ellama is a tool for interacting with large language models from Emacs. It allows you to ask questions and receive responses from the LLMs. Ellama can perform various tasks such as translation, code review, summarization, enhancing grammar/spelling or wording and more through the Emacs interface. Ellama natively supports streaming output, making it effortless to use with your preferred text editor.

但还不能和lsp-bridge集成使用

**Comment by manateelazycat** [comment]
最近没时间哈， 欢迎PR
