### ISSUE TITLE
使用中会出现卡字母的情况

### ISSUE THREAD

**Issue by e665107** [manateelazycat/lsp-bridge#1044]
![image](https://github.com/user-attachments/assets/6285f23c-770e-4dde-85b6-0a23932f7c9e)

**Comment by e665107** [comment]
输入s后直接死掉了

**Comment by manateelazycat** [comment]
lsp-bridge 不能和 corfu/company 等插件混合使用， 请用 emacs -Q 对比测试

**Comment by e665107** [comment]
是的，可以了
