### ISSUE TITLE
使用hakell时一定会报找不到hie.yml

### ISSUE THREAD

**Issue by DanielLiuCD** [manateelazycat/lsp-bridge#1047]
我得haskell项目已经有hie.yml，但是每次打开在日志窗口会报找不到hie.yml。换成eglot可以正常使用
[study.zip](https://github.com/user-attachments/files/17092224/study.zip)

**Comment by manateelazycat** [comment]
Found "/home/andy/下载/study/hie.yaml" for "/home/andy/下载/study/src/a"

我的可以呀

**Comment by DanielLiuCD** [comment]
> Found "/home/andy/下载/study/hie.yaml" for "/home/andy/下载/study/src/a"
> 
> 我的可以呀

我这里不行，报这个： --- [09:25:25.649250] Send initialize request (14029) to 'hls' for project study
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 2.9.0.1 aarch64 ghc-9.10.1

**Comment by manateelazycat** [comment]
感觉我的版本是不是太低了呀

haskell-language-server version: 1.9.1.0 (GHC: 9.2.8) (PATH: /usr/bin/haskell-language-server-wrapper)

**Comment by DanielLiuCD** [comment]
> 感觉我的版本是不是太低了呀
> 
> haskell-language-server version: 1.9.1.0 (GHC: 9.2.8) (PATH: /usr/bin/haskell-language-server-wrapper)

不知道是不是因为Apple M3的原因。按理来说haskell的语言服务器都是兼容低版ghc的

**Comment by manateelazycat** [comment]
> > 感觉我的版本是不是太低了呀
> > haskell-language-server version: 1.9.1.0 (GHC: 9.2.8) (PATH: /usr/bin/haskell-language-server-wrapper)
> 
> 不知道是不是因为Apple M3的原因。按理来说haskell的语言服务器都是兼容低版ghc的

还要麻烦大佬帮忙看看原因哇， 没有 Apple M3 设备
