### ISSUE TITLE
lsp-bridge-enable-search-words 没有被使用

### ISSUE THREAD

**Issue by fuyu0425** [manateelazycat/lsp-bridge#1050]
https://github.com/manateelazycat/lsp-bridge/blob/f9d540ff451d9a0ee92819b84472820f16be15d5/lsp-bridge.el#L233

`lsp-bridge-enable-search-words` 没有被其他地方 referenced

是不是应该在 `lsp-bridge-search-words-index-files` 加个判断 `lsp-bridge-enable-search-words` 是不是 t?

**Comment by manateelazycat** [comment]
最新版已经修复了， 感谢反馈
