### ISSUE TITLE
在undo-tree中移动时，有可能触发lsp-bridge 补全

### ISSUE THREAD

**Issue by C-Entropy** [manateelazycat/lsp-bridge#1051]
当在undo-tree中移动时，编辑中文本的光标位置也会跟着移动。
如果碰巧移动到可以补全的词后，将会触发lsp-bridge补全。
这种情况下触发补全会打断操作，建议做一个判断，在这种情况下不显示补全提示框。

**Comment by C-Entropy** [comment]
测了下，这个应该可以
```
(defun lsp-bridge--not-follow-complete ()
  "Hide completion if last command is `acm-complete'."
  (or
   (not (member (format "%s" last-command) '("acm-complete" "acm-complete-quick-access" "undo-tree-visualize-redo" "undo-tree-visualize-undo")))
   (member (format "%s" this-command) '("self-insert-command" "org-self-insert-command"))
   ))
```

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/5a7185a2a05f303424873d93f4c534d00902713a

Thanks

**Comment by C-Entropy** [comment]
想问下`lsp-bridge-completion-stop-commands`和`lsp-bridge--not-follow-complete`在使用上有啥区别？
我看到`lsp-bridge-completion-stop-commands` 里 有 `undo-tree-undo`和`undo-tree-redo`。

**Comment by manateelazycat** [comment]
其实可以加到 lsp-bridge-completion-stop-commands 中的， lsp-bridge--not-follow-complete 主要针对 acm-complete 命令
