### ISSUE TITLE
在开启两个buffer的时候使用lsp-bridge-code-action，会展示到另一个buffer中

### ISSUE THREAD

**Issue by C-Entropy** [manateelazycat/lsp-bridge#1052]
如图,在main.rs中调用lsp-bridge-code-action时,会在上方的buffer中显示。
![mmexport1727768235782.jpg](https://github.com/user-attachments/assets/4e536724-be6d-4113-9078-4525eed9be2e)

**Comment by C-Entropy** [comment]
又试了几次，候选框不一定会展示到上面的buffer，但光标会跳到上面的buffer中。
如果init-packages.el这个buffer在main.rs这个buffer下面的话，光标不会跳到init-packages.el的buffer里，但是不会被候选框捕获：按上下键的话，光标会在main.rs这个buffer中移动。

**Comment by manateelazycat** [comment]
我测试了， 没有问题， 最好 emacs -Q 对比测试一下

**Comment by C-Entropy** [comment]
可能是用moti编译的原因。
改用pgtk -X后光标不会乱跳了。
但候选框还是有可能跳到上面的buffer。

**Comment by manateelazycat** [comment]
你环境的问题，我没有重现，glib那个报错没关系
