### ISSUE TITLE
rust下 的 inlay-hint能否优化一下光标位置

### ISSUE THREAD

**Issue by C-Entropy** [manateelazycat/lsp-bridge#1054]
如图
在字符`o`之后按右键，光标的位置直接跳到`&WallLocation`后面了。
能否在按右键后让光标出现在`n`后面，`&WallLocation`前面？

按右键前
![IMG20241002153901.jpg](https://github.com/user-attachments/assets/4a5dd0c1-da83-490a-abf2-0b314cb8ce67)

按右键后
![IMG20241002153845.jpg](https://github.com/user-attachments/assets/d08b2e6d-b0fb-4c43-9678-009331c604a7)

**Comment by manateelazycat** [comment]
不影响操作， 因为这种 overlay 只是视觉的， 并不会影响你向左删除。

overlay 这里不能改， 改了会导致其他地方出现更多的bug
