### ISSUE TITLE
BUg: When in insert-mode and in org-mode with evil-mode selection of yasnippet does not work in doom emacs

### ISSUE THREAD

**Issue by Y0ngg4n** [manateelazycat/lsp-bridge#1062]
I am using doom emacs.
When i am opening a .org file that is not a roam file and not babel, so a normal org file
and i am in insert-mode and i am typing a yasnippet, i cant select the first entry with `Tab` or `Enter`.
The only thing that works is selecting it by using `M-n` and then `M-b` to select it.
I am not using wenls or pinyin and disabled company popup for org-mode.

**Comment by manateelazycat** [comment]
I don't use evil, can't help you.

**Comment by harisonkhlil** [comment]
I also not fount resolution of it, the follows is my stopgap

```elisp
  (map! :map org-mode-map
        :ie [M-tab]        #'acm-complete)
```

**Comment by Y0ngg4n** [comment]
@harisonkhlil for me it kinda works if i set the following:
`(setq org-src-tab-acts-natively t)`
