### ISSUE TITLE
[Bug?] Inputting Chinese is abnormally slow

### ISSUE THREAD

**Issue by harisonkhlil** [manateelazycat/lsp-bridge#1063]
经过探查，具体问题在于 `acm-enable-capf t`

https://github.com/user-attachments/assets/5a84996c-5900-4adf-89b8-19ece74cc62a

问题仅仅出现在 org-mode，因为已经添加了list  `(add-to-list 'acm-backend-capf-mode-list 'org-mode)` 目的为了补全 org-mode 的 LaTeX 体验。

可能和处理拼音是一个一个寻找补全有关，越长的句子停顿也就越长。

**Comment by manateelazycat** [comment]
capf 慢是因为你当前模式提供 capf 的函数慢， 请排查你的 capf 配置

**Comment by manateelazycat** [comment]
lsp-bridge本身不会卡顿， acm-enable-capf 是为了兼容一些没有 LSP 的场景提供补全， 但是提供 acm-enable-capf 的副作用就是如果某个模式对应的  capf 实现糟糕， 还是会卡Emacs。 

你需要把那些糟糕的 capf 实现配置清除， capf 的问题和 lsp-bridge 无关。
