### ISSUE TITLE
如何在 C++ 项目中补全？

### ISSUE THREAD

**Issue by Grant-S-Z** [manateelazycat/lsp-bridge#1069]

**Comment by manateelazycat** [comment]
你的项目是一个 git 项目吗？

**Comment by Grant-S-Z** [comment]
我是想在 Geant4 项目中尝试使用 lsp-bridge，就是使用 cmake 组织的项目。

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/0ad04b2f-f142-4d91-8dbd-65ed5b2a411a">

文件结构如上图所示。

README 中提到需要配置和 CMakeList.txt 和 compile_commands.json，但仅有这两个文件应该不能直接让 lsp-bridge 获取补全信息？是否还需要配置一个类似于 c_cpp_properties.json 的文件呢？抑或是 lsp-bridge 没有确定项目位置，需要一个 projectile 这样的配置呢？

**Comment by manateelazycat** [comment]
你直接在你的项目 git init 试一下

**Comment by Grant-S-Z** [comment]
> 你直接在你的项目 git init 试一下

谢谢你，建立 git 仓库之后确实有补全了！

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/560be496-4917-4393-81a7-d294e00edfe3">

不过在 include 库的时候没有补全，这是正常的么？

<img width="849" alt="image" src="https://github.com/user-attachments/assets/59043cdc-02b4-4f78-9d6d-52e8520d5a10">

**Comment by manateelazycat** [comment]
这个要看你的 compile_commands.json 是怎么生成的， compile_commands.json 有问题 lsp-bridge 也没办法
