### ISSUE TITLE
Lsp-bridge does not recognize project directory

### ISSUE THREAD

**Issue by bluzky** [manateelazycat/lsp-bridge#1070]
Hi,  I've just set up lsp-bridge and when I started my elixir project, it used user directory as project directory.

![image](https://github.com/user-attachments/assets/42896379-13e1-41da-9cff-5b470a73605c)

Here is my config

```elisp
(use-package lsp-bridge
  :quelpa (lsp-bridge :fetcher github :repo "manateelazycat/lsp-bridge"
                      :files ("*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources"))
  :init
  (global-lsp-bridge-mode)
  :custom
  (lsp-bridge-elixir-lsp-server 'lexical)
  )
```
Is there any option that I missing?

Thanks

**Comment by manateelazycat** [comment]
You need execute "git init" in your project path.
