### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\w'   words = set(re.findall("[\w|-]+", search_content_dict[search_file]))

### ISSUE THREAD

**Issue by DanielLiuCD** [manateelazycat/lsp-bridge#1071]
最近把工作环境换到Linux上了，lsp-bridge无法使用。
系统： opensuse leap 15.6
python：python3.12.6

错误信息： lsp-bridge/core/search_file_words.py:167: SyntaxWarning: invalid escape sequence '\w'
  words = set(re.findall("[\w|-]+", search_content_dict[search_file]))

**Comment by manateelazycat** [comment]
有项目测试文件吗？

**Comment by DanielLiuCD** [comment]
> 有项目测试文件吗？

任何rust工程都会出现。直接cargo new一个新项目就会有这问题，不过目前似乎只有rust会有这个问题。我试了elixir项目正常

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/8d8f021c3bea352240a2041e07e8e4e43fe423a0

已经修复了， 感谢反馈， 估计我的系统默认没有打开 Python 3.12 这个 SyntaxWarning 这个选项
