### ISSUE TITLE
请教lsp-bridge-find-reference 使用

### ISSUE THREAD

**Issue by jason--liu** [manateelazycat/lsp-bridge#1075]
请问下在lsp-bridge-ref窗口中按`r` ，提示
```
Replace nil all matches with:
```
看起来并没有匹配到这里的`ret`，是我的使用有问题吗？
![image](https://github.com/user-attachments/assets/57a5941b-c174-41f5-94e5-5128891d2270)

**Comment by manateelazycat** [comment]
lsp-bridge-ref.el 的代码是从 colo-rg.el 重构过来的， 这个是bug， 已经修复 https://github.com/manateelazycat/lsp-bridge/commit/1911b1f99c47c6df9b0bb00daefd2af74c113374

感谢反馈。
