### ISSUE TITLE
lsp-ui sideline is missing

### ISSUE THREAD

**Issue by Y0ngg4n** [manateelazycat/lsp-bridge#1076]
The feature to show errors on the right is missing in lsp-bridge:

https://github.com/emacs-lsp/lsp-ui

I am missing all the lsp-ui-sideline-* features.

**Comment by manateelazycat** [comment]
(setq lsp-bridge-signature-show-function 'lsp-bridge-signature-show-with-frame)

**Comment by Y0ngg4n** [comment]
@manateelazycat i set it like you said but i still only can see the errors if i hover with the cursor over it.
