### ISSUE TITLE
there're so many workspace/symbol error after upgrade latest version

### ISSUE THREAD

**Issue by curtainp** [manateelazycat/lsp-bridge#1093]
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/cd1f3a14-e8a7-44e6-a92d-82315f2bb68b">

**Comment by manateelazycat** [comment]
Caused by https://github.com/manateelazycat/lsp-bridge/pull/1089

Has fixed in newest version.

Thanks for report.
