### ISSUE TITLE
python 智能提示有问题 Method Not Found: workspace/symbol

### ISSUE THREAD

**Issue by nigo81** [manateelazycat/lsp-bridge#1096]
作者您好，

![image](https://github.com/user-attachments/assets/c0d6ef97-3160-477d-be68-2d11b56fd922)
就是我设置的`(setq lsp-bridge-python-lsp-server "pylsp")`后端，启动的时候：```[LSP-Bridge] Method Not Found: workspace/symbol [9 times]
[LSP-Bridge] Error: can’t find command ’basedpyright-langserver’ to start LSP server basedpyright (/Users/nigo/github/digit-audit/tools.py)
[LSP-Bridge] found language server: /opt/homebrew/bin/pylsp
```，但是我在python代码中，智能提示出现问题，比如`pd.`输入逗号后，并没有出现提示，并且emacs会提示：[LSP-Bridge] Method Not Found: workspace/symbol [9 times]。    请问这个问题是什么原因，可以怎么解决呢？其它功能是正常的，比如lsp-bridge-find-def  是正常的。 感谢！

**Comment by manateelazycat** [comment]
给一下日志吧， 是不是最新版本， 是否装了  lsp server ?

**Comment by nigo81** [comment]
> 给一下日志吧， 是不是最新版本， 是否装了 lsp server ?

[lsp-log.txt](https://github.com/user-attachments/files/17552950/lsp-log.txt)
我是更新到最新的版本的，10月29号的版本。安装了python-lsp-server. 上面文件是日志。感谢

**Comment by manateelazycat** [comment]
更新最新版再试试？

https://github.com/manateelazycat/lsp-bridge/commit/ae40b360147342aa0e8cf2e74a4cc2e5081924e3 应该修复啦。

**Comment by nigo81** [comment]
> 更新最新版再试试？
> 
> [ae40b36](https://github.com/manateelazycat/lsp-bridge/commit/ae40b360147342aa0e8cf2e74a4cc2e5081924e3) 应该修复啦。

没有再出现那个报错提示了。但是智能提示非常弹出非常慢，大概需要10秒，以前都是瞬间出来的。

**Comment by nigo81** [comment]
> > 更新最新版再试试？
> > [ae40b36](https://github.com/manateelazycat/lsp-bridge/commit/ae40b360147342aa0e8cf2e74a4cc2e5081924e3) 应该修复啦。
> 
> 没有再出现那个报错提示了。但是智能提示非常弹出非常慢，大概需要10秒，以前都是瞬间出来的。

我把`(setq lsp-bridge-enable-log nil)`日志关了，就恢复快了。应该是没有问题。感谢大佬的付出。
