### ISSUE TITLE
【Question】请问有开发指南吗

### ISSUE THREAD

**Issue by awerdx520** [manateelazycat/lsp-bridge#1105]
我在修改当前项目代码时，会有很多代码格式化相关的修改。有统一的代码格式化的相关配置和以及其他命名规则等开发指南吗？

**Comment by manateelazycat** [comment]
现在的代码就是格式化规范， 我建议把功能和格式化代码分开， 要不补丁没法review

**Comment by awerdx520** [comment]
ok
