### ISSUE TITLE
Error in post-command-hook (lsp-bridge-start-process): (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by patka-123** [manateelazycat/lsp-bridge#1106]
This is probably very trivial to solve, but I have no clue.

I'm trying to use lsp-bridge in combination with Doom emacs (just followed your readme, seems to install correctly), but it doesn't want to start and gives the error in the title. It also doesn't let me enable logs. Maybe this is because the process hasn't started yet? I don't know.

Is there anything I can try?

**Comment by manateelazycat** [comment]
emacsd -Q for compare test.
