### ISSUE TITLE
java 代码补全，补全时会删掉开头手动输入的几个字母

### ISSUE THREAD

**Issue by ginqi7** [manateelazycat/lsp-bridge#111]
使用 emacs -Q -l init.el 加载，就只有ReadMe里的配置项。进行Java代码补全时：
进行代码补全时，显示的是正确的补全项：
![image](https://user-images.githubusercontent.com/1028971/169191914-706bed3f-45fc-41c2-89e9-6fc1c0ba5465.png)
但是，使用tab或者回车选中时，删除了补全前手动输入的几个字母：sub：
![image](https://user-images.githubusercontent.com/1028971/169192141-6eecd82d-1c7d-4e53-a7ec-eca934672868.png)

**Comment by manateelazycat** [comment]
感谢反馈，我这边暂时没有测试环境，等lsp-bridge团队的其他开发者帮忙看一下。

**Comment by ginqi7** [comment]
问题补充，应该是 Java 在 lsp-bridge-completion-items 里存储的 :insertText 不包含用户已经输入的内容。
![image](https://user-images.githubusercontent.com/1028971/169265179-fb411d3d-0440-484c-aee3-3fc730172fe8.png)

lsp-bridge 补全时，会先删除已经输入的内容，然后再插入 :insertText 当中的数据。导致了补全的内容有所缺失。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/pull/113/files 这个补丁正在修复这个问题

**Comment by manateelazycat** [comment]
已经修复了 https://github.com/manateelazycat/lsp-bridge/pull/113
