### ISSUE TITLE
Openscad LSP

### ISSUE THREAD

**Issue by Y0ngg4n** [manateelazycat/lsp-bridge#1110]
Would be nice to support https://github.com/Leathong/openscad-LSP

**Comment by manateelazycat** [comment]
PR are welcome.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/41530f4dfafa63ebb6b510cdcf2bef0e5757b56a Done

**Comment by Y0ngg4n** [comment]
Oh wow that was fast! Thank you :)

**Comment by Y0ngg4n** [comment]
@manateelazycat i can´t find the scad-mode function. I updated to latest but can not find the `scad-mode` function

**Comment by Y0ngg4n** [comment]
@manateelazycat ah sorry. Now it works.
