### ISSUE TITLE
didSave should not depend on textDocumentSync/willSave

### ISSUE THREAD

**Issue by fuyu0425** [manateelazycat/lsp-bridge#1111]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didSave

didSave should depend on server capability `textDocumentSync.save` instead of `textDocumentSync/willSave`

https://github.com/manateelazycat/lsp-bridge/blob/fece34b8d9572aab930b3bcb3bbb904b3d9c8e08/core/lspserver.py#L767

https://github.com/manateelazycat/lsp-bridge/blob/fece34b8d9572aab930b3bcb3bbb904b3d9c8e08/core/lspserver.py#L545

After that change, lsp-bridge never sends `disSave` in rust project because rust-analyzer didn't set `textDocumentSync/willSave` Therefore, the diagnostics will not be updated.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/d30043e19ff84119326a81601b8d08e17d0391f7

Fixed
