### ISSUE TITLE
关闭indent-tabs-mode后，Yas-Snippet没有补全提示

### ISSUE THREAD

**Issue by panshouren** [manateelazycat/lsp-bridge#1112]
测试代码如下：
```
(global-whitespace-mode)

(setq-default indent-tabs-mode nil)

(use-package yasnippet)
(yas-global-mode 1)
(use-package yasnippet-snippets)
 
 (use-package lsp-bridge
   :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"
                          :files (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
                          :build (:not compile))
   :init
   (global-lsp-bridge-mode))
 
 (require 'lsp-bridge-jdtls) 
 (setq lsp-bridge-enable-auto-import t)
 (setq lsp-bridge-jdtls-jvm-args '("-javaagent:/home/pansr1/.m2/repository/org/projectlombok/lombok/1.18.28/lombok-1.18.28.jar"))
```
---

当光标前面是TAB的时候，能弹出Yas-Snippet的选项（而且还有个问题，只有输入snippet的name才有提示，关闭lsp-bridge，输入snippet的key，比如as，ae就有对应提示）：
![Screenshot from 2024-11-14 11-47-01](https://github.com/user-attachments/assets/058b37a2-fe8b-4d59-8f4b-a1312958bb84)

光标前面是普通空格，只有JDK的选项：
![Screenshot from 2024-11-14 11-47-47](https://github.com/user-attachments/assets/d1af9143-969d-4ca3-8f86-220c215771fc)

**Comment by manateelazycat** [comment]
没看懂

**Comment by panshouren** [comment]
就是我在写Java代码的时候，发现补全框里没有yas的提示。
通过二分法排除，发现和indent-tabs-mode有关，indent-tabs-mode我设置的是nil，改成t就有了。
