### ISSUE TITLE
followed instructions : lsp-bridge running but no "in buffer" error reporting

### ISSUE THREAD

**Issue by rileyrg** [manateelazycat/lsp-bridge#1116]
I followed all the instructions here https://github.com/manateelazycat/lsp-bridge and the mode line indicates its running, but I'm not seeing any lsp annotations - I am seeing errors underlined but no further information .

Is there something very obvious I am missing?

![screenshot-2024-11-27-20:18:48](https://github.com/user-attachments/assets/3e9e3424-a63c-4ed3-ac30-0d4a95a2adc5)

**Comment by rileyrg** [comment]
OK. I got somewhere, but I feel this needs documenting. It i svery snappy (ie fast) but I do wonder why the usual xref and flymake error navigations aren't used?

My lsp-bridge config:

```
  (use-package lsp-bridge
    :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"
              :files (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
              :build (:not compile))
    :init
    (global-lsp-bridge-mode)
    (defun rgr/lsp-bridge-hook()
      (when corfu-mode
          (corfu-mode -1)))
    :custom
    (lsp-bridge-enable-hover-diagnostic t)
    :hook
    (lsp-bridge-mode-hook . rgr/lsp-bridge-hook)
    :bind (
     :map lsp-bridge-mode-map
          ("C-." . lsp-bridge-show-documentation)
          ("M-n" . lsp-bridge-diagnostic-jump-next)
          ("M-p" . lsp-bridge-diagnostic-jump-prev)
          ("M-." . lsp-bridge-find-def)
          ("M-," . lsp-bridge-find-def-return)
          ))
```

**Comment by manateelazycat** [comment]
Can you give me test code? Thanks

**Comment by rileyrg** [comment]
> Can you give me test code? Thanks

Any code. I replied with my "fix"..  And suggested this should be in the documentation.

I really like it, btw.
