### ISSUE TITLE
Debug support

### ISSUE THREAD

**Issue by oscarvarto** [manateelazycat/lsp-bridge#1119]
Is there a way to support debugging, maybe dap-mode?
Using JVM languages for work (Java/Scala), but general debug support is helpful in most languages, I think.

Or is this subject tangential to lsp support? Can dap-mode work with lsp-bridge?

**Comment by manateelazycat** [comment]
Please use https://github.com/svaante/dape , it can works with lsp-bridge.

Thanks.

**Comment by oscarvarto** [comment]
Hi!
I have a doubt regarding the Java configuration given there:
```elisp
(add-to-list 'eglot-server-programs
             `((java-mode java-ts-mode) .
               ("jdtls"
                :initializationOptions
                (:bundles ["/PATH/TO/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-VERSION.jar"]))))
```
The docs say dape (for Java) depends on eglot running before. Does it work for lsp-bridge as well? Does it work with a change to the above config?

**Comment by manateelazycat** [comment]
Please check https://github.com/manateelazycat/lsp-bridge?tab=readme-ov-file#customize-language-server-configuration-file

Copy lspbridge/langserver/jdtls.json to your customize dir, and change option `initializationOptions` for your need.
