### ISSUE TITLE
C++ LSP补全很慢

### ISSUE THREAD

**Issue by 4lsa** [manateelazycat/lsp-bridge#1120]
server: clangd
compile_commands.json size: ~64M
chip: M3 pro 36G 

问题描述：
find-def、find-reference等操作很快，但是lsp补全肉眼可见的慢，肉眼预估lsp补全信息约在打字后10s左右会更新出来（在此之前都是一些yasnippet和search word的候选项）。
请问补全分析这个大小的compile_commands.json，这个速度是符合预期的吗？
下面附有我dump的性能剖析日志
[lsp-bridge.prof.zip](https://github.com/user-attachments/files/17994898/lsp-bridge.prof.zip)

**Comment by manateelazycat** [comment]
关闭 lsp-bridge-enable-log 选项

**Comment by 4lsa** [comment]
> 关闭 lsp-bridge-enable-log 选项

测试是在关闭lsp-bridge-enable-log的情况下测试的

**Comment by manateelazycat** [comment]
emacs -Q 对比测试过吗？ 

lsp-bridge 的配置发一下吧

**Comment by 4lsa** [comment]
```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(setq straight-use-package-by-default t)
(setq use-package-always-ensure t)
;; (setq lsp-bridge-c-lsp-server "ccls")

(use-package lsp-bridge
  :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"
            :files (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
            :build (:not compile))
  :init (global-lsp-bridge-mode)
  :custom (acm-enable-quick-access t)
  :bind (("M-n" . acm-select-next)
         ("M-p" . acm-select-prev)))

(provide 'init-lsp-bridge)
``` 
emacs -Q对比测试过也是LSP补全肉眼可见的延迟，我怀疑是不是我本身用的compile_commands.json就限制了lsp的速度，所以就dump了性能剖析日志，希望大佬能帮忙看下或者指点下可能得排查方向

**Comment by manateelazycat** [comment]
方便发测试代码给我看一下吗？ 我帮你远程测试下， 看看我自己卡不卡？

如果我卡， 我就可以快速修复

**Comment by 4lsa** [comment]
抱歉，代码部分比较私密不能公开，但是我理解应该可以定位问题在lsp-bridge，因为eglot中使用同样的设置并不会出现这样的问题

**Comment by manateelazycat** [comment]
> 抱歉，代码部分比较私密不能公开，但是我理解应该可以定位问题在lsp-bridge，因为eglot中使用同样的设置并不会出现这样的问题

Emacs除非是非常干净的配置文件对比， 99%的问题最后都是用户自己的配置造成的。

lsp-bridge 要比 eglot/lsp-mode 快很多很多， 如果不能提供测试代码， 暂时无法解决， 抱歉。
