### ISSUE TITLE
custom lsp server insteaf of default lsp server

### ISSUE THREAD

**Issue by nanakura** [manateelazycat/lsp-bridge#1124]
lsp-bridge use basedpyright, pyright, jedi as default lsp server options for python. However, I would like to use a different LSP server, such as delance. How can I set this up?

**Comment by manateelazycat** [comment]
If you use multiple server , you can set lsp-bridge-python-multi-lsp-server, if you use simple lsp server, need remove python-mode   from lsp-bridge-multi-lang-server-mode-list, then set lsp-bridge-python-lsp-server.

customize lsp server config file , please check https://github.com/manateelazycat/lsp-bridge?tab=readme-ov-file#customize-language-server-configuration-file

**Comment by nanakura** [comment]
> If you use multiple server , you can set lsp-bridge-python-multi-lsp-server, if you use simple lsp server, need remove python-mode from lsp-bridge-multi-lang-server-mode-list, then set lsp-bridge-python-lsp-server.
> 
> customize lsp server config file , please check [manateelazycat/lsp-bridge#customize-language-server-configuration-file](https://github.com/manateelazycat/lsp-bridge?tab=readme-ov-file#customize-language-server-configuration-file)

直接改源码不太好，我想在use-package的config中改，但是我不是很熟悉elisp的语法，请问怎么把python-mode从lsp-bridge-multi-lang-server-mode-list中移除，我尝试了如下写法没有效果
```elisp
  (add-to-list 'lsp-bridge-single-lang-server-mode-list
          '(python-mode . "delance"))
```

**Comment by manateelazycat** [comment]
不需要改源代码， 看 https://github.com/manateelazycat/lsp-bridge/blob/master/README.zh-CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by nanakura** [comment]
> 不需要改源代码， 看 [`master`/README.zh-CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6](https://github.com/manateelazycat/lsp-bridge/blob/master/README.zh-CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

```lisp
(use-package lsp-bridge
  :custom
  (lsp-bridge-user-langserver-dir "~/.emacs.d/langserver")
  :config
  (add-to-list 'lsp-bridge-single-lang-server-mode-list
          '(python-mode . "delance"))
)
```

然后我加了个json配置

```json
{
  "name": "delance",
  "languageId": "python",
  "command": [
    "delance-langserver",
    "--stdio"
  ],
  "settings": {
    "python.analysis": {
      "autoImportCompletions": true,
      "typeshedPaths": [],
      "stubPath": "",
      "useLibraryCodeForTypes": true,
      "diagnosticMode": "openFilesOnly",
      "typeCheckingMode": "basic",
      "logLevel": "verbose",
      "autoSearchPaths": true,
      "extraPaths": []
    },
    "pythonPath": "python",
    "venvPath": ""
  }
}

```

但是我的配置没有任何效果

**Comment by nanakura** [comment]
似乎  (setq lsp-bridge-user-langserver-dir "~/.emacs.d/langserver")这个失效了，但是手动添加配置到本地repo是有效果的

**Comment by manateelazycat** [comment]
没看懂

**Comment by nanakura** [comment]
> 没看懂

我想设置一个文件夹放json配置，但是失败了，只能手动添加配置到repo里的langserver文件夹

**Comment by manateelazycat** [comment]
> lsp-bridge-user-langserver-dir

你的json文件叫什么？

**Comment by nanakura** [comment]
> (setq lsp-bridge-user-langserver-dir "~/.emacs.d/langserver")

,我使用`(setq lsp-bridge-user-langserver-dir "~/.emacs.d/langserver")`没有效果
我的 json是`delance.json`
```json
{
  "name": "delance",
  "languageId": "python",
  "command": [
    "delance-langserver",
    "--stdio"
  ],
  "settings": {
    "python.analysis": {
      "autoImportCompletions": true,
      "typeshedPaths": [],
      "stubPath": "",
      "useLibraryCodeForTypes": true,
      "diagnosticMode": "openFilesOnly",
      "typeCheckingMode": "basic",
      "logLevel": "verbose",
      "autoSearchPaths": true,
      "extraPaths": []
    },
    "pythonPath": "python",
    "venvPath": ""
  }
}
```

**Comment by manateelazycat** [comment]
lsp-bridge-multi-lang-server-mode-list 变亮是什么内容？

**Comment by nanakura** [comment]
> lsp-bridge-multi-lang-server-mode-list 变亮是什么内容？

![image](https://github.com/user-attachments/assets/5af69dbe-b33b-4525-a7b1-1270267cf101)
感觉跟lsp-bridge-multi-lang-server-mode-list没关系，就是单纯的lsp-bridge-user-langserver-dir失效了，它没有去我指定的目录找配置，log如下
```elisp
Eval in Emacs: (lsp-bridge--first-start '54855)
Traceback (most recent call last):
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 643, in event_dispatcher
    getattr(self, func_name)(*func_args)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 930, in _do
    open_file_success = self.open_file(filepath)  # _do is called inside event_loop, so we can block here.
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 730, in open_file
    return self.load_single_lang_server(project_path, filepath)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 768, in load_single_lang_server
    lang_server_info = load_single_server_info(single_lang_server)
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 1044, in load_single_server_info
    with open(lang_server_info_path, encoding="utf-8", errors="ignore") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Islatan\\AppData\\Roaming\\.emacs.d\\straight\\build\\lsp-bridge\\langserver\\delance.json'

```

**Comment by nanakura** [comment]
> > lsp-bridge-multi-lang-server-mode-list 变亮是什么内容？
> 
> ![image](https://private-user-images.githubusercontent.com/69560752/395929357-5af69dbe-b33b-4525-a7b1-1270267cf101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTMzNTEsIm5iZiI6MTczNDMxMzA1MSwicGF0aCI6Ii82OTU2MDc1Mi8zOTU5MjkzNTctNWFmNjlkYmUtYjMzYi00NTI1LWE3YjEtMTI3MDI2N2NmMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAxMzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYmVmYjliNWU2MzkyNTJlZjRlMTE3N2E5NjNkOWVhZGM1MzJlMGQwODQzMDVhZjFmNzk1MmY4ZTFlYWM4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KnYcEknsfjQu_G6uyB2erE5ApcbCs7fe9l9MrcR78t8) 感觉跟lsp-bridge-multi-lang-server-mode-list没关系，就是单纯的lsp-bridge-user-langserver-dir失效了，它没有去我指定的目录找配置，log如下
> 
> ```emacs-lisp
> Eval in Emacs: (lsp-bridge--first-start '54855)
> Traceback (most recent call last):
>   File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 643, in event_dispatcher
>     getattr(self, func_name)(*func_args)
>     ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
>   File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 930, in _do
>     open_file_success = self.open_file(filepath)  # _do is called inside event_loop, so we can block here.
>   File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 730, in open_file
>     return self.load_single_lang_server(project_path, filepath)
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 768, in load_single_lang_server
>     lang_server_info = load_single_server_info(single_lang_server)
>   File "c:\Users\Islatan\AppData\Roaming\.emacs.d\straight\build\lsp-bridge\lsp_bridge.py", line 1044, in load_single_server_info
>     with open(lang_server_info_path, encoding="utf-8", errors="ignore") as f:
>          ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Islatan\\AppData\\Roaming\\.emacs.d\\straight\\build\\lsp-bridge\\langserver\\delance.json'
> ```

解决了，路径不能用“~/”
