### ISSUE TITLE
golang 自动补全消失

### ISSUE THREAD

**Issue by yinchunlong-rgb** [manateelazycat/lsp-bridge#1126]
环境：windows
问题:
1.打开一个go  工程的.go文件， 第一次能自动补全；
2.使用lsp-bridge-find-def 跳转到另一个文件，不能补全，但是可以查看引用
3.使用emacs内置的find-file指令打开新的go文件，能自动补全

**Comment by manateelazycat** [comment]
可以给测试代码吗？

**Comment by yinchunlong-rgb** [comment]
破案了！
1.能补全的情况(c盘小写)：Eval in Emacs: (lsp-bridge-completion--record-items '"c:/Users/oj/project/gotest/main.go
2.不能补全的时候(c盘大写)：Eval in Emacs: (lsp-bridge-completion--record-items '"C:/Users/oj/project/gotest/testp/test.go

lsp-bridge--with-file-buffer ---->>> lsp-bridge-get-match-buffer-by-filepath  名字匹配不上

额外：通过lsp-bridge-find-def 跳转到另一个文件的时候，诊断信息也是同样的问题（大写c盘）
Eval in Emacs: (lsp-bridge-diagnostic--render '"C:/Users/oj/project/gotest/testp/test.go

辛苦大佬改一下，我还不会改， 学习中。。。。

**Comment by yinchunlong-rgb** [comment]
```
(defun lsp-bridge-get-match-buffer-by-filepath (name)
  (cl-dolist (buffer (buffer-list))
    (with-current-buffer buffer
      (when-let* ((file-name (buffer-file-name buffer))
                  (match-buffer (or (string-equal (downcase file-name) (downcase name))
                                    (string-equal (file-truename file-name) name))))
        (cl-return buffer)))))
```

我现在是先转换小写再比较，暂时用起来了，速度真快，大佬牛逼

**Comment by manateelazycat** [comment]
我推送了补丁 https://github.com/manateelazycat/lsp-bridge/commit/2031e6d2d2dddb66410a772becdae8814a2e7963 修复这个问题， 有任何问题欢迎继续反馈。

感谢。 ：）
