### ISSUE TITLE
lsp-bridge-ref-get-match-buffer 报错

### ISSUE THREAD

**Issue by yinchunlong-rgb** [manateelazycat/lsp-bridge#1130]
操作系统：windows

表现：golang 查找引用后，不能打开对应的文件

![img_v3_02hp_a2b12f2d-ad22-41e5-9b64-5a0d1bb9e95g](https://github.com/user-attachments/assets/cc4b0f8d-e31f-4cf0-b182-3e36e2ebaac1)

我这样改了下，可以用，原因未知。

**Comment by manateelazycat** [comment]
可以给我重现的测试代码吗？ 谢谢

**Comment by deangl** [comment]
我也遇到这个问题，和语言无关。看上去是因为 (buffer-file-name #<buffer *lsp-bridge-ref*>)之类的返回了 nil。这里是不是不需要轮整个buffer-list呀？

**Comment by manateelazycat** [comment]
应该是 https://github.com/manateelazycat/lsp-bridge/commit/2031e6d2d2dddb66410a772becdae8814a2e7963 引起的， 最新版已经修复。
