### ISSUE TITLE
retrieving document symbols

### ISSUE THREAD

**Issue by serezlan** [manateelazycat/lsp-bridge#1131]
Hi,

This is more of a questions. Pleas let me know if there's more appropriate place to ask.

I need to generate test command which requires namespace, class and method information. In lsp-mode, i query document-symbols at current pos and parse the result.
However I still haven't wrapped my head around lsp bridge async nature.
Can someone point me on how to retrieve this info?

Thx

**Comment by manateelazycat** [comment]
lsp-bridge-workspace-list-symbol-at-point

lsp-bridge-workspace-list-symbols
