### ISSUE TITLE
更新到最新版以后（c349dd9），Java lsp server 启动出错

### ISSUE THREAD

**Issue by ginqi7** [manateelazycat/lsp-bridge#120]
![image](https://user-images.githubusercontent.com/1028971/169464801-f3f8602b-08df-40f1-ab06-3e571241e7ac.png)

**Comment by manateelazycat** [comment]
怎么重现呢？

**Comment by ginqi7** [comment]
按照 eamcs -Q -l init.el 按照 ReadMe 里的初始化配置。然后打开任意的 Java 文件，*lsp-bridge* buffer 里展示的就是如截图的出错。

**Comment by ginqi7** [comment]
我这边测试，如果引入 (require 'lsp-bridge-jdtls)  那么 lsp server 启动就会有问题。
如果不引入就无法进行补全和其他lsp action

**Comment by ginqi7** [comment]
初步定位，应该是我环境里的 jdtls 有问题，我重新下载最新的试试看

**Comment by ginqi7** [comment]
果然 jdtls 的问题，替换后已经正常。

**Comment by ddling** [comment]
> 果然 jdtls 的问题，替换后已经正常。

jdtls 的build在哪里下载，貌似官网的都没有下载速度

**Comment by ginqi7** [comment]
https://download.eclipse.org/jdtls/milestones/1.23.0/ 

我看官方下载网络挺好的呀。应该也没被墙。
