### ISSUE TITLE
删除字符过程中，触发自动补全，导致删掉的字符又被补了回来

### ISSUE THREAD

**Issue by jadestrong** [manateelazycat/lsp-bridge#135]
在 volar 中，编辑 css 时，很容易触发这个问题。

比如，输入 `padding: 2px` ，在输入过程中，并没有选中候选项的操作，只是当输入完成 `2px` 的最后一个 `x` 之后，如果侯选项里面存在符合的选项时就会触发 `corfu-insert` 并调用 `exit-function` ;

所以，感觉是删除的时候，同样满足了这个条件时就会触发补全，所以会删不掉。

![image](https://user-images.githubusercontent.com/18475217/170035098-fc5dff7f-4f2f-4aa5-a269-4e2e62df0d08.png)

**Comment by manateelazycat** [comment]
目前看是 doom-emacs + evil 会遇到这个问题，原生Emacs -Q没有这个问题。

**Comment by georgealbert** [comment]
我用evil，python的代码也是有这个问题，删除一个函数最后的字母后会自动补齐，如图中代码把`get_emacs_version()`的最后一个`n`删掉后，自己再加上一个n，get_emacs_versionn() 就多一个。按`u`键undo还是会自动补一个n上去，就有2个n了。

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5278617/170157306-ff34f859-125e-428a-b9e5-11ab7b8a411e.png">

**Comment by manateelazycat** [comment]
> 我用evil，python的代码也是有这个问题，删除一个函数最后的字母后会自动补齐，如图中代码把`get_emacs_version()`的最后一个`n`删掉后，自己再加上一个n，get_emacs_versionn() 就多一个。按`u`键undo还是会自动补一个n上去，就有2个n了。
> 
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/5278617/170157306-ff34f859-125e-428a-b9e5-11ab7b8a411e.png">

目前看不是 lsp-bridge 的问题，更像 evil 和 corfu 配合会出现的问题。

**Comment by georgealbert** [comment]
好的。如果删掉的话也可以再按tab补齐的，但是自己手工输入的话就不行了。最近代码写得少，这个issue影响不大。。。

**Comment by jadestrong** [comment]
```
(setq corfu-on-exact-match 'quit)
```
可以试试设置下这个

当输入匹配出的侯选项只有一个的时候，默认是会自动插入，这会触发 exit-function 执行，然后会触发文件更新 ,文件变化又会触发 lsp-bridge 的监听，它会触发 didChange 和 completion 请求，请求回来又会触发 corfu 出弹窗，因为只有一个，又会自动插入，所以这里就会出现循环。

我这里加上上面那句，改成只有一个惟一匹配的时候退出就好了。

**Comment by manateelazycat** [comment]
可以试一下 https://github.com/manateelazycat/lsp-bridge/pull/141 这个补丁的方法，看看是不是 evil 在 command 模式下自动插入了？

**Comment by georgealbert** [comment]
收到。我试试

**Comment by manateelazycat** [comment]
> 收到。我试试

注意，你要用 

```(add-to-list 'lsp-bridge-enable-popup-predicates
                        '((lambda ()
                            (and
                            (< corfu--index 0) ; not select a candidate
                            (or (not (featurep 'evil)) (evil-insert-state-p)))))
```

**Comment by manateelazycat** [comment]
> ```
> (setq corfu-on-exact-match 'quit)
> ```
> 
> 可以试试设置下这个
> 
> 当输入匹配出的侯选项只有一个的时候，默认是会自动插入，这会触发 exit-function 执行，然后会触发文件更新 ,文件变化又会触发 lsp-bridge 的监听，它会触发 didChange 和 completion 请求，请求回来又会触发 corfu 出弹窗，因为只有一个，又会自动插入，所以这里就会出现循环。
> 
> 我这里加上上面那句，改成只有一个惟一匹配的时候退出就好了。

你说的问题已经被 https://github.com/manateelazycat/lsp-bridge/commit/6c6aa6f840a638ba402315f457f4ef2595e07d2c 修复了
