### ISSUE TITLE
How to support Inlay Hints in Rust

### ISSUE THREAD

**Issue by e190** [manateelazycat/lsp-bridge#137]
https://rust-analyzer.github.io/manual.html#inlay-hints
![图片](https://user-images.githubusercontent.com/39932163/170226230-5e3a74ed-eaad-427b-bf95-d127bb7ba276.png)

And Lsp-mode also has this function
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-analyzer/#inlay-hints

**Comment by manateelazycat** [comment]
Inlay Hints 这个会影响性能，暂时不想支持，抱歉。

**Comment by smallstepman** [comment]
@manateelazycat would you be open to reconsidering? I'd be happy to take a performance hit, but not having inlay hints in rust makes this package a no-go for me

**Comment by manateelazycat** [comment]
inlay hint has implement by https://github.com/manateelazycat/lsp-bridge/commit/0ad8afb5fccf4ec0f3295698908db2d769728181

But Emacs' overlay is buggy, overlay will infect buffer's content if turn this feature in realtime.

**Comment by manateelazycat** [comment]
@e190 @smallstepman lsp-bridge newest version has implement inlay hint, control by option `lsp-bridge-enable-inlay-hint`
