### ISSUE TITLE
Feature Request: support completionItem/resolve 

### ISSUE THREAD

**Issue by jadestrong** [manateelazycat/lsp-bridge#139]
`completionItem/resolve` 可以在pre-select侯选项的时候发送该请求，增量获取 `additionalTextEdits` 等信息来实现 volar 等服务的自动引入功能

**Comment by manateelazycat** [comment]
意思就是补全菜单选中发生变化的时候发送一个请求来更新 additionalTextEdits ?

**Comment by jadestrong** [comment]
![image](https://user-images.githubusercontent.com/18475217/170288701-360363ab-a1df-4794-bbf3-193eea294da7.png)

我看 lsp-mode 里面效果是，用户在侯选列表里面切换侯选项的时候会同步发送一个请求，然后拿回来数据之后会和本地的那份数据做一下合并，这样就增量的添加了一些新的字段，当选中侯选项的时候就能够插additionalTextEdits 了

**Comment by manateelazycat** [comment]
@jadestrong [completion_item.py](https://github.com/manateelazycat/lsp-bridge/commit/779bb42266ecf62b67614286051b959690e693bc#diff-d8c0da4d4ab66b6e587bb94f46c30c44c91e95938b6c47bfe0b4687c65129265) has add.

Can you help add auto-import feature ?
