### ISSUE TITLE
lsp-bridge-lang-server-list and lsp-bridge-default-mode-hooks sample config

### ISSUE THREAD

**Issue by haidong** [manateelazycat/lsp-bridge#143]
I am still struggling getting this up and running. I think some sample config for `lsp-bridge-lang-server-list` and `lsp-bridge-default-mode-hooks` would be very useful. (Yes, I know I should learn elisp...).

For example, assuming `clangd` and `pyright` have been installed, get the config for C/C++/Python right. That'll help greatly in adaptation.

Thanks!

**Comment by manateelazycat** [comment]
If you has install clangd and pyright, nothing need config, lsp-bridge will works out of box.

**Comment by anonimitoraf** [comment]
@haidong Check your lsp-bridge buffer for potential error msgs

**Comment by manateelazycat** [comment]
> @haidong Check your lsp-bridge buffer for potential error msgs
> 
> I had to check mine to realize that I had to install epc

Just follow README.

**Comment by haidong** [comment]
> If you has install clangd and pyright, nothing need config, lsp-bridge will works out of box.

Indeed! Awesome.

I now have another issue, related to the the buffer follows the backup files. Not sure where the problem is yet, but will file a different issue.
