### ISSUE TITLE
Backup file is opened in buffer after save

### ISSUE THREAD

**Issue by haidong** [manateelazycat/lsp-bridge#148]
1. Creating Hello World C++ program under `~/messAround/junk` folder called `cpp_tutorial.cc`;
2. Saving file, after which `lsp-bridge` immediately flows the backup file and opens it up in the buffer! In my case, it opens up `~/.saves/'!home!haidong!messAround!junk!cpp_tutorial.cc~'`.

I turned on debugging, and this is the output. Note that I also tested a Python Hello World program and it did the same thing.
```
[yas] Prepared just-in-time loading of snippets (but no snippets found).
Turning on magit-auto-revert-mode...done
Using default formatter emacs-lisp
For information about GNU Emacs and the GNU system, type C-h C-a.
(New file)
Using default formatter clang-format
Wrote /home/haidong/messAround/junk/cpp_tutorial.cc
recover-file: Auto save file ~/messAround/junk/#cpp_tutorial.cc# does not exist
[LSP-Bridge] Start LSP server (clangd) for /home/haidong/messAround/junk/cpp_tutorial.cc...
[LSP-Bridge] Start LSP server (clangd) for /home/haidong/messAround/junk/cpp_tutorial.cc complete, enjoy hacking!
backward-delete-char-untabify: Beginning of buffer [5 times]
Quit
Save file /home/haidong/messAround/junk/cpp_tutorial.cc? (y, n, !, ., q, C-r, C-f, d or C-h) 
Save file /home/haidong/messAround/junk/cpp_tutorial.cc? (y, n, !, ., q, C-r, C-f, d or C-h) !
Saving file /home/haidong/messAround/junk/cpp_tutorial.cc...
Wrote /home/haidong/.saves/!home!haidong!messAround!junk!cpp_tutorial.cc~
[LSP-Bridge] Start LSP server (clangd) for /home/haidong/.saves/!home!haidong!messAround!junk!cpp_tutorial.cc~...
[LSP-Bridge] Start LSP server (clangd) for /home/haidong/.saves/!home!haidong!messAround!junk!cpp_tutorial.cc~ complete, enjoy hacking!
(New file)
Can’t guess python-indent-offset, using defaults: 4
Using default formatter black
Wrote /home/haidong/messAround/junk/hell.py
[LSP-Bridge] Start LSP server (pyright) for /home/haidong/messAround/junk/hell.py...
[LSP-Bridge] Start LSP server (pyright) for /home/haidong/messAround/junk/hell.py complete, enjoy hacking!
Save file /home/haidong/messAround/junk/hell.py? (y, n, !, ., q, C-r, C-f, d or C-h) 
Save file /home/haidong/messAround/junk/hell.py? (y, n, !, ., q, C-r, C-f, d or C-h) !
Saving file /home/haidong/messAround/junk/hell.py...
Wrote /home/haidong/.saves/!home!haidong!messAround!junk!hell.py~
[LSP-Bridge] Start LSP server (pyright) for /home/haidong/.saves/!home!haidong!messAround!junk!hell.py~...
[LSP-Bridge] Start LSP server (pyright) for /home/haidong/.saves/!home!haidong!messAround!junk!hell.py~ complete, enjoy hacking!

```

Here is [`init.el` I used](https://github.com/haidong/haidongUtilities/blob/master/init.el)

Thanks!

**Comment by manateelazycat** [comment]
backup file is your emacs config, not bug of lsp-bridge

you can try my another github plugin auto-save.el

**Comment by haidong** [comment]
>> backup file is cause by your emacs config, not bug of lsp-bridge

That may or may not be the case. The strange thing is before the introduction of `lsp-bridge` into my config, along with its dependencies, I had no such issue.

I just tried your `auto-save`. It works file. One wrinkle for me is since I am a long time Vim/Evil user, running `:w` is second nature to me. Which still caused the `~` tilde backup file being saved and opened! I added `(setq make-backup-files nil)` to avoid it.

I suppose I really should read and learn `elisp`. Anyway, all of this is to say: I'm good now, but be aware that this may come up and get asked in the future.

Impressive and smooth experience for me so far! Thanks for the hard work and wonderful product!

**Comment by manateelazycat** [comment]
> > > backup file is cause by your emacs config, not bug of lsp-bridge
> 
> That may or may not be the case. The strange thing is before the introduction of `lsp-bridge` into my config, along with its dependencies, I had no such issue.
> 
> I just tried your `auto-save`. It works file. One wrinkle for me is since I am a long time Vim/Evil user, running `:w` is second nature to me. Which still caused the `~` tilde backup file being saved and opened! I added `(setq make-backup-files nil)` to avoid it.
> 
> I suppose I really should read and learn `elisp`. Anyway, all of this is to say: I'm good now, but be aware that this may come up and get asked in the future.
> 
> Impressive and smooth experience for me so far! Thanks for the hard work and wonderful product!

Thank you for your kind words, enjoy lsp-bridge. ;)
