### ISSUE TITLE
revert buffer 后（文件在emacs 外修改) client/server 两端文件内容、光标定位等出现不一致，出现补全错乱

### ISSUE THREAD

**Issue by jixiuf** [manateelazycat/lsp-bridge#158]
eglot 里有对对 `before-revert-hook` 与`'after-revert-hook` 进行处理
```
    (add-hook 'before-revert-hook 'eglot--signal-textDocument/didClose nil t)
    (add-hook 'after-revert-hook 'eglot--after-revert-hook nil t)
```
可以参考。
本想提个pr ,但代码没看太懂。

**Comment by manateelazycat** [comment]
> eglot 里有对对 `before-revert-hook` 与`'after-revert-hook` 进行处理
> 
> ```
>     (add-hook 'before-revert-hook 'eglot--signal-textDocument/didClose nil t)
>     (add-hook 'after-revert-hook 'eglot--after-revert-hook nil t)
> ```
> 
> 可以参考。 本想提个pr ,但代码没看太懂。

可以参考lsp-bridge的renameFiles协议来实现，revert之前关闭文件，revert后重新打开文件。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/3f546d441caa016a4364b5e44555d972d8af6a27

这个补丁应该修复了，我看了 eglot 的源码，就是 revert 之前 close file, revert 以后 open file.

lsp-bridge 已经做了 close file 处理，open file 不用处理，lsp-bridge 会自动在合适的机会 open file.
