### ISSUE TITLE
当使用 lsp-bridge-show-signature-help-in-minibuffer command 的时候报越界问题

### ISSUE THREAD

**Issue by zhongke** [manateelazycat/lsp-bridge#161]
emacs 28.1
Suse Linux

![list_out_of_range](https://user-images.githubusercontent.com/490275/170871614-b3d4ebba-0d99-4922-bc3b-094371f3d5a5.JPG)

**Comment by manateelazycat** [comment]
请打开日志选项 `(setq lsp-bridge-enable-log t)` 后重新测试，出错以后，请把 `*lsp-bridge*` buffer 的内容粘贴一下， 看了日志以后应该可以快速修复， 谢谢。

**Comment by manateelazycat** [comment]
已经修复
