### ISSUE TITLE
Some small bugs with using Corfu-doc

### ISSUE THREAD

**Issue by WindWang2** [manateelazycat/lsp-bridge#169]
1. Disable modeline shown in doc frame.
![q1](https://user-images.githubusercontent.com/7421840/171092794-72486b07-14ed-4ea5-8cc0-127218625ce3.png)
Update: It (gfm-view-mode) can be disable by `hide-mode-line `package.

2. Selecting the tabnine item (tabnine-capf) will promote error information in minibuffer due to no doc. 
![q2](https://user-images.githubusercontent.com/7421840/171093229-bd13bbff-1dbc-4e60-837d-bdad546b77e4.png)

Thanks.

**Comment by manateelazycat** [comment]
You need restart Emacs after upgrade lsp-bridge.

**Comment by theFool32** [comment]
@WindWang2 I issue PR #170. Please kindly check whether it solves this problem :)

**Comment by WindWang2** [comment]
> @WindWang2 I issue PR #170. Please kindly check whether it solves this problem :)

It works, thank you very much.
