### ISSUE TITLE
Go 只能在 '.' '=' '\' 等符号以后才会触发代码补全

### ISSUE THREAD

**Issue by ginqi7** [manateelazycat/lsp-bridge#171]
测试的 lsp-bridge commit: d4915643
使用 README 当中推荐的配置，emacs -Q 启动。
测试代码如下：
``` go
package main
import "fmt"
func hello0001() {
	fmt.Println("hello world")
}

func main() {
	world := "new world"
	fmt.Println("hello world")
	
	
}
```

当我想要在 main 函数中，使用变量 ‘world’ 或者函数 ’hello0001‘，并不会进行代码补全。只有使用非英文字母时会弹出补全窗口。

![image](https://user-images.githubusercontent.com/1028971/171170244-6d8693a5-fc02-4a7e-94bb-aedf947d99ec.png)
![image](https://user-images.githubusercontent.com/1028971/171169924-e9fb4d7f-866e-4d93-b8dc-2398b8a8474d.png)

其他，如果 `hello0001` 定义在 `main` 后面，hello函数无法补全。

**Comment by manateelazycat** [comment]
![2022-05-31 23-53-13 的屏幕截图](https://user-images.githubusercontent.com/237487/171216728-ef7b08a8-7487-4d58-b8e0-e7c129073dbc.png)
我可以呀。

请检查 https://github.com/manateelazycat/lsp-bridge/blob/d4915643a8e4ccf59f67ce9c2dbeab932dc14665/lsp-bridge.el#L558 这里的每个函数，看看是不是有失败的函数？

**Comment by ginqi7** [comment]
打开，(setq lsp-bridge-enable-log t) 
定位到问题：
![image](https://user-images.githubusercontent.com/1028971/171323840-b67baa44-b50f-4140-b148-ced0161dcc49.png)
应该是 gopls 的使用问题。需要首先创建一个 go module 才能正常的进行代码补全。
``` shell
go mod init example.com/hello
```
![image](https://user-images.githubusercontent.com/1028971/171324329-d14dc08a-8799-4db6-a0bc-b3fdff868f4a.png)
