### ISSUE TITLE
get yas-condidate from (yas--get-snippet-tables)

### ISSUE THREAD

**Issue by ShuguangSun** [manateelazycat/lsp-bridge#186]
It seems in the current implementation that the snippets are read from the `yas/root-dir`. However, the yasnippet provided a function `yas--get-snippet-tables` to get snippet tables if using jit. It may be more convenient to using this `yas--get-snippet-tables` way.

**Comment by manateelazycat** [comment]
`yas--get-snippet-tables` is too slow.
