### ISSUE TITLE
写Python代码时，在import后输入待引入模块名字，选定特定模块，回车之后，补全候选框继续出现

### ISSUE THREAD

**Issue by md11235** [manateelazycat/lsp-bridge#192]
比如输入

import sys

之后，在我的电脑上此时补全候选提示框的内容为：
syslog Module
sysconfig Module
sys Module
mmsystem Module

然后我用alt+n选中sys Module，按下回车，紧接着上面所示的补全候选提示框的内容依然出现。

**Comment by manateelazycat** [comment]
最新版已经修复，谢谢反馈。
