### ISSUE TITLE
golang 出现多插入字符的情况

### ISSUE THREAD

**Issue by zy9306** [manateelazycat/lsp-bridge#196]
https://user-images.githubusercontent.com/18747432/172763625-2ced3690-c21a-450e-87f5-4bcf35e7ce81.mov

emacs -Q 测试的（我这边开了日志非常卡，几乎出不了正常的补全，这边暂时没有日志，看看能不能复现）

**Comment by manateelazycat** [comment]
已经修复了，感谢反馈。
