### ISSUE TITLE
The complete popup frame display on main display when emacs frame is display on extend display

### ISSUE THREAD

**Issue by xqliu** [manateelazycat/lsp-bridge#198]
Hi, thanks for the great plugin, that's really very smooth and fast!!

I have meet an behaviour, not sure whether it's a bug, just record here for reference

## Description

I have an extend display setup connected to my laptop, observe a strange behaviour 

The complete popup frame been displayed on main display when emacs frame is display on extend display,

## Screenshot

can refer to follow screen shot for reference

This is the content on extend display

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/22554/172842126-c9d0311a-e9ad-4bd7-b7ba-d508e7848d75.png">

This is the content on main display

<img width="879" alt="image" src="https://user-images.githubusercontent.com/22554/172842171-21938f17-e258-4c85-8188-2bf86d4f9848.png">

The popup posframe is suppose to be display on the extend display instead of main display

## How to reproduce 

1. Open emacs on the laptop display 
2. Run make-frame to create another frame and move it to make it display on the extend display 
3. Create a java file and when editing the file, the complete posframe displays on laptop display instead of current cursor point

## Emacs settings

```
;; lombok support
(setq lombok-path (substitute-in-file-name "$HOME/dotfiles/private/libraries/lombok.jar"))
(setq lsp-bridge-jdtls-jvm-args (format "%s%s" "-javaagent:" lombok-path))

(setq acm-fetch-candidate-doc-delay 1)
(setq acm-enable-doc nil)
(setq acm-enable-dabbrev t)
(setq lsp-bridge-enable-log nil)
(setq lsp-bridge-org-babel-lang-list '("python" "java"))

(require 'yasnippet)
(require 'lsp-bridge)
;; provide Java third-party library jump and -data directory support, optional
(require 'lsp-bridge-jdtls)

(yas-global-mode 1)
(global-lsp-bridge-mode)
```

Thanks for the great work again :)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/d5c689ef70e6213d4ed472a84b966692b4040e76/acm/acm.el#L526

Change `(window-pixel-edges)` to `(window-absolute-pixel-edges)` , it will fixed your problem?

**Comment by xqliu** [comment]
Yes your suggestion fixes the issue !!

Great 👍 

> https://github.com/manateelazycat/lsp-bridge/blob/d5c689ef70e6213d4ed472a84b966692b4040e76/acm/acm.el#L526
> 
> Change `(window-pixel-edges)` to `(window-absolute-pixel-edges)` , it will fixed your problem?
