### ISSUE TITLE
acm macos 窗口漂移

### ISSUE THREAD

**Issue by stepdc** [manateelazycat/lsp-bridge#199]
更新 [5a6f294](https://github.com/manateelazycat/lsp-bridge/commit/5a6f2940d0422e77f0a9beb2e8a9f7df085fb324)之后，acm补全窗口位置出现漂移。emacs 放在屏幕左面和右面漂移的程度也不一样。

![20220609220459-convert](https://user-images.githubusercontent.com/17965049/172866874-0e37754a-523f-4384-a16d-abd28bb61602.gif)

环境 macos 12.4， 用外接屏幕：
![image](https://user-images.githubusercontent.com/17965049/172867431-7c42c365-ff1f-4750-b847-3c8652366dad.png)

配置：
```
(add-to-list 'load-path "~/.emacs.d/site-lisp/lsp-bridge")
(add-to-list 'load-path "~/.emacs.d/elpa-28.1/posframe-20220528.27")
(add-to-list 'load-path "~/.emacs.d/elpa-28.1/markdown-mode-20220603.300")
(add-to-list 'load-path "~/.emacs.d/elpa-28.1/go-mode-20220114.2239")
(require 'posframe)
;;(require 'yasnippet)
(require 'lsp-bridge)
;; (require 'lsp-bridge-jdtls)       ;; provide Java third-party library jump and -data directory support, optional

(yas-global-mode 1)
(global-lsp-bridge-mode)
(require 'go-mode)
```

外接显示器在左面，如果把emacs放到右面笔记本的窗口里，补全的窗口会消失不可见；所有缩放都关闭了也是同样的效果。

**Comment by stepdc** [comment]
是双屏，之前没有问题

**Comment by manateelazycat** [comment]
看来要针对 macOS 单独处理，已经修复了，更新吧，感谢反馈。

**Comment by WindWang2** [comment]
> 看来要针对 macOS 单独处理，已经修复了，更新吧，感谢反馈。

可是 Manjaro 更新后（[c937ee6](https://github.com/manateelazycat/lsp-bridge/commit/c937ee64e4efab204e6e300108601d536d103875)）出现这个问题，此前（[d5c689e](https://github.com/manateelazycat/lsp-bridge/commit/d5c689ef70e6213d4ed472a84b966692b4040e76)）没有问题的，也是双屏。
![1](https://user-images.githubusercontent.com/7421840/172969040-f6ee9f60-9d5e-4f79-a92b-db8bf48b6503.png)

**Comment by manateelazycat** [comment]
那我先回滚吧

**Comment by manateelazycat** [comment]
今天我发现如果只有一个 frame 的时候， 这个 frame 在不同的屏幕上， 补全菜单的位置都是对的。

但是如果用户在不同的屏幕上使用不同的 frame 时， acm 菜单只会在第一个 frame 上显示， 所以补全菜单的位置是错的。

已经推送了一个补丁， 在弹出补全菜单之前先检查一下 acm 菜单的 parent 和 (selected-frame) 是否一致， 如果不一致证明用户切换了不同 frame 进行操作， 遇到不一致的情况先删除 acm 菜单后新建就好了。

https://github.com/manateelazycat/lsp-bridge/commit/006a34b50da3db87500203ab319aa85f46029706
