### ISSUE TITLE
Is there any way to set the width of popup frame?

### ISSUE THREAD

**Issue by xqliu** [manateelazycat/lsp-bridge#202]
Hi, 

Would like to know is there any way to set width of the popup frame?

For some languages, like java, the package name is normally quite long, like below

<img width="730" alt="image" src="https://user-images.githubusercontent.com/22554/173111641-d9fa49b0-6034-4138-8aab-40cb6b6f3b3d.png">

And it's hard to see the full package name, while there's still some space left on the right side of the package name left.

For example, it will become an issue if a project contains both apache common utils and common utils version 3... because the name of the package is both starts with `org.apache.common....`, so it will be shown exactly the same in the package part.

Is there any custom settings for the frame width? have checked `defcustom` in both acm.el and lsp-bridge.el, seems didn't find a suitable setting for this?

Thanks.

**Comment by manateelazycat** [comment]
Please custom acm-backend-lsp-candidate-limit
