### ISSUE TITLE
one-key 调用 next-diagnostic 或 prev-diagnostic 之后，Diagnostic tooltip 闪了一下就消失

### ISSUE THREAD

**Issue by SuperMMX** [manateelazycat/lsp-bridge#203]
重现方法：

test-init.el

```
(require 'one-key)
(require 'posframe)
(require 'lazy-load)
(require 'seq)
(require 'yasnippet)
(require 'lsp-bridge)

;; Java
(require 'lsp-bridge-jdtls)

(global-lsp-bridge-mode)

(one-key-create-menu
 "LSP"
 '(
   (("n" . "Next Diag") . lsp-bridge-jump-to-next-diagnostic)
   (("p" . "Prev Diag") . lsp-bridge-jump-to-prev-diagnostic)
   )
 t)

(lazy-load-set-keys
 '(
   ("C-c l" . one-key-menu-lsp)
   ))
```

Test.java
```

import java.util.List;

public class Test {
    public static void main(String[] args) {
    }
}

```

开启 lsp-bridge 之后，"import java.util.List" 这行会有一个警告，`M-x lsp-bridge-jump-to-next-diagnostic` 没有问题，posframe 会出现。但用 `C-c l n` 或 `C-c l p` 就会发现 posframe 闪了一下就没了。

研究发现因为 `lsp-bridge-monitor-post-command` 中判断 `this-command` 如果不是 "next-diagnostic" 或 "prev-diagnostic"，就隐藏 diag 信息。而使用 one-key 调用的 `this-command` 是 "one-key-menu-xxx"，所以就隐藏了。如果是 M-x 或者其他方法直接调用则没问题。

再想办法解决，主要就是 post-command-hook 中的 `this-command` 不对，再研究了一番发现这个是可以改的，所以可以在 `one-key-menu` 中设成真正运行的命令。

PR 在路上……

**Comment by manateelazycat** [comment]
感谢补丁，研究很深刻，👍
