### ISSUE TITLE
打开 vue 文件报错

### ISSUE THREAD

**Issue by laampui** [manateelazycat/lsp-bridge#206]
[LSP-Bridge] Process restarted.
[LSP-Bridge] Start LSP server (volar) for /home/laampui/Documents/vite-project/src/App.vue...
[LSP-Bridge] Request initialize failed with message: Cannot find module ’/usr/lib/node_modules/typescript/lib/tsserverlibrary.js’
Require stack:
- /home/laampui/.nvm/versions/node/v16.14.2/lib/node_modules/@volar/vue-language-server/out/node.js
- /home/laampui/.nvm/versions/node/v16.14.2/lib/node_modules/@volar/vue-language-server/bin/vue-language-server.js

**Comment by manateelazycat** [comment]
你要用npm在全局安装 typescript

**Comment by laampui** [comment]
全局安装了之后，*.vue 文件一直返回 0 个补全项，*.ts 文件倒是正常...
![录屏_emacs_20220614201649](https://user-images.githubusercontent.com/15785343/173575227-80f5587b-5f48-496d-9dd5-2e8984729a14.gif)
