### ISSUE TITLE
Suggestion: better strategy for project choosing

### ISSUE THREAD

**Issue by Commelina** [manateelazycat/lsp-bridge#210]
I have tried the project and it is blazing fast. Thanks for you developers! However, it failed when I ran it on an example Haskell project:

```
Eval in Emacs: (message '"[LSP-Bridge] Error on initialize: /home/commelina/Code/hs-example/app/Main.hs: changeWorkingDirectory: inappropriate type (Not a directory)")
```

Then I turned on the debug mode and found that it sent an incorrect message to the server while initializing:

```
--- Send (15630): initialize
{
   "id": 15630,
   "method": "initialize",
   "params": {
   "rootPath": "/home/commelina/Code/hs-example/app/Main.hs",
   ...
   },
   ...
   "rootUri": "file:///home/commelina/Code/hs-example/app/Main.hs",
   ...
}
```

Apparently, the client did not get the correct project path. Then I found that the logic is all defined in `get_project_path` of `core/utils.py`, which depends on VCS(actually, git) only. When this strategy fails it will just return the file path without any other consideration. Unfortunately, my simple example project was not configured by git and it fails with some very weird error message.

To reach a better user experience, I am wondering if the client can add more strategies to determine the project root(for example, let the user choose or determine by language-specific config file). Also, a warning message may be needed when the client can not determine it in order to avoid weird errors from the server.

**Comment by manateelazycat** [comment]
If the LSP-Bridge detects the .git in project, it will treat the current project as a directory. If it do not see .git, it will treat the current file as a single file to provide LSP completion, such as, python can completion single file and don't need .git directory.

I think best way is do `git init` in your project directory, and is simplest way.

**Comment by jixiuf** [comment]
不是所有的语言都是一个git 一个项目 比如有些go的项目 一个git下的多个目录下会有各自的go.module gopls需要找对go.module 才能正常工作 eglot的处理方式是使用project 那针对go这种场景 就可以通过一下代码来更改project-root 很灵活
再说project 带来的性能损失应该不大 还是建议能进行支持 
```
(defun project-find-go-module (dir)
  (when-let ((root (locate-dominating-file dir "go.mod")))
    (cons 'go-module root)))

(cl-defmethod project-root ((project (head go-module)))
  (cdr project))

(add-hook 'project-find-functions #'project-find-go-module)
```

**Comment by manateelazycat** [comment]
> project-root

我一直反对的是 `project-root` 有时候是不准的， snails 经常遇到 proejct 不准的问题。

**Comment by jixiuf** [comment]
> 

那就调查不准的原因，

就算最终找不到原因，你也可以通过我上面的代码调整`project-find-functions` 来强制使用`git` 来定位`project-root`.
使用`git` 来强制定位`project-root` ,感觉不太通用。

**Comment by manateelazycat** [comment]
> > 
> 
> 那就调查不准的原因，
> 
> 就算最终找不到原因，你也可以通过我上面的代码调整`project-find-functions` 来强制使用`git` 来定位`project-root`. 使用`git` 来强制定位`project-root` ,感觉不太通用。

那是emacs本身 project root 实现的bug，它无法很好的识别 git 嵌套目录。

你最后找到原因后，还是和现在git命令实现的方式一样。

除了git我没有想到更好的通用识别project的方法，我不想基于不靠谱的方法去修N个语言各种特殊识别方法。
