### ISSUE TITLE
clangd trying to get preamble for non-added document

### ISSUE THREAD

**Issue by nesteiner** [manateelazycat/lsp-bridge#213]
https://user-images.githubusercontent.com/46296608/173568182-ba0326c0-3b21-4969-b143-b21c170758cc.mp4

**Comment by nesteiner** [comment]
再试试这个程序  

https://user-images.githubusercontent.com/46296608/173579344-53fa80d9-f70d-4a5c-950a-afc0a6286799.mp4

**Comment by manateelazycat** [comment]
暂时无法重现，原因未知。

**Comment by AllTheLife** [comment]
我也遇到了这个问题，我排查了一下配置，发现这个应该是lsp-bridge与其他package的冲突，但因为无法稳定重现，所以没法准确定位。可能与以下几个packages有关。希望 nesteiner 大佬可以和我一起比对一下，找出根源；或者能帮忙给出一种准确复现的方法，我来排查。

- beacon
- rainbow-delimiters
- meow
- puni
- auto-save

**Comment by ErinaInit** [comment]
我现在也有这个问题, 之后看看能不能构造一个最小可复现案例......
