### ISSUE TITLE
Bug on word search: not breaking candidates correctly

### ISSUE THREAD

**Issue by adouzzy** [manateelazycat/lsp-bridge#217]
In python, on lsp-bridge commit 2258117 2022-06-16 (HEAD, origin/master, origin/HEAD) fix pyright-langserver path err in windows which install by npm (#216) [GitHub]

"juice=10" is not broken down as "juice" but "juice10"
![image](https://user-images.githubusercontent.com/1818289/173984055-9378394e-f396-4863-9512-97ae5985f4ae.png)

add space between "=" would fix it
![image](https://user-images.githubusercontent.com/1818289/173984187-aa9261d2-9361-4ba8-93f8-da5b6e4121b5.png)

**Comment by adouzzy** [comment]
I have non-compliant python script below. But I think word splitting is generic regardless of which language it is.
```
juice=10
def foobar(apple:float)->float:
    print(apple);print(1)
    b="asdf"+"foobar"
    return apple
```
Would it make sense if I change in search_file_words.py  as following?
```
words = set(open(search_file).read().split())
```
to 
```
word_split_regex="[\s|\-\>|=|:|;|\(|\)|\{|\}|\[|\]|+|&]"
words = set(re.split(word_split_regex, open(search_file).read()))
```

**Comment by manateelazycat** [comment]
thanks
