### ISSUE TITLE
D语言支持？

### ISSUE THREAD

**Issue by electricface** [manateelazycat/lsp-bridge#223]
对D语言有兴趣吗？
https://ddili.org/ders/d.en/
https://www.zhihu.com/question/24802934/answer/735235973

**Comment by manateelazycat** [comment]
增加新的语言很简单，基本上抄抄 VSCode 的配置就好了。

https://github.com/manateelazycat/lsp-bridge/blob/master/README.zh-CN.md#%E6%B7%BB%E5%8A%A0%E6%96%B0%E7%9A%84%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81
