### ISSUE TITLE
add all-the-icon support for acm completions which a replacement for svg icons

### ISSUE THREAD

**Issue by hathawayANdRX105** [manateelazycat/lsp-bridge#225]
希望能有 像 [糊了一个 corfu 适用的 all-the-icons 的 icon 效果](https://emacs-china.org/t/corfu-all-the-icons-icon/20907) 这种icon示例显示效果。有空慢慢做就行了！！！

**Comment by manateelazycat** [comment]
svg比all-the-icons更好，svg能实现像素对齐，all-the-icons不行。
