### ISSUE TITLE
Any plans to integrate tramp support?

### ISSUE THREAD

**Issue by Blade6570** [manateelazycat/lsp-bridge#231]
I tried lsp-bridge mode on remote files but seems like it does not understand the path starting with '/ssh:server-name:'. Would love to see this support :)

**Comment by manateelazycat** [comment]
no plan，any PR are welcome

**Comment by Blade6570** [comment]
Bitter truth !!

**Comment by manateelazycat** [comment]
PR are welcome, I haven't time to research it.
