### ISSUE TITLE
How to add configuration for python virtual environment

### ISSUE THREAD

**Issue by nicehiro** [manateelazycat/lsp-bridge#232]
Thanks for your great work on lsp-bridge! It's really fast.

I want to config lsp-bridge to use python virtual env. After checking the readme, I modify my `pyrightconfig.json` as follows(only `pythonPath` and `venvPath` has been modified):

```
{
  "name": "pyright",
  "languageId": "python",
  "command": ["pyright-langserver", "--stdio"],
  "settings": {
    "python.analysis": {
      "autoImportCompletions": true,
      "typeshedPaths": [],
      "stubPath": "",
      "useLibraryCodeForTypes": true,
      "diagnosticMode": "openFilesOnly",
      "typeCheckingMode": "basic",
      "logLevel": "verbose",
      "autoSearchPaths": true,
      "extraPaths": []
    },
    "pythonPath": "/Users/wangfangyuan/Projects/deformed/venv/bin/python",
    "venvPath": "/Users/wangfangyuan/Projects/deformed/venv/"
  }
}
```

I also write a simple `lsp-bridge-get-lang-server-by-project` to find the configuration. As we can see from logs, the configuration was loaded correctly:
```
--- Send (notification): workspace/didChangeConfiguration
{
   "method": "workspace/didChangeConfiguration",
   "params": {
      "settings": {
         "python.analysis": {
            "autoImportCompletions": true,
            "typeshedPaths": [],
            "stubPath": "",
            "useLibraryCodeForTypes": true,
            "diagnosticMode": "openFilesOnly",
            "typeCheckingMode": "basic",
            "logLevel": "verbose",
            "autoSearchPaths": true,
            "extraPaths": []
         },
         "pythonPath": "/Users/wangfangyuan/Projects/deformed/venv/bin/python",
         "venvPath": "/Users/wangfangyuan/Projects/deformed/venv/"
      }
   },
   "jsonrpc": "2.0"
}
```

So I guess there's a problem with my config file. But there's no more documents about those variables.

**Comment by manateelazycat** [comment]
我没有看懂你的问题，你是说修改了 pyright.json 配置以后没有补全，还是有啥问题？

**Comment by nicehiro** [comment]
Sorry，是我没写清楚。

是配置了之后启动的还是原来的server，不是虚拟环境中的。

**Comment by EdmondFrank** [comment]
> Sorry，是我没写清楚。
> 
> 是配置了之后启动的还是原来的server，不是虚拟环境中的。

这个应该主要受pyright-langserver的影响，确保这个pyright-langserver的command用到的是虚拟环境中的，我一边会用`bash -c `之类的方式复用用户的环境变量来启动lsp

**Comment by nicehiro** [comment]
> 这个应该主要受pyright-langserver的影响，确保这个pyright-langserver的command用到的是虚拟环境中的，我一边会用`bash -c `之类的方式复用用户的环境变量来启动lsp

哦，也就是说设置那两个变量只是把`python`的环境变量变了，但是server仍然是用外部的。

那我再继续看一下吧，感觉也可以用 `direnv` 来解决。

**Comment by zy9306** [comment]
如果你用 pyvenv 的话，可以看看这个很不优雅的处理方式，因为我不想写入额外的 json，就这么粗暴的处理了

https://github.com/manateelazycat/lsp-bridge/commit/9dd30ddf4a9ab4549bf357020daac56d30bed4e7

https://github.com/zy9306/.emacs.d/blob/master/lisp/init-lsp-bridge.el#L69

**Comment by nicehiro** [comment]
> 后续只需要保证 pythonPath 是你当前虚拟环境的 python 就可以了

请教一下你是如何保证`pythonPath`是当前虚拟环境中的，直接在这个config文件中设置吗？

我现在使用`direnv`在每次进入某个项目时强行设置环境中的`python`，目前是达到我的目的了。

**Comment by zy9306** [comment]
> > 后续只需要保证 pythonPath 是你当前虚拟环境的 python 就可以了
> 
> 请教一下你是如何保证`pythonPath`是当前虚拟环境中的，直接在这个config文件中设置吗？
> 
> 我现在使用`direnv`在每次进入某个项目时强行设置环境中的`python`，目前是达到我的目的了。

https://github.com/manateelazycat/lsp-bridge/commit/9dd30ddf4a9ab4549bf357020daac56d30bed4e7
https://github.com/zy9306/.emacs.d/blob/master/lisp/init-lsp-bridge.el#L69

我是在 pyvenv 的 hook 里搞的，本来是写了这段，但这只是我个人的用法，且极不优雅，就编辑去掉了，总体思路就是进入项目时，且在 server 发送配置前覆盖掉 config，我为了方便不想新增 json 直接改了 lsp-bridge

**Comment by nicehiro** [comment]
@zy9306 好的👌 非常感谢
