### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by anonimitoraf** [manateelazycat/lsp-bridge#233]
Hi Andy, I regularly follow lsp-bridge's progress! I think it's getting closer and closer to perfection. I have 2 questions:

- Is it possible to manually bring up the completion popup? For example, in Typescript, I want to destructure and see what fields exist:
```js
const { | } = someObj // cursor is |
```
- Does auto-import require extra setup? Ive debugged a bit of the code and found that it uses the additionalTextEdits field but that field seems to be empty for all candidates (at least in Typescript)

Thank you!

**Comment by manateelazycat** [comment]
I have push new commint https://github.com/manateelazycat/lsp-bridge/commit/34bf16d8ea0d0ec2ffb0e4555c9034b90d562dfe that remove delay to fetch documentation or additionalTextEdits information.

So auto-import information will ready when you select candidate from menu.

**Comment by manateelazycat** [comment]
Currently, lsp-bridge not support popup completion menu manually, any PR are welcome! ;)

**Comment by anonimitoraf** [comment]
Cool thanks! Will have a look
