### ISSUE TITLE
volar completion may delete the content between the previous marker and the current point.

### ISSUE THREAD

**Issue by EvanMeek** [manateelazycat/lsp-bridge#235]
![lsp-bridge-bug](https://user-images.githubusercontent.com/27056033/175338877-314fc248-4586-468b-a4d9-8cab324370aa.gif)

**Comment by manateelazycat** [comment]
他这个主要是volar服务器

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/f7cfa136ea017915f1e93e3dd35a3324f96ea3d5/acm/acm-backend-lsp.el#L160

加一行 (message "**** %s %s %s" insert-candidate delete-start-pos delete-end-pos)

**Comment by manateelazycat** [comment]
应该是这个原因 https://github.com/manateelazycat/lsp-bridge/commit/0606d7f0f8e330d33696e471433d09b336e8ed98

更新测试一下。

**Comment by EvanMeek** [comment]
> 应该是这个原因 [0606d7f](https://github.com/manateelazycat/lsp-bridge/commit/0606d7f0f8e330d33696e471433d09b336e8ed98)
> 
> 更新测试一下。

测试过已经不会出现错误的情况了！真不错
