### ISSUE TITLE
typescript's completion list is too big and causes too much memory allocation

### ISSUE THREAD

**Issue by zhongweiy** [manateelazycat/lsp-bridge#237]
Hi, 

I'm using lsp-bridge on a typescript project and I find emacs becomes very slow due to a very big completion candiate list.

Here is the profiling result. On the left panel of CPU profiling, 93% time is in GC (the ... part). There is a lot of memory allocation in the `acm-backend-lsp-candidates` function. I print the `acm-backend-lsp-items` size, it is 3793 (even `keyword` is not empty).

<img width="1283" alt="Screen Shot 2022-06-23 at 1 57 46 PM" src="https://user-images.githubusercontent.com/1575247/175441122-1fc7aaf0-b73d-4235-a9c9-8c2f43902980.png">

So do you have any suggestion to improve it?

Appreciate any reply!

**Comment by manateelazycat** [comment]
how much memory in your computer?

**Comment by zhongweiy** [comment]
My laptop is 16 GB memory. I have tried the emacs gc threshold from 100MB to 500MB. But it does not help.

**Comment by manateelazycat** [comment]
In https://github.com/manateelazycat/lsp-bridge/blob/34bf16d8ea0d0ec2ffb0e4555c9034b90d562dfe/acm/acm.el#L458

I have adjust `gc-cons-threshold` to maximize temporary when you call `acm-update`, it should not do GC when completion menu popup.

Can you test `emacs -Q` that only load lsp-bridge and not load any other plugin?

**Comment by zhongweiy** [comment]
Thanks for your suggestion!

I tested with `emacs -Q` and only have `lsp-bridge` enabled during test. But the result does not change: the typing in emacs becomes sluggish gradually due to too much GCing (according to the following profiling result).

In the following screenshot, the left column is the memory profiling. The middle is cpu profiling. I print some log in the right column at this [line in acm-backend-lsp-candidates function](https://github.com/manateelazycat/lsp-bridge/blob/master/acm/acm-backend-lsp.el#L132). I type `a` to `d` in my typescript buffer during the test. 

BTW, I notice the `acm-backend-lsp-candidates` function is called twice for each input, which probably creates more short-live objects and add more memory pressure. 

<img width="1400" alt="Screen Shot 2022-06-24 at 9 07 59 PM" src="https://user-images.githubusercontent.com/1575247/175757474-5bb07fa6-07a6-4883-9819-89484e179a8c.png">

And I was thinking the `(gc-cons-threshold most-positive-fixnum)` won't help for overall performance. Since it only disable GC in that function. After exiting that function, if the garbage object size is big after exiting the function, GC will still be triggered, right?

**Comment by zhongweiy** [comment]
I feel the typescript language server returns so many candidate makes no sense to me. Too much completion candiates will not help me code. 

So I came up a hack to work around this issue. I abandon the completion list at this [core/handler/completion.py#L60](https://github.com/manateelazycat/lsp-bridge/blob/master/core/handler/completion.py#L60) when the candiate list size is larger than a threshold (for now I use 1000). It works for me for now. And also appreciate if you have any other suggestion!

**Comment by zhongweiy** [comment]
And I also have a question regarding this [elisp candidate function](https://github.com/manateelazycat/lsp-bridge/blob/master/acm/acm-backend-lsp.el#L116). Why it filter the "textDocument/completion" response by keyword? I am thinking the response from language server already ensure the response starts with the key word. Am I missing something here?

**Comment by manateelazycat** [comment]
LSP is return candidates by prefix, acm can search candidates by regex again that you don't need type keyword from first char.

**Comment by manateelazycat** [comment]
I have fixed this issue by https://github.com/manateelazycat/lsp-bridge/commit/671ec73acd93b9922aa97762922b91745fd1925c

**Comment by zhongweiy** [comment]
thanks a lot!
