### ISSUE TITLE
cland no signature help information in minibuffer 

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [manateelazycat/lsp-bridge#238]
When working with c/c++ code i get not signature information in minibuffer when i hover on any kind of code ):
![image](https://user-images.githubusercontent.com/62380543/175770713-1c086651-6668-4e67-95c2-6b351917d680.png)
Normally there is signature help info.
![image](https://user-images.githubusercontent.com/62380543/175770742-6192598a-21da-4ee3-a73a-ffde95b7b642.png)

**Comment by manateelazycat** [comment]
you need move cursor into parentheses to show signature help information

**Comment by manateelazycat** [comment]
readme has write `acm-enable-doc`
