### ISSUE TITLE
Two suggestions coming.

### ISSUE THREAD

**Issue by ankitsharma07** [manateelazycat/lsp-bridge#239]
I installed lsp-bridge recently and I am amazed by the performance. However, I uninstalled lsp and lsp for different languages along with lsp-ui. But I am getting the suggestions from that. Is it because of the company setup?

Has anyone else faced this similar issue?

Emacs: doom-emacs
OS: macOS

Attaching screenshots for better understanding.
<img width="389" alt="Screenshot 2022-06-25 at 10 54 12 PM" src="https://user-images.githubusercontent.com/12720159/175784222-bb475f81-84b3-482d-ab36-6012d076336a.png">
<img width="440" alt="Screenshot 2022-06-25 at 10 54 22 PM" src="https://user-images.githubusercontent.com/12720159/175784223-4b81a2f6-c42b-4b3d-8dbb-e5747287bc6f.png">

**Comment by manateelazycat** [comment]
you need remove company,corfu,lsp-mode,lsp-ui
