### ISSUE TITLE
clangd include file expanding doesn't clear placeholders' text

### ISSUE THREAD

**Issue by zhscn** [manateelazycat/lsp-bridge#241]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45552541/175813806-9bc190f1-e228-4db4-82ef-6bbaedf44096.png">
when we type 'c', we expect to clear 'header', insert 'c' and show complete menu, but it not wroks as expected:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45552541/175813903-dbf6b78b-da54-4fb8-83e5-37f4a4d41255.png">
function expand works well
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45552541/175813975-3a4232a2-ad5a-4c04-b6e9-fdbc33afe193.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45552541/175814014-5f786ae3-ddfd-48ce-bca5-5c1ec347a3ee.png">

env:
macOS 12.4 m1
GNU Emacs 29.0.50 (build 2, aarch64-apple-darwin21.5.0, NS appkit-2113.50 Version 12.4 (Build 21F79)) of 2022-06-22
lsp-bridge a2caa0c9fb7dfab9020aab2c696712040e9f2b00

config:

```
(add-to-list 'load-path (expand-file-name "straight/repos/lsp-bridge" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "straight/repos/posframe" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "straight/repos/markdown-mode" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "straight/repos/yasnippet" user-emacs-directory))
(require 'posframe)
(require 'yasnippet)
(require 'lsp-bridge)
(yas-global-mode 1)
(global-lsp-bridge-mode)
```
[log.tar.gz](https://github.com/manateelazycat/lsp-bridge/files/8986609/log.tar.gz)

**Comment by manateelazycat** [comment]
It should issue of yasnippet or behavior of snippet content, lsp-bridge just call `yas-expand-snippet` to expand yasnippet template, lsp-bridge nothing to do with snippet insert or replace, it is yasnippet does.

**Comment by zhscn** [comment]
ok, reproduced with yasnippet.

in this case, clangd returns

```
"insertText": "include <${0:header}>"
```

and build a new snippet item：

```
# -*- mode: snippet -*-
# name: asdf
# key: asdf
# --
include <${0:header}>
```

it also not clears the text of placeholder

**Comment by manateelazycat** [comment]
> ok, reproduced with yasnippet.
> 
> in this case, clangd returns
> 
> ```
> "insertText": "include <${0:header}>"
> ```
> 
> and build a new snippet item：
> 
> ```
> # -*- mode: snippet -*-
> # name: asdf
> # key: asdf
> # --
> include <${0:header}>
> ```
> 
> it also not clears the text of placeholder
> 
> BTW, I test the same case in VSCode and it works as expected.

its bug of yasnippet
