### ISSUE TITLE
Can't find command None for <filepath>, disable lsp-bridge-mode.

### ISSUE THREAD

**Issue by samhedin** [manateelazycat/lsp-bridge#242]
Hi!
While I normally use Doom, I can reproduce this on vanilla emacs as well.

Steps to reproduce:
``` sh
emacs -q
# M-x:
package-install posframe
package-install yasnippet
package-install markdown-mode
load lsp-bridge according to instructions
find-file ~/git/lsp-bridge/lsp_bridge.py
```
Error in \*Messages\*: `[LSP-Bridge] Error: can’t find command None for /home/sam/git/lsp-bridge/lsp_bridge.py, disable lsp-bridge-mode.`
The `*lsp-bridge*` buffer is empty.
Emacs version: 29, python version 3.10.2

I wish I had more details to share, but can not come up with any relevant ones. My initial hunch was that it had to do
with the python environment, but since `epc` gets imported properly at line 28 I guess it's fine?

**Comment by manateelazycat** [comment]
did you install pyright?

you need install lsp server first

**Comment by samhedin** [comment]
That was it, thanks! I had pyright installed with the use of lsp-mode, which meant it was missing from my standard path. Installing with pip as in the readme fixed it.
