### ISSUE TITLE
Dont show completion popup menu when inside a comment

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [manateelazycat/lsp-bridge#246]
I think popup menu should not show at all when inside the comment. Maybe this behavior could be achieved with some regex, that checks when typing, if cursor is inside comment or not, and disable / enable completion accordingly. Thanks for this project btw, i really enjoy having code completions in emacs without any lag, like in VSCode :D

**Comment by manateelazycat** [comment]
you can implement in-comment-p function like https://github.com/manateelazycat/lsp-bridge/blob/cfd9c637f2c2ff21d5f861400408d6cd9a0ada2a/lsp-bridge.el#L655

then add in-comment-p function in https://github.com/manateelazycat/lsp-bridge/blob/cfd9c637f2c2ff21d5f861400408d6cd9a0ada2a/lsp-bridge.el#L109

**Comment by manateelazycat** [comment]
> ```emacs-lisp
> (defun not-in-comment ()
>   (not (nth 4 (syntax-ppss))))
> 
> 
> (defcustom lsp-bridge-completion-popup-predicates '(lsp-bridge-not-only-blank-before-cursor
>                                                     lsp-bridge-not-match-hide-characters
>                                                     lsp-bridge-not-match-completion-position
>                                                     lsp-bridge-not-match-stop-commands
>                                                     lsp-bridge-not-in-string
>                                                     lsp-bridge-not-follow-complete
>                                                     lsp-bridge-is-evil-insert-state
>                                                     not-in-comment
>                                                     )
> ```
> 
> i mean, that was was pretty easy... why not make it as default behavior?

not everyone like this behavior
