### ISSUE TITLE
clang下无法检测到include_directories所包含的头文件

### ISSUE THREAD

**Issue by ac-khaos** [manateelazycat/lsp-bridge#249]
在cmakelists中设置的头文件目录编译是正常的，但是lsp bridge无法检测到相关头文件并进行补全提示

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/45448146/176981183-de544bf4-eb24-4ab9-b040-363f0748c9a4.png">

在我以这样的方式引入后能部分正常补全，并且补全响应会有延迟两秒左右

**Comment by manateelazycat** [comment]
没有测试环境，暂时关闭
