### ISSUE TITLE
Allow specifiy project root

### ISSUE THREAD

**Issue by jilen** [manateelazycat/lsp-bridge#250]
It is common that project root is not vc root.  Especially monorepo codebase.

**Comment by jilen** [comment]
I mean project path is a subdir of the vc root. e.g.
```
prj
  |-- frontend(vue project)
  |-- backend
```

**Comment by manateelazycat** [comment]
lsp-bridge-get-lang-server-by-project: write your own function to get server configuration based on project-path and file-path, this function is nil by default

**Comment by jilen** [comment]
What should this function return ? Any example ?

**Comment by manateelazycat** [comment]
If you expect that you do not run the `git` command but customize the project directory, you need to customize the function ```lsp-bridge-get-lang-server-project```, the input parameter is `project-path` and `file-path`, return the corresponding LSP server string, you can query all LSP servers in the list of `lsp-bridge-lang-server-mode-list` option, this function return nil default

**Comment by jilen** [comment]
Seem this function returns server config file path(like volar.json) ? Still cannot get how to use a subdir of vc root with this function.

**Comment by manateelazycat** [comment]
Check https://github.com/manateelazycat/lsp-bridge/commit/7ee5ea078d4fb39b9b1d28b704e208e47d747230
