### ISSUE TITLE
support ccls

### ISSUE THREAD

**Issue by emacsbliss** [manateelazycat/lsp-bridge#256]
eglot support ccls and ccls works better in certain case than clangd.

wonder if we can add support for ccls for C++?  Hopefully it won't be too much effort.

Thanks!

**Comment by manateelazycat** [comment]
Add new LSP server is simple, just need add ccls.json under lsp-bridge/langserver directory.

I haven't time to research, PR are welcome.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/pull/275 

Done
