### ISSUE TITLE
go怎么使用lsp-bridge？

### ISSUE THREAD

**Issue by arstum** [manateelazycat/lsp-bridge#261]
# 系统情况
OS: Arch Linux x86_64 
Host: B85M-D2V-SI 
Kernel: 5.15.49-1-lts 
Uptime: 1 day, 13 hours, 28 mins 
Packages: 990 (pacman) 
Shell: zsh 5.9 
Resolution: 1920x1080 
WM: dwm 

# 运行安装配置
yay -S go
go install golang.org/x/tools/gopls@latest
ln -s ~/go/bin/gopls ~/.local/bin
go mod init goproject

运行 emacs , 打开 *.go 文件，lsp-bridge 没运行

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/master/README.zh-CN.md#%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98

根据这个里面描述来反馈日志

**Comment by manateelazycat** [comment]
please install go-mode
