### ISSUE TITLE
pyright支持虚拟环境问题请教

### ISSUE THREAD

**Issue by Peter-Chou** [manateelazycat/lsp-bridge#266]
懒猫大神你好，我想请教下如何使用lsp-bridge 支持python的虚拟环境。
我根据readme简单地自定义了`lsp-bridge-get-lang-server-by-project` 函数进行了测试

``` emacs lisp
  (defun lsp-bridge-get-lang-server-by-project (project-path filepath)
    "/home/peter/projects/cgec-initialized-with-plm/pyright.json")
```

项目内的pyright.json内容如下：

``` json
{
    "name": "pyright",
    "languageId": "python",
    "command": [
        "pyright-langserver",
        "--stdio"
    ],
    "ignore-diagnostic": "# type: ignore",
    "settings": {
        "python.analysis": {
            "autoImportCompletions": true,
            "typeshedPaths": [],
            "stubPath": "",
            "useLibraryCodeForTypes": true,
            "diagnosticMode": "openFilesOnly",
            "typeCheckingMode": "basic",
            "logLevel": "verbose",
            "autoSearchPaths": true,
            "extraPaths": []
        },
        "pythonPath": "/home/peter/miniconda3/envs/cgec/bin/python",
        "venvPath": "/home/peter/miniconda3/envs/cgec"
    }
}
````

lsp-bridge对应的python，我安装在了其他虚拟环境中：
``` emacs lisp
;; WORKON_HOME="$HOME/miniconda3/envs"
(setq lsp-bridge-python-command (expand-file-name "lsp-bridge/bin/python" (getenv "WORKON_HOME")))
```

然后开启项目的文件后，仍无法导入虚拟环境下安装的包

> models/trainer.py

![image](https://user-images.githubusercontent.com/28672146/178186423-398c508e-5cb1-45d9-a75f-0d866a747910.png)

想请问下懒猫大神 pyright支持虚拟环境的正确操作是如何的？非常感谢！

**Comment by manateelazycat** [comment]
没有用过虚拟环境， 不知道怎么修复。

**Comment by zy9306** [comment]
venvPath 可以不配，然后再打印一下 https://github.com/manateelazycat/lsp-bridge/blob/master/core/lspserver.py#L383 的 settings，看看发给 server 的对不对，我这边虚拟环境使用正常的

**Comment by Peter-Chou** [comment]
@zy9306 你好 我打印了下：

![image](https://user-images.githubusercontent.com/28672146/178189593-1be5e35b-3c3c-44d1-9070-36b39b46bfd1.png)

貌似还是传的default server config

**Comment by zy9306** [comment]
> @zy9306 你好 我打印了下：
> 
> ```
> --- Send (notification): workspace/didChangeConfiguration
> {
>    "method": "workspace/didChangeConfiguration",
>    "params": {
>       "settings": {
>          "python.analysis": {
>             "autoImportCompletions": true,
>             "typeshedPaths": [],
>             "stubPath": "",
>             "useLibraryCodeForTypes": true,
>             "diagnosticMode": "openFilesOnly",
>             "typeCheckingMode": "basic",
>             "logLevel": "verbose",
>             "autoSearchPaths": true,
>             "extraPaths": []
>          },
>          "pythonPath": "/usr/bin/python",
>          "venvPath": ""
>       }
>    },
>    "jsonrpc": "2.0"
> }
> ```
> 
> 还传的是default server config，请问下如何覆盖原有的json文件，貌似`lsp-bridge-get-lang-server-by-project` 这个方法好像不行

你给你自定义的函数换个名字，再 (setq lsp-bridge-get-lang-server-by-project 'you_func)，再 debug 下 https://github.com/manateelazycat/lsp-bridge/blob/19a20c95878ec0ba98581af20052b363fa3f9868/lsp-bridge.el#L460 的返回值

**Comment by Peter-Chou** [comment]
@zy9306 你好呀 我已经按你说的进行了替换

``` emacs lisp
  (defun petmacs/lsp-bridge-get-lang-server-by-project (project-path filepath)
    "/home/peter/projects/cgec-initialized-with-plm/pyright.json")
  (setq lsp-bridge-get-lang-server-by-project 'petmacs/lsp-bridge-get-lang-server-by-project)
```

log中的内容的确改成了自定义的内容了

``` json
--- Send (notification): workspace/didChangeConfiguration
{
   "method": "workspace/didChangeConfiguration",
   "params": {
      "settings": {
         "python.analysis": {
            "autoImportCompletions": true,
            "typeshedPaths": [],
            "stubPath": "",
            "useLibraryCodeForTypes": true,
            "diagnosticMode": "openFilesOnly",
            "typeCheckingMode": "basic",
            "logLevel": "verbose",
            "autoSearchPaths": true,
            "extraPaths": []
         },
         "pythonPath": "/home/peter/miniconda3/envs/cgec/bin/python"
      }
   },
   "jsonrpc": "2.0"
}
```

只是pyright并没有能提示虚拟环境中安装的包 🤕 

![image](https://user-images.githubusercontent.com/28672146/178193017-0302e368-69f9-40da-a42b-0d1de3604205.png)

**Comment by zy9306** [comment]
也许是 pytouch 没有生成相应的 stub，你可以在你的虚拟环境中装个其它包，看看能不能用，如果能，那应该就是 pyright 或者 pytouch 的问题 @Peter-Chou 还有 venvPath 不用删，用空字符串就行了（我确定空字符串是没问题的，不确定直接删了会怎么样，不过和你这个问题应该没啥关系）

**Comment by Peter-Chou** [comment]
@zy9306 我将默认环境中的numpy删除后，的确numpy也无法正确导入，应该是pyright并没有对应到虚拟环境中，如图

![image](https://user-images.githubusercontent.com/28672146/178194673-eb972fb2-d467-43af-bbc3-3b46cc941869.png)

应该不是pytorch对应没有stub的缘故，因为我使用lsp-mode时pytorch没有stub也是可以补全

**Comment by zy9306** [comment]
是不是 pylint 误报了? 你查找定义能点得进去吗? 我这边试了是可以的

**Comment by Peter-Chou** [comment]
@zy9306 看借鉴下你关于虚拟环境的配置吗，我这是调用lsp-bridge-find-def 返回的是[LSP-Bridge] No definition found.

**Comment by zy9306** [comment]
> @zy9306 你好，能借鉴下你关于虚拟环境的配置吗？定义处我也点不进去，我调用lsp-bridge-find-def 返回的是：[LSP-Bridge] No definition found.

https://github.com/manateelazycat/lsp-bridge/issues/232#issuecomment-1165202589 我的用法比较粗暴。。你可以试下

**Comment by Peter-Chou** [comment]
@zy9306 你的方法直接跳过了pyright.json，应该是避开了我这里遇到的问题。

**Comment by zy9306** [comment]
@Peter-Chou 按理说发送自定义的文件，和直接修改掉，效果应该是一样的，我目前想不到两者差异在哪

**Comment by Peter-Chou** [comment]
@zy9306 嗯嗯 好哒，非常感谢你的帮助，我先暂时切换到lsp-mode，最近比较忙，先不折腾了。

**Comment by zy9306** [comment]
我写了篇 wiki，你试一下，我测了是可以用的 https://github.com/manateelazycat/lsp-bridge/wiki/Python-virtual-env-config

**Comment by Peter-Chou** [comment]
@zy9306 谢谢， 我测试了下的确是切换到了虚拟环境了

![image](https://user-images.githubusercontent.com/28672146/178209465-5d4eadd4-d5ea-427b-b8d2-e9f2932ae538.png)

**Comment by zy9306** [comment]
@Peter-Chou 记得加个 hook，不然其它语言就挂了，或者用其它方式也可以 `(add-hook 'python-mode-hook (lambda () (setq-local lsp-bridge-get-lang-server-by-project 'local/lsp-bridge-get-lang-server-by-project)))`
