### ISSUE TITLE
Improve configuration of language servers

### ISSUE THREAD

**Issue by lambdadog** [manateelazycat/lsp-bridge#268]
Currently if I wish to set `--venv-path` for `pyright`, as recommended in the docs, then I am required to either fork lsp-bridge or write a function for `lsp-bridge-get-lang-server-by-project` which requires me to implement the logic to select a json file then additionally copy the json file over.

It would be nice if there was a better way for me to do so.

**Comment by lambdadog** [comment]
Also, LSP configuration will be complex for users running distros such as NixOS, so an easier way for users to replace the `<lsp>.json` configuration files entirely or configure LSP server settings through elisp would be very nice.

**Comment by zy9306** [comment]
Please check the wiki for jdtls and python virtualenv examples, I think `lsp-bridge-get-lang-server-by-project` is handy enough.

**Comment by manateelazycat** [comment]
LSP server has so many options, we cannot convert those option to elisp code.

json file is better way
