### ISSUE TITLE
clangd 模板补全选项错误

### ISSUE THREAD

**Issue by zilongshanren** [manateelazycat/lsp-bridge#27]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/785541/167610835-935fd844-213a-4e43-bffc-78cfaafc132f.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/785541/167610959-b9ad21fc-4558-4ec8-8783-768d7a20ea4e.png">

模板参数没有正确处理，需要使用类似snippet的机制来实现比较好。

**Comment by manateelazycat** [comment]
@EdmondFrank 先把模板补全关闭了，以后有模板支持我们再考虑加回来？

**Comment by EdmondFrank** [comment]
> @EdmondFrank 先把模板补全关闭了，以后有模板支持我们再考虑加回来？

那改成直接用默认参数启动好了, 不开启其他feature了 :)

**Comment by VitalyAnkh** [comment]
你怎么把这么多都关了，"--enable-config"，  "--header-insertion-decorators=0" 还是加上比较好

**Comment by zerolfx** [comment]
问题原因：

1. 应该选择 lsp 提供的 `insertText` 或者 `textEdit` 作为补全项而不是 `label`
2. 包含空格的字符串在传给 elisp 后被切成了多个字符串

![Screenshot_20220510_235746](https://user-images.githubusercontent.com/20219056/167766254-2ae8b58b-1eac-4611-b79a-177243164a6a.png)
![Screenshot_20220510_235806](https://user-images.githubusercontent.com/20219056/167766293-e9030f07-3966-4399-b2d2-f7086c8c2b73.png)

**Comment by EdmondFrank** [comment]
> 你怎么把这么多都关了，"--enable-config"， "--header-insertion-decorators=0" 还是加上比较好

看来是我解决问题的思路不太对，我直接照着eglot的配置了，我先关了这个pr，按 @zerolfx 的思路看看.

**Comment by manateelazycat** [comment]
> 问题原因：
> 
> 1. 应该选择 lsp 提供的 `insertText` 或者 `textEdit` 作为补全项而不是 `label`
> 2. 包含空格的字符串在传给 elisp 后被切成了多个字符串
> 
> ![Screenshot_20220510_235746](https://user-images.githubusercontent.com/20219056/167766254-2ae8b58b-1eac-4611-b79a-177243164a6a.png) ![Screenshot_20220510_235806](https://user-images.githubusercontent.com/20219056/167766293-e9030f07-3966-4399-b2d2-f7086c8c2b73.png)

为啥你的 -> 可以补全，我的不行呀。 ;)

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/9d8ead517fca3df9c74f79d729b57628975e021c
