### ISSUE TITLE
acm绘制窗口在pgtk下会特别的慢(卡顿)

### ISSUE THREAD

**Issue by EvanMeek** [manateelazycat/lsp-bridge#280]
上次有提到过，大概是怎么个原因呢？pgtk还是有一定优势的。

**Comment by manateelazycat** [comment]
pgtk的分支没法跑 EAF, 暂时不想研究 pgtk 。

**Comment by EvanMeek** [comment]
> pgtk的分支没法跑 EAF, 暂时不想研究 pgtk 。

好的，那先把这个issue关闭了吧
