### ISSUE TITLE
`posframe` missing from the `Package-Requires` statement 

### ISSUE THREAD

**Issue by junyi-hou** [manateelazycat/lsp-bridge#281]
`lsp-bridge.el` requires `posframe`, but in its `Package-Requires` statement only contains `((emacs "27"))`. Can we add posframe dependency in the statement so there's no need to manually install posframe? Thanks!

**Comment by junyi-hou** [comment]
actually, `markdown-mode` and `yassnippet` are also missing - should we add all of them back?

**Comment by manateelazycat** [comment]
sure, can you send PR? thanks
