### ISSUE TITLE
feature request: offer manual trigger for autocompletion

### ISSUE THREAD

**Issue by junyi-hou** [manateelazycat/lsp-bridge#282]
As of now, there is no way to trigger `acm` manually (i.e., not starting autocompletion everytime I type). Is there a way that I can achieve this?

I've tried [modifying the `lsp-bridge-monitor-post-command`](https://github.com/manateelazycat/lsp-bridge/blob/master/lsp-bridge.el#L648) to check whether `acm-frame` is visible (see code below)
```
    (when lsp-bridge-mode
      (when (and (or (eq this-command 'self-insert-command)
                     (eq this-command 'org-self-insert-command))
                 (acm-frame-visible-p acm-frame))
        (lsp-bridge-try-completion)))
```

but this doesn't seem to be working. Any advice?

**Comment by manateelazycat** [comment]
Done.

**Comment by junyi-hou** [comment]
Thanks! The current implementation of `lsp-bridge-complete-manually` will disable updating candidate when I manually start an autocompletion session, which is not desirable. I use the following workaround to temporarily restore candidate update when `acm-frame` is visible:

```
(defun gatsby:lsp-bridge--completion-auto-update-on (&rest _)
    (setq lsp-bridge-complete-manually nil))

  (defun gatsby:lsp-bridge--completion-auto-update-off (&rest _)
    (setq lsp-bridge-complete-manually t))

  (advice-add #'acm-menu-adjust-pos :before #'gatsby:lsp-bridge--completion-auto-update-on)
  (advice-add #'acm-hide :after #'gatsby:lsp-bridge--completion-auto-update-off)
```

**Comment by manateelazycat** [comment]
Fixed https://github.com/manateelazycat/lsp-bridge/commit/848ba0db56bd7cee9a55374b186ad6f4e0460578
