### ISSUE TITLE
`Error running timer: (void-variable acm-backend-lsp-filepath)` when lsp-bridge-mode is turned on then off

### ISSUE THREAD

**Issue by yatsky** [manateelazycat/lsp-bridge#296]
# Issue
With minimum setup, if `lsp-bridge-mode` is turned on and then off for whatever reason and then you revert the buffer, you'll have this error in `*Message*` buffer.

```
Error running timer: (void-variable acm-backend-lsp-filepath)
```
# Steps to reroduce
* `emacs -Q`
* load packages with the following code
```emacs-lisp
(add-to-list 'load-path "~/.emacs.d/straight/markdown-mode")
(add-to-list 'load-path "~/.emacs.d/straight/posframe")
(add-to-list 'load-path "~/.emacs.d/straight/yasnippet")
(add-to-list 'load-path "~/.emacs.d/other-packages/lsp-bridge")

(require 'lsp-bridge)
(global-lsp-bridge-mode)
```
* open any `test.html`
* `M-x lsp-bridge-mode` (turn on)
* `M-x lsp-bridge-mode` (turn off)
* `M-x revert-buffer`
* type anything in the buffer
* `Error running timer: (void-variable acm-backend-lsp-filepath)` shows up in `*Messages*` buffer
# Solution
I have located the issue and going to make a PR.

**Comment by 404cn** [comment]
Same here,  use `M-x lsp-bridge-mode` to turn on in any file in project, and then open other file in same project, lsp-bridge-mode is not turn on(C-h v lsp-bridge-mode is nil), and same error message in minibuffer.

**Comment by AllTheLife** [comment]
The diff cannot work for me.

After loading the package called `lsp-bridge`, I would get the same error when I installed any package else.

**Comment by manateelazycat** [comment]
> The diff cannot work for me.
> 
> After loading the package called `lsp-bridge`, I would get the same error when I installed any package else.

Newest version has fixed.
