### ISSUE TITLE
多服务使用部分函数报错

### ISSUE THREAD

**Issue by angelporo** [manateelazycat/lsp-bridge#299]
本地server列表
- volar
- emmet-ls
- 之前用的 `vue-language-server` 因为停更 转移到 [`vls`](https://github.com/vuejs/vetur/tree/master/server)

之前没有更新多服务功能之前，几乎(因为没有用到所有功能不能满足覆盖)所有的功能都可以使用，vls补全也很及时

更新多服务后，vue代码补全没有问题，两个服务都可以提示补全内容，但是使用一下功能报错
<img width="678" alt="image" src="https://user-images.githubusercontent.com/16830481/182347349-b256cefe-8382-4c9c-bd22-f1d9da89afba.png">

报错信息全部都一样
```
--- Recv response volar (4295): textDocument/signatureHelp

--- Send (57303): textDocument/signatureHelp

--- Recv response volar (57303): textDocument/signatureHelp
Traceback (most recent call last):
  File "/Users/liyuan/elisp/lsp-bridge/lsp_bridge.py", line 110, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/Users/liyuan/elisp/lsp-bridge/lsp_bridge.py", line 247, in _do
    action.call(name, *args)
  File "/Users/liyuan/elisp/lsp-bridge/core/fileaction.py", line 111, in call
    return self.send_server_request(self.single_lsp_server, method, *args, **kwargs)
  File "/Users/liyuan/elisp/lsp-bridge/core/fileaction.py", line 220, in send_server_request
    handler: Handler = self.method_handlers[lsp_server.server_info["name"]][handler_name]
AttributeError: 'NoneType' object has no attribute 'server_info'

```

下面是我`volar.json`的配置
<img width="756" alt="image" src="https://user-images.githubusercontent.com/16830481/182348187-e66911c5-c85c-48ba-9774-b59fa3859450.png">

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/fe2ff229e244acd63f80f0009e77b3cb4a42bf37

修复了。

**Comment by angelporo** [comment]
大佬辛苦了
