### ISSUE TITLE
volar returns too many completions item.

### ISSUE THREAD

**Issue by jilen** [manateelazycat/lsp-bridge#300]
Request 
```json
{
   "id": 2936,
   "method": "textDocument/completion",
   "params": {
      "position": {
         "line": 6,
         "character": 18
      },
      "context": {
         "triggerCharacter": "'",
         "triggerKind": 2
      },
      "textDocument": {
         "uri": "file:///home/jilen/Workspaces/zd-monorepo/zd-web/client/src/stat/components/report/salesReportView/ReportHeader.vue"
      }
   },
   "jsonrpc": "2.0"
}
```
More than `970k` lines (still growing)  can be found in `lsp-bridge` buffer.

Seems all kind of completion (`files` / `methods` / `folders` / `modules` etc) are returned at once. 

Note `lsp-mode` can do completion (but is very slow).

**Comment by manateelazycat** [comment]
please disable log, log only for developer debug use.

**Comment by jilen** [comment]
But `lsp-bridge` cannot do any completion in time. Since it is to slow to process such large response body. 

With `lsp-mode` or `eglot`  I haven't see such large response body.

**Comment by manateelazycat** [comment]
I USE VOLAR EVERYFAY, FAST ALWAYS.

DID YOU DO NPM INSTALL IN YOUR PROJECT?

**Comment by jilen** [comment]
Of course with npm installed.  But it is very large project.

Actually the server did return completion items, but it is too many for `lsp-bridge` to complete.

**Comment by jilen** [comment]
Maybe related to trigger char `'`, with `eglot` I haven't see single quote as trigger char

**Comment by manateelazycat** [comment]
> Of course with npm dependencies installed. But it is a very large project.
> 
> Actually the server did return completion items (response body with 970k lines), but it is too many for `lsp-bridge` to complete.

I have told, if you turn off log, lsp-bridge python won't turn 970k lines to emacs, why you not turn off log?

can you give a mini project to reproduce your prolem?

**Comment by jilen** [comment]
With log disabled.
The recv log show 10 or more seconds after typing.


![Screenshot from 2022-08-03 11-08-49](https://user-images.githubusercontent.com/546573/182515790-59877e84-6a84-4572-93a2-ba69baa94047.png)

> can you give a mini project to reproduce your prolem?

Could be hard, since there are too many files in my project.
