### ISSUE TITLE
clojure-lsp-native 补全关键字的时候会多一个冒号

### ISSUE THREAD

**Issue by vinurs** [manateelazycat/lsp-bridge#305]
之前的 clojure-lsp 是使用 `brew install clojure-lsp` 来进行安装的，这时候使用是没问题的，但是这个 clojure-lsp 版本是比较老的版本了
<img width="603" alt="图片" src="https://user-images.githubusercontent.com/37489300/183839623-55299935-63f0-4d37-8f4a-6cfc51be7d3a.png">
最新的clojure-lsp 应该是 clojure-lsp-native
<img width="1065" alt="图片" src="https://user-images.githubusercontent.com/37489300/183840602-dd84f1fa-13f0-40e7-8ee2-a0cc323d6f5d.png">
在macOS上面安装，但是安装好以后在macOS上面也叫 `clojure-lsp`
```
brew remove clojure-lsp # if you have old clojure-lsp installed via brew
brew install clojure-lsp/brew/clojure-lsp-native
```
https://clojure-lsp.io/installation/#homebrew-macos-and-linux ， 其它平台只要参照这个安装最新的即可，补全的时候会出现下面的问题，多一个冒号

![Kapture 2022-08-10 at 15 14 16](https://user-images.githubusercontent.com/37489300/183838892-c085dae6-5a4d-406d-8d00-e83b4f35dadc.gif)
测试代码地址 https://github.com/vinurs/clojure-demo

**Comment by manateelazycat** [comment]
已经修复了
