### ISSUE TITLE
Conflict with python-black (emacs-reformatter?)

### ISSUE THREAD

**Issue by petercheng00** [manateelazycat/lsp-bridge#317]
I'm using lsp-bridge with pyright, and also use [python-black](https://github.com/wbolster/emacs-python-black) (which uses [emacs-reformatter](https://github.com/purcell/emacs-reformatter)).
When I run `python-black-buffer`, the contents of the buffer sometimes get mangled - I've noticed it sometimes changes based on cursor position.

Formatting works as expected when lsp-bridge is disabled.

Example:
```
x = 1+1;print(x) [cursor here]`
```
After `python-black-buffer` with lsp-bridge:
```
x = 1x = 1print(x)
```
After `python-black-buffer` without lsp-bridge:
```
x = 1 + 1
print(x)
```
Happens even if I only run the following packages:
```
(use-package posframe)
(use-package markdown-mode)
(use-package yasnippet
  :config
  (yas-global-mode 1))
(yas-global-mode 1)
(add-to-list 'load-path "/home/pcheng/libraries/lsp-bridge")
(require 'lsp-bridge)
(global-lsp-bridge-mode)
(use-package python-black)

```

After reformatting, I've also noticed that the lsp server seems to be out of sync with the buffer contents - errors and highlighting show up incorrectly, until I do `lsp-bridge-restart-process`

**Comment by manateelazycat** [comment]
Why not use command `lsp-bridge-code-format` ？

**Comment by petercheng00** [comment]
pyright does not do formatting. I can try another language server, but thought this might be a symptom of a bigger issue.

**Comment by zy9306** [comment]
It also happens to me when I run black directly from the command line, and it also happens when goimports formats golang. But there is no stable recurrence condition.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/d9940fd1b1a1d7513d8b1758f085cbb69fe955cf

**Comment by manateelazycat** [comment]
I have try python-black today, I found python-black will break code after it format buffer.
