### ISSUE TITLE
[feature request] support tailwind css language server

### ISSUE THREAD

**Issue by emacsbliss** [manateelazycat/lsp-bridge#322]
It would be great if lsp-bridge can add support for the tailwind css language server (https://github.com/tailwindlabs/tailwindcss-intellisense).

thanks!

**Comment by manateelazycat** [comment]
Tailwind is not easy to add, because tailwind won't send LSP response when it start.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/2475ebd9d088a914788c8dfe7259632692059efb
