### ISSUE TITLE
definition is not found in multiple java projects in one workspace

### ISSUE THREAD

**Issue by zhongweiy** [manateelazycat/lsp-bridge#323]
Hi, team, 
I have a workspace setup like (the whole workspace can be download at [here](https://github.com/zhongweiy/lsp-bridge/blob/e109e573976119d8680cb8dd371519a7f3bf998f/test_projs.tar)). The workspace here does not have special meaning, it is just a directory contains multiple java projects.
```
├──/my/java/workspace
    ├── projBar
    │   ├── .classpath
    │   ├── .project
    │   ├── .settings
    │   │   └── org.eclipse.jdt.core.prefs
    │   └── src
    │       └── com
    │           └── projBar
    │               └── Book.java
    ├── projFoo
    │   ├── .classpath
    │   ├── .project
    │   ├── .settings
    │   │   └── org.eclipse.jdt.core.prefs
    │   └── src
    │       └── com
    │           └── projFoo
    │               └── BookStore.java
```

And projBar depends on projFoo. But I can not resolve the definition in projBar:
```java
package com.projBar;

import com.projFoo.BookStore; // <-- definition can not be resolved. It is defined in proFoo.

public class Book {
	private BookStore bs;
	
	public Book() {
		this.bs = new BookStore();
	}
}
```

I checked the Eclipse IDE supports the feature by add the `<classpathentry kind="src" path="/projFoo"/>` to the projBar/.classpath:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="src" path="/projFoo"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

Does lsp-bridge support this feature?

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/39bfa3be5bbb98c0098c0709a7f3fb4f50e1a786/core/handler/jdt_uri_resolver.py#L11

Current, lsp-bridge will jump to third library define with jdt_uri_resolver that reuse current JDT LSP server.

But I haven't idea how to support classpathentry.

Any PR are welcome. ;)

**Comment by zhongweiy** [comment]
Sorry for my late reply.

After check the VS Code's lsp initialization setup for the same 2 projects, I find the issue can be solved by adding the following config change to the `langserver/jdtls.json`:
```
modified   langserver/jdtls.json
@@ -4,6 +4,11 @@
   "command": [
     "jdtls"
   ],
+  "capabilities": {
+    "workspace": {
+      "workspaceFolders": true
+    }
+  },
   "settings": {
     "java": {
       "completion": {
@@ -14,6 +19,9 @@
     }
   },
   "initializationOptions": {
+    "workspaceFolders": [
+        "file://///my/java/workspace"
+     ],
     "settings": {
       "java": {
         "maxConcurrentBuilds": 1,

```

So my question becomes what is the best practise for supporting this case in lsp-bridge. There are 2 options:
1. let the user to add the "workspaceFolders" for their project.
2. let lsp-bridge automatically discover this setup and add "workspaceFolders" for user.

I don't know which way is preferred in lsp-bridge. I saw lsp-mode has some discussion about this topic here: https://github.com/emacs-lsp/lsp-mode/discussions/3095. It seems quite complex.

**Comment by manateelazycat** [comment]
Hi @zhongweiy

I have add new elisp API get-workspace-folder, this function return workspace folder by given project path.
You can customize `lsp-bridge-get-workspace-folder` option, then test it is your need?

Thanks for digg reason. ;)

**Comment by zhongweiy** [comment]
Thanks for your commit. It works. And it is a flexible and elegant solution!

Here is my definition for reference:
```
(defun my-lsp-bridge-workspace (proj)
  (let* ((proj-2-workspace
          '(("/home/user/projects/workspace1/proj1" .
             "file:///home/user/projects/workspace1/")
            ("/home/user/projects/workspace2/proj2" .
             "file:///home/user/projects/workspace2/")))
         (kv (assoc proj proj-2-workspace)))
    (if kv
        (cdr kv)
      nil)))

(custom-set-variables '(lsp-bridge-get-workspace-folder 'my-lsp-bridge-workspace))
```

**Comment by manateelazycat** [comment]
> Thanks for your commit. It works. And it is a flexible and elegant solution!
> 
> Here is my definition for reference:
> 
> ```
> (defun my-lsp-bridge-workspace (proj)
>   (let* ((proj-2-workspace
>           '(("/home/user/projects/workspace1/proj1" .
>              "file:///home/user/projects/workspace1/")
>             ("/home/user/projects/workspace2/proj2" .
>              "file:///home/user/projects/workspace2/")))
>          (kv (assoc proj proj-2-workspace)))
>     (if kv
>         (cdr kv)
>       nil)))
> 
> (custom-set-variables '(lsp-bridge-get-workspace-folder 'my-lsp-bridge-workspace))
> ```

You can use `(when kv (cdr kv))` to avoid return nil in else branch.

**Comment by manateelazycat** [comment]
> Thanks for your commit. It works. And it is a flexible and elegant solution!
> 
> Here is my definition for reference:
> 
> ```
> (defun my-lsp-bridge-workspace (proj)
>   (let* ((proj-2-workspace
>           '(("/home/user/projects/workspace1/proj1" .
>              "file:///home/user/projects/workspace1/")
>             ("/home/user/projects/workspace2/proj2" .
>              "file:///home/user/projects/workspace2/")))
>          (kv (assoc proj proj-2-workspace)))
>     (when kv
>         (cdr kv))))
> 
> (custom-set-variables '(lsp-bridge-get-workspace-folder 'my-lsp-bridge-workspace))
> ```

Can you help add those code in Wiki? Maybe someone need this.

Thanks

**Comment by zhongweiy** [comment]
Sure. Done.
