### ISSUE TITLE
acm-backend-lsp-candidates: Invalid function: (server-items (gethash server-name acm-backend-lsp-items))

### ISSUE THREAD

**Issue by opsnull** [manateelazycat/lsp-bridge#327]
test code:

```
package main

import "log"

func main() {
	log.
}

```

lsp-bridge does not autocomplete, and when  exec `M-x lsp-bridge-popup-complete`, report error message:

> acm-backend-lsp-candidates: Invalid function: (server-items (gethash server-name acm-backend-lsp-items))

**Comment by manateelazycat** [comment]
make sure install https://github.com/golang/tools/tree/master/gopls

and make sure install [go-mode](https://github.com/dominikh/go-mode.el) and gopls in PATH, please do ln -s ~/go/bin/gopls ~/.local/bin, and do go mod init first

**Comment by opsnull** [comment]
@manateelazycat 
Yes, I have done them all and make sure lsp-bridge can call gopls:
![image](https://user-images.githubusercontent.com/433567/186663886-e6b4c388-c7ca-46f6-8c78-6f8004d1bfbb.png)

I can conform  the latest lsp-bridage broken for gopls,  when I switch back to 2 months code [749e078](https://github.com/manateelazycat/lsp-bridge/commit/749e078), it's ok.

**Comment by manateelazycat** [comment]
> @manateelazycat Yes, I have done them all and make sure lsp-bridge can call gopls: ![image](https://user-images.githubusercontent.com/433567/186663886-e6b4c388-c7ca-46f6-8c78-6f8004d1bfbb.png)
> 
> I confirm the latest lsp-bridage broken for gopls, when I switch back to 2 months code [749e078](https://github.com/manateelazycat/lsp-bridge/commit/749e078), it's ok.
> 
> ![image](https://user-images.githubusercontent.com/433567/186665961-7a51fcee-55f9-4f93-81fa-aaaa96335e6c.png)

I have test your code and newest version, works fine.
