### ISSUE TITLE
Error after upgrading to latest version

### ISSUE THREAD

**Issue by xqliu** [manateelazycat/lsp-bridge#330]
Inside java file, when trying to show completion like below

```
public class HelloWorld {
   public static void main(String[] args) {
      "".toS
           //~~ here no completion shows up and message buffer shows error as below
   } 
}
```

Error message

```
Error in post-command-hook (lsp-bridge-monitor-post-command): (invalid-function (server-items (gethash server-name acm-backend-lsp-items)))
acm-backend-lsp-candidates: Invalid function: (server-items (gethash server-name acm-backend-lsp-items))
```

And the completion popup can not be shown.

also doesn't work on ts and TSX files.

but works inside elisp file,

**Comment by xqliu** [comment]
Seems similar to issue https://github.com/manateelazycat/lsp-bridge/issues/327

**Comment by manateelazycat** [comment]
I have test your Java Code, works fine.

Please test with `emacs -Q`

**Comment by manateelazycat** [comment]
![截图 2022-08-29 16-17-39](https://user-images.githubusercontent.com/237487/187156599-68883e34-ee6d-4c26-9825-163af5ef8a96.png)

**Comment by xqliu** [comment]
May I ask which python version are you using? 

Python 3.9 or python 3.10? 

Which jdtls version are you using?

Is it jdt-1.12.0 or other version.

When I enable log output sees follow error in *lsp-bridge* buffer 

```
--- Completion items number: 50
ERROR:epc:ReturnError([Symbol('invalid-function'), [Symbol('server-items'), [Symbol('gethash'), Symbol('server-name'), Symbol('acm-backend-lsp-items')]]])
```

I suppose it might related to lsp server or python version or epc version?

Thanks.
