### ISSUE TITLE
About grouping acm-backends and display acm-backends contextually

### ISSUE THREAD

**Issue by ssl19** [manateelazycat/lsp-bridge#350]
hi, Andy Stewart!

First of all, thanks again for creating such an excellent package!

The current backends display order is hard-coded in function. And we couldn't choose the backend contextually.

Here are a few examples:

When editing in comments and strings of elisp files, we want to use
acm-backend-elisp in `symbol' pairs, else we want to use acm-backend-english.

Besides, the users could benefit from the flexible orders of displaying orders.
In some projects, display acm-backend-citre before acm-backend-lsp, or inhibit
the display of acm-backend-lsp if acm-backend-citre has results. In other projects, use acm-backend-lsp only.

Grouping acm-backends and letting acm-backends have their predicates to
display or not provides such flexibility and makes it easier to create new
acm-backend package (don't have to pr and hard-coded edge cases).

The gist below is a hack that implements this functionality :)

[acm-hack.el](https://gist.github.com/ssl19/4ba8151bb32f0f6baeea00889745b237)

I'll be appreciated it if you could share your thoughts about it.

If you think this idea and implementation are appropriate, I can prepare a pull request 😆.

And this is the demo:

[demo](https://www.dropbox.com/s/nmeccim6n2z7oyc/demo.mp4?dl=0)

**Comment by manateelazycat** [comment]
在 lsp-bridge 之前， Emacs用户折腾补全主要是两个痛点：
1. 折腾补全前端、 折腾补全后端， 这个各种胶水配置
2. 折腾不同后端的融合问题， 写各种复杂的配置函数去融合代码

目前看， lsp-bridge已经很好的解决了第一个问题，基本上开箱即用就可以实现代码补全。
第二个问题， lsp-bridge 目前的做法是直接在 acm-update-candidates 里面硬编码， 保证用户开箱即用， 但是缺点是各种场景的细微排序还没法做。

所以， 欢迎补丁， 但是这个补丁的前提是， 用户可以很好定制排序的情况下，不要搅浑用户， 像之前 company 和 corfu 的都写了又臭又长的融合配置， 配置一旦复杂就容易出错， 用户半天配置不好就会很烦躁。
