### ISSUE TITLE
Support LTEX LS

### ISSUE THREAD

**Issue by manateelazycat** [manateelazycat/lsp-bridge#353]
最近发现了 https://github.com/valentjn/ltex-ls ， 周末的时候看看能否添加对它的支持， 对于我这种英文语法很差的人， LSP server 可以教我怎么写对英文长句。

可以在开启lsp-bridge English backend 的时候， 同时开启这个离线语法检测服务。

**Comment by mkvoya** [comment]
请问是有计划将语言作为单独一类 backend 使用吗？我最近根据 https://github.com/emacs-grammarly/lsp-grammarly 将 grammarly 与 texlab 做成了一个 multiserver：https://github.com/manateelazycat/lsp-bridge/commit/20bb0e02b11b21cce65c3d92f829222dbfd6e732
虽然勉强能用，但是我也觉得语言类 LS 比较特殊，用排列组合做 multiserver 的方法不太能拓展（比如 markdown/asciidoc/text/org/... 与 grammarly/languagetool/...）

**Comment by manateelazycat** [comment]
啥意思，没看懂

**Comment by mkvoya** [comment]
在我理解中，现在的 LSP server 就像是 Emacs 的 major mode，只能选择其中一个来使用。而 multiserver 的机制也只是把两个 server 生硬拼凑在一起。

如果我理解正确的话，我认为”语法检查“这类任务更适合作为 minor mode 用于与其他 major mode 配合使用，而且应该可以随时开启/关闭。

我现在想把 grammarly 的 server 也加到 lsp-bridge 中，但是我目前也只知道怎么配置为 multiserver。看到最开始您提到的

> lsp-bridge English backend

我好奇这是不是一种把 grammarly 加到 lsp-bridge 的更合适机制。

**Comment by manateelazycat** [comment]
是呀，grammarly 适合单独于其他代码类lsp server。

根据mode来开启更为合适。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/570d9072001aff313975a6cdf47ad321e3a6c07a/langserver/digestif.json#L2

**Comment by manateelazycat** [comment]
Has digestif lsp server supported
