### ISSUE TITLE
远程文件补全

### ISSUE THREAD

**Issue by manateelazycat** [manateelazycat/lsp-bridge#357]
lsp-bridge要实现远程补全的思路：

### 方案1
1. Python + paramiko + elisp 实现 tramp 中登录、list ssh files、保存文件到远端的功能
2. LSP Server 和 lsp-bridge 部署到和源代码一样的服务器上， 这样 LSP Server 可以找到定义的外部文件
3. 同时本地端的Emacs要通过paramiko来告知 lsp-bridge 文件的变动信息， 相当于paramiko是本地Emacs和远端lsp-bridge的通讯桥梁
4. lsp-bridge解析了 LSP 消息后， 把补全的信息通过 ssh/http或者websocket 的方式传到本地，再由 acm 做本地菜单渲染， 用户acm做完操作以后再发送指令给远端的 lsp-bridge

整个伪代码流程：

paramiko ssh login  --> paramiko list file --> paramiko open file --> paramiko pass file content to local Emacs --> Emacs change file --> sync to remote paramiko --> paramiko notify remote lsp-bridge --> remote lsp-bridge send message remote LSP Server --> remote lsp-bridge send completion items to Emacs --> Emacs popup completion acm menu --> Select acm candidate --> Emacs change file --> ...

上面是一个完整的逻辑循环， Emacs和acm在本地， 源代码、LSP Server, lsp-bridge 在远端， paramiko 在本地 Emacs 和远端 lsp-bridge 之间。

### 方案2
1. 实现一个文件改动追踪模块， 类似 LSP Server 的 changeFile 协议原理， Emacs把每次变动的 diff 告诉这个模块， 这个模块一方面转发 diff 细节给 LSP Server, 一方面在内存中维护文件实时的版本状态， 当Emacs发送保存命令时才保存文件内容到服务器磁盘， 这样可以避免Emacs和服务器一直在传送文件内容全大小， 每次只传送diff大小， 避免 tramp 的性能问题
2. 根据不同的协议实现Emacs到服务器模块的通信， ssh或者其他协议都可以
3. LSP Server、 源代码以及lsp-bridge的后端模块都部署到服务器上
4. lsp-bridge后端解析的补全数据或者文档数据实时通过网络传送到本地， 由acm来渲染绘制

**Comment by manateelazycat** [comment]
仅提供思路， 暂时没有时间实现， 欢迎好汉挑战。

**Comment by Jemoka** [comment]
所以现在lsp-bridge支持tramp运行吗？例如用本地的lsp-server，但使用远程的venv等等

**Comment by manateelazycat** [comment]
tramp 性能太弱， 不可用， 不会支持。

如果支持， 将来也会开发一个高性能的 tramp 替代品， 再在之上开发远程开发功能。

我个人基本不使用远程开发，仅写上理论想法到 issue 给感兴趣的社区开发者参考。

**Comment by zwpaper** [comment]
有没有可能不使用 ssh？

虽然说 lsp 需要根据文件的内容进行分析，但是有些场景下没办法开放 ssh，像很多公司需要跳板机，这个功能就没法使用了

**Comment by manateelazycat** [comment]
只是记录，没有时间开发，主要是没动力。

**Comment by manateelazycat** [comment]
> 哈哈，先记录一下是理解的，所以也先是探讨一下，看看是否能不通过 ssh 实现？
> 
> 通过某个机制同步文件，还是能怎么编辑远程文件？

记录最重要是思路，技术选项皆可变

**Comment by manateelazycat** [comment]
![Uploading IMG_20230128_064150_edit_239428523797099.jpg…]()

**Comment by manateelazycat** [comment]
![IMG_20230128_064150_edit_239428523797099](https://user-images.githubusercontent.com/237487/215220082-999193dc-cfe9-42ed-8213-6400189068bb.jpg)

**Comment by manateelazycat** [comment]
已经通过 https://github.com/manateelazycat/nova 实现了， 补全计算在服务器上， 补全菜单渲染在本地， 明天我会补充一下 lsp-bridge 与 nova 结合配置的文档。

**Comment by Jemoka** [comment]
哇哦！精彩 （期待这块的发展，如果nova有机会解决tramp的问题以及能实现文件补全那就太好了。。。

**Comment by manateelazycat** [comment]
> 哇哦！精彩 （期待这块的发展，如果nova有机会解决tramp的问题以及能实现文件补全那就完美了。。。

tramp设计太糟糕了，性能太差了，nova会替换tramp并提供同样功能。

**Comment by zwpaper** [comment]
为啥远端的服务器上还要安装 emacs？能否在远端只跑 nova？

**Comment by manateelazycat** [comment]
> 为啥远端的服务器上还要安装 emacs？能否在远端只跑 nova？

当初写 lsp-bridge 的时候， 考虑自定义选项， Python代码要大量读取 emacs 的配置，理论上其实只用跑 lsp-bridge 的Python模块就行了， 不应该跑 Emacs 的。

现在主要考虑是先把远程编辑的功能做出来， 再慢慢优化吧。

**Comment by manateelazycat** [comment]
> 为啥远端的服务器上还要安装 emacs？能否在远端只跑 nova？

今天写了一个新的补丁 https://github.com/manateelazycat/lsp-bridge/commit/fd80ffa4ad4895c450feeebe1a56907858cb37ac

现在远程补全不需要在服务端启动Emacs, 直接启动 lsp-bridge 的Python模块就好了：

1. 在远程服务器上安装 lsp-bridge 以及对应的LSP Server
2. 启动lsp-bridge 服务: python3 lsp-bridge/lsp_bridge.py
3. 使用命令 `lsp-bridge-open-remote-file` 打开远程文件，输入远程服务器 IP 和文件路径，比如 `xxx.xxx.xxx.xxx:/path/file`

lsp-bridge依赖的elisp代码， 我想了办法， 让lsp-bridge服务端通过SSH隧道反向来本机查找Elisp变量和函数值。

最新的设计的好处是：

1. 用户只用在服务器安装 lsp-bridge 和 LSP Server就行了， 不需要在远端安装编辑插件
2. Emacs插件和配置全部在本地
3. lsp-bridge会自动探测所处的环境， 选择用本地还是远端 lsp-bridge 代码去计算补全菜单
