### ISSUE TITLE
升级到最新版(master) 之后，启动时，出错了。

### ISSUE THREAD

**Issue by zw963** [manateelazycat/lsp-bridge#366]
我通常使用 Emacs 的时候，总是使用 daemon-mode, 即，首先启动一个 server, 然后，用 emacsclient 连接它。

然而，当我升级到最新版之后，启动 server 的时候出错了。

下面的日志来自于几乎最小化配置。

```
Cleaning up the recentf list...done (0 removed)
Repeat mode is enabled for 14 commands and 7 keymaps; see ‘describe-repeat-maps’
Loading /home/zw963/Dropbox/common/.emacs.d/base_init.el (source)...done
Loading /home/zw963/Dropbox/common/.emacs.d/early_init.el (source)...done
Starting Emacs daemon.
Debugger entered--Lisp error: (wrong-type-argument lsp-bridge-epc-manager nil)
  signal(wrong-type-argument (lsp-bridge-epc-manager nil))
  (or (progn (and (memq (type-of mngr) cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr)))
  (progn (or (progn (and (memq (type-of mngr) cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr))) (aref mngr 7))
  (let ((uid (lsp-bridge-epc-uid)) (sessions (progn (or (progn (and (memq ... cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr))) (aref mngr 7))) (d (lsp-bridge-deferred-new))) (setq sessions (cons (cons uid d) sessions)) (progn (or (progn (and (memq (type-of mngr) cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr))) (let* ((v mngr)) (aset v 7 sessions))) (lsp-bridge-epc-manager-send mngr 'call uid method-name args) d)
  lsp-bridge-epc-call-deferred(nil tabnine_complete ("\n(setq default-directory \"/home/zw963/Dropbox/comm..." "" nil t t 10))
  (setq it (lsp-bridge-epc-call-deferred lsp-bridge-epc-process (read method) args))
  (let (it) (setq it (lsp-bridge-epc-call-deferred lsp-bridge-epc-process (read method) args)) it)
  lsp-bridge-call-async("tabnine_complete" "\n(setq default-directory \"/home/zw963/Dropbox/comm..." "" nil t t 10)
  (let* ((buffer-min 1) (buffer-max (1+ (buffer-size))) (chars-number-before-point 3000) (chars-number-after-point 1000) (max-num-results 10) (before-point (max (point-min) (- (point) chars-number-before-point))) (after-point (min (point-max) (+ (point) chars-number-after-point)))) (lsp-bridge-call-async "tabnine_complete" (buffer-substring-no-properties before-point (point)) (buffer-substring-no-properties (point) after-point) (or (buffer-file-name) nil) (= before-point buffer-min) (= after-point buffer-max) max-num-results))
  lsp-bridge-tabnine-complete()
  (progn (lsp-bridge-tabnine-complete))
  (if acm-enable-tabnine-helper (progn (lsp-bridge-tabnine-complete)))
  lsp-bridge-monitor-after-change(1 109 0)
  command-line-1(("-l" "~/Dropbox/common/.emacs.d/set_load_path.el"))
  command-line()
  normal-top-level()

Wrote /home/zw963/.emacs.d/places
Wrote /home/zw963/.emacs.d/recentf
Error: server did not start correctly
```

**Comment by zw963** [comment]
正常模式启动，似乎也是出错的。


Debugger entered--Lisp error: (wrong-type-argument lsp-bridge-epc-manager nil)
  signal(wrong-type-argument (lsp-bridge-epc-manager nil))
  (or (progn (and (memq (type-of mngr) cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr)))
  (progn (or (progn (and (memq (type-of mngr) cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr))) (aref mngr 7))
  (let ((uid (lsp-bridge-epc-uid)) (sessions (progn (or (progn (and (memq ... cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr))) (aref mngr 7))) (d (lsp-bridge-deferred-new))) (setq sessions (cons (cons uid d) sessions)) (progn (or (progn (and (memq (type-of mngr) cl-struct-lsp-bridge-epc-manager-tags) t)) (signal 'wrong-type-argument (list 'lsp-bridge-epc-manager mngr))) (let* ((v mngr)) (aset v 7 sessions))) (lsp-bridge-epc-manager-send mngr 'call uid method-name args) d)
  lsp-bridge-epc-call-deferred(nil tabnine_complete ("\n(setq default-directory \"/home/zw963/Dropbox/comm..." "" nil t t 10))
  (setq it (lsp-bridge-epc-call-deferred lsp-bridge-epc-process (read method) args))
  (let (it) (setq it (lsp-bridge-epc-call-deferred lsp-bridge-epc-process (read method) args)) it)
  lsp-bridge-call-async("tabnine_complete" "\n(setq default-directory \"/home/zw963/Dropbox/comm..." "" nil t t 10)
  (let* ((buffer-min 1) (buffer-max (1+ (buffer-size))) (chars-number-before-point 3000) (chars-number-after-point 1000) (max-num-results 10) (before-point (max (point-min) (- (point) chars-number-before-point))) (after-point (min (point-max) (+ (point) chars-number-after-point)))) (lsp-bridge-call-async "tabnine_complete" (buffer-substring-no-properties before-point (point)) (buffer-substring-no-properties (point) after-point) (or (buffer-file-name) nil) (= before-point buffer-min) (= after-point buffer-max) max-num-results))
  lsp-bridge-tabnine-complete()
  (progn (lsp-bridge-tabnine-complete))
  (if acm-enable-tabnine-helper (progn (lsp-bridge-tabnine-complete)))
  lsp-bridge-monitor-after-change(1 109 0)
  command-line-1(nil)
  command-line()
  normal-top-level()

**Comment by manateelazycat** [comment]
已经修复， 如果还有问题重新打开。
