### ISSUE TITLE
org block 中无法补全

### ISSUE THREAD

**Issue by QuarterHeaven** [manateelazycat/lsp-bridge#372]
系统：MacOS 12.6
lsp bridge 配置：
```
(require 'lsp-bridge)
(global-lsp-bridge-mode)

(require-package 'rustic)
(setq rustic-lsp-client 'lsp-bridge)

(setq lsp-bridge-org-babel-lang-list '("rust" "c" "cpp" "python" "latex"))
(setq lsp-bridge-enable-auto-format-code t)
(setq acm-enable-tabnine t)
(setq lsp-bridge-enable-log t)
```
在单独的代码文件里面补全一切正常，但是在 org 的代码块中无法使用 lsp 补全，只有 `search words`。c/cpp 代码没有反应，rust 按下 tab 显示：
```
Initialization fails with: "Cannot open load file: No such file or directory, lsp-rust"
```
python 一直显示 ：
```
Can’t guess python-indent-offset, using defaults: 4
Wrote /Users/takaobsid/Documents/orgs/.org-src-babel
```
latex 只显示了 `Wrote /Users/takaobsid/Documents/orgs/.org-src-babel`，但是也没有 lsp 补全。

**Comment by manateelazycat** [comment]
第一. 在 org-mode 代码块中按 C-c ' 弹出窗口才能补全
第二. lsp-bridge 只需要 README 中配置， 不需要
`
(require-package 'rustic)
(setq rustic-lsp-client 'lsp-bridge)
`
rustic 是基于 lsp-mode 开发的， lsp-bridge 不需要 lsp-mode 代码就能提供代码补全。
