### ISSUE TITLE
Elisp补全时进行模糊匹配(fuzzy matching)

### ISSUE THREAD

**Issue by liushihao456** [manateelazycat/lsp-bridge#380]
大佬的插件很赞！写代码无比流畅，和以前用lsp-mode完全是两个体验！

一个小的feature request：目前在acm-lsp后端中调用了`acm-candidate-fuzzy-search`来进行模糊匹配（将`acm-candidate-match-function`设为`orderless-flex`即可），而这个功能在acm-elisp后端中好像没有，能否添加一个？我自己尝试改了一下`acm-backend-elisp-candidates`，但发现变得很卡，应该是改的方式不对。写elisp时如果有模糊匹配功能，就能省去频繁地将手指移到键盘右上角去按"-"键的痛苦。效果如下图：
<img width="576" alt="image" src="https://user-images.githubusercontent.com/28855328/196029041-2389c690-3ea9-42a8-8d0d-a14e045e5e4d.png">

**Comment by manateelazycat** [comment]
Elisp 的补全主要靠 obarray, 这个有1.5万条， 模糊匹配， Elisp 的性能不够， 会很卡。

如果要流畅， 要在acm弹出之前， 把 obarray 传递到 Python 端搜索才行。

**Comment by manateelazycat** [comment]
模糊搜索已经支持了， 下面是实例：

save-ex save-excursion

s-curs save-excursion

savee save-excursion

save-in save-point

w-let widget-delete
