### ISSUE TITLE
Can't use lsp-omnisharp

### ISSUE THREAD

**Issue by Kenneth-Mata** [manateelazycat/lsp-bridge#382]
i get the following output in a sample project 

``[LSP-Bridge] Error: can’t find LSP server ’mono’ for /home/kenneth/Desktop/CSharp/Code/IsTrue/Program.cs, disable lsp-bridge-mode.
``

this is the only relevant configuration i have 
``` lisp
(add-to-list 'load-path "~/.emacs.d/lisp/lsp-bridge")

(require 'lsp-bridge)
(global-lsp-bridge-mode)
```
![2022-10-20_09-35](https://user-images.githubusercontent.com/92641443/196950135-8c7ab8c2-c8ef-4dbd-a0c0-885b6e5860cc.png)
when running lsp-bridge-install-omnisharp it does download and unpack in .cache

Thanks in advance

**Comment by manateelazycat** [comment]
You need install mono command from your os.
