### ISSUE TITLE
使用gopls有报错，但是不影响使用

### ISSUE THREAD

**Issue by blithefeng** [manateelazycat/lsp-bridge#385]
--- Recv notification: window/logMessage
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "type": 3,
      "message": "2022/10/23 12:55:38 Handshake session update\n\tupdate_session=1\n\tdebug_address=\"\"\n\tlogfile=\"\"\n\tserver=\"1\"\n\tgopls_path=\"/Users/blithe/.go/bin/gopls\"\n"
   }
}
lsprpc.go:294: unable to add local env to initialize request: json: cannot unmarshal bool into Go struct field WorkspaceSymbolClientCapabilities.capabilities.workspace.symbol.resolveSupport of type struct { Properties []string "json:\"properties\"" }

不知道这个返回是不是对应请求的
--- Recv response gopls (18996)
{
   "jsonrpc": "2.0",
   "result": {
      "capabilities": {
         "textDocumentSync": {
            "change": 2,
            "openClose": true,
            "save": {}
         },
         "completionProvider": {
            "triggerCharacters": [
               "."
            ],
            "completionItem": {}
         },
         "hoverProvider": true,
         "signatureHelpProvider": {
            "triggerCharacters": [
               "(",
               ","
            ]
         },
         "definitionProvider": true,
         "typeDefinitionProvider": true,
         "implementationProvider": true,
         "referencesProvider": true,
         "documentHighlightProvider": true,
         "documentSymbolProvider": true,
         "codeActionProvider": {
            "codeActionKinds": [
               "quickfix",
               "refactor.extract",
               "refactor.rewrite",
               "source.fixAll",
               "source.organizeImports"
            ]
         },
         "codeLensProvider": {},
         "documentLinkProvider": {},
         "workspaceSymbolProvider": true,
         "documentFormattingProvider": true,
         "documentOnTypeFormattingProvider": {
            "firstTriggerCharacter": ""
         },
         "renameProvider": true,
         "foldingRangeProvider": true,
         "executeCommandProvider": {
            "commands": [
               "gopls.add_dependency",
               "gopls.add_import",
               "gopls.apply_fix",
               "gopls.check_upgrades",
               "gopls.edit_go_directive",
               "gopls.gc_details",
               "gopls.generate",
               "gopls.generate_gopls_mod",
               "gopls.go_get_package",
               "gopls.list_imports",
               "gopls.list_known_packages",
               "gopls.regenerate_cgo",
               "gopls.remove_dependency",
               "gopls.run_tests",
               "gopls.run_vulncheck_exp",
               "gopls.start_debugging",
               "gopls.test",
               "gopls.tidy",
               "gopls.toggle_gc_details",
               "gopls.update_go_sum",
               "gopls.upgrade_dependency",
               "gopls.vendor"
            ]
         },
         "callHierarchyProvider": true,
         "workspace": {
            "workspaceFolders": {
               "supported": true,
               "changeNotifications": "workspace/didChangeWorkspaceFolders"
            }
         },
         "inlayHintProvider": {}
      },
      "serverInfo": {
         "name": "gopls",
         "version": "{\"GoVersion\":\"go1.18\",\"Path\":\"golang.org/x/tools/gopls\",\"Main\":{\"Path\":\"golang.org/x/tools/gopls\",\"Version\":\"v0.9.5\",\"Sum\":\"h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=\",\"Replace\":null},\"Deps\":[{\"Path\":\"github.com/BurntSushi/toml\",\"Version\":\"v1.2.0\",\"Sum\":\"h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=\",\"Replace\":null},{\"Path\":\"github.com/google/go-cmp\",\"Version\":\"v0.5.8\",\"Sum\":\"h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=\",\"Replace\":null},{\"Path\":\"github.com/sergi/go-diff\",\"Version\":\"v1.1.0\",\"Sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\",\"Replace\":null},{\"Path\":\"golang.org/x/exp\",\"Version\":\"v0.0.0-20220722155223-a9213eeb770e\",\"Sum\":\"h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=\",\"Replace\":null},{\"Path\":\"golang.org/x/exp/typeparams\",\"Version\":\"v0.0.0-20220722155223-a9213eeb770e\",\"Sum\":\"h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=\",\"Replace\":null},{\"Path\":\"golang.org/x/mod\",\"Version\":\"v0.6.0-dev.0.20220419223038-86c51ed26bb4\",\"Sum\":\"h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=\",\"Replace\":null},{\"Path\":\"golang.org/x/sync\",\"Version\":\"v0.0.0-20220722155255-886fb9371eb4\",\"Sum\":\"h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=\",\"Replace\":null},{\"Path\":\"golang.org/x/sys\",\"Version\":\"v0.0.0-20220722155257-8c9f86f7a55f\",\"Sum\":\"h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=\",\"Replace\":null},{\"Path\":\"golang.org/x/text\",\"Version\":\"v0.3.7\",\"Sum\":\"h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=\",\"Replace\":null},{\"Path\":\"golang.org/x/tools\",\"Version\":\"v0.1.13-0.20220908144252-ce397412b6a4\",\"Sum\":\"h1:glzimF7qHZuKVEiMbE7UqBu44MyTjt5u6j3Jz+rfMRM=\",\"Replace\":null},{\"Path\":\"golang.org/x/vuln\",\"Version\":\"v0.0.0-20220901221904-62b0186a1058\",\"Sum\":\"h1:YnB27EXBD8XxB0JcaOeluuvhF2kS4DrH0k+lpopG2xc=\",\"Replace\":null},{\"Path\":\"honnef.co/go/tools\",\"Version\":\"v0.3.2\",\"Sum\":\"h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=\",\"Replace\":null},{\"Path\":\"mvdan.cc/gofumpt\",\"Version\":\"v0.3.1\",\"Sum\":\"h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=\",\"Replace\":null},{\"Path\":\"mvdan.cc/xurls/v2\",\"Version\":\"v2.4.0\",\"Sum\":\"h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=\",\"Replace\":null}],\"Settings\":[{\"Key\":\"-compiler\",\"Value\":\"gc\"},{\"Key\":\"CGO_ENABLED\",\"Value\":\"1\"},{\"Key\":\"CGO_CFLAGS\",\"Value\":\"\"},{\"Key\":\"CGO_CPPFLAGS\",\"Value\":\"\"},{\"Key\":\"CGO_CXXFLAGS\",\"Value\":\"\"},{\"Key\":\"CGO_LDFLAGS\",\"Value\":\"\"},{\"Key\":\"GOARCH\",\"Value\":\"amd64\"},{\"Key\":\"GOOS\",\"Value\":\"darwin\"},{\"Key\":\"GOAMD64\",\"Value\":\"v1\"}],\"Version\":\"v0.9.5\"}"
      }
   },
   "id": 18996
}
Eval in Emacs: (message '"[LSP-Bridge] Start LSP server (gopls) for /Users/blithe/Workspace/playground/chess with 'project' mode, enjoy hacking!")

gopls版本：golang.org/x/tools/gopls v0.9.5

**Comment by manateelazycat** [comment]
这种报错，但不影响补全的错误不用管吧。

这都是lsp sever打印错误的自由。

**Comment by blithefeng** [comment]
好的，我还以为有协议版本的问题
