### ISSUE TITLE
popup 错位

### ISSUE THREAD

**Issue by Corona09** [manateelazycat/lsp-bridge#391]
lsp-bridge 的补全框明显错位
emacs 29.0.50，源码编译，pgtk 或非 pgtk 都有该问题
fedora 37 gnome, 无论是 x11 还是 wayland 都有该问题
只安装了 lsp-bridge, 未安装 company 等补全插件

![](https://raw.githubusercontent.com/Corona09/images/main/%E6%88%AA%E5%9B%BE%202022-10-26%2023-24-02.png)

**Comment by manateelazycat** [comment]
emacs -Q 测试过了吗？

**Comment by Corona09** [comment]
> emacs -Q 测试过了吗？

运行 emacs -Q 后一切正常，不会启动 lsp-bridge

**Comment by manateelazycat** [comment]
我没法重现你的问题， 请排查你的配置。
