### ISSUE TITLE
omnisharp.exe start in wrong directory

### ISSUE THREAD

**Issue by igaryhe** [manateelazycat/lsp-bridge#396]
system info:
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```
emacs version:
```
GNU Emacs 28.2
```
i'm using the latest lsp-bridge from master branch.

my emacs.exe is installed at `d:\scoop\apps\emacs\current\bin\`, and when i open emacs, and then open the c# file in a project, it successfully starts the corresponding omnisharp lsp process. however, in the *lsp-bridge* buffer, it shows the following message:
```
--- Recv notification: window/logMessage
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "type": 3,
      "message": "OmniSharp.LanguageServerProtocol.LanguageServerHost: Omnisharp server running using Lsp at location 'd:\\scoop\\apps\\emacs\\current\\bin' on host 31512. | "
   }
}
```
which indicates that omnisharp isn't running at the project directory, thus not properly analyzing the c# solution.
if i start emacs in powershell, in the c# solution directory, it would shows the following in the *lsp-bridge* buffer:
```
--- Recv notification: window/logMessage
{
   "jsonrpc": "2.0",
   "method": "window/logMessage",
   "params": {
      "type": 3,
      "message": "OmniSharp.MSBuild.ProjectSystem: Detecting projects in 'x:\\workspace\\kg_project\\kgp\\kgp.sln'. | "
   }
}
```

by the way, the current `omnisharp-window.json` seems doing something wrong. i have to manually install a windows version of omnisharp and change the startup script to `omnisharp -z -lsp` to make it work properly. i might submit a pull request for this, but i think it has nothing to do with the previously mentioned behaviour.

**Comment by manateelazycat** [comment]
I'm not window user, nothing can help.

Anyway, any PR are welcome ! ;)

**Comment by manateelazycat** [comment]
your git is not works, please read https://github.com/manateelazycat/lsp-bridge#usage
