### ISSUE TITLE
Tabnine completion issue in PHP Mode

### ISSUE THREAD

**Issue by zonuexe** [manateelazycat/lsp-bridge#402]
Leading `$` in variable replaced with Tabnine completion in [PHP Mode](https://github.com/emacs-php/php-mode) is trimmed.

<img width="344" alt="スクリーンショット 2022-11-07 20 44 32" src="https://user-images.githubusercontent.com/822086/200302738-96fd3384-3c94-4566-a083-0cb1910fd61f.png">
<img width="240" alt="スクリーンショット 2022-11-07 20 44 38" src="https://user-images.githubusercontent.com/822086/200302752-5cf2da5f-3ac2-4c07-8fbd-b6042d09ffaf.png">

It looks like the range of strings that can be replaced with replacement strings is out of alignment.

**Comment by zonuexe** [comment]
If you select the `$entry` supplied by the top LSP in the image above, the `$` will not be trimmed. The problem seems to be only with candidates by Tabnine.

**Comment by manateelazycat** [comment]
I don't understand what your mean, sorry. ;)

**Comment by zonuexe** [comment]
When I type `$ent`, I expect it to be completed with `$entry`. It is actually replaced by `entry` without the leading `$`.

**Comment by zonuexe** [comment]
I figured out that `acm-get-input-prefix-bound` solves the problem.

**Comment by manateelazycat** [comment]
> I figured out that `acm-get-input-prefix-bound` solves the problem.

It's a bug? If yes, can you help send PR? Thanks. ;)

**Comment by zonuexe** [comment]
I decided to adjust the value with the following advice.

```el
(defun php-acm-backend-tabnine-candidate-expand-filter-args (args)
  "Adjust Tabnine replacement bound-start ARGS in PHP."
  (cl-multiple-value-bind (candidate-info bound-start) args
    (save-excursion
      (goto-char bound-start)
      (when (looking-at-p (eval-when-compile (regexp-quote "$")))
        (setq bound-start (1+ bound-start))))
    (list candidate-info bound-start)))

(defun my-php-mode-setup ()
  (advice-add #'acm-backend-tabnine-candidate-expand
              :filter-args #'php-acm-backend-tabnine-candidate-expand-filter-args
              '(local)))
```

Some combinations of language-independent completion engines like Tabnine and languages with variable prefixes (called [sigil](https://en.wikipedia.org/wiki/Sigil_(computer_programming))) like PHP or Perl may need to be corrected in this way. But, other common Emacs major modes (eg ruby-mode and perl-mode) are not affected because `$` is registered as `'` (prefix) in the [syntax table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html). On the other hand, `$` is `_` (symbol) in PHP Mode due to historical reasons.

So this is mostly a php-mode specific problem. I plan to solve this problem in php-mode in the future, so it doesn't seem necessary to add a workaround to lsp-bridge.

**Comment by manateelazycat** [comment]
> I decided to adjust the value with the following advice.
> 
> ```emacs-lisp
> (defun php-acm-backend-tabnine-candidate-expand-filter-args (args)
>   "Adjust Tabnine replacement bound-start ARGS in PHP."
>   (cl-multiple-value-bind (candidate-info bound-start) args
>     (save-excursion
>       (goto-char bound-start)
>       (when (looking-at-p (eval-when-compile (regexp-quote "$")))
>         (setq bound-start (1+ bound-start))))
>     (list candidate-info bound-start)))
> 
> (defun my-php-mode-setup ()
>   (advice-add #'acm-backend-tabnine-candidate-expand
>               :filter-args #'php-acm-backend-tabnine-candidate-expand-filter-args
>               '(local)))
> ```
> 
> Some combinations of language-independent completion engines like Tabnine and languages with variable prefixes (called [sigil](https://en.wikipedia.org/wiki/Sigil_(computer_programming))) like PHP or Perl may need to be corrected in this way. But, other common Emacs major modes (eg ruby-mode and perl-mode) are not affected because `$` is registered as `'` (prefix) in the [syntax table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html). On the other hand, `$` is `_` (symbol) in PHP Mode due to historical reasons.
> 
> So this is mostly a php-mode specific problem. I plan to solve this problem in php-mode in the future, so it doesn't seem necessary to add a workaround to lsp-bridge.

Glad you fix problem, and thank you report this issue help other phper. ;)

**Comment by zonuexe** [comment]
Added workarounds to PHP Mode so users no longer need to configure.
