### ISSUE TITLE
选择补全项后，后续输入的字符无法上屏，但一直有补全项弹出

### ISSUE THREAD

**Issue by 50ways2sayhard** [manateelazycat/lsp-bridge#41]
偶现，目前只出现在 dart-mode 中。
复现方式：
1. 输入字符
2. 选择补全项
3. 持续输入，发现字符不能上屏，但是一直能弹出正确的补全项
4. 重新打开 buffer，发现刚刚输入的字符已经上屏了。

[![Od26zt.gif](https://s1.ax1x.com/2022/05/11/Od26zt.gif)](https://imgtu.com/i/Od26zt)

**Comment by manateelazycat** [comment]
我还没法重现你说的问题。能给一个复现的最小代码吗？ 我有空测试一下。

**Comment by 50ways2sayhard** [comment]
我更新代码后也不能重现了，后面再观察一下吧😂
