### ISSUE TITLE
haskell setting issues

### ISSUE THREAD

**Issue by raymentkong** [manateelazycat/lsp-bridge#411]
之前，按照lsp-mode主页的安装说明，配置 lsp-haskell，一直没有成功。
因此尝试使用lsp-bridge。按照主页的安装步骤进行设置，打开.hs文件没有任何提示和响应，也没有报错误提示。

运行环境：ubuntu 20.04  emacs28.1
haskell 使用ghcup安装，hls也安装好（在$PATH中可以找到），通过使用vscode的haskell插件调用hls，打开.hs文件是没有任何问题。
查看过lsp-bridge/langserver/hls.json文件，hls设置是没有问题。
另外，打开c文件是可以使用clangd，没有问题。
所以，请问通过lsp-bridge使用haskell还需要怎样的设置才可以使用？

我的init.el设置（涉及lsp-bridage部分）如下：
(add-to-list 'load-path "~/.emacs.d/lsp-bridge")
(use-package posframe)

(use-package markdown-mode
  :ensure t
  :mode ("README\\.md\\'" . gfm-mode)
  :init (setq markdown-command "multimarkdown"))

(require 'yasnippet)
(yas-global-mode 1)

(require 'lsp-bridge)
(global-lsp-bridge-mode)
      
(provide 'init-package)

**Comment by manateelazycat** [comment]
你安装了 haskell-mode 这个插件了吗？

**Comment by raymentkong** [comment]
问题解决了，需要安装 haskell-mode ，lsp-mode，lsp-haskell，company，dante插件，就有代码自动完成提示。
