### ISSUE TITLE
输入以后要过很久才会弹出lsp的补全选项

### ISSUE THREAD

**Issue by QuarterHeaven** [manateelazycat/lsp-bridge#415]
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/41909950/201514270-d2108c7f-d980-4676-990c-d3e183800fb4.png">
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/41909950/201514294-04df860a-711d-4cb5-ae8c-586c6aba006b.png">
如图所示，emacs -q 只加载了 lsp-bridge 和 yasnippet，在输入 `vec` 以后只有 yasnippet 的补全，过了大概 5 秒出现 word search 补全，又过了 10 秒才出现了 lsp 的补全。打开 *lsp-bridge* 可以看见我输入 `vec` 大概在 50000 行左右，lsp 刷到了大概 60000 行才出现补全。试了一下 rust，情况也类似。请问这是什么原因？

**Comment by manateelazycat** [comment]
你平常使用的时候不要打开log选项呀。
