### ISSUE TITLE
lsp-bridge-diagnostic-list shows lots of unexpected symbols 

### ISSUE THREAD

**Issue by zilongshanren** [manateelazycat/lsp-bridge#429]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/785541/204087906-49e6e03d-7451-423c-a6af-ea0df0064c89.png">

**Comment by zilongshanren** [comment]
^[[94m^[[0m)

**Comment by zilongshanren** [comment]
platform: MacOS 12.5.1
Emacs version: 28.2
lsp-bridge version: latest master

**Comment by zilongshanren** [comment]
这个问题并不是必现，在切换项目的时候容易出现。

lsp-bridge-diagnostic-jump-next 有时候不显示Posframe，大概率重现。

还有就是多个不同项目切换的时候，diagnostic信息会丢失，修改buffer后，diagnostic信息会再次出来

**Comment by manateelazycat** [comment]
这个发一个 main.rs 给我吧， 应该可以修复。

**Comment by zilongshanren** [comment]
```
fn solution(phrase: &str) -> String {
    phrase.chars().rev().collect()
}

fn main() {
    assert_eq!(solution("world"), "dlrow")

}


#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn sample_test() {
        assert_eq!(solution("world"), "dlrow");
    }
}

```

**Comment by manateelazycat** [comment]
你的 rust和rust-analyzer 是什么版本？ 为什么我一个诊断都没有呢？

我怀疑最近的几个issue也是版本差异导致的。
