### ISSUE TITLE
how to exclude certain file type in lsp-bridge?

### ISSUE THREAD

**Issue by suliveevil** [manateelazycat/lsp-bridge#430]
请问猫大如何才能给单独的文件类型（或特定文件）排除到 lsp-bridge 之外啊？谢谢 🙏

clojure-lsp 不支持针对单文件的 lsp 服务

![clojure-lsp](https://user-images.githubusercontent.com/35763237/204131746-94448fda-7ed6-4b3a-b3a2-33e0ae9cf59d.png)

**Comment by manateelazycat** [comment]
就是定制 lsp-bridge-get-single-lang-server-by-project 函数， 如果是 clojure 单文件直接返回 nil.

**Comment by suliveevil** [comment]
好的，谢谢老大。🥰
