### ISSUE TITLE
Omnisharp does not install correctly on windows

### ISSUE THREAD

**Issue by JordanAnthonyKing** [manateelazycat/lsp-bridge#431]
When attempting to install omnisharp you get a message like: `Directory does not exist _<path-to-user-emacs-directory>AppData/Local/Temp_`. It appears that the download path is relative isntead of absolute.

I fixed this with a simple override, setting the path directly instead of with `%userprofile%`
```
(defun +lsp-bridge-install-omnisharp (&rest args)
  (interactive)
  (let ((url "https://github.com/OmniSharp/omnisharp-roslyn/releases/latest/download/omnisharp-mono.zip")
        (down-des (if (eq system-type 'windows-nt)
                      "~/AppData/Local/Temp/omnisharp-mono.zip" <-- *here*
                    "/tmp/omnisharp-mono.zip"))
        (install-des (if (eq system-type 'windows-nt)
                         (format "%s.cache\\omnisharp\\" user-emacs-directory)
                       "~/.emacs.d/.cache/omnisharp/"
                       (format "%s.cache/omnisharp/" user-emacs-directory))))
    (url-copy-file url down-des 1)
    (unless (file-directory-p install-des)
      (make-directory install-des t))
    (call-process-shell-command (format "%s -xf %s -C %s" "tar" down-des install-des))
    ))

(advice-add 'lsp-bridge-install-omnisharp :override '+lsp-bridge-install-omnisharp)
```

However, after successfully downloading omnisharp, it is not successfully installed to `.emacs.d/.cache/omnisharp`. The folder is created, but the zip is not extracted. There are no error messages given as to why. Tar is installed on the system.

After manually copying the files from the zip to the .cache directory it seems to work (but I've not given it a proper test drive yet).

**Comment by manateelazycat** [comment]
PR are welcome

**Comment by JordanAnthonyKing** [comment]
I'm looking to improve the omnisharp download and add support for the official .net sdk as well as mono, but I don't know where to start with debugging the `call-process-shell-command` issue.

**Comment by manateelazycat** [comment]
You need add `BUFFER` argument in call-process-shell-command for debug purpose.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/45714bb5f2c61991713ae8458ba10ce7fec9e02b
