### ISSUE TITLE
lsp-bridge expects _.emacs.d_ to be under _AppData_ on Windows

### ISSUE THREAD

**Issue by JordanAnthonyKing** [manateelazycat/lsp-bridge#432]
Looking in `omnisharp-window.json` we can see:
```
{
    "name": "omnisharp",
    "languageId": "c#",
    "command": ["mono",
                "%USERPROFILE%\\AppData\\Roaming\\.emacs.d\\.cache\\omnisharp\\OmniSharp.exe",
                "-z",
                "-lsp"],
    "settings": {}
}
```
Which expects the user emacs directory to be under AppData, although this is the default on Windows `~/.emacs.d/` or `C:\Users\<user>\.emacs.d\` work also.

**Comment by manateelazycat** [comment]
PR are welcome

**Comment by JordanAnthonyKing** [comment]
How would one go about making this dynamic? A concat at the point that its read?

**Comment by manateelazycat** [comment]
You can customize omnisharp-window.json content and put file with your own path, then customize function `lsp-bridge-get-single-lang-server-by-project` that reutrn new path.

lsp-bridge will load omnisharp config with new path.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/45714bb5f2c61991713ae8458ba10ce7fec9e02b
