### ISSUE TITLE
C# - View diagnostics?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [manateelazycat/lsp-bridge#435]
Hi, I'm currently working through fixing some issues with the C# language server. Diagnostic messages don't seem to work:

![image](https://user-images.githubusercontent.com/58787893/204662039-c0d17077-a607-40f8-9adb-da50cac91cd1.png)

Although the offender is correctly highlighted, there's no message in the echo area or a childframe. I'm seeing `--- Recv notification: textDocument/publishDiagnostics` in the lsp-bridge buffer, but nothing reflected in the actual buffer.

Calling `lsp-bridge-diagnostic-copy` returns `Wrong type argument: frame-live-p nil`.

Where is a good place to start debugging this? Or is this something not supported by lsp-bridge?

**Comment by JordanAnthonyKing** [comment]
Ah!

![image](https://user-images.githubusercontent.com/58787893/204664042-c0fd7062-3644-4f75-976f-78a48b51c7b3.png)

I got it to trigger after calling the jump-function. Is it supposed to trigger automatically on mouse over?

**Comment by manateelazycat** [comment]
I have fix this issue, thanks for report.

BTW, have you make C# lsp server works with lsp-bridge?

**Comment by JordanAnthonyKing** [comment]
Hi @manateelazycat yes, I have fixes on my fork. I will be submitting a PR, however there's one issue wrt to hardcoded paths in the .json files I don't have a solution for.
