### ISSUE TITLE
Hide markdown markup in acm-doc

### ISSUE THREAD

**Issue by JordanAnthonyKing** [manateelazycat/lsp-bridge#438]
Hi, I'm trying to hide markup from the documentation popup. I'd have thought adding these two lines would do the trick, but although the mode is activated, the buffer contents are unchanged.

![image](https://user-images.githubusercontent.com/58787893/204919658-0cd3bd10-f81e-4b90-8980-f675805c1f2a.png)

Any idea why?

**Comment by manateelazycat** [comment]
Did you try `emacs -Q` for comparison test?

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/pull/440
