### ISSUE TITLE
补全隐藏目录会多一个.

### ISSUE THREAD

**Issue by devbins** [manateelazycat/lsp-bridge#442]
补全 `"~/.emac.d"` 之后会变成 `"~/..emacs.d"` 多了一个 `.`

**Comment by manateelazycat** [comment]
我才测试的，不会多一个 . 

请 `emacs -Q` 对比测试排除一下自己的配置影响。

**Comment by devbins** [comment]
我也是用 emacs -Q 测试的，刚刚又试了下，写lisp不会，写Go、Rust、Python才会

**Comment by manateelazycat** [comment]
修复了， 请更新， 感谢反馈。
