### ISSUE TITLE
Omnisharp can't start.

### ISSUE THREAD

**Issue by BigCrow** [manateelazycat/lsp-bridge#446]
When the omnisharp server is trying to start I get this message in the *lsp-bridge* buffer

```
Cannot open assembly '$HOME/.emacs.d/.cache/omnisharp/OmniSharp.exe': No such file or directory.

--- Lsp server exited, exit code: 2
b''

```

The OmniSharp.exe is in that directory - I could access it through the terminal via the "mono $HOME/.emacs.d/.cache/omnisharp/OmniSharp.exe" command.
I'm using omnisharp-mono. 

I tried downloading  omnisharp-dotnet as well. The omnisharp folder of dotnet does not contain an "OmniSharp.exe" and instead just an "Omnisharp" executable. Changing the json command for omnisharp-dotnet to use the "OmniSharp" executable instead of the "OmniSharp.exe" gives that error in the message buffer (*lsp-bridge* is empty) 
"[LSP-Bridge] Error: can’t find command ’$HOME/.emacs.d/.cache/omnisharp/OmniSharp’ to start LSP server omnisharp-dotnet".
The "Omnisharp" executable can be launched via the terminal with the "$HOME/.emacs.d/.cache/omnisharp/OmniSharp" command.

OS: Arch Linux x86_64
Emacs: 28.2.50 pgtk-nativecomp 91394b03a ~/.emacs.d/
lsp-bridge: https://github.com/manateelazycat/lsp-bridge/commit/45714bb5f2c61991713ae8458ba10ce7fec9e02b

**Comment by manateelazycat** [comment]
You need update to newest and restart Emacs, try agian.

**Comment by BigCrow** [comment]
The newest update fixes the first issue, but the issue with the omnisharp-dotnet persist.

**Comment by manateelazycat** [comment]
> The newest update fixes the first issue, but the issue with the omnisharp-dotnet persist.

```
{
    "name": "omnisharp-dotnet",
    "languageId": "c#",
    "command": ["$HOME/.emacs.d/.cache/omnisharp/OmniSharp",
                "-lsp"],
    "settings": {},
    "support-single-file": false
}
```
omnisharp-dotnet will works if remove `.exe` ?

**Comment by BigCrow** [comment]
It does not. It gives the message "[LSP-Bridge] Error: can’t find command ’$HOME/.emacs.d/.cache/omnisharp/OmniSharp’ to start LSP server omnisharp-dotnet". *lsp-bridge* buffer is empty.

**Comment by manateelazycat** [comment]
What is your OmniSharp full path?

**Comment by BigCrow** [comment]
/home/cabalcrow/.emacs.d/.cache/omnisharp/

**Comment by manateelazycat** [comment]
Add `print(lang_server_info)` after line https://github.com/manateelazycat/lsp-bridge/blob/c11a6961cbe20be7727e26f3e25effe831b2a18c/lsp_bridge.py#L236

And paste content of `*lsp-bridge*` to here, thanks.

**Comment by manateelazycat** [comment]
Update to newest and try again, thanks.

**Comment by BigCrow** [comment]
Sorry, I found the issue - it was on my end. The downloaded OmniSharp executable did not have rights to be used as an executable from the system. The dotnet works after I set the correct permissions.

**Comment by BigCrow** [comment]
Yes the new version starts omnisharp-dotnet correctly.

**Comment by BigCrow** [comment]
There is actually one issue in the new version.

The omnisharp-mono was working correctly and is using .exe . So the file should be
```
 "name": "omnisharp-mono",
    "languageId": "c#",
    "command": ["mono",
                "$HOME/.emacs.d/.cache/omnisharp/OmniSharp.exe",
                "-z",
                "-lsp"],
    "settings": {}
    ```
    
    The onmisharp-dotnet is not using an exe file so it only needs the fix from the new version.

**Comment by manateelazycat** [comment]
> There is actually one issue in the new version.
> 
> The omnisharp-mono was working correctly and is using .exe . So the file should be
> 
> ```
>  "name": "omnisharp-mono",
>     "languageId": "c#",
>     "command": ["mono",
>                 "$HOME/.emacs.d/.cache/omnisharp/OmniSharp.exe",
>                 "-z",
>                 "-lsp"],
>     "settings": {}
>     ```
>     
>     The onmisharp-dotnet is not using an exe file so it only needs the fix from the new version.
> ```

Can you give me a PR ? Thanks.

**Comment by manateelazycat** [comment]
Nevermind, I fix it.

**Comment by manateelazycat** [comment]
> There is actually one issue in the new version.
> 
> The omnisharp-mono was working correctly and is using .exe . So the file should be
> 
> ```
>  "name": "omnisharp-mono",
>     "languageId": "c#",
>     "command": ["mono",
>                 "$HOME/.emacs.d/.cache/omnisharp/OmniSharp.exe",
>                 "-z",
>                 "-lsp"],
>     "settings": {}
>     ```
>     
>     The onmisharp-dotnet is not using an exe file so it only needs the fix from the new version.
> ```

Done https://github.com/manateelazycat/lsp-bridge/commit/f2a91e727e113e278466fc9934ae6548fdc0bbb8
