### ISSUE TITLE
补全后端没有优先匹配yas snippet的key

### ISSUE THREAD

**Issue by thiefuniverse** [manateelazycat/lsp-bridge#447]
![image](https://user-images.githubusercontent.com/12184047/205445318-03ead87e-21b1-4014-a5aa-4982b20b656b.png)
![image](https://user-images.githubusercontent.com/12184047/205445416-371f6fb5-9a7d-4476-8ad7-c2eb8e17b3e2.png)
如第一张图，没有优先匹配key，往下滑应该能找到ct，只是感觉它应该优先显示；然后第二张图，我是想尝试用name去匹配，发现也不行；另外这里还想请教下对于匹配内容里面有空格的情况，可以怎么操作呢？

**Comment by manateelazycat** [comment]
acm 现在是融合多个补全后端的， 由函数 acm-update-candidates 控制的。

匹配内容有空格啥意思？

**Comment by thiefuniverse** [comment]
有空格 是说 我前面发的图里面，第二张图的红色箭头里，整个选项是"comment box"(我怀疑是不是用了我snippet里定义的name作为candidates, 图片右侧是我这里的snippet定义)；这个时候我不能输入空格去匹配了；我只要输入空格之后，不管再输入什么，就会重新开始匹配。当然这里我可以不输入空格....      
![image](https://user-images.githubusercontent.com/12184047/205448085-9cad0b24-27ac-45a2-98b9-dd4de9984e40.png)

我看到acm-update-candidates 了，我看看能不能改下.

**Comment by manateelazycat** [comment]
空格应该是 yasnippet 的名称， 你可以改进一下 yas 后端的过滤算法: acm-backend-yas-candidates

**Comment by liuyinz** [comment]
@thiefuniverse 没明白你的问题是什么。
1. 你两张图都是用snippet name匹配的，没用key。
2. 我还没考虑过会有人在snippet name里面用空格，如果你想用lsp-bridge来输入yasnippet的话，那会很麻烦，因为补全在取prefix的时候默认使用空格分割的。snippet name 用-或者_来链接会更好，正如你的snippet filename那样。而且默认的话snippet filename 要么和snippet name一样，要么和snippet key一样，你这三者都不一样完全是自找麻烦，朋友。

**Comment by thiefuniverse** [comment]
> @thiefuniverse 没明白你的问题是什么。
> 
> 1. 你两张图都是用snippet name匹配的，没用key，`acm-backend-yas-match-by-trigger-keyword`是否设置为 t ？
> 2. 我没考虑过会有人在snippet name里面用空格，如果你想用lsp-bridge来输入yasnippet的话，那会很麻烦，因为补全在取prefix的时候会使用空格分割的。snippet name 用-或者_来链接会更好，正如你的snippet filename那样。而且按照惯例，snippet filename 要么和snippet name一样，要么和snippet key一样，你这三者都不一样完全是自找麻烦，朋友。

我的第一张图是用了key的，ct就是我定义的key；我设置这个acm-backend-yas-match-by-trigger-keyword 这个之后可以在首屏上看到snippet了，多谢~ 另外说明下，这里之所以我定义name的时候加了空格，其实是想更直观的表示它的意思，加下划线总感觉不是很顺畅，snippet的filename不想用空格来命名，所以用了下划线，这块确实混乱了点

**Comment by manateelazycat** [comment]
如果要支持空格搜索， 得把整个 yas 搜索弄到 python 那边去， 就像 acm-backend-elisp.el 那样。

欢迎 PR， 这个issue先关闭了。
