### ISSUE TITLE
variable rename strange behavior on windows 

### ISSUE THREAD

**Issue by honghuzi** [manateelazycat/lsp-bridge#457]
When I tried renaming a python variable on Windows, the variable name did not change. Instead, emacs asked me 
>> Directory "D:/d%3A/my-project/test" does not exist! Create it? (y or n) 

sys info and configs are
- Win10, Emacs version 28.2
- doom emacs configuration
- all lsp features deleted in the init.el file

**Comment by manateelazycat** [comment]
(setq lsp-bride-enable-log t) then, check content of `*lsp-bridge*`, and do rename operation.

Last, paste content of `*lsp-bridge*` here, thanks.

**Comment by manateelazycat** [comment]
Can you send all log to me ?

**Comment by honghuzi** [comment]
[log.txt](https://github.com/manateelazycat/lsp-bridge/files/10175742/log.txt)

i found similar behavior of lsp-bridge for command like
- lsp-bridge-workspace-list-symbols

**Comment by honghuzi** [comment]
[log.txt](https://github.com/manateelazycat/lsp-bridge/files/10175956/log.txt)

![screenshots](https://user-images.githubusercontent.com/8718754/206177857-66ddc798-807a-4896-9f7b-9b292f7c3caf.gif)
already evaled

**Comment by manateelazycat** [comment]
> [log.txt](https://github.com/manateelazycat/lsp-bridge/files/10175956/log.txt)
> 
> ![screenshots](https://user-images.githubusercontent.com/8718754/206177857-66ddc798-807a-4896-9f7b-9b292f7c3caf.gif) [ ![screenshots](https://user-images.githubusercontent.com/8718754/206177857-66ddc798-807a-4896-9f7b-9b292f7c3caf.gif) ](https://user-images.githubusercontent.com/8718754/206177857-66ddc798-807a-4896-9f7b-9b292f7c3caf.gif) [ ](https://user-images.githubusercontent.com/8718754/206177857-66ddc798-807a-4896-9f7b-9b292f7c3caf.gif) already evaled

enable log option

restart lsp-bridge

and send me log

**Comment by honghuzi** [comment]
[log.txt](https://github.com/manateelazycat/lsp-bridge/files/10176562/log.txt)

same issue.

**Comment by manateelazycat** [comment]
> [log.txt](https://github.com/manateelazycat/lsp-bridge/files/10176562/log.txt)
> 
> same issue.

Did you restart Emacs after update lsp-bridge to newest version ?

**Comment by honghuzi** [comment]
Sorry,  I forgot to backup my lsp-bridge folder before git pull. now everything works fine. I have been testing my own language support for lsp-bridge, and that caused the git pull issue.
