### ISSUE TITLE
acm bindings not activating when pop-up window is available

### ISSUE THREAD

**Issue by ConceitedZebra** [manateelazycat/lsp-bridge#458]
First off, thank you for this package, the performance is excellent.

I added the recommended lines in the [installation step](https://github.com/manateelazycat/lsp-bridge#installation), and lsp-bridge activates without issue. I can use `M-x` lsp-bridge commands, and autocompletion results show up when I type.

When completions are available, I can select the next completion witb ‘C-n’, select the previous completion witb ‘C-p’, and confirm a completion with ‘Tab’. 

However, most of the keybindings listed in the [Keymap section](https://github.com/manateelazycat/lsp-bridge#keymap) do not seem to work when a pop up window is active, and instead perform the regular action bound to the key. Did I miss a configuration step?

**Comment by ConceitedZebra** [comment]
I'm sorry, I missed part of my config where `company` was being loaded.

**Comment by manateelazycat** [comment]
> Is there a way to bind keys `lsp-bridge-popup-documenation-scroll-up` or `lsp-bridge-popup-documenation-scroll-down` where the mapping is only active when the documentation popup is shown via `lsp-bridge-pop-documentation`?

Yes.
