### ISSUE TITLE
Lisp error: (error "Already at start of element")

### ISSUE THREAD

**Issue by cxb811201** [manateelazycat/lsp-bridge#463]
Debugger entered--Lisp error: (error "Already at start of element")
  error("Already at start of element")
  nxml-backward-single-balanced-item()
  nxml-forward-balanced-item(-1)
  forward-sexp(-1)
  up-list(-1)
  (let ((_ counter)) (up-list -1) (save-excursion (if (eq (char-after) 40) (progn (forward-char 1) (if (condition-case nil (progn (save-excursion ... ...)) (error nil)) (progn (skip-chars-forward " \11\n") (cond (... ... ...) (... ... ...))))))))
  (while (< counter upper-bound) (let ((_ counter)) (up-list -1) (save-excursion (if (eq (char-after) 40) (progn (forward-char 1) (if (condition-case nil (progn ...) (error nil)) (progn (skip-chars-forward " \11\n") (cond ... ...))))))) (setq counter (1+ counter)))
  (let ((upper-bound acm-backend-elisp-parse-depth) (counter 0)) (while (< counter upper-bound) (let ((_ counter)) (up-list -1) (save-excursion (if (eq (char-after) 40) (progn (forward-char 1) (if (condition-case nil ... ...) (progn ... ...)))))) (setq counter (1+ counter))))
  (save-excursion (let ((upper-bound acm-backend-elisp-parse-depth) (counter 0)) (while (< counter upper-bound) (let ((_ counter)) (up-list -1) (save-excursion (if (eq (char-after) 40) (progn (forward-char 1) (if ... ...))))) (setq counter (1+ counter)))))
  (condition-case nil (save-excursion (let ((upper-bound acm-backend-elisp-parse-depth) (counter 0)) (while (< counter upper-bound) (let ((_ counter)) (up-list -1) (save-excursion (if (eq ... 40) (progn ... ...)))) (setq counter (1+ counter))))) (scan-error nil))
  (let ((regexp "[ \11\n]*\\(\\_<\\(?:\\sw\\|\\s_\\)*\\_>\\)") (pos (point)) res) (condition-case nil (save-excursion (let ((upper-bound acm-backend-elisp-parse-depth) (counter 0)) (while (< counter upper-bound) (let ((_ counter)) (up-list -1) (save-excursion (if ... ...))) (setq counter (1+ counter))))) (scan-error nil)) res)
  acm-backend-elisp-local-symbols()
  (append (acm-backend-elisp-local-symbols) (acm-backend-elisp-global-symbols))
  acm-backend-elisp-get-symbols()
  lsp-bridge-elisp-symbols-update()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_66>()
  apply(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_66> nil)
  explain-pause--wrap-callback(#s(explain-pause-command-record :command idle-timer :native t :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 1016379 :entry-snap (25494 41022 199385 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_66>)
  apply(explain-pause--wrap-callback (#s(explain-pause-command-record :command idle-timer :native t :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 1016379 :entry-snap (25494 41022 199385 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_66>))
  timer-event-handler([t 0 3 0 t explain-pause--wrap-callback (#s(explain-pause-command-record :command idle-timer :native t :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 1016379 :entry-snap (25494 41022 199385 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_66>) idle 0 nil])

**Comment by cxb811201** [comment]
打开一个xml文件后，会报上面错误，xml-mode中并未启用lsp-bridge-mode

**Comment by manateelazycat** [comment]
你看你的错误堆栈信息和lsp-bridge没关系啊

**Comment by cxb811201** [comment]
![image](https://user-images.githubusercontent.com/2104470/206972555-e900fc7e-eedd-4c4c-bc61-7f037809931a.png)
在红框中执行了lsp-bridge-elisp-symbols-update
理论上xml-mode未启用lsp-bridge-mode的话，不会执行lsp-bridge的相关逻辑才对吧。

**Comment by manateelazycat** [comment]
> ![image](https://user-images.githubusercontent.com/2104470/206972555-e900fc7e-eedd-4c4c-bc61-7f037809931a.png) 在红框中执行了lsp-bridge-elisp-symbols-update 理论上xml-mode未启用lsp-bridge-mode的话，不会执行lsp-bridge的相关逻辑才对吧。

lsp-bridge会定期更新elisp符号，xml文件方便发我下吗？

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/22264d63cdedf53ae337ad2777f4f192d0fcf9e5

推送了这个补丁， 更新试一下。

**Comment by cxb811201** [comment]
@manateelazycat 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    FA-Software License, Version 1.0

    Copyright (c) 2022 FA Software (Shanghai) Co., Ltd. All Rights Reserved.

    https://www.fa-software.com/licenses/LICENSE-1.0

-->

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <pluginGroups/>

  <proxies/>

  <servers>
    <server>
      <id>cimNexus</id>
      <username>admin</username>
      <password>Accp1234</password>
    </server>
  </servers>

  <mirrors>
      <mirror>
          <id>cimNexus</id>
          <mirrorOf>*</mirrorOf>
          <name>cim maven repo</name>
          <url>http://192.168.1.168:8081/repository/maven-public/</url>
      </mirror>
  </mirrors>

  <profiles/>
</settings>
```

**Comment by cxb811201** [comment]
@manateelazycat 没有问题了，Thanks
