### ISSUE TITLE
Submit MELPA recipe

### ISSUE THREAD

**Issue by aspiers** [manateelazycat/lsp-bridge#465]
Hi, thanks for this awesome project!  I am just trying to install it, and I see that there is no MELPA recipe yet:

https://melpa.org/#/?q=lsp-bridge

Is this intentional, or would it be OK if I submitted one?  This would make installation a lot easier for many people.

**Comment by manateelazycat** [comment]
no i dislike melpa, thanks

**Comment by aspiers** [comment]
Sorry to hear you don't like MELPA.  However, a huge number of emacs users rely on MELPA for installing their packages, so not having `lsp-bridge` on there can significantly reduce the number of people who will adopt `lsp-bridge`.

I can totally understand if you don't want to submit a recipe yourself, but I have already written one and am volunteering to submit it to MELPA and maintain it.  So you don't need to worry about it.  Please let me know if you see any problem with this approach.  Thanks!

**Comment by manateelazycat** [comment]
I will not prevent others from uploading code to melpa, but I will not deal with problems from mepla. 

I will emphasize over and over again that git installing lsp-bridge is the correct way.

**Comment by aspiers** [comment]
Thanks very much for the response.  As a maintainer myself, I totally understand the need to place limits on what you can realistically support.  In order to avoid having to repeat the same installation recommendations many times, if there are specific reasons for avoiding certain approaches to installation, I would suggest documenting those and then fewer people will experience the associated pitfalls.

**Comment by MatthewZMD** [comment]
> Thanks very much for the response.  As a maintainer myself, I totally understand the need to place limits on what you can realistically support.  In order to avoid having to repeat the same installation recommendations many times, if there are specific reasons for avoiding certain approaches to installation, I would suggest documenting those and then fewer people will experience the associated pitfalls.

Lazycat just personally dislike the design of melpa. You can continue submit the recipe, thanks a lot for putting in effort!!

**Comment by aspiers** [comment]
Thanks a lot, I have it almost working now and will submit when it's ready :-)

**Comment by slackline** [comment]
If not MELPA is a release to any other ELPA such as nonGNU-ELPA likely?
