### ISSUE TITLE
lsp-bridge-code-action 执行后导致emacs29不能工作

### ISSUE THREAD

**Issue by zayfen** [manateelazycat/lsp-bridge#469]
OS: ubuntu22.04 ( Wayland)
Emacs: 29.60

开发的typescriptreact项目，当执行 lsp-bridge-code-action时，弹出菜单，选择菜单项之后，会导致Emacs无法使用; *Message* buffer的报错信息： 

Wrote /tmp/voice-pkg-form.tsxht4Asc
error in process sentinel: split-window: Window #<window 10 on *lsp-bridge-code-action-menu*>  too small for splitting
error in process sentinel: Window #<window 10 on *lsp-bridge-code-action-menu*>  too small for splitting
[LSP-BRIDGE] Execute code action 'Remove unused declaration for : 'return''
Error in post-command-hook (winner-save-old-configurations): (wrong-type-argument frame-live-p #<dead frame code action 0x556766d61d10>)

**Comment by zayfen** [comment]
> 

刚才测试了下，emacs -Q 会有一样的问题，是个必现的bug

**Comment by manateelazycat** [comment]
@kongds 大佬能帮忙看看这个问题吗？ 谢谢。

**Comment by zayfen** [comment]
`const VoicePkgForm: FC<VoicePkgFormProps> = (props: VoicePkgFormProps) => {

  const { initialValues, productCode } = props;
  const [scenesList, setScenesList] = useState<{ label: string, value: number }[]>([]);

  useEffect(() => {
    console.log("voice-pkg-form.sceneId: ", sceneId)
    if (sceneId === initialValues.code_id) {
      setScenesList(JSON.parse(props.jsonScene))
      return
    }
  })
}
`

光标放在 `return`的后面（和n字符挨着）， 执行 `lsp-bridge-code-action` ，弹窗后回车，必现。

**Comment by zayfen** [comment]
我更新了最新的lsp-bridge, 重复这个bug的时候，emacs的确能工作了，但是又引入了一个新的问题，即lsp-bridge-code-action的弹窗没法退出，  报错： `lsp-bridge-code-action-popup-quit: Invalid function: acm-cancel-timer`

**Comment by manateelazycat** [comment]
再更新看看吧。

**Comment by zayfen** [comment]
@manateelazycat  我更新了最新的代码，并使用emacs -Q 复现，现在 lsp-bridge-code-action的弹窗能关闭了，但是又有一个新问题，即弹窗关闭之后我的光标不见了，按键盘，emacs没有任何的反应，像是又回到了当前(#469) 这个bug...

**Comment by manateelazycat** [comment]
完全看不懂你说的意思

**Comment by zayfen** [comment]
> @manateelazycat 我更新了最新的代码，并使用emacs -Q 复现，在lsp-bridge-code-action的弹窗出现之后，按Enter键，对应的code-action会正确执行，并且弹窗也随之正常消失; 当以上动作完成之后，我的emacs的光标会丢失，整个界面处于无法编辑的状态，在编辑区域点击鼠标没有反应， 被迫只能将emacs重启。 如果你们不好复现的话，晚些时候，我可以上传这个操作流程gif

Error Message:      `Error in post-command-hook (winner-save-old-configurations): (wrong-type-argument frame-live-p #<dead frame code action 0x563ea51cbf70>)`  有可能是emacs29的bug...

**Comment by manateelazycat** [comment]
> > @manateelazycat 我更新了最新的代码，并使用emacs -Q 复现，在lsp-bridge-code-action的弹窗出现之后，按Enter键，对应的code-action会正确执行，并且弹窗也随之正常消失; 当以上动作完成之后，我的emacs的光标会丢失，整个界面处于无法编辑的状态，在编辑区域点击鼠标没有反应， 被迫只能将emacs重启。 如果你们不好复现的话，晚些时候，我可以上传这个操作流程gif
> 
> Error Message: `Error in post-command-hook (winner-save-old-configurations): (wrong-type-argument frame-live-p #<dead frame code action 0x563ea51cbf70>)` 有可能是emacs29的bug...

这个你要自己排查，不是lsp-bridge的问题，emacs 29依然是开发版本，我们现在不会去大力支持，太不稳定了。

**Comment by zrubing** [comment]
我在wayland也遇到了这个问题，换成xwayland好了
