### ISSUE TITLE
Can't handle jump to "include/c++/v1" on MacOS

### ISSUE THREAD

**Issue by ezchi** [manateelazycat/lsp-bridge#47]
try to jump to <vector> header file with `lsp-bridge-ref-def`, it opens file `include/c%2B%2B/v1/vector` instead of `include/c++/v1`. 

Emacs version: 29.0.50
MacOS version: Monterey 12.3.1

**Comment by manateelazycat** [comment]
I haven't macOS, can't help you now, sorry.

**Comment by wsw0108** [comment]
Try pull latest code.

**Comment by ezchi** [comment]
Pull the latest, problem solved. Thanks for the quick fix.
