### ISSUE TITLE
Ansible support

### ISSUE THREAD

**Issue by laech** [manateelazycat/lsp-bridge#471]
Hi there,

I was trying to test ansible support by hacking `yaml-language-server.json` to use `ansible-language-server --stdio` instead of `yaml-language-server --stdio`.

And it works well when I type `ansible` and it show's all the available tasks as shown here:

<img src="https://user-images.githubusercontent.com/66709197/207746096-3573cb44-1fbf-4757-9b02-ab6f030f02f9.png" width="480" />

However as soon as I type `.` after it the completion no longer works:

<img src="https://user-images.githubusercontent.com/66709197/207745963-6ea97f5c-b89e-4788-aa43-36198af62fc5.png" width="480" />

~~After some debugging it seems in the second case, `lsp-bridge` is sending an empty string as the completion prefix to the server causing this issue.~~

Thanks.

**Comment by manateelazycat** [comment]
Can you send  ansible-language-server PR first?

I guess ansible-language-server prefix rule is not same other LSP server

**Comment by manateelazycat** [comment]
I have push new commit https://github.com/manateelazycat/lsp-bridge/commit/933701b4cf7ff3dd8f8fcec4938c0f67c8daa2fb

You need add `"prefixStyle": "symbol"` in json file, and try again.

**Comment by laech** [comment]
I tried the new `"prefixStyle": "symbol"` but unfortunately it didn't work either.

I have created https://github.com/manateelazycat/lsp-bridge/pull/472 for adding `ansible-language-server`.

With that, I can recreate the issue like so:

1. Install `ansible-language-server`:
   ```shell
   sudo npm install -g @ansible/ansible-language-server
   ```
1. Have this in `init.el`:
   ```elisp
   (setq
     lsp-bridge-get-single-lang-server-by-project
     (lambda (project-path filepath)
       (when (string-equal filepath "/tmp/ansible-test.yaml")
         "ansible-language-server")))

   ```
1. Then create `/tmp/ansible-test.yaml` with the following content
   ```yaml
   ---
   - name: test
     ansible
   ```
   and see the completion behavior by typing after `ansible`

**Comment by manateelazycat** [comment]
我这边一直没法成功， ansible-language-server 返回错误

```
      "message": "An error occurred in 'onDidSave' handler: [TypeError] Cannot read properties of undefined (reading 'has')\nTypeError: Cannot read properties of undefined (reading 'has')\n    at /usr/lib/node_modules/@ansible/ansible-language-server/out/server/src/providers/validationProvider.js:74:36\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/lib/node_modules/@ansible/ansible-language-server/out/server/src/providers/validationProvider.js:5:58)"
```

感觉像我需要配置啥才能补全。

Anyway, 我推送了新的补丁 https://github.com/manateelazycat/lsp-bridge/commit/b7b5f3764ce45e38c66194a763258b41d5f59387 以支持 prefixStyle 选项， 你可以更新最新版再试一下。

**Comment by laech** [comment]
> 我这边一直没法成功， ansible-language-server 返回错误
> 
> ```
>       "message": "An error occurred in 'onDidSave' handler: [TypeError] Cannot read properties of undefined (reading 'has')\nTypeError: Cannot read properties of undefined (reading 'has')\n    at /usr/lib/node_modules/@ansible/ansible-language-server/out/server/src/providers/validationProvider.js:74:36\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/lib/node_modules/@ansible/ansible-language-server/out/server/src/providers/validationProvider.js:5:58)"
> ```
> 
> 感觉像我需要配置啥才能补全。

这我也不太清楚，要不试试换成 `/tmp/dir/ansible-test.yaml` 然后在 `/tmp/dir` 做 `git init` 把它变成有project的试试？

> Anyway, 我推送了新的补丁 [b7b5f37](https://github.com/manateelazycat/lsp-bridge/commit/b7b5f3764ce45e38c66194a763258b41d5f59387) 以支持 prefixStyle 选项， 你可以更新最新版再试一下。

刚试了一下，可惜还是一样的问题。试了试 eglot 也有一样的问题。

**Comment by manateelazycat** [comment]
> > 我这边一直没法成功， ansible-language-server 返回错误
> > ```
> >       "message": "An error occurred in 'onDidSave' handler: [TypeError] Cannot read properties of undefined (reading 'has')\nTypeError: Cannot read properties of undefined (reading 'has')\n    at /usr/lib/node_modules/@ansible/ansible-language-server/out/server/src/providers/validationProvider.js:74:36\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/lib/node_modules/@ansible/ansible-language-server/out/server/src/providers/validationProvider.js:5:58)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 感觉像我需要配置啥才能补全。
> 
> 这我也不太清楚，要不试试换成 `/tmp/dir/ansible-test.yaml` 然后在 `/tmp/dir` 做 `git init` 把它变成有project的试试？
> 
> > Anyway, 我推送了新的补丁 [b7b5f37](https://github.com/manateelazycat/lsp-bridge/commit/b7b5f3764ce45e38c66194a763258b41d5f59387) 以支持 prefixStyle 选项， 你可以更新最新版再试一下。
> 
> 刚试了一下，可惜还是一样的问题。试了试 eglot 也有一样的问题。

你更新后重启 Emacs 了吗？

**Comment by manateelazycat** [comment]
![截图 2022-12-15 18-01-47](https://user-images.githubusercontent.com/237487/207830867-035374af-24e3-4a71-8186-b370e16d6d4b.png)

我主要是你第一个截图的效果都达不到， 所以没法测试第二个图。

**Comment by laech** [comment]
啊我忘了是需要安装 ansible 还有 ansible-lint 在系统上的，然后一个 YAML 文件就行。

**Comment by manateelazycat** [comment]
![截图 2022-12-16 12-43-49](https://user-images.githubusercontent.com/237487/208024095-c02c4b5b-9114-4678-a797-0a359ad1760e.png)

更新吧， 应该好了， 需要专门针对 ansible-language-server 引入一个新的 prefix style, 这个服务器不像传统的 LSP Server 看 . 以后的内容， 它好像是看光标前所有不为空格的字符串。

**Comment by laech** [comment]
谢谢！
