### ISSUE TITLE
Unexpected keyword argument "text"

### ISSUE THREAD

**Issue by ezchi** [manateelazycat/lsp-bridge#474]
I am using python 3.6.8. I got error as 

`TypeError: __init__() got an unexpected keyword argument 'text'`

Located the issue is in core/utils.py line 150. Remove the `text` keyword fix the issue.

**Comment by manateelazycat** [comment]
Has fixed in newest version, thanks for report.

**Comment by manateelazycat** [comment]
Sorry github CI won't pass after https://github.com/manateelazycat/lsp-bridge/commit/c584603fd2189276f8fa9a7576b995698201d01e, I have revert patch.

Please uprade your python version.
