### ISSUE TITLE
ERROR:epc:ReturnError([Symbol('invalid-function'), Symbol('lsp-bridge--with-file-buffer')])

### ISSUE THREAD

**Issue by zayfen** [manateelazycat/lsp-bridge#477]
OS：ubuntu22.04（wayland）
Emacs： 29.0.60
Language-Server： typescript-language-server（v2.1.0）
编辑typescriptreact代码，
*lsp-brdge* buffer频繁报错：

--- [00:24:38.598284] Recv notification: textDocument/publishDiagnostics
{
   "jsonrpc": "2.0",
   "method": "textDocument/publishDiagnostics",
   "params": {
      "uri": "file:////xxxx.tsx",
      "diagnostics": [
         {
            "range": {
               "start": {
                  "line": 2,
                  "character": 0
               },
               "end": {
                  "line": 2,
                  "character": 26
               }
            },
            "message": "'React' is declared but its value is never read.",
            "severity": 1,
            "code": 6133,
            "source": "typescript"
         },
         {
            "range": {
               "start": {
                  "line": 79,
                  "character": 23
               },
               "end": {
                  "line": 79,
                  "character": 41
               }
            },
            "message": "This condition will always return true since this function is always defined. Did you mean to call it instead?",
            "severity": 1,
            "code": 2774,
            "source": "typescript"
         }
      ]
   }
}
Eval in Emacs: (lsp-bridge-diagnostic--render '"/home/xxxx/xxx/xxx/xxx.tsx" '((:range (:start (:line 2 :character 0) :end (:line 2 :character 26)) :message "'React' is declared but its value is never read." :severity 1 :code 6133 :source "typescript") (:range (:start (:line 79 :character 23) :end (:line 79 :character 41)) :message "This condition will always return true since this function is always defined. Did you mean to call it instead?" :severity 1 :code 2774 :source "typescript")))
ERROR:epc:ReturnError([Symbol('invalid-function'), Symbol('lsp-bridge--with-file-buffer')])

--- [00:26:01.194100] Recv response typescriptreact (46942): textDocument/signatureHelp
{
   "jsonrpc": "2.0",
   "id": 46942,
   "result": null
}
ERROR:epc:ReturnError([Symbol('invalid-function'), Symbol('lsp-bridge--with-file-buffer')])

**Comment by manateelazycat** [comment]
你是怎么安装的？你编译了elc文件了？emacs -Q对比测试过没？

**Comment by zayfen** [comment]
不好意思，提issue前没有经过严格的测试验证，后续会注意下。我现在在emacs -Q的环境下没有复现这个问题。
我的开发环境是基于doom emacs改的，增加了 (lsp +lsp-bridge)选项，的确编译了elc文件。
