### ISSUE TITLE
[feature request] flex (fuzzy) candidate selection

### ISSUE THREAD

**Issue by jugcoding** [manateelazycat/lsp-bridge#478]
Good morning,

First of all thank you for your work! It’s the framework I dreamed about emacs that became a reality.

I installed it yesterday and everything went perfectly, except the blocking BUG "basic-save-buffer" (I have many hooks on save like autoformater). But this one was solved before even I have time to submit an issue.

However, I am missing one important feature for me: selection of candidates with flex search.

Here is a concrete example in ruby:

```
Module.mod => candidates = [module, module_function, etc ..] 
then 
Module.modn => I expect "module_function" to be selected.

```
I tried the parameter: **"incomplete-fuzzy-match": true** in solargraph.json but it doesn’t work.

I then tried to solve my problem by filtering the candidates at the end of the "acm-update-candidates" function.

This does not work either because lsp-bridge runs completion queries every time you type the keyboard. Most langage server filter candidates who do not begin with the prefix (this is the case of solargraph). As no method starts with "modn" the list of candidates becomes empty.

What would be the right way to implement the "flex" select functionality ? I seek help and advice before seeking a solution by myself.

I thought of one path:

First add an option in the definition of server languages: **"prefix_max_length"** which will contain the maximum length of the prefix for completions. (I think I will set it to 1)

Then in **lsp-bridge.py** if this option is enabled one can use this algorhythm :

1: In **"Completion.process_request"** :
  - send the completion query with **prefix[prefix_max_length]** instead of the whole prefix.

2: In **"Completion.process_response"** :
  - self.prefix_memo = (prefix[prefix_max_length], prefix.position)
  - self.candidates_memo = candidates
  - send to emacs: **self.candidates_memo.fuzzy_filtered_by(prefix).sorted**

3: In "**Completion.process_request"**
   - if new_prefix != self.prefix_memo:
     * self.prefix_memo = None
     * launch a new completion_request
   - else:
     * directly send to emacs: self.candidates_memo.fuzzy_filtered_by(**new_prefix**).sorted
     * cancel request completions from lang server (ie return "Cancel" to "FileAction.send_server_request" )

This is a simplified algorhythm. We should take care of **IsComplete=False** in **"Completions.process_response"**

It seems to me that most server languages don’t do anything special when adding characters to the prefix. They just filter candidates who do not start with the prefix. You get no new candidates with a new request for completion. There must be some exceptions however such as Tabnine. For my part I use solargraph which simply lists methods of the object preceding the prefix. For solargraph the prefix seems of no use in the context of completion.

Do you think it’s a good idea to add the functionality like "flex" candidate selection in lsp-bridge? (Corfu and Company offer it)

If you’re not going to implement it, I can try. lsp-bridge behavior would not be changed as long as the "prefix_max_length" option is absent from the json file.

Thank you in advance, and my apologies if I missed the right path to evoke a new feature. This is the first time I submit such a request. Before I went out on my own looking for a solution I thought it would be a good idea to ask for help and advice.  I really want to use lsp-bridge, this is a concept I like a lot. But I’m too used to the "flex" selection.

Sorry for my English and also sorry if my message is too long.

At the risk of being too long again, here’s how I proceed with completion tools:

- type [tab] then a separator character (for example space) to use the first candidate. => ok in lsp-bridge.

- or type [tab] several times to select a close candidate in the list of candidates. => ok in lsp-bridge

- or type more characters to fuzzy select a remote candidate in the list of candidates. => seems not ok in lsp-bridge

Thank you for your project!

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/lsp-bridge/commit/f654fa598525aec27e64a4d6fc9e83c3e6bc4f15

Press `Alt + u` enter filter mode, type something to filter LSP candidates.

**Comment by jugcoding** [comment]
Thank you so much for your responsiveness, that’s great.

It’s not exactly the functionality I was expecting, but it’s great. 

My workflow is to select without typing shortcuts before (ie selecting without having to type the Alt-u).

I will try to change my habits, or possibly try to code myself the functionality I’m looking for.

Thanks again.

**Comment by manateelazycat** [comment]
No, your way won't work.

Because everytime you type character in buffer, LSP server will synchrony buffer content in LSP server process and response completion candidates.

LSP server response completion candidates base on your buffer content, not base on `prefix` argument pass to completion.py

So we need convert user typing character to after-string overlay to avoid change buffer content, then we wan't filter LSP candidates result with overlay string.

**Comment by jugcoding** [comment]
You mean that every time a langage server will receive a _textDocument/didChange_ it may send back unsollicited completions ? I was thinking langage server send completions only in response to a _textDocument/completion_

In my algo I plan to block _textDocument/completion_ requests if first letters of prefix is unchanged.

I'have noticed that every keystroke schedule new _textDocument/completion_ :
 - in _FileAction.change_file_ the completion timer is activated, 
 - then _try_completion_ is called, 
 - then _send_server_request_ is called. 
 - in _send_server_request_ I plan to block the completion request, if the prefix is unchanged. ( based on the return value of handler.process_request(*args, **kwargs) )

**Comment by jugcoding** [comment]
As a bonus we win a marginal performance gain by not flooding the langage server with unnecessary completion request.

Some langage server can take avantage of more prefix characters, but I think the vast majority don't.

**Comment by manateelazycat** [comment]
If you type some new character in file, you must send textDocument/didChange request to LSP server, then LSP server can synchrony file content.

And completion candidates response is base on the string you had type.

I have did some logic like you said in earlier version, not send textDocument/completion request everytime, but some LSP server will lost many candidates expect, such as golang, volar etc.

LSP protocol just define textDocument/completion input/ouput format, not define the behaviour when time LSP server will response **complete** candidates list.

If you block textDocument/completion requests when prefix is unchanges, you will find some LSP servers won't send completion candidates.

Trust me, man, acm-filter is only way to filter LSP candidates.

**Comment by jugcoding** [comment]
I do not plan to block textDocument/didChange, only  unnecessary  textDocument/completion, and this only for langage server configured with the max_prefix_len option. Other langage servers will be left unchanged. For go lang server it's maybe not a good idea, but for solargraph maybe it is.

In an ideal world all langage server should handle correctly fuzzy completion (Tabnine does), but in a practice some only does start_with prefix filtering (like solargraph for ex).

I think we can correct this at lsp-brige level by not sending the full prefix but only the first letter of the prefix.

For example with solargraph (ruby ls) :

Foo.b, Foo.ba, Foo.baz  all receive the same set of possibles completions (the methods of Foo)

so with solargraph my solution is : if you typed "Foo.ba" only send once a completion request  for "Foo.b" then if you type "Foo.bar" the prefix is unchanged ("Foo.b") it is not necessary to ask again solagraph for completions.

If blocking textDocument/completion happen to be problematic, we have others options at lsp-bridge level like : 

for example : at each completion responses : don't remove previous candidates if the prefix is unchanged, just add the eventuals new ones.

**Comment by jugcoding** [comment]
OK I understand the problem now !

At the time the langage server decide to compute the candidates, he may do so based on the content of the document (documentDidChange) ... so he will not take in account the prefix in completion request.

temporary blocking of documentDidChange is certainly too complex.

so only the second option have some chance to work : not removing previous candidates as long as the prefix is unchanged.

Thanks ! I'didn't anticipate this complex behavior of langage server !

**Comment by manateelazycat** [comment]
> I do not plan to block textDocument/didChange, only unnecessary textDocument/completion, and this only for langage server configured with the max_prefix_len option. Other langage servers will be left unchanged. For go lang server it's maybe not a good idea, but for solargraph maybe it is.
> 
> In an ideal world all langage server should handle correctly fuzzy completion (Tabnine does), but in a practice some only does start_with prefix filtering (like solargraph for ex).
> 
> I think we can correct this at lsp-brige level by not sending the full prefix but only the first letter of the prefix.
> 
> For example with solargraph (ruby ls) :
> 
> Foo.b, Foo.ba, Foo.baz all receive the same set of possibles completions (the methods of Foo)
> 
> so with solargraph my solution is : if you typed "Foo.ba" only send once a completion request for "Foo.b" then if you type "Foo.bar" the prefix is unchanged ("Foo.b") it is not necessary to ask again solagraph for completions.
> 
> If blocking textDocument/completion happen to be problematic, we have others options at lsp-bridge level like :
> 
> for example : at each completion responses : don't remove previous candidates if the prefix is unchanged, just add the eventuals new ones.

As I said, no every LSP server will response complete candidates base on prefix, it's base on LSP server's design, can not control be LSP client.a band of

Currently `prefix` pass to completion.py only use to adjust wrong candidates by some LSP servers (pylsp or jedi will response wrong candiates that include wrong prefix).

But when you change file, LSP server will send different candidates, and prefix nothing help.

Second, you can't keep previous candidates, because candidates will out-of-date when you type new character in file, we can't trust those candidates base on same prefix, it's not right.

lsp-bridge is multi-thread and asynchronous lsp-client, it's much different with traditional completion framework (such company or corfu), you can't keep your last candidates while typing.

You can read my blog about lsp-bridge: https://manateelazycat.github.io/emacs/lsp/2022/05/12/lsp-bridge.html and https://manateelazycat.github.io/emacs/lsp/2022/06/26/why-lsp-bridge-not-use-capf.html , to understand the design of lsp-bridge.

**Comment by jugcoding** [comment]
I'm fully aware of the asynchronous nature of lsp-bridge, it's why I like it so much. I don't want my emacs to be slowed down for completion (I prefer no completion at all in this case). A long time ago I've tried Tabnine, then I discovered that the Tabnine company backend freeze the ui for 0.2 secs on every completion (ie keystroke) to let time for Tabnine to respond. This is when I discovered the synchronous nature of company. Like you, already at that time I was wondering why is company synchrous. When I said that I have dreamed of a completion framework like lsp-bridge it is for real !

I like too the fact that everything is done outside emacs. From my pov more should be done outside emacs, I'm kindof extremist :-) Even for example the popup can be done with pyqt, limiting the slowdown of emacs to the maximum. But I understand too that's a bit complicated for small gain (except maybe the gain of a popup for terminals).

I clearly underestimate the complexity inherent with asynchronous completion. But for now (I still have a lot to learn), I still hope finding a solution ( I think that a side effect of beeing naive is that it help me learn new things :-) so it's fine for me )

From my pov the completions of "Foo.ba" is necessarily a subset of completions of "Foo.b"

I understand now that if I've already typed "Foo.ba", by no easy mean I can ask solargraph to give me completions for "Foo.b". By asynchronous nature : solargraph will decide of the when. And it's too complex to block the document in possession of solargraph to "Foo.b".

But I don't need to fuzzy search until some completions are displayeds on the screen.

And if there are completions on the screen, I still hope naively that I can cache them effectively.

When lsp-bridge handler receive candidates, we can easily store them. The only difficulty is to decide how long this cache will be valid.

When we receive new candidates in the same handler, we have to decide whether the old candidates are still valids or not.

For my pov. if the point before prefix is the same of the one in the cache we can assume the cache is still valid. But I may be wrong on that point.

**Comment by manateelazycat** [comment]
You can check my patch before https://github.com/manateelazycat/lsp-bridge/commit/8d19f83061a1533d25f4b90e54cf7b50e2e99895

I remove those conditions from function fileaction.py/try_completion, lsp-bridge is so fast that send textDocument/completion request every type is faster you add condition in try_completion function.

And the reason I remove filter condition from try_completion is buggy on some LSP servers, because every LSP server has own rule that when time response completion candidates and what result return.

I think you need write some code to valid my point, I just told you I had tried that will save your time.

**Comment by jugcoding** [comment]
You've already saved me a lot of time ! Thanks.

I'm agree with you, the best for me is to test some code now. I believe and trust you, but it certainly best if I experiment it. 

My mind is not able to catch it for now, so I must switch to the help of my eyes :-)

**Comment by jugcoding** [comment]
I realize after what you explain to me, that perhaps the best and easiest solution is to patch directly solagraph (where the asynchronous problem does not exist).

There seems to be no generic advantage taking action at lsp-bridge level. Since each language server is so different from each other, the risk of causing unexpected side effects like you mentioned is high.

It was tempting to solve the problem for many langage server in on place for all. But unfortunaly not easily feasible.

Thank again for giving me time and for saving me time !
