### ISSUE TITLE
epc ReturnError

### ISSUE THREAD

**Issue by ezchi** [manateelazycat/lsp-bridge#479]
pull the latest lsp-bridge, got error for c++-mode as below:

`--- [09:35:12.044920] Recv notification: textDocument/publishDiagnostics
ERROR:epc:ReturnError([Symbol('invalid-function'), Symbol('lsp-bridge--with-file-buffer')])`

Here is the initialise message

`I[09:35:06.905] Homebrew clangd version 15.0.5
I[09:35:06.906] Features: mac+xpc
I[09:35:06.906] PID: 13047
I[09:35:06.906] argv[0]: /usr/local/opt/llvm/bin/clangd
I[09:35:06.906] argv[1]: --all-scopes-completion
I[09:35:06.906] argv[2]: --clang-tidy
I[09:35:06.906] argv[3]: --enable-config
I[09:35:06.906] argv[4]: --header-insertion-decorators=0
I[09:35:06.907] Starting LSP over stdin/stdout
I`

**Comment by manateelazycat** [comment]
Not compile .el files.

**Comment by manateelazycat** [comment]
Please update newest version and try again.
