### ISSUE TITLE
lsp-bridge-find-def-return: Issues returned in different projects

### ISSUE THREAD

**Issue by opsnull** [manateelazycat/lsp-bridge#484]
I usually open multiple projects for development at the same time. When I execute the
`lsp-bridge-find-def-return` command in one project, it may return to the files of other projects.

 Hope lsp-bridge-find-def-return can limit to return only the last position of the current project.

**Comment by manateelazycat** [comment]
说清楚一点吧， 完全没看懂你说的啥意思。

**Comment by opsnull** [comment]
同时打开多个 project，都执行一些 lsp-bridge-find-def 命令，然后在某个 project 中连续执行多次 lsp-bridge-find-def-return 时会跳转到其他 project 中。
希望在多次执行 lsp-bridge-find-def-return  来返回时能局限在当前 project 中历史位置。

**Comment by manateelazycat** [comment]
给例子吧，什么语言？

**Comment by opsnull** [comment]
go 语言

**Comment by opsnull** [comment]
![document](https://user-images.githubusercontent.com/433567/209339932-cf5cfec6-3e3e-4cb0-943c-232a84d4011e.gif)
比如左右分别是两个项目，左边执行两次  lsp-bridge-find-def ，右边执行一次  lsp-bridge-find-def ，然后返回左边执行  lsp-bridge-find-def-return，就返回右边项目的上一次位置了。

**Comment by manateelazycat** [comment]
> ![document](https://user-images.githubusercontent.com/433567/209339932-cf5cfec6-3e3e-4cb0-943c-232a84d4011e.gif) [ ![document](https://user-images.githubusercontent.com/433567/209339932-cf5cfec6-3e3e-4cb0-943c-232a84d4011e.gif) ](https://user-images.githubusercontent.com/433567/209339932-cf5cfec6-3e3e-4cb0-943c-232a84d4011e.gif) [ ](https://user-images.githubusercontent.com/433567/209339932-cf5cfec6-3e3e-4cb0-943c-232a84d4011e.gif) 比如左右分别是两个项目，左边执行一次 lsp-bridge-find-def ，右边执行一次 lsp-bridge-find-def ，然后返回左边执行 lsp-bridge-find-def-return，就返回右边项目的上一次位置了。

你这样我才算是看懂里啥意思。

**Comment by manateelazycat** [comment]
更新吧，已经修复了。
