### ISSUE TITLE
Completion confusing behavior

### ISSUE THREAD

**Issue by liuyinz** [manateelazycat/lsp-bridge#487]
When the completion prefix matchs, the candidates filter and update normally, but when the prefix don't match, the candidates just keep unchanges. Is this behavior a bug or just designed like this? Test it in python and css, they behave the same.

![Kapture 2022-12-25 at 02 57 01](https://user-images.githubusercontent.com/35212403/209448300-97eb0dd6-041f-4d14-8191-e7921a8ce70e.gif)

**Comment by manateelazycat** [comment]
已经修复了， 感谢反馈。
