### ISSUE TITLE
Windows中文路径提示 UnicodeDecodeError: 'gbk' codec can't decode

### ISSUE THREAD

**Issue by lynnux** [manateelazycat/lsp-bridge#49]
win7 64, emacs 29.0.50，创建目录`C:\Users\Administrator\Desktop\新建文件夹`，`git init`，创建个`test.py`，开启lsp-bridge-mode后，补全没反应，lsp buffer报错：
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:/green/emacs/.emacs.d/packages/corfu/corfu-main/lsp-bridge-master/lsp-bridge.py", line 90, in postgui_dispatcher
    self._open_file(message["content"])
  File "c:/green/emacs/.emacs.d/packages/corfu/corfu-main/lsp-bridge-master/lsp-bridge.py", line 123, in _open_file
    action = FileAction(filepath, lang_server)
  File "c:\green\emacs\.emacs.d\packages\corfu\corfu-main\lsp-bridge-master\core\fileaction.py", line 88, in __init__
    self.project_path = get_command_result("git rev-parse --show-toplevel", dir_path)
  File "c:\green\emacs\.emacs.d\packages\corfu\corfu-main\lsp-bridge-master\core\utils.py", line 91, in get_command_result
    return "".join((process.stdout if ret == 0 else process.stderr).readlines()).strip()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb9 in position 45: illegal multibyte sequence
Cache action change_cursor, wait for file c:/Users/Administrator/Desktop/新建文件夹/test.py to open it before executing.
```
手动执行`git rev-parse --show-toplevel`:
```
C:\Users\Administrator\Desktop\新建文件夹>git rev-parse --show-toplevel
C:/Users/Administrator/Desktop/新建文件夹

Warning: Your console font probably doesn't support Unicode. If you experience s
trange characters in the output, consider switching to a TrueType font such as C
onsolas!

C:\Users\Administrator\Desktop\新建文件夹>
```

**Comment by zilongshanren** [comment]
别用中文路径看看

**Comment by lynnux** [comment]
再报一个没有在git目录的test.py，路径`C:\Users\Administrator\Desktop\test.py`，lsp buffer：
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:/green/emacs/.emacs.d/packages/corfu/corfu-main/lsp-bridge-master/lsp-bridge.py", line 90, in postgui_dispatcher
    self._open_file(message["content"])
  File "c:/green/emacs/.emacs.d/packages/corfu/corfu-main/lsp-bridge-master/lsp-bridge.py", line 131, in _open_file
    server = LspServer(self.message_queue, file_action, self.enable_lsp_server_log)
  File "c:\green\emacs\.emacs.d\packages\corfu\corfu-main\lsp-bridge-master\core\lspserver.py", line 231, in __init__
    self.p = subprocess.Popen(self.get_server_command(),
  File "c:\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Cache action change_cursor, wait for file c:/Users/Administrator/Desktop/test.py to open it before executing.
```
这个路径不含中文，pyright也正常安装了，eglot都是正常执行的。

**Comment by lynnux** [comment]
打印了get_server_command()是`['pyright-langserver.cmd', '--stdio']`，是在pyright.json里配置的
```
 "nt": ["pyright-langserver.cmd", "--stdio"],
```
而我的C:\Python38\Scripts是
```
  c:/Python38/Scripts:
  drwxr-xr-x 1 Administrator 197121    0 2022/05/08 08:48 .
  drwxr-xr-x 1 Administrator 197121    0 2022/03/27 19:07 ..
  -rwxr-xr-x 1 Administrator 197121 104K 2022/05/08 08:48 nodeenv.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/03/26 17:47 pip.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/03/26 17:47 pip3.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/03/26 17:47 pip3.8.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/05/08 08:48 pyright.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/05/08 08:48 pyright-langserver.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/05/08 08:48 pyright-python.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/05/08 08:48 pyright-python-langserver.exe
  -rwxr-xr-x 1 Administrator 197121 104K 2022/03/26 17:47 wheel.exe

```
pyright-langserver.cmd用everything搜索了下也有，但是不在bin路径里，手动cmd里执行pyright-langserver.cmd也报错了

**Comment by lynnux** [comment]
pyright.json里改为：
```
    "nt": ["pyright-langserver", "--stdio"],
```
正常了，嘿嘿，就剩下个中文路径问题了，可以考虑emacs传project root给python不？emacs支持不止git一种哟

**Comment by lynnux** [comment]
又发现个问题，我编辑那个pyright.json貌似启动lsp bridge了，导致这边test.py没有补全了，好奇怪，lsp buffer提示
```
Cache action change_cursor, wait for file c:/green/emacs/.emacs.d/packages/corfu/corfu-main/lsp-bridge-master/langserver/pyright.json to open it before executing.
['typescript-language-server', '--stdio']  --------这是我加的get_server_command()打印，所以是json文件启动ts后端了？

```

**Comment by lynnux** [comment]
lsp bridge确实很快，太爽了，太感谢懒猫了，希望越来越好，加油！

**Comment by wsw0108** [comment]
运行git时的编码问题，git的stdin stdout都期待是utf-8

**Comment by manateelazycat** [comment]
> pyright.json里改为：
> 
> ```
>     "nt": ["pyright-langserver", "--stdio"],
> ```
> 
> 正常了，嘿嘿，就剩下个中文路径问题了，可以考虑emacs传project root给python不？emacs支持不止git一种哟

Emacs 的 project-root 在嵌套 git 项目中不会正确判断，你只要把 git 创建好， lsp-bridge 就可以正常工作。

**Comment by manateelazycat** [comment]
> pyright.json里改为：
> 
> ```
>     "nt": ["pyright-langserver", "--stdio"],
> ```
> 
> 正常了，嘿嘿，就剩下个中文路径问题了，可以考虑emacs传project root给python不？emacs支持不止git一种哟

Windows 不是 pyright-langser.cmd 吗？ 如果是这样 https://github.com/manateelazycat/lsp-bridge/blob/master/langserver/pyright_nt.json 文件没有存在的必要了。

**Comment by wsw0108** [comment]
> 

安装途径不一样，他这个是exe的

**Comment by lynnux** [comment]
感觉是没必要，就算只有`pyright-langserver.cmd`没有`pyright-langserver.exe`，`pyright-langserver`照样能调用`pyright-langserver.cmd`，我看eglot代码也只有个`pyright-langserver`。我是通过`pip install pyright`安装的，貌似还要装个node。

**Comment by lynnux** [comment]
另外这个gbk问题，用的今天最新代码在win10 64位上测试(python Python 3.10.4 64位)又可以正常在`C:\Users\lynnux\Desktop\新建文a 件夹`这样的git仓库里补全py文件。难道跟win10，或者python版本有关系？ 貌似git输出是utf-8，可以考虑在get_command_result里decode("utf-8")之类，今天晚上回去在win7上测试下。

**Comment by wsw0108** [comment]
> 感觉是没必要，就算只有`pyright-langserver.cmd`没有`pyright-langserver.exe`，`pyright-langserver`照样能调用`pyright-langserver.cmd`，我看eglot代码也只有个`pyright-langserver`。我是通过`pip install pyright`安装的，貌似还要装个node。

python的Popen为了所谓的安全问题，不会去把`pyright-langserver` “解析” 成`pyright-langserver`+`PATHEXT(.cmd/.bat/.ps1)`

**Comment by lynnux** [comment]
测试subprocess.Popen加个` encoding="utf-8"`就不报错了：
```
def get_command_result(command_string, cwd):
    import subprocess
    process = subprocess.Popen(command_string, cwd=cwd, shell=True, text=True,
                               stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                               encoding="utf-8")
    ret = process.wait()
    return "".join((process.stdout if ret == 0 else process.stderr).readlines()).strip()
```
不过含中文路径的补全有点问题，见gif（由于我设置了(setq-local corfu-auto-prefix 1)，有些是手动触发completion-at-point）:
![22](https://user-images.githubusercontent.com/367894/168281842-dd449ae5-56a4-444e-955a-5759ed76df9a.gif)
而且lsp bridge buffer没有任何显示。

**Comment by lynnux** [comment]
对于非中文路径，函数名含中文好像也会有问题，测试代码：
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

def b中文():
    print("测试中文")

def ab中哈():
    pass

def main():
    # 这里补全试试
    os.
    
if __name__ == "__main__":
    try:
        main()
    except:
        import traceback
        traceback.print_exc()
        input()
```

**Comment by manateelazycat** [comment]
> 测试subprocess.Popen加个` encoding="utf-8"`就不报错了：
> 
> ```
> def get_command_result(command_string, cwd):
>     import subprocess
>     process = subprocess.Popen(command_string, cwd=cwd, shell=True, text=True,
>                                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
>                                encoding="utf-8")
>     ret = process.wait()
>     return "".join((process.stdout if ret == 0 else process.stderr).readlines()).strip()
> ```
> 
> 不过含中文路径的补全有点问题，见gif（由于我设置了(setq-local corfu-auto-prefix 1)，有些是手动触发completion-at-point）: ![22](https://user-images.githubusercontent.com/367894/168281842-dd449ae5-56a4-444e-955a-5759ed76df9a.gif) 而且lsp bridge buffer没有任何显示。

这个最新的commint已经修正了，感谢反馈。

**Comment by manateelazycat** [comment]
> 对于非中文路径，函数名含中文好像也会有问题，测试代码：
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> import os
> import sys
> 
> def b中文():
>     print("测试中文")
> 
> def ab中哈():
>     pass
> 
> def main():
>     # 这里补全试试
>     os.
>     
> if __name__ == "__main__":
>     try:
>         main()
>     except:
>         import traceback
>         traceback.print_exc()
>         input()
> ```

这个你继续折腾吧，欢迎发送PR

**Comment by lynnux** [comment]
OK，中文路径问题解决了。上面今天没重现。先关闭了。
还发现不知道是不是win7 python3.8环境问题，有时候pyright的进程半天都启动不起来，只有个lsp bridge的python进程，再观察下。。
