### ISSUE TITLE
weird acm behavior: acm popup failed even if yas source has matched candidates

### ISSUE THREAD

**Issue by liuyinz** [manateelazycat/lsp-bridge#492]
![Kapture 2023-01-02 at 18 53 23](https://user-images.githubusercontent.com/35212403/210222119-905521ed-2248-4a86-b048-3eda6e654674.gif)

Reproduce:
1. download the markdown-mode.zip and unzip into test directory (e.g. "~/test/snippets")
[markdown-mode.zip](https://github.com/manateelazycat/lsp-bridge/files/10331269/markdown-mode.zip)

3. mini config;
```elisp
(require 'markdown-mode)
(require 'yasnippet)
(require 'posframe)
(require 'lsp-bridge)

(setq acm-enable-yas t)
(setq acm-snippet-insert-index 2)
(setq acm-backend-yas-match-by-trigger-keyword t)

;; unzip the markdown-mode.zip into the example directory
(setq test-snippet-dir "~/test/snippets")

(add-to-list 'yas-snippet-dirs test-snippet-dir t)
(yas-load-directory test-snippet-dir t)
(yas-global-mode)

;;enable lsp-bridge-mode in .md
(add-to-list 'lsp-bridge-default-mode-hooks 'markdown-mode-hook)

(global-lsp-bridge-mode)
```
3. open test file below and input prefix like "tl" or "bd" or "bt"
[README.md](https://github.com/manateelazycat/lsp-bridge/files/10331277/README.md)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/c41bce2520867d60126b2e620eb245930735c7cf has fixed
