### ISSUE TITLE
finish support for eslint-language-server

### ISSUE THREAD

**Issue by aspiers** [manateelazycat/lsp-bridge#495]
#468 added the groundwork for supporting eslint-language-server.  However I have tried it using the draft PR #494 and am running into issues.  It is successfully launching the server process, but then I get the following error in the `*lsp-bridge*` buffer:

```
Uncaught exception received.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.isAbsolute (node:path:1157:5)
    at /home/adam/.nvm/versions/node/v16.13.0/lib/node_modules/vscode-langservers-extracted/lib/eslint-language-server/eslint.js:1133:19
Uncaught exception received.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.isAbsolute (node:path:1157:5)
    at /home/adam/.nvm/versions/node/v16.13.0/lib/node_modules/vscode-langservers-extracted/lib/eslint-language-server/eslint.js:1133:19
```

The relevant code is:

```js
      if (settings.nodePath !== null) {
        nodePath = settings.nodePath;

        if (!path.isAbsolute(nodePath) && workspaceFolderPath !== undefined) {
          nodePath = path.join(workspaceFolderPath, nodePath);
        }
      }
```

By inserting debugging just before this:

```js
      connection.console.info(`>>settings.nodePath: ${settings.nodePath}`);
      connection.console.info(`>>settings.nodePath !== null: ${settings.nodePath !== null}`);
```

I can see that `settings.nodePath` is actually `undefined`.  In the TypeScript source, it is supposed to be impossible for it to be anything but `string` or `null`:

https://github.com/microsoft/vscode-eslint/blob/578cd50f38f076b22f7f751376b77aba1608bc43/%24shared/settings.ts#L172

but clearly this is happening anyway.  I assume it's because `lsp-bridge` is omitting `nodePath` from `settings` when starting the server.  Indeed, `lsp-mode` sets it to the value of the custom variable `lsp-eslint-node-path`:

https://github.com/emacs-lsp/lsp-mode/blob/1e14a3fdb195a557cba5a7b7e3372dc850a5ce95/clients/lsp-eslint.el#L287

But it is unrealistic to hardcode this to a fixed value, because it will change per user, and even per project / workspace.

So how can lsp-bridge allow `nodePath` to be calculated dynamically?  I noticed that `get-workspace-folder` already exists and seems to be a mechanism for allowing emacs to calculate the workspace folder dynamically and return it to the Python bridge server.  I guess we need to create something similar called `get-node-path`?

But this is not a great solution because it's only required by the `eslint` language server and not others, whereas the existing `get-workspace-folder` approach applies to all language servers.  As you can see above, `lsp-mode` allows dynamic options per language server.  Would it be better to extend `lsp-bridge` so it can do the same?

For example, `langserver/vscode-eslint-language-server.json` could contain:

```json
  "settings": {
    "nodePath-func": "lsp-bridge-get-node-path"
  }
```

and then `lsp_bridge.py` could search for any settings ending in `-func` and call that function to get the value and then replace the `nodePath-func` key with a `nodePath` key and the returned value.  So in this example, it would call `get_emacs_func_result('lsp-bridge-get-node-path')`, get a result like `/home/adam/.nvm/versions/node/v16.13.0/bin/node` back, and then replace

```json
  "settings": {
    "nodePath-func": "lsp-bridge-get-node-path"
  }
```

with

```json
  "settings": {
    "nodePath": "/home/adam/.nvm/versions/node/v16.13.0/bin/node"
  }
```

before starting the language server.

Does this sound like a reasonable approach, or is there a better way?

Thanks!

**Comment by aspiers** [comment]
Actually, even hardcoding the JSON file to this doesn't cause `settings.nodePath` to have the right value in the language server:

```json
{
  "name": "vscode-eslint-language-server",
  "languageId": "html",
  "command": ["vscode-eslint-language-server", "--stdio"],
  "settings": {
    "eslint.debug": true,
    "nodePath": "/home/adam/.nvm/versions/node/v16.13.0/bin/node",
    "eslint": {
      "nodePath": "/home/adam/.nvm/versions/node/v16.13.0/bin/node"
    }
  }
}
```

so apparently I'm misunderstanding something.

**Comment by manateelazycat** [comment]
> Actually, even hardcoding the JSON file to this doesn't cause `settings.nodePath` to have the right value in the language server:
> 
> ```json
> {
>   "name": "vscode-eslint-language-server",
>   "languageId": "html",
>   "command": ["vscode-eslint-language-server", "--stdio"],
>   "settings": {
>     "eslint.debug": true,
>     "nodePath": "/home/adam/.nvm/versions/node/v16.13.0/bin/node",
>     "eslint": {
>       "nodePath": "/home/adam/.nvm/versions/node/v16.13.0/bin/node"
>     }
>   }
> }
> ```
> 
> so apparently I'm misunderstanding something.

we need make sure json file works even hardcoding.

dynamic option is not problem, lsp-bridge have way to support it

**Comment by aspiers** [comment]
Any ideas how I could check why it's not working?

**Comment by manateelazycat** [comment]
If lsp-mode can work, you can turn on lsp-mode's log option, then check `option content` that lsp-mode sent to LSP server.

Then make sure lsp-bridge sent same options as lsp-mode, if it works, then we can develop some dynamically function to fix node path problem.

And check LSP server's source code or strace also can help.

**Comment by aspiers** [comment]
Thanks, good ideas!  I did already check the server's source code last night but still learning how the protocol works so didn't finish this investigation yet.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/pull/569
