### ISSUE TITLE
有没有大佬愿意帮忙添加 ds-pinyin 后端啊？感谢感谢

### ISSUE THREAD

**Issue by suliveevil** [manateelazycat/lsp-bridge#496]
感觉这个比 Wen 安装更简单一些

https://github.com/iamcco/ds-pinyin-lsp

**Comment by manateelazycat** [comment]
cargo install ds-pinyin-lsp, 下载 ds-pinyin 的 dict.db3 文件， 并保存到目录 ~/.emacs.d/ds-pinyin/ , 最后开启选项 lsp-bridge-use-ds-pinyin-in-org-mode

![截图 2023-01-07 14-18-59](https://user-images.githubusercontent.com/237487/211134531-ab919dff-7007-47ec-8159-05853fa51284.png)

**Comment by suliveevil** [comment]
感谢猫大，已经用上了。

不过我发现输入时必须每次之间添加空格，不然就会删除前面的中文。

这样的输入和英文单词是一个逻辑，对中文来说有点奇怪。

最小配置

```emacs-lisp
(package-initialize)

(setq mac-option-modifier 'meta
      mac-right-command-modifier 'hyper
      )

( add-to-list 'load-path "~/.config/debug/lib/lsp-bridge/")
(require 'yasnippet)
(yas-global-mode 1)
(require 'lsp-bridge)
(setq lsp-bridge-enable-mode-line nil)
(setq lsp-bridge-use-ds-pinyin-in-org-mode t)
(global-lsp-bridge-mode)
```

**Comment by manateelazycat** [comment]
更新最新版就好了。

**Comment by suliveevil** [comment]
猫大神速 👍

**Comment by suliveevil** [comment]
请问猫大可不可以想办法支持 `user-emacs-directory` 啊？这样就不用把路径写成固定的了。

感谢感谢 🙏

我现在的做法是 fork 之后修改了 `db_path`

```diff
-    "db_path": "$HOME/.emacs.d/ds-pinyin/dict.db3",
+    "db_path": "$HOME/.config/emacs/ds-pinyin/dict.db3",
```

**Comment by manateelazycat** [comment]
这个路径放哪都可以啊

**Comment by suliveevil** [comment]
好吧，是我肤浅了 🤣

刚装好的时候没有文字显示出来，我一看 `db_path` 和我实际路径不一样就自己修改了一下，能用了我就没有深究怎么自定义路径。
