### ISSUE TITLE
Organize imports in one go

### ISSUE THREAD

**Issue by asif-mahmud** [manateelazycat/lsp-bridge#498]
Hi, first of all, thanks to you all for this ground up work. The package is looking really competitive. I have been trying it and it feels really smooth experience.

One query, I couldn't figure out a way to run `source.organizeImports` code action using any of it's functions. If any of you guys have been trying it out or know already please help me out. My target is to bind a key to clean up unused imports.

**Comment by manateelazycat** [comment]
Run lsp-bridge-code-action command?

**Comment by asif-mahmud** [comment]
yes, but if i run that command cursor has to be on the point where the action is available. i want to be run it from anywhere. i have done that in neovim  like this -

**Comment by manateelazycat** [comment]
can you give me some example code for test?

**Comment by asif-mahmud** [comment]
for example this typescript file has one unused import -

**Comment by asif-mahmud** [comment]
thats very unfortunate. please take your time.

**Comment by manateelazycat** [comment]
@asif-mahmud Can you try `(lsp-bridge-code-action "source.organizeImports")` ? 

I think lsp-bridge is support special code action already.

Please let me know if it can't works.

**Comment by asif-mahmud** [comment]
Hi,  i tried evaluating it, apparently a temporary file was created with the same content as the source file.

**Comment by manateelazycat** [comment]
Can you give me a mini tar.gz package that I can test "source.organizeImports" ?

**Comment by asif-mahmud** [comment]
sorry for late, heres a git repo to test it out on typescript file - [https://github.com/asif-mahmud/typescript-unused-imports](https://github.com/asif-mahmud/typescript-unused-imports)

**Comment by manateelazycat** [comment]
Did you run lsp-bridge under terminal ?

**Comment by manateelazycat** [comment]
I believe https://github.com/manateelazycat/lsp-bridge/commit/6bad830b3df742ce894f4d699cd2d5951f6ffc36 has fixed this issue.

Please update to newest version, then execute `(lsp-bridge-code-action "source.organizeImports")`, lsp-bridge will remove unused import code directly.

![Peek 2023-01-22 09-15](https://user-images.githubusercontent.com/237487/213896226-acd77008-42e8-47b3-815c-e858e8f0a842.gif)
