### ISSUE TITLE
How to check docs in terminal mod ?

### ISSUE THREAD

**Issue by BURISTUS** [manateelazycat/lsp-bridge#501]
Is it possible to view lsp-bridge-popup-documentation in terminal mode or any other way to view documentation in it?

**Comment by BURISTUS** [comment]
And have one more question. How to enable linter using lsp-bridge ?

**Comment by manateelazycat** [comment]
> Is it possible to view lsp-bridge-popup-documentation in terminal mode or any other way to view documentation in it?

Terminal is not fully support, we need write new code to replace posframe for terminal, it's not easy mission.

**Comment by manateelazycat** [comment]
> linter

linter is not support yet, please don't ask two questions in one issue.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/nova Has support remote server completion, acm-terminal is don't need.
