### ISSUE TITLE
Make yasnippet an optional dependency

### ISSUE THREAD

**Issue by AlynxZhou** [manateelazycat/lsp-bridge#502]
Currently yasnippet is listed as dependency, but it seems no longer actively maintained and not all users need it, also we have tempel support in lsp-bridge, so what about make yasnippet an optional dependency?

**Comment by manateelazycat** [comment]
No, LSP snippet expansion still need yasnippet https://github.com/manateelazycat/lsp-bridge/blob/ee33fc9c75c0595b9082ae0f16869aa9d8cb22a3/acm/acm-backend-lsp.el#L226

I don't think tempel can replace yasnippet for LSP snippet expansion.

**Comment by AlynxZhou** [comment]
> No, LSP snippet expansion still need yasnippet
> 
> https://github.com/manateelazycat/lsp-bridge/blob/ee33fc9c75c0595b9082ae0f16869aa9d8cb22a3/acm/acm-backend-lsp.el#L226
> 
> I don't think tempel can replace yasnippet for LSP snippet expansion.

Reasonable, thanks.
