### ISSUE TITLE
lsp-bridge in c++-mode seems to respond slowly

### ISSUE THREAD

**Issue by AllTheLife** [manateelazycat/lsp-bridge#503]
When I was editing a c++ file, I found that `lsp-bridge` responded slowly.

![Peek 2023-01-12 09-24](https://user-images.githubusercontent.com/87554738/212220309-2d6faeab-43d2-4f45-a74f-4eab5a8a7022.gif)

This problem only appears in `c++-mode`. I've tried the `emacs -Q` but the issue still exists. 

[Logs](https://github.com/AllTheLife/logs/blob/main/a.txt)

**Comment by AllTheLife** [comment]
Problems seems to be more serious.
Now when I edit `python` file and `c` file, it will also be slow.

My `gc` configuration:
``` elisp
(let ((normal-gc-cons-threshold (* 50 1024 1024))
       (init-gc-cons-threshold (* 128 1024 1024)))
   (setq gc-cons-threshold init-gc-cons-threshold)
   (add-hook 'emacs-startup-hook
            (lambda () (setq gc-cons-threshold normal-gc-cons-threshold))))
```

**Comment by manateelazycat** [comment]
你需要检查你的GC设置

**Comment by manateelazycat** [comment]
我估计慢是因为你最近的GC设置导致的，因为GC太小导致 lsp-bridge 返回补全数据多的时候GC在执行。

请排查你的配置吧。
