### ISSUE TITLE
Render markdown documents changes other buffer's markdown highlight style

### ISSUE THREAD

**Issue by AlynxZhou** [manateelazycat/lsp-bridge#504]
To reproduce:

1. Open a markdown file that contains code blocks.
2. Split another window and open a javascript file (or other languages that have markdown docs).
3. Type in javascript to trigger acm's completion and document popup.
4. The other window's code block also changes color.

![Screenshot from 2023-01-15 16-57-10](https://user-images.githubusercontent.com/8444615/212532251-eaa45818-d9ec-435f-b1ff-253cfe52a839.png)

What's expected (Elisp's doc are not rendered as markdown so it's OK):

![Screenshot from 2023-01-15 16-57-32](https://user-images.githubusercontent.com/8444615/212532274-9c0338f7-f49f-42ce-88cd-0becf74af131.png)

**Comment by AlynxZhou** [comment]
Maybe an option to skip <https://github.com/manateelazycat/lsp-bridge/blob/master/acm/acm.el#L947-L950> is needed?

**Comment by AlynxZhou** [comment]
Maybe `face-remap-add-relative` should be used here, according to <https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Remapping.html#index-face_002dremap_002dadd_002drelative>, I'd like to try this later.

**Comment by manateelazycat** [comment]
Please check https://github.com/manateelazycat/lsp-bridge/pull/412

I think it's your config problem, please check with `emacs -Q` first.

**Comment by AlynxZhou** [comment]
> I think it's your config problem, please check with `emacs -Q` first.

Nope, I can reproduce it with `emacs -Q` and commit `ee33fc9c75c0595b9082ae0f16869aa9d8cb22a3`.

Emacs is started with the following commands, `markdown-mode` should be installed:

```
emacs -Q --eval "\
(progn
	(setq package-user-dir \"~/.emacs.d/elpa/\")
	(package-initialize)

	(add-to-list 'load-path \"~/.emacs.d/site-lisp/lsp-bridge/\")

	(require 'yasnippet)
	(yas-global-mode 1)

	(require 'lsp-bridge)
	(global-lsp-bridge-mode))"
```

Then split it into two window, open a Markdown file that has code blocks in one window and run `gfm-mode` for that buffer, and then open a javascript file to type. Check the code block background before and after acm document frame pops up.

Before (no background color for code blocks):

![Screenshot from 2023-01-16 00-33-49](https://user-images.githubusercontent.com/8444615/212553782-e902ec15-f7a4-4293-8b71-57158de873ba.png)

After (acm frame's code block style also affects the Markdown buffer):

![Screenshot from 2023-01-16 00-34-01](https://user-images.githubusercontent.com/8444615/212553875-4425e7eb-aa9f-4c54-ac09-19323e74908c.png)

So that should not be my config problem.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/pull/505 补丁已经合并， 感谢反馈。
