### ISSUE TITLE
lsp-bridge not working

### ISSUE THREAD

**Issue by ckulemeyer** [manateelazycat/lsp-bridge#506]
Hi,
I am trying to set up lsp-bridge. I am using conda envs and direnv. But even disabling direnv or restarting process does not seem to work. Lsp-bridge-find-def, -find-impl does not do anything (edit: no error messages). Acm-completion only works for words and citre.
Any guess what I am doing wrong?
Cheers
Christoph 

Edit: I am using Emacs 28, installed all python- and emacs packages

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/wiki/Python%20virtualenv

**Comment by ckulemeyer** [comment]
Thank you very much
