### ISSUE TITLE
lsp-bridge causes org mode `org-insert-item` exception

### ISSUE THREAD

**Issue by ginqi7** [manateelazycat/lsp-bridge#518]
lsp-bridge causes org mode `org-insert-item` exception.
![image](https://user-images.githubusercontent.com/1028971/215127429-d2ca9698-1608-42a7-8f39-47a2835dc84a.png)
when i run `org-insert-item`, i get:
![image](https://user-images.githubusercontent.com/1028971/215127683-25235407-1a47-40f3-8de8-6647f89666f4.png)
emacs -Q
config is just:
``` emacs-lisp
(require 'lsp-bridge)
(global-lsp-bridge-mode)
```
emacs version:GNU Emacs 30.0.50
Org mode version 9.6
lsp-bridge commit id: 80229722bdfc0518813c7c95e1c67a9406176308

**Comment by manateelazycat** [comment]
尝试更新到 https://github.com/manateelazycat/lsp-bridge/commit/db2abc02a3f5d95562eb0c6fb3033b23d24c304a

**Comment by ginqi7** [comment]
fixed
