### ISSUE TITLE
lsp-bridge-mode breaks `+org/insert-item-below`

### ISSUE THREAD

**Issue by WasistJonas** [manateelazycat/lsp-bridge#521]
I had similar problems like #518. 

# Expected Behavior 
Invoking `org/insert-item-below` in a list should create a new empty list item below the current item and place the cursor behind the new item.
# Actual Behavior 
Pretty similar to #518. 

Before invoking `+org/insert-item-below`:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/83202538/215482486-ace946d6-5152-4337-a601-0608afe10ad9.png">

After:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/83202538/215482062-66bd0797-55fe-4776-8a22-f2dc28d84c85.png">

# How to reproduce
Simply use the function with `lsp-bride-mode` enabled. 

| component | version |
|---|---|
| lsp-bridge commit id | [c82bfb8](https://github.com/manateelazycat/lsp-bridge/commit/c82bfb893b1c251a3fe5a6405fb3b575ddc3e5c5) |
| org-mode | Org mode version 9.6 (9.6-??-bed47b4) |
| GNU Emacs  |  v28.2  |
| Doom core |   v3.0.0-pre       HEAD -> master e96624926 |
| Doom modules | v22.10.0-pre     HEAD -> master e96624926 |

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/29ad09b9c33d384edaf57b114c9c94708892b68e

**Comment by WasistJonas** [comment]
Thanks for the quick fix!
