### ISSUE TITLE
The buffer-saving is triggered automatically in the org babel edit mode.

### ISSUE THREAD

**Issue by GTrunSec** [manateelazycat/lsp-bridge#527]
- Org-mode
- org-babel - `C-c '` enter the edit mode

```org
#+begin_src python 
import os
<...>
#+begin_end
```
pretty noise. Is there a way to disable the buffer-saving or just a bug trigger when lsp-bridge running? 
![3  ssh 2023-02-07 20-47-49](https://user-images.githubusercontent.com/21156405/217436240-d7c9dd9e-6841-42d0-a1c3-76595c802968.jpg)

**Comment by manateelazycat** [comment]
Customize lsp-bridge-org-babel-lang-list

**Comment by GTrunSec** [comment]
org-bable-lang-list在babel中使用lsp-bridge是正常的，但键入信息后会触发一个 popup buffer is modified， 选择save后会自动退出org-bable-src-edit。感觉是开启lsp-bridge在org-src后当输出信息后回出发一个auto-save-buffer的什么功能，你能否够复现此问题？

Env:
- doom-emacs
-  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.16.0)

**Comment by GTrunSec** [comment]
确定是自己的配置问题，doom-emacs有点复杂。

**Comment by manateelazycat** [comment]
emacs -Q只加载lsp-bridge会重现吗？
