### ISSUE TITLE
Not connecting to multiple LSP's

### ISSUE THREAD

**Issue by chookity-pokk** [manateelazycat/lsp-bridge#528]
I just installed this with the instructions from the README and made sure company/LSP-mode/Eglot etc were all turned off. I opened a Java file and it shows the popup for my snippets but doesn't have any other LSP features. I thought I may have messed up my install so I went and opened a Go file and it found the LSP just fine there, but opening a Rust file doesn't work again.

I uninstalled LSP-mode and all the other packages used by it, restarted Emacs and have the same issue. My modeline shows that lsp-bridge is running and it also shows I have rust-analyzer installed as well as the Eclipse server for Java. 

All three versions worked just fine under LSP-mode, so I'm not exactly sure what the problem is here or how to really troubleshoot it.

**Comment by manateelazycat** [comment]
emacs -Q and enable lsp-bridge only

**Comment by chookity-pokk** [comment]
I can't enable lsp-bridge if I launch with the -Q command.

**Comment by manateelazycat** [comment]
> I can't enable lsp-bridge if I launch with the -Q command.

emacs -Q and eval lsp-bridge config

**Comment by chookity-pokk** [comment]
Whenever I try that I get that `No such file or directory, posframe` with the config below.

```
(require 'posframe)
(require 'yasnippet)
(yas-global-mode 1)
(add-to-list 'load-path "~/.emacs.d/lsp-bridge")
(require 'lsp-bridge)
(global-lsp-bridge-mode)
```

**Comment by chookity-pokk** [comment]
It still doesn't work with launching with `-Q` then using `lsp-bridge-mode`. Turning off `lsp-bridge-mode` then turning on Eglot works for both Java and Rust.

**Comment by manateelazycat** [comment]
I can works well for all languages, you need test with your config, and find which config conflicts with lsp-bridge

**Comment by chookity-pokk** [comment]
Is there a command to try and force the connection or a way to see if the connection is attempted but failing?

**Comment by manateelazycat** [comment]
> Is there a command to try and force the connection or a way to see if the connection is attempted but failing?

https://github.com/manateelazycat/lsp-bridge#report-bug

**Comment by chookity-pokk** [comment]
Okay, so I think what happened is that when I installed the Python dependencies it installed a different version of sexpdata because installing 0.0.3 made it work.
