### ISSUE TITLE
ACM to complete paths

### ISSUE THREAD

**Issue by chookity-pokk** [manateelazycat/lsp-bridge#537]
Less of a bug and more of a feature request. 

With company if you start typing a path it will give you the available options for what's next like in the screenshot below. 

It would be nice if ACM did something similar. 

![image](https://user-images.githubusercontent.com/24358100/218792649-b591e282-e1d2-4052-bfbc-308dc172b517.png)

**Comment by manateelazycat** [comment]
I don't understand what your mean

**Comment by chookity-pokk** [comment]
ACM doesn't (or hasn't) do path completion like in that screenshot whereas company does. It would be nice if ACM had something similar.

**Comment by manateelazycat** [comment]
Yes, acm can completion path, it just completion path in string.

**Comment by manateelazycat** [comment]
![截图 2023-02-15 12-53-14](https://user-images.githubusercontent.com/237487/218935084-94d67b2c-179c-499e-9367-3ce6003501fc.png)

**Comment by chookity-pokk** [comment]
Okay, I didn't know that! Thank you for the information, I'll go ahead and close the issue now.

**Comment by chookity-pokk** [comment]
Quick question, what are you using for tabs in that screenshot? I really like that look!

**Comment by manateelazycat** [comment]
My another plugin: https://github.com/manateelazycat/sort-tab
