### ISSUE TITLE
Strange diagnostic behavior for pyright_ruff when both servers are enabled

### ISSUE THREAD

**Issue by seraphlive** [manateelazycat/lsp-bridge#538]
Description:
When both pyright and ruff are set as diagnostic sources, results from both source are not shown at the same time. Pyright's result shows when the file is open for the first time or whenever it's edited but not saved. Ruff's result only shows when the file is saved after being edited.

Command to reproduce:
```bash
emacs -Q -L lsp-bridge -L posframe -L yasnippet -L markdown-mode -L exec-path-from-shell -l ~/test.el ~/bug.py
```
test.el:
```elisp
(package-initialize)

(when (featurep 'cocoa)
  (require 'exec-path-from-shell)
  (exec-path-from-shell-initialize))

(require 'lsp-bridge)
(setq lsp-bridge-enable-log t)
(setq lsp-bridge-python-ruff-lsp-server "pyright_ruff")
(global-lsp-bridge-mode)
```
pyright_ruff.json:
```json
{
  "completion": ["pyright"],
  "completion_item_resolve": ["pyright"],
  "diagnostics": ["pyright", "ruff"],
  "code_action": ["pyright", "ruff"],
  "execute_command": ["pyright", "ruff"],
  "find_define": "pyright",
  "find_implementation": "pyright",
  "find_references": "pyright",
  "formatting": "pyright",
  "hover": "pyright",
  "signature_help": "pyright",
  "prepare_rename": "pyright",
  "rename": "pyright",
  "document_symbol": "pyright"
}
```
bug.py:
```python
def foo(bar):
    pass

foo(bar1, bar2)
```

Diagnostic results from pyright and ruff cli regarding this piece of python code:
```bash
pyright 1.1.289
bug.py
  bug.py:4:11 - error: Expected 1 positional argument (reportGeneralTypeIssues)
  bug.py:4:5 - error: "bar1" is not defined (reportUndefinedVariable)
  bug.py:4:11 - error: "bar2" is not defined (reportUndefinedVariable)
3 errors, 0 warnings, 0 informations
Completed in 0.45sec
```
```bash
bug.py:4:5: F821 Undefined name `bar1`
bug.py:4:11: F821 Undefined name `bar2`
Found 2 errors.
```

Operations to reproduce:
(use lsp-bridge-diagnostic-list to check in each step)
1. File is initially opened -> pyright's results
2. Modify "bar1", ("bfar1" for example) but don't save the file -> pyright's results
3. Save the file -> Ruff's results
4. Edit "bfar1" again, ("bftar1" for example) but don't save the file -> pyright
5. Save the file -> Ruff
6. Restore "bftar1" to original "bar1" but don't save the file -> pyright
7. save the file -> Ruff

From lsp-bridge's log, we can see that: ([lsp-bridge.log](https://github.com/manateelazycat/lsp-bridge/files/10768560/lsp-bridge.log))
1. When pyright's results are shown, Both servers' diagnostic data are recorded. (But only pyright's are displayed)
2. When Ruff's results are shown, Only Ruff's diagnostic data is triggered and recorded.

**Comment by manateelazycat** [comment]
已经修复了， 感谢反馈。
