### ISSUE TITLE
c语言补全不能像yasnippet那样

### ISSUE THREAD

**Issue by nesteiner** [manateelazycat/lsp-bridge#54]
![图片](https://user-images.githubusercontent.com/46296608/168303293-1054bfdd-3237-4ad6-a60b-379f9222945b.png)

补全的时候直接把不全选项打印出来了，不能像yasnippet模板那样不全，要一个一个来改  
ps: 其他语言我还没试过

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/commit/9d8ead517fca3df9c74f79d729b57628975e021c
