### ISSUE TITLE
Support codeium

### ISSUE THREAD

**Issue by manateelazycat** [manateelazycat/lsp-bridge#543]
https://github.com/Exafunction/codeium.el

**Comment by VitalyAnkh** [comment]
Please consider supporting https://github.com/zerolfx/copilot.el,  too.

**Comment by sawyerzheng** [comment]
codegeex is a better choice than copilot which is free and open source. 
- codegeex vscode extension: https://github.com/CodeGeeX/codegeex-vscode-extension
- codegeex itself: https://github.com/CodeGeeX/codegeex-vscode-extension

**Comment by VitalyAnkh** [comment]
@sawyerzheng Don't be biased. There are no reasons to support one and exclude others for lsp-bridge.
