### ISSUE TITLE
How to set up with pyright and pyenv

### ISSUE THREAD

**Issue by andcarnivorous** [manateelazycat/lsp-bridge#544]
Hi,
I really like the package, it's incredibly fast compared to other lsp services for Emacs.
I am trying to use it with pyright for my projects, in each project I have a pyrightconfig.json that points to the pyenv virtual env directory in my system under `~/.pyenv/versions/`, however the virtual env is never picked up and so all imports of installed packages are marked as unresolved references.

Is there some doc on how to set up lsp-bridge with pyright and pyenv?

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/wiki/Python%20virtualenv

**Comment by andcarnivorous** [comment]
Thanks! This works, however I would like to make it more dynamic since I have multiple projects with different venvs.
Are the arguments passed to this function (`project-path` and `filepath`) the project-root from project.el and the absolute filepath to the file? Also, when is this function executed? Because I tried to log its arguments to a temp buffer and the messages buffer but could not get anything logged.
Given what is written I can use the project-path to do something like the following?
`(custom-config (concat project-path "mypyrightconfig.json"))`

**Comment by manateelazycat** [comment]
please read README
