### ISSUE TITLE
Error running timer ‘acm-template-candidate-update’: (buffer-read-only #<buffer  *acm-doc-buffer*>)

### ISSUE THREAD

**Issue by sweet66** [manateelazycat/lsp-bridge#548]
This error is reported when using acm complete menu

Emacs version
GNU Emacs 28.2 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H15)) of 2023-02-21

**Comment by manateelazycat** [comment]
Update to newest version?

**Comment by manateelazycat** [comment]
Please re-open if still have issue.

**Comment by sweet66** [comment]
I try to update Emacs version to 29 and lsp-bridge to latest still following error
```
Error running timer ‘acm-template-candidate-update’: (buffer-read-only #<buffer  *acm-doc-buffer*>)
save-current-buffer: Buffer is read-only: #<buffer  *acm-doc-buffer*> [5 times]
```
After that acm-doc cannot display.  An error occurred on the display javascript comment documentation

**Comment by manateelazycat** [comment]
@sweet66 Upgrade lsp-bridge and try again?

**Comment by sweet66** [comment]
There is no error. thanks. lsp-bridge is so great
