### ISSUE TITLE
corfu-insert 后补全窗口没有关闭

### ISSUE THREAD

**Issue by Eason0210** [manateelazycat/lsp-bridge#55]
猫哥，

在pyright 下使用 lsp-bridge ，按回车后仍然会继续补全。

Corfu 完成补全一般会用 `corfu-complete`（ <kbd>Tab </kbd>） 和 `corfu-insert`（ <kbd>RET </kbd>） 这两个命令，目前 <kbd>Tab</kbd> 是可以正常工作，但是 <kbd>RET </kbd>后，会继续弹出补全窗口。

**Comment by manateelazycat** [comment]
你更新了最新版了吗？

**Comment by Eason0210** [comment]
是最新版 https://github.com/manateelazycat/lsp-bridge/commit/4fe5db0

**Comment by manateelazycat** [comment]
知道了，今晚修复， 你可以先把 corfu-insert 加入 lsp-bridge-completion-stop-commands 后看看好不好？

**Comment by Eason0210** [comment]
这样设置后 Tab 和 RET 都能正常工作了。
```
(setq lsp-bridge-completion-stop-commands '(corfu-complete corfu-insert))
```

**Comment by manateelazycat** [comment]
已经修复，谢谢反馈。
