### ISSUE TITLE
Freezes Emacs when trying to complete  a snippet in Org Mode

### ISSUE THREAD

**Issue by chookity-pokk** [manateelazycat/lsp-bridge#553]
When trying to complete a snippet in org mode my Emacs freezes 100% of the time unless I don't have lsp-bridge loaded at all. Even having it loaded but disabled still causes the when completing a yasnippet in org mode. Below is my lsp-bridge setup. 

```
(add-to-list 'load-path "~/.emacs.d/lsp-bridge")
(require 'lsp-bridge)
(global-lsp-bridge-mode)
(require 'lsp-bridge-jdtls)
(setq acm-enable-tabnine nil) ;t is on
(setq acm-enable-quick-access 1)
(setq acm-backend-yas-candidates-number 4) ;number of snippets
```

I am using emacs 29.0.6 on EndeavorOS.

**Comment by manateelazycat** [comment]
I have test, no performance issue, please test lsp-bridge with "emacs -Q"
