### ISSUE TITLE
`lsp-bridge--position` calculates the wrong line number

### ISSUE THREAD

**Issue by skykanin** [manateelazycat/lsp-bridge#565]
`lsp-bridge--position` gives you the wrong line number.

Steps to reproduce:
1. Open a file with lsp-bridge-mode enabled
2. Evaulate `(lsp-bridge--position)`
3. Observe that the returned line number is one less than the actual line number

![image](https://user-images.githubusercontent.com/3789764/224551468-1a3d9281-e952-4033-b02f-08a267b6d3a4.png)

I can see from the code that the implementation is wrong:
```lisp
(defun lsp-bridge--position ()
  "Get position of cursor."
  (list :line (1- (line-number-at-pos)) :character (lsp-bridge--calculate-column)))
```

There is no need to subtract 1 from the result of `(line-number-at-pos)` as it returns the correct line number as is.

**Comment by manateelazycat** [comment]
No, lsp-bridge--position is calcuate line number from zero, it's need by LSP Server, not use for display.

**Comment by skykanin** [comment]
Ah ok, but it seems that `lsp-bridge-popup-documentation` isn't correct then because I'm getting docs for the line above the cursor position since it uses `lsp-bridge--position` to get the position:
![image](https://user-images.githubusercontent.com/3789764/224551930-a847ede2-c66a-4b2a-92dd-ac1a5dcde515.png)

**Comment by skykanin** [comment]
@manateelazycat should I open a new issue for this?

**Comment by manateelazycat** [comment]
I just tested `lsp-bridge-popup-documentation` and didn't reproduce your problem.

**Comment by skykanin** [comment]
@manateelazycat pinning my `lsp-bridge` version to latest master commit fixes the issue :+1:
