### ISSUE TITLE
top options of completion list is not relavant to real demand.

### ISSUE THREAD

**Issue by sawyerzheng** [manateelazycat/lsp-bridge#571]
the completion result order is not relavant to what we want.

for example "from sys im", this should be `import` at top. but i got ImportError which is seldomly used.

**lsp-bridge + pyright**
![image](https://user-images.githubusercontent.com/44355570/226805371-3910d9b8-5761-4d90-bf96-06fabe4688e4.png)

**eglot + pyright**
![image](https://user-images.githubusercontent.com/44355570/226805664-58ccdb26-bf93-4303-986f-45584868b813.png)

**Comment by manateelazycat** [comment]
Done
