### ISSUE TITLE
当citre的tag文件过大时，会将emacs卡死

### ISSUE THREAD

**Issue by hellosigma** [manateelazycat/lsp-bridge#572]
环境：
         doom emacs
         ubuntu20.04
tag文件大小：
17G 3月  21 20:58 .tags
配置：
(use-package! lsp-bridge
  :hook
  (python-mode . lsp-bridge-mode)
  :init
  (global-lsp-bridge-mode)
  (setq acm-enable-citre t)
  (set-lookup-handlers! 'rustic-mode :async t
    :definition #'lsp-bridge-find-def
    :implementations #'lsp-bridge-find-impl))

(unless (display-graphic-p)
  (after! acm
    (use-package! acm-terminal)))

**Comment by manateelazycat** [comment]
目前没有办法， citre 并没有像 lsp-bridge 这样做异步多线程设计。

**Comment by hellosigma** [comment]
试了单kernel的话卡顿还能接受，全Android分支的话就不能用了。暂时先关了cirtre，没有已经够用了
