### ISSUE TITLE
cl-reduce: Wrong number of arguments: #<subr max>, 0

### ISSUE THREAD

**Issue by falood** [manateelazycat/lsp-bridge#573]
I'm using lsp-bridge with elixir, and got the error once I open a file

```
[LSP-Bridge] Start LSP server (elixirLS) for /path/to/my/project with ’project’ mode, enjoy hacking!
cl-reduce: Wrong number of arguments: #<subr max>, 0
```

I'm using emacs 30.0.50 with native comp, and have tabnine enabled in my config

```elisp
(require 'lsp-bridge)
(setq acm-enable-icon t)
(setq acm-enable-tabnine t)
```

**Comment by manateelazycat** [comment]
Looks something wrong at https://github.com/manateelazycat/lsp-bridge/blob/1ab1dafbb2e642056e9a4660519f5aff8804367c/acm/acm.el#L661

Can you add `(message "%s" (mapcar (lambda (v)
                       (funcall acm-string-width-function
                                (format "%s %s" (plist-get v :display-label) (plist-get v :annotation))))
                     acm-menu-candidates))` at 661

Then return message string to me?

**Comment by falood** [comment]
thanks for the response, it return `nil`

**Comment by manateelazycat** [comment]
It's looks strange, if mapcar return nil, acm-menu-candidates will be empty or something wrong with acm-string-width-function.

Please turn on lsp-bridge-enable-log option and send log of `*lsp-bridge*` to me.

**Comment by manateelazycat** [comment]
Please remove native comp, I guess native comp is reason.

native comp is bad tech that don't improve anything but include so many other issues.

**Comment by falood** [comment]
I just tried to recompile emacs without `--native-comp` and got the same error

**Comment by falood** [comment]
I got the issue, it's my bad, I added `(acm-mode)` to my `elixir-mode-hook`, and my `C-n` was replaced by `acm-select-next`, and got the error once I type `C-n`.
thanks for you help all the same.
