### ISSUE TITLE
Remote editing mode only supports literal IPv4 addresses?

### ISSUE THREAD

**Issue by sdt16** [manateelazycat/lsp-bridge#582]
It seems like the parsing code for a remote file only supports literal

`xxx.xxx.xxx.xxx:/path`

This is extremely problematic for a lot of different reasons.

* Can't change usernames

* A lot of people have complicated ssh setups where ProxyCommands etc are setup through aliases, different keys, etc.

* You can't use IPv6. 

I feel like I must me missing something, because as it is the remote file support doesn't work for anything but the most absolute simple setups. I tried searching closed issues but couldn't find anything.

This is the first project that seems like it might free folks from the suffering of TRAMP, I'd love to be able to use it!

**Comment by manateelazycat** [comment]
@sdt16 Newest version has support username and ipv6, you can upgrade to newest version for test.

lsp-bridge-open-remote-file with user@ip:/path/file

**Comment by manateelazycat** [comment]
Please re-open this issue if still have problem.

**Comment by drwebb** [comment]
@manateelazycat Hi I am considering reopening this issue. I think the original author wasn't clear on a better solution.

I'd like to be able to use the hosts in my `~/.ssh/config`. For example in my `.ssh/config`

```
#
Host devbox
	HostName coder.devbox
	ConnectTimeout=0
	StrictHostKeyChecking=no
	UserKnownHostsFile=/dev/null
	LogLevel ERROR
	ProxyCommand /usr/local/bin/coder --global-config "/Users/twebb/Library/Application Support/coderv2" ssh --stdio devbox
```

`lsp-bridge-open-remote-file` I was to give it the `<host>:<path>`. Thanks for your package and hope to be rid of Tramp myself. Tramp inevitably usually stalls out my editor when my ssh connection goes bad. For the moment I'm just going to get a static IP so I can continue testing.

**Comment by manateelazycat** [comment]
PR are welcome.
