### ISSUE TITLE
Is it possible to jump to type definition?

### ISSUE THREAD

**Issue by luckysori** [manateelazycat/lsp-bridge#587]
For instance, using `lsp-mode` and `rust-analyzer` with the following code

```rust
struct Foo;

fn main() {
    let foo = Foo;
}
```

if I place my cursor on the variable `foo` and I call `lsp-find-type-definition`, Emacs will take me to the definition of `Foo`.

I haven't been able to do this using `lsp-bridge`. Is it possible?

---

The `rust-analyzer` feature is explained [here](https://rust-analyzer.github.io/manual.html#go-to-type-definition).

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/lsp-bridge/commit/0712a1fe86fe7c3acc9772259d769ec5a7422bfe

**Comment by luckysori** [comment]
Wow, that was so fast 🤩

**Comment by manateelazycat** [comment]
> Wow, that was so fast star_struck

lsp-bridge has good framework design, it's easy to add those protocol if I understand it.
