### ISSUE TITLE
Support remote file browsing

### ISSUE THREAD

**Issue by spcmxxd** [manateelazycat/lsp-bridge#589]
Thank you for your efforts in development.

While working on projects related to deep learning, it's convenient to connect to a pre-configured PyTorch environment on a GPU server through VS Code. 

By using the VS Code Remote Development extension, one can `edit and execute codes` on the server and `browse server files` through VS Code's file explorer. 

I wonder if the `lsp-bridge` enables remote file browsing capability?

**Comment by manateelazycat** [comment]
We need copy code get_file_infos from eaf-file-manager https://github.com/emacs-eaf/eaf-file-manager/blob/83d9583a9b8fa3a7e196c92c7aa833106a9c9c30/buffer.py#L327 to lsp-bridge

Then pass those files json information to EAF File Manager or dired.

Not hard to implement, just haven't time recently.

Leave message to lsp-bridge or EAF hacker that how to implement remote file browsing.

**Comment by manateelazycat** [comment]
@spcmxxd Please enable lsp-bridge-enable-with-tramp option.
