### ISSUE TITLE
Lisp nesting exceeds "max-lisp-eval-depth" when using tramp in Emacs29

### ISSUE THREAD

**Issue by nanasess** [manateelazycat/lsp-bridge#598]
The following code causes frequent **Lisp nesting exceeds 'max-lisp-eval-depth'** when tramp is used.
https://github.com/manateelazycat/lsp-bridge/blob/f2ef0c0d6ef3ed948627630c701741b641d31cd7/lsp-bridge.el#L2064-L2066
If commented out, this will not occur.

Emacs revison: https://github.com/emacs-mirror/emacs/tree/1b8b2cf61bdc29db098e8c7dd61fd5a7971c3a1e

**Comment by manateelazycat** [comment]
Done， please update to newest version.

**Comment by nanasess** [comment]
@manateelazycat It worked! Thank you for quick fix!

**Comment by manateelazycat** [comment]
> @manateelazycat It worked! Thank you for quick fix!

You're welcome, thanks for report. ;)
