### ISSUE TITLE
tree-sitter syntax highlight messed up after `lsp-bridge-code-format`

### ISSUE THREAD

**Issue by bzy-debug** [manateelazycat/lsp-bridge#601]
Hi,

Thanks for the great package! But I got some problems with syntax highlight when using this. Every time after `lsp-bridge-code-format`, the syntax highlight breaks.

lsp: `clangd`, colortheme: [solarized](https://github.com/bbatsov/solarized-emacs)
code:
```
int main(int argc, char *argv[])
{
	int aa;
	int bb;
}
```
before `lsp-bridge-code-format`:

<img width="363" alt="截屏2023-04-20 20 21 56" src="https://user-images.githubusercontent.com/71200607/233364388-06f39c40-2113-4f50-a868-723fe81e63d0.png">

after `lsp-bridge-code-format`:

<img width="370" alt="截屏2023-04-20 20 22 51" src="https://user-images.githubusercontent.com/71200607/233364637-101b0383-e028-4017-afe3-99718143f8ee.png">

The color of `int aa;`, `int bb;`, and `return 0;` is messed up.

This does not happen when `tree-sitter-hl-mode` is disabled.

**Comment by manateelazycat** [comment]
It's looks like a bug of tree-sitter, not lsp-bridge's bug.

**Comment by damanis** [comment]
@manateelazycat 
There is no problem with [tree-sitter](https://emacs-tree-sitter.github.io/installation/) when instead of `lsp-bridge` the `lsp-mode` module is used.

**Comment by manateelazycat** [comment]
I will looks this issue recently

**Comment by manateelazycat** [comment]
I didn't reproduce the problem, strange

**Comment by damanis** [comment]
I just open js-file, insert new line (`ctrl-o`) — tree-sitter (not builtin) highlight fail. Then `undo` — highlight still incorrect.
If use `lsp-mode` instead of `lsp-bridge`, all works properly.
(The problem, does not occur with builtin treesit, but it works bad.)

**Comment by manateelazycat** [comment]
I always use treesit, I see.

**Comment by damanis** [comment]
I used treesit, but it has strange problem with indent in some js files.

**Comment by manateelazycat** [comment]
> I used treesit, but it has strange problem with indent in some js files.

What's problem?

**Comment by manateelazycat** [comment]
Execute toggle-debug-on-error and paste backtrace to author of js-jsx--treesit module.

**Comment by manateelazycat** [comment]
Please use treesit to test, tree-sitter is external module, I think it won't support by Emacs developer team.
