### ISSUE TITLE
lsp-bridge-find-impl does not find all implementations for a  C++ virtual pure method.

### ISSUE THREAD

**Issue by dfszb** [manateelazycat/lsp-bridge#606]
If I use lsp-bridge-find-impl on a C++ virtual pure method, it will find the first implementation, instead of showing a list with all implementations.

Example:
class A {
public:
virtual void f() = 0;
};

class B : public A{
public:
virtual void f() override;
};

class C : public A{
public:
virtual void f() override;
};

In this case B::f will be found as implementation, however I'd expect to have a list instead with both B::f and C::f
(this is how it works in lsp-mode for example, or in other IDE-s).

**Comment by manateelazycat** [comment]
Done

**Comment by dfszb** [comment]
Thanks, this seems to work, in the sense that a completion prompt is displayed in the modeline.

However, maybe an even nicer implementation would be if there was a separated window similar to the one displayed by lsp-bridge-find-references.

I experimented with this, simply copying the process_response from the find_references.py to the find_implementation.py, and it seemed to work (after fixing constant definitions and imports).

**Comment by manateelazycat** [comment]
> Thanks, this seems to work, in the sense that a completion prompt is displayed in the modeline.
> 
> However, maybe an even nicer implementation would be if there was a separated window similar to the one displayed by lsp-bridge-find-references.
> 
> I experimented with this, simply copying the process_response from the find_references.py to the find_implementation.py, and it seemed to work (after fixing constant definitions and imports).

https://github.com/manateelazycat/lsp-bridge/commit/e199d0981398c628d589155bae9e91dca891e407

Done
