### ISSUE TITLE
Running clangd inside docker container

### ISSUE THREAD

**Issue by realbogart** [manateelazycat/lsp-bridge#607]
Hello!

I just watched the EmacsConf2022 lsp-bridge presentation and was intrigued. I'm currently giving Emacs a chance as an alternative to vscode and I would like to replicate its devcontainer workflow. I have a development container that has all of my C++ development tools set up. Is it possible to run clangd inside my container but use lsp-bridge on the host system? If so, how can I set it up?

Thank you, and keep up the good work!

**Comment by realbogart** [comment]
Thank you for the quick reply.

Does this mean the lsp-bridge also needs to run inside the docker container or only the language server?

**Comment by manateelazycat** [comment]
> Thank you for the quick reply.
> 
> Does this mean the lsp-bridge also needs to run inside the docker container or only the language server?

python part of lsp-bridge need running inside docker

**Comment by manateelazycat** [comment]
@realbogart I have ask this issue with ChatGPT, ChatGPT told me, nothing need change in source code of lsp-bridge, we just need:

1. Edit `/etc/docker/daemon.json` with

{
  "hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:9999",
            "unix:///var/run/docker.sock", "tcp://0.0.0.0:9998",
            "unix:///var/run/docker.sock", "tcp://0.0.0.0:9997"]
}

2. Then restart docker with command

`sudo systemctl restart docker`

3. Make sure firewall pass above ports.

Can you help us to test it ?

**Comment by manateelazycat** [comment]
@realbogart lsp-bridge support docker now!

https://github.com/manateelazycat/lsp-bridge/pull/962
