### ISSUE TITLE
lsp-bridge ccls-cache directory error

### ISSUE THREAD

**Issue by getong** [manateelazycat/lsp-bridge#608]
```
14:16:48                     utils.cc:177 E failed to write to 
src/Server/ServerWorld/player_hero.cpp/.ccls-cache/src@Server@ServerWorld@player_hero.cpp/@Library@Developer@CommandLineTools@SDKs@MacOSX13.3.sdk@usr@include@c++@v1@__type_traits@remove_cv.h.blob Not a directory
```

win32 project, but I open it in macos 
It might be the same error with 
MaskRay/ccls#928

**Comment by manateelazycat** [comment]
Which command cause this error ?

**Comment by MaskRay** [comment]
Please can you check out "How To Ask Questions The Smart Way" and give detailed information about your environment and setup? Others don't have your `ServerWorld/player_hero.cpp` and it would be difficult / impossible to reproduce your issue.

**Comment by getong** [comment]
> Which command cause this error ?

I just set 
(setq lsp-bridge-c-lsp-server "ccls")

and then open the cpp project,  and run the command `lsp-bridge-find-def`, the ccls start to index the cpp project source file, after a few seconds, the lsp-bridge can works. 
But a lot error in the `*lsp-bridge*` buffer,  this is only one line sample of the error msg.

**Comment by manateelazycat** [comment]
Can you give me a source code for test ?

**Comment by getong** [comment]
I can not give my cpp source project to you, mine is using svn, this error might be related to svn.

I reproduce the error with another project:
```
git clone https://github.com/elhoangvu/ExpenditureManagement-Win32
cd ExpenditureManagement-Win32
## this is a must 
mv .git .git-bak
```

then open ExpenditureManagement-Win32/Source/1512682/1512682.cpp

that error occurs:
```
15:57:51                     utils.cc:177 E failed to write to ExpenditureManagement-Win32/Source/1512682/1512682.cpp/.ccls-cache/@@ExpenditureManagement-Win32@Source@1512682@1512682.cpp/@Library@Developer@CommandLineTools@SDKs@MacOSX13.3.sdk@usr@include@c++@v1@__type_traits@remove_reference.h.blob Not a directory
```

**Comment by manateelazycat** [comment]
> I can not give my cpp source project to you, mine is using svn, this error might be related to svn.
> 
> I reproduce the error with another project:
> 
> ```
> git clone https://github.com/elhoangvu/ExpenditureManagement-Win32
> cd ExpenditureManagement-Win32
> ## this is a must 
> mv .git .git-bak
> ```
> 
> then open ExpenditureManagement-Win32/Source/1512682/1512682.cpp
> 
> that error occurs:
> 
> ```
> 15:57:51                     utils.cc:177 E failed to write to ExpenditureManagement-Win32/Source/1512682/1512682.cpp/.ccls-cache/@@ExpenditureManagement-Win32@Source@1512682@1512682.cpp/@Library@Developer@CommandLineTools@SDKs@MacOSX13.3.sdk@usr@include@c++@v1@__type_traits@remove_reference.h.blob Not a directory
> ```

Can you give me detail steps? Step by step?

I just clone this repo, completion is ok when use ccls, find-define just give "No define found", I don't know how to got "failed to write " error.

**Comment by getong** [comment]
The doc is updated.

**Comment by manateelazycat** [comment]
If don't delete .git directory, lsp-bridge will start ccls with workspace same as .git directory, I got "no define found"

If delete .git directory, lsp-bridge will start ccls with single-file mode, and I got same error as you paste.

I haven't idea now, looks something wrong for ccls config.

Did you config compile_commands.json in project path before you call ccls ?

**Comment by getong** [comment]
> If don't delete .git directory, lsp-bridge will start ccls with workspace same as .git directory, I got "no define found"
> 
> If delete .git directory, lsp-bridge will start ccls with single-file mode, and I got same error as you paste.
> 
> I haven't idea now, looks something wrong for ccls config.
> 
> Did you config compile_commands.json in project path before you call ccls ?

I don't know how to use compile_commands.json. Would you give a doc link?

**Comment by manateelazycat** [comment]
You need google it, how to generate compile_commands.json
