### ISSUE TITLE
Latex: digestif template placeholder is not resolved

### ISSUE THREAD

**Issue by ST-Saint** [manateelazycat/lsp-bridge#609]
after selecting the candidate, the template expands literally but the placeholders are not resolved

Example:

```tex
\cit % complete there

% select: cite [subcite]{keys} =>

\cite${1:[${2:subcite}]}{${3:keys}}$0
```

minimal config
```emacs-lisp
(package-initialize)

(require 'use-package)

(use-package lsp-bridge
  :load-path "/home/.emacs.d/elpa/lsp-bridge-20230425.32403"
  :config
  (setq lsp-bridge-tex-lsp-server 'digestif))
```

**Comment by manateelazycat** [comment]
I don't understand LaTeX, can't help you now.

**Comment by smallzhan** [comment]
template placeholder is expanded by yasnippet,  so you need 
```(use-package 'yasnippet) 
```
it is ok in my emacs.

![Uploading Snipaste_2023-05-06_13-57-36.png…]()

**Comment by ST-Saint** [comment]
> template placeholder is expanded by yasnippet, so you need
> 
> ```
> (use-package yasnippet) 
> ```
> 

OK I guess `yas-minor-mode` has to be enabled as well.

However, if I enable `yas-minor-mode`, the candidates are shown when I typed `\cit` rather than `\cite`
![latex-cit](https://user-images.githubusercontent.com/13213464/236648926-9196036c-6d5f-408d-8f87-844d7b6cd4a9.png)
![latex-cite](https://user-images.githubusercontent.com/13213464/236648931-bd5ad8cd-566a-4a7e-988e-ab87eb4f1b90.png)

**Comment by manateelazycat** [comment]
> > template placeholder is expanded by yasnippet, so you need
> > ```
> > (use-package yasnippet) 
> > ```
> 
> OK I guess `yas-minor-mode` has to be enabled as well.
> 
> However, if I enable `yas-minor-mode`, the candidates are shown when I typed `\cit` rather than `\cite` ![latex-cit](https://user-images.githubusercontent.com/13213464/236648926-9196036c-6d5f-408d-8f87-844d7b6cd4a9.png) ![latex-cite](https://user-images.githubusercontent.com/13213464/236648931-bd5ad8cd-566a-4a7e-988e-ab87eb4f1b90.png)

What's Prenote? ACM haven't this backend.

**Comment by ST-Saint** [comment]
> What's Prenote? ACM haven't this backend.

`[prenote][postnote]` is the cite style introduced by

```
\documentclass[acmsmall, nonacm]{acmart}\settopmatter{printfolios=false,printccs=false,printacmref=false}
```

the backend is still `digestif` and you can still trigger it without any latex context by merely invoking `lsp-bridge-popup-complete-menu` after `\cite`

Only `\cite` triggers this problem, and I feel it is because yassnippet also has the `cite` keywords and it overwrites digestif's feedback

**Comment by smallzhan** [comment]
> Only `\cite` triggers this problem, and I feel it is because yassnippet also has the `cite` keywords and it overwrites digestif's feedback

maybe a bug for digestif,  I've tried the minimal example, found that, when typing `\cit`, digestif return 19 completion items, where 0 completion items for `\cite`.

<img width="629" alt="截屏2023-05-07 17 16 13" src="https://user-images.githubusercontent.com/1635790/236668867-d0fe0bd2-a489-44b9-8612-0a91c2b76245.png">
