### ISSUE TITLE
Very large *lsp-bridge* buffer

### ISSUE THREAD

**Issue by Bitnut** [manateelazycat/lsp-bridge#61]
I found that using lsp-bridge after a while the `*lsp-bridge*` buffer will become very large,  with many packages info in it. and no completion comes out. 

Maybe lsp-brige should filter message that is too long for a emacs buffer, or clean the `*lsp-bridge*` buffer from time to time?  

![image](https://user-images.githubusercontent.com/21965633/168407292-2c3f6b29-8d4e-4b1f-a8b3-8269546d1d13.png)

I am using lsp-bridge at commit `0e642391`, and use it to work on a typescript project.

**Comment by Bitnut** [comment]
I have found that this line inputs too many messages into `*lsp-bridge*` buffer.

Maybe the logging level should be set into `ERROR`, or this should be a variable that can be configure somewhere?
 
[logger.setLevel(logging.INFO)](https://github.com/manateelazycat/lsp-bridge/blob/0e642391aa7412b46b3be377bdb35500ccfad955/core/utils.py#L34)

**Comment by manateelazycat** [comment]
你是不是打开了 ```(setq lsp-bridge-enable-log t)``` ? 默认只会发送消息标题
