### ISSUE TITLE
lsp-bridge does nothing (Emacs 30.0.50, Windows)

### ISSUE THREAD

**Issue by tuhdo** [manateelazycat/lsp-bridge#613]
So, I installed `lsp-bridge` according to the instructions, open a random Python file in a this Python project: https://github.com/JeffLIrion/adb_shell and nothing happened. I already enabled `global-lsp-bridge-mode`.

Python backend is `pylsp` and python command is `pypy3.exe` (even so, changed to `python.exe` does nothing).

**Comment by manateelazycat** [comment]
please read bottom of readme

**Comment by tuhdo** [comment]
I finally set it up correctly. It turned out that I set to `pypy` but forgot to install dependencies. The log buffer helped, thanks.
