### ISSUE TITLE
Show completion candiates without having to press a keyt

### ISSUE THREAD

**Issue by tuhdo** [manateelazycat/lsp-bridge#616]
Currently, I need to insert at least a character to get completion candidates. But, I want to get a list of all candidates, e.g. within a namespace like in `std::` in C++. I haven't found a way to do it.

**Comment by manateelazycat** [comment]
Maybe you need remove `lsp-bridge-not-match-hide-characters` from `lsp-bridge-completion-popup-predicates` to do that. ;)

**Comment by tuhdo** [comment]
I removed, but `std::` still does not show candidates. Only if I enter some character behind the colon. 
![image](https://user-images.githubusercontent.com/4818719/235489482-d3ea511b-976a-4fa3-88b6-a2ed709c7e9f.png)

To make it clear, `lsp-bridge` is working fine with my `clangd`. It's just that namespace completion provides no candidate until you type something.

For example, this will show:

![image](https://user-images.githubusercontent.com/4818719/235489641-815b6044-d3fe-46c4-8678-be4f875858b4.png)

But not this:

![image](https://user-images.githubusercontent.com/4818719/235489672-6337a5f7-273e-41fd-acc8-a1dcaf57e43b.png)

**Comment by manateelazycat** [comment]
Update to newest version and try again. ;)

**Comment by tuhdo** [comment]
It works now. Thanks for a blazing fast and smooth LSP package.

**Comment by zijianyue** [comment]
I have removed ':' from lsp-bridge-completion-hide-characters ,but it only pop like below, use lsp-bridge-popup-complete-menu can work well.
``
(custom-set-variables
 '(lsp-bridge-completion-hide-characters '(";" "(" ")" "[" "]" "{" "}" "," "\"")))
``
1. after insert colon pop this menu
![image](https://github.com/manateelazycat/lsp-bridge/assets/6119928/a6341d7b-f197-4092-b231-bb1e55ce445d)
2. use lsp-bridge-popup-complete-menu can work well
![image](https://github.com/manateelazycat/lsp-bridge/assets/6119928/c090b05d-7701-46da-a3f8-a52a6d3d9f75)

**Comment by manateelazycat** [comment]
Please uncomment https://github.com/manateelazycat/lsp-bridge/blob/ccf28fa12b11f75b903a6c1543522282fe88b2d6/lsp-bridge.el#L1147 line and paste log from `*Messages*`, that will help.

**Comment by zijianyue** [comment]
please check the output info
> [LSP-Bridge] Start LSP server (clangd) for /home/xxx/myproject with ’project’ mode, enjoy hacking!
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (s)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead. [2 times]
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (t)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (d)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (d)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (d)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command nil
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t
> *** lsp-bridge-not-delete-command t
> *** lsp-bridge-not-follow-complete t
> *** lsp-bridge-not-match-stop-commands t
> *** lsp-bridge-not-match-hide-characters t
> *** lsp-bridge-not-only-blank-before-cursor (:)
> *** lsp-bridge-not-in-string t
> *** lsp-bridge-not-in-org-table t
> *** lsp-bridge-not-execute-macro t
> *** lsp-bridge-not-in-multiple-cursors t
> *** lsp-bridge-not-in-mark-macro t
> *** lsp-bridge-is-evil-state t
> *** lsp-bridge-is-meow-state t
> *** lsp-brige-not-in-chatgpt-response t
> *** lsp-bridge-not-complete-manually t

**Comment by manateelazycat** [comment]
@zijianyue Please update to the latest version

我推送了补丁 https:github.com/manateelazycat/lsp-bridge/commit/97b060f6ed95ce3011fed98b5847bc680d589032

The purpose of this patch is to set the lsp-bridge-completion-obey-trigger-characters-p option to t, so that the trigger-characters will be matched instead of lsp-bridge-completion-hide-characters.

BTW, lsp-bridge-completion-hide-characters should be set with setq instead of custom-set-variables

**Comment by zijianyue** [comment]
@manateelazycat Thanks for your reply, but my issue is not the modification of lsp-bridge-completion-hide-characters not work,but    
the pop up menu is wrong, not the member in std, after update to today's version, this issue still exist.
![image](https://github.com/manateelazycat/lsp-bridge/assets/6119928/58d464e4-814c-43aa-85fa-d67b51030d5c)

**Comment by manateelazycat** [comment]
@zijianyue I have push https://github.com/manateelazycat/lsp-bridge/commit/267974880570ae2c49ce63c3e804be4e6baffda6

Try again.

**Comment by zijianyue** [comment]
It looks like this now
![image](https://github.com/manateelazycat/lsp-bridge/assets/6119928/d288939f-aea7-450d-a173-0ff4b7b70697)
and if I backspace one colon,and tap colon again ,it works well
![image](https://github.com/manateelazycat/lsp-bridge/assets/6119928/b382f1e1-b6e0-4b6e-a441-1b9dcfb6094b)

**Comment by manateelazycat** [comment]
first one is not right？

**Comment by manateelazycat** [comment]
lsp server will return score or sortText by user input.

When you change from "sort:" to "sort::", sort list is not different with "sort::a" to "sort::", it's control by lsp server.

**Comment by zijianyue** [comment]
> first one is not right？

first one is not right, the candidates are not member in std

**Comment by manateelazycat** [comment]
Two candidate list is give by clangd, I don't know why clangd return two different list.

No idea now.

**Comment by manateelazycat** [comment]
> It looks like this now ![image](https://user-images.githubusercontent.com/6119928/280264718-d288939f-aea7-450d-a173-0ff4b7b70697.png) and if I backspace one colon,and tap colon again ,it works well ![image](https://user-images.githubusercontent.com/6119928/280264940-b382f1e1-b6e0-4b6e-a441-1b9dcfb6094b.png)

I found it's because electric-indent-mode conflict with lsp-bridge, you set (electric-indent-mode -1) will fixed it temp.

**Comment by manateelazycat** [comment]
> It looks like this now ![image](https://user-images.githubusercontent.com/6119928/280264718-d288939f-aea7-450d-a173-0ff4b7b70697.png) and if I backspace one colon,and tap colon again ,it works well ![image](https://user-images.githubusercontent.com/6119928/280264940-b382f1e1-b6e0-4b6e-a441-1b9dcfb6094b.png)

I believe https://github.com/manateelazycat/lsp-bridge/commit/d25a63a1e7cca38fc931bb6ddb52acf590912685 fix this issue.

**Comment by zijianyue** [comment]
Yes, Great ! It's work well now, though new line and indent seems not work now, any advice about how to act as electric-indent-mode does.

> > It looks like this now ![image](https://user-images.githubusercontent.com/6119928/280264718-d288939f-aea7-450d-a173-0ff4b7b70697.png) and if I backspace one colon,and tap colon again ,it works well ![image](https://user-images.githubusercontent.com/6119928/280264940-b382f1e1-b6e0-4b6e-a441-1b9dcfb6094b.png)
> 
> I believe [d25a63a](https://github.com/manateelazycat/lsp-bridge/commit/d25a63a1e7cca38fc931bb6ddb52acf590912685) fix this issue.

**Comment by manateelazycat** [comment]
> Yes, Great ! It's work well now, though new line and indent seems not work now, any advice about how to act as electric-indent-mode does.
> 
> > > It looks like this now ![image](https://user-images.githubusercontent.com/6119928/280264718-d288939f-aea7-450d-a173-0ff4b7b70697.png) and if I backspace one colon,and tap colon again ,it works well ![image](https://user-images.githubusercontent.com/6119928/280264940-b382f1e1-b6e0-4b6e-a441-1b9dcfb6094b.png)
> > 
> > 
> > I believe [d25a63a](https://github.com/manateelazycat/lsp-bridge/commit/d25a63a1e7cca38fc931bb6ddb52acf590912685) fix this issue.

electric-indent-mode write too many hacking code to hook post-insert-char-hook, you should write your own new and indent code or download other indent plugin use normal tech.

**Comment by zijianyue** [comment]
@manateelazycat I have tested that `std::` completing works fine with `electric-indent-mode` enabled. So, you can now remove the restriction on `electric-indent-mode`.
I made a defadvice like this to enable electric-indent-mode in c++-ts-mode。
`emacs-lisp
(defadvice lsp-bridge--enable(after lsp-bridge--enable-af activate)
    (electric-indent-mode 1))
`
![image](https://github.com/manateelazycat/lsp-bridge/assets/6119928/f8e8e9d0-4e01-4fda-942d-18b8e737dc73)

**Comment by manateelazycat** [comment]
electric-indent-mode fix this issue in newest version? Can you share fix commit link ?

**Comment by zijianyue** [comment]
> electric-indent-mode fix this issue in newest version? Can you share fix commit link ?

No, my emacs  version is the same as before, maybe lsp-bridge fixed that unintentionally.
