### ISSUE TITLE
Support tab-and-go?

### ISSUE THREAD

**Issue by SoulAttacker** [manateelazycat/lsp-bridge#618]
Hello and thanks for making contributions to this elegant package!! I tried this package and very like it!

but I have a quesiton for this if there is plan to support tab-and-go keymap api for keymapping (or the acm-mode-map). (*like the configuration in package: [corfu](https://github.com/minad/corfu#tab-and-go-completion)*)

my configuration is below
```emacs lisp
(defun setup-lsp-bridge ()
  "init package: lsp-bridge"
  (require 'lsp-bridge)
  (setq lsp-bridge-python-command "~/miniconda3/bin/python"
        lsp-bridge-python-lsp-server 'pylsp
        lsp-bridge-c-lsp-server 'clangd)
  (define-key acm-mode-map [tab] 'acm-select-next)
  (define-key acm-mode-map [backtab] 'acm-select-prev)
  (define-key acm-mode-map "\M-j" 'acm-complete)
  (global-lsp-bridge-mode))
```

and the enhanced api is `acm-select-and-insert`, which can be set to `TAB`. When I press tab, select `acm-select-next` and `acm-complete` and **keep opening the candidates box** here.

Thanks again for this fantastic work, and have a nice day!

**Comment by manateelazycat** [comment]
It need use overlay implement this feature, it's not easy, will intro new bugs when add this feature.

PR are welcome.

**Comment by SoulAttacker** [comment]
> It need use overlay implement this feature, it's not easy, will intro new bugs when add this feature.↳
> 
> PR are welcome.↳

Catch that, thank you for your reply, btw, could u please tag it a `enhancement`, and I will do that someday, maybe someone do that earlier :)

Thanks again and have a nice day!

**Comment by manateelazycat** [comment]
Support by patch https://github.com/manateelazycat/lsp-bridge/pull/638
