### ISSUE TITLE
Delay or manual activation of ACM

### ISSUE THREAD

**Issue by tuhdo** [manateelazycat/lsp-bridge#623]
Is there a way to make the completion popup wait for a while before showing? Or a way to manually activate ACM?

**Comment by manateelazycat** [comment]
lsp-bridge-complete-manually: Only popup completion menu when user call lsp-bridge-popup-complete-menu command, default is nil

lsp-bridge-popup-complete-menu: Manually popup the completion menu, you only need this command when turn on option lsp-bride-complete-manually
