### ISSUE TITLE
support mojo as runtime environment

### ISSUE THREAD

**Issue by falood** [manateelazycat/lsp-bridge#624]
https://www.modular.com/mojo

**Comment by manateelazycat** [comment]
mojo has lsp server?

**Comment by falood** [comment]
I mean use mojo as the replacement of pypy to improve the performance.
but mojo is not opensource right now 😂

**Comment by manateelazycat** [comment]
I don't think mojo can replace python now.

**Comment by dragove** [comment]
> I mean use mojo as the replacement of pypy to improve the performance. but mojo is not opensource right now joy

mojo is internally using CPython if you just write python code. its non-python code is ugly compared to other modern programming languages. In fact, even mojo's implementation of matrix multiplication is slower than numpy (you know, python has a great power with C/Cpp) . Don't expect too much from mojo.
