### ISSUE TITLE
Error after doing [M-x] lsp-bridge-mode

### ISSUE THREAD

**Issue by RudolfWhicker** [manateelazycat/lsp-bridge#627]
# The Issue
When I try to enable `lsp-bridge-mode`, it throws an error - `Symbol’s value as variable is void: acm-buffer`. 
Then when I try to disable it, it says `Symbol’s function definition is void: acm-cancel-timer`.

# What I have done
- I cloned the repository.
- Added the following to my emacs config.
```
(add-to-list 'load-path "~/.config/emacs-flavors/emacs/lisp/lsp-bridge")
(require 'yasnippet)
(yas-global-mode 1)

(require 'lsp-bridge)
```
- I tried to enable lsp-bridge-mode via M-x.

**Comment by manateelazycat** [comment]
Add (global-lsp-bridge-mode) in your config

**Comment by RudolfWhicker** [comment]
It still give the same error - `Symbol’s value as variable is void: acm-buffer`

**Comment by manateelazycat** [comment]
emacs -Q for compare test

**Comment by RudolfWhicker** [comment]
I'm not sure what happened but the problem just solved itself.
Sorry if I wasted your time.
