### ISSUE TITLE
终端模式下补全菜单弹出之后显示文档出错

### ISSUE THREAD

**Issue by ipyffor** [manateelazycat/lsp-bridge#630]
![image](https://github.com/manateelazycat/lsp-bridge/assets/47955238/58f85e3b-948b-4962-8e49-7a8926ccf5f6)
# doomemacs配置：
![image](https://github.com/manateelazycat/lsp-bridge/assets/47955238/2bae3122-cfc5-44da-9100-68d35007f02d)
# emacs 28.2 manjaro linux

**Comment by ipyffor** [comment]
![image](https://github.com/manateelazycat/lsp-bridge/assets/47955238/3efdae0d-e4fb-4a48-803f-04604fcdd762)
一直提示这个不知道怎么回事

**Comment by manateelazycat** [comment]
> ![image](https://user-images.githubusercontent.com/47955238/238116231-3efdae0d-e4fb-4a48-803f-04604fcdd762.png) 一直提示这个不知道怎么回事

这个错误是EAF报出来的， 你应该仔细看EAF关于 Gnome 的文档。

**Comment by manateelazycat** [comment]
Emacs 终端的 frame 弹出无法做到跨窗口， 维护两套 (终端和GUI) 太麻烦了， 我将关闭这个 issue , 并从 README 中移除 acm-terminal 的信息。
