### ISSUE TITLE
lsp-bridge-popup-complete-mene does not complete after `.` character or from no character

### ISSUE THREAD

**Issue by tuhdo** [manateelazycat/lsp-bridge#633]
For example, suppose you want to look for completion in package `os` in Python:

```
import os
os.
````

Activate the command after the `.` character shows nothing. Or, if you complete from character at point, the completion command shows nothing as well. In the first case (after the `.` character, when let lsp-bridge handles the completion popup, I get completion candidates.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge#report-bug

**Comment by tuhdo** [comment]
I can reproduce it with `emacs -Q`. Here is my config:

```
(require 'yasnippet)
(yas-global-mode 1)

(require 'lsp-bridge)
(global-lsp-bridge-mode)

(setq lsp-bridge-python-command "pypy3")
(setq lsp-bridge-python-lsp-server "pyright")
(setq acm-enable-doc nil
      lsp-bridge-complete-manually t)
(define-key acm-mode-map (kbd "M-j") 'backward-char)
(define-key acm-mode-map (kbd "M-l") 'forward-char)
(define-key acm-mode-map (kbd "M-u") 'backward-word)
(define-key acm-mode-map (kbd "M-o") 'forward-word)
(global-set-key (kbd "M-SPC") 'lsp-bridge-popup-complete-menu)
```

After adding `posframe` and `yasnippet` to the load path, run the above config with `emacs -Q`.  Then, create a new Python file, put in `import os` then `os.` the next line. I tried running `lsp-bridge-popup-complete-menu` via `M-SPC` or `M-x`, but no completion popup appears.

Note that I'm on Windows.

**Comment by manateelazycat** [comment]
@tuhdo Update to newest version and try again. ;)
