### ISSUE TITLE
disable lsp-bridge in 'compile'

### ISSUE THREAD

**Issue by avkoval** [manateelazycat/lsp-bridge#636]
Hello!

I am having the problem with lsp-bridge mode activating in 'compile' screen, e.g.:
![image](https://github.com/manateelazycat/lsp-bridge/assets/3540984/65deb00e-bae0-455f-9a47-b5feb480b6f2)

It is not useful here at all, but I do not understand yet how to disable it here (global-lsp-bridge-mode is **not** activated)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/d82f78c60ea7b0c7b03d57e15c1905b8d651783e/lsp-bridge.el#L1719

**Comment by avkoval** [comment]
> (add-hook 'minibuffer-setup-hook #'lsp-bridge-enable-in-minibuffer) 

Probably you meant:

```emacs-lisp
(remove-hook 'minibuffer-setup-hook #'lsp-bridge-enable-in-minibuffer)
```

Which actuallyu helps! Thank you @manateelazycat
