### ISSUE TITLE
Make lsp-bridge popframe font the same size and font as the main frame

### ISSUE THREAD

**Issue by tuhdo** [manateelazycat/lsp-bridge#637]
Currently, the popframe is using the default size and font, e.g.:

![image](https://github.com/manateelazycat/lsp-bridge/assets/4818719/9241565e-e8e5-4e46-ba5c-c17bdd779068)

The command in the example is `lsp-bridge-popup-documentation`.

**Comment by manateelazycat** [comment]
Strangle, why your posframe not same as main frame?

Are you test with `emacs -Q` ?

**Comment by manateelazycat** [comment]
I can't produce this issue, sorry.

**Comment by tuhdo** [comment]
@manateelazycat I'm on Windows using Emacs 29.0.91 (built from source). You could reproduce with your config and setting custom frame font and size, e.g. setting text size to something like 28 or 30 for the main frame, but the child posframe only displays the default size.

**Comment by tuhdo** [comment]
@manateelazycat is there a way to display the doc in the mini-buffer? At least this can fix the problem and others might want the doc to stay in minibuffer too.

**Comment by manateelazycat** [comment]
documention is too long, minibuffer is not good for display documention.

**Comment by manateelazycat** [comment]
I see, I will use acm-frame instead posframe to fix this issue.

**Comment by tuhdo** [comment]
@manateelazycat thanks, that fixed it 
![image](https://github.com/manateelazycat/lsp-bridge/assets/4818719/45c0b333-4db7-4366-ac33-08d2d7012a0c)
