### ISSUE TITLE
c-indent-offset maybe default `set-from-style`

### ISSUE THREAD

**Issue by zwpaper** [manateelazycat/lsp-bridge#643]
some mode use `c-indent-offset` to detect `tabSize` and are used to format code.

but it may be `set-from-style` by default, it may cause error:

(gopls in my case)

```json
{
   "jsonrpc": "2.0",
   "error": {
      "code": -32700,
      "message": "JSON RPC parse error: json: cannot unmarshal string into Go struct field FormattingOptions.options.tabSize of type uint32"
   },
   "id": 11588
}
```

the format options is:

```json
{'tabSize': Symbol('set-from-style'), 'insertSpaces': False, 'trimTrailingWhitespace': True, 'insertFinalNewline': False, 'trimFinalNewlines': True}
```

it can be fixed by 

```lisp
(setq c-indent-offset 4)
```

but we should fix it in lsp-bridge

**Comment by manateelazycat** [comment]
just golang lsp server will failed?

**Comment by zwpaper** [comment]
I just tried clangd, and it works with the `set-from-style`.

not tested on other servers.

**Comment by manateelazycat** [comment]
Can you give some test code?

**Comment by zwpaper** [comment]
I tried emacs -q, and then enable lsp-bridge.

create a go file with the content:

```
package main

func main(){}
```

type `C-h v` to make sure `c-basic-offset` is the default `set-from-style`,

<img width="1389" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/3764335/0472a21c-ce9d-4696-80df-b98ef84e3259">

it should be able to format the code by adding space between `()` and `{}` after `func main` when calling `lsp-bridge-code-format`. but it failed:

<img width="1783" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/3764335/4085a30e-af6d-4e75-ba56-054a33595bf9">


the green square is printed because I have added a `print()` in `lsp-bridge` source code for debugging

**Comment by manateelazycat** [comment]
Has fixed in newest version, thanks for report. ;)
