### ISSUE TITLE
gopls 诊断消息不准确

### ISSUE THREAD

**Issue by opsnull** [manateelazycat/lsp-bridge#657]
示例代码如下：
``` shell
$ mkdir test; cd test
$ go mod init test.dev
$ cat test.go
package main

import "fmt"

func main() {
	fmt.Printf("test %s\n", "just for test")
	fmt.Fscan() // 敲入 fmt.F 出现候选者敲回车，诊断信息不对
}

```

go 和 gopls 版本：
``` shell
$ go version
go version go1.20.3 darwin/amd64
$ gopls version
golang.org/x/tools/gopls v0.12.1
    golang.org/x/tools/gopls@v0.12.2 h1:s4mznBqCHVHeuTYjxGYJhsW3Wp4FYon8YAqiJlwlpTY=
$ 
```

![image](https://github.com/manateelazycat/lsp-bridge/assets/433567/c40194c0-26f0-4dda-9246-4ff0473cf2c1)

**Comment by manateelazycat** [comment]
怎么不对？

**Comment by opsnull** [comment]
> 怎么不对？

自动补全 fmt.Fscan() 函数后，显示的诊断消息不对呢，按说应该报的是未指定函数参数之类的。

但是上面截图的错误，看起来是把 Fscan 的 Fs 截断了，然后说 can 不对。

**Comment by opsnull** [comment]
还会出现类似这种诊断错误，看起来把补全的 Append 方法重复了：
![image](https://github.com/manateelazycat/lsp-bridge/assets/433567/b5de4e17-d0b1-4eca-b320-61bc60761b79)

**Comment by manateelazycat** [comment]
![截图 2023-06-17 23-42-52](https://github.com/manateelazycat/lsp-bridge/assets/237487/9494504a-942d-4630-bb85-f7eb4324f0e0)
![截图 2023-06-17 23-43-55](https://github.com/manateelazycat/lsp-bridge/assets/237487/ba4fc670-39c2-49fb-bc9a-50699fd00e0d)
                                                                                                                                       
go version go1.20.4 linux/amd64                                                                                                                                    
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@(devel)

我这边没有重现到你的情况， 但是我们的版本确实有差异。

**Comment by manateelazycat** [comment]
我昨天发现 rust-analyzer 和 python ruff 都有类似的情况， 最后发现是 lsp server 的问题： https://manateelazycat.github.io/2023/06/28/lsp-server-diagnosis-bug/

我估计这个问题是 golang lsp server 的问题或者是版本的问题， 应该不是 lsp-bridge 本身的问题， 因为 lsp-bridge 只是1:1的现实lsp server返回的信息。

你可以看看这个函数 https://github.com/manateelazycat/lsp-bridge/blob/0b01f189fb2a04b5a0f8507039775a3e04c4c777/core/fileaction.py#L276

如果 golang 诊断日志也有绕过去的方法， 欢迎发送PR

**Comment by manateelazycat** [comment]
这个问题已经被 https://github.com/manateelazycat/lsp-bridge/commit/e13ba8410d9c0d1de2f724adbc399a621e83976a 修复了， 请更新吧。
