### ISSUE TITLE
当诊断信息出现在边界附近会显示不全

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#662]
如图
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/6f65791d-d577-4542-a37c-77348e98b61a)

**Comment by manateelazycat** [comment]
已经修复了 https://github.com/manateelazycat/lsp-bridge/commit/0c03ffa13396ae6489bec833a0c9ee623e0f853c
