### ISSUE TITLE
Does not display diagnostics from zig (ZLS)

### ISSUE THREAD

**Issue by mmcjimsey26** [manateelazycat/lsp-bridge#663]
It seems that completion is working fine through zls, although if there is an error, it won't be displayed in the buffer. Also, whenever I run `lsp-bridge-diagnostic-list`, it displays the following message: `[LSP-Bridge] No diagnostics found.` I've tested this with both eglot and lsp-mode, which work fine and display the errors properly.

Errors are displayed when using other lsp clients, like clangd and rust-analyzer, but not with zls.

Running `zig ast-check` on the file highlights the errors just fine.

Emacs: emacs-ng version 30.0.50
Zig: 0.11.0-dev.3867+ff37ccd29
ZLS: 0.11.0-dev.516+5c7bf22
lsp-bridge: master (e969f25)

Thanks for your help!

**Comment by manateelazycat** [comment]
can you give me some test code?

**Comment by mmcjimsey26** [comment]
Sure!
Here's an example:
```zig
const std = @import("std");

pub fn main() !void {
    std.debug.print("test\n", .{} // should highlight error here!
}
```

And here's the output of `zig ast-check`:
```
test.zig:4:34: error: expected ')', found '}'
    std.debug.print("test\n", .{} // should highlight error here!
                                 ^
```

**Comment by manateelazycat** [comment]
I have test it, works fine in my computer:
![截图 2023-06-30 16-08-28](https://github.com/manateelazycat/lsp-bridge/assets/237487/ef662a07-cc0f-463e-929a-271d126f5486)

![截图 2023-06-30 16-08-17](https://github.com/manateelazycat/lsp-bridge/assets/237487/a27b64f5-7aa4-453a-a2ba-10d6e3c1b3f9)



zig version: 0.10.1
zls version: 0.10.0

**Comment by manateelazycat** [comment]
Can't reproduce this issue, please commit new issue if you still have problem.
