### ISSUE TITLE
中文文档格式出错了

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#664]
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/501efcf6-462e-4b03-ac0f-bb19013ec91a)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/1b494278c15707acdb97f9d243ce9a620eb5442f 已经修复， 感谢反馈
