### ISSUE TITLE
存在诊断信息信息时，可以jump，但是list显示没有

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#665]
用lsp-bridge-diagnostic-jump-next可以跳过去
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/54d3ed9d-5ff2-403a-b76b-0c4534280e76)
但是用lsp-bridge-diagnostic-list的时候显示没有诊断信息
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/0515e7a1-cc5d-40f5-a945-942cc8996bc8)

**Comment by manateelazycat** [comment]
给一份测试代码吧

**Comment by heheda123123** [comment]
奇怪，今天又无法复现了
