### ISSUE TITLE
windows下jdtls存在但无法启动

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#666]
jdtls是个py脚本，win下用`python jdtls`运行也可以，已经加到环境变量但还是提示找不到jdtls
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/9a920795-b807-4faf-ba41-5c7d8768197b)
无法做到wiki描述的这样直接`jdtls`启动

**Comment by manateelazycat** [comment]
你是怎么添加环境变量的呢？

**Comment by heheda123123** [comment]
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/2c601778-df13-4558-84f9-a5f2d84edb97)
直接运行jdtls能找到，只是win上是用后缀来识别程序，没后缀他不知道用啥运行
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/0717cb4a-ffa0-47ff-ab33-f711caf72e77)

**Comment by smallevilbeast** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/master/langserver/jdtls.json#L5  @heheda123123 改成 python jdtls

**Comment by heheda123123** [comment]
> https://github.com/manateelazycat/lsp-bridge/blob/master/langserver/jdtls.json#L5 @heheda123123 改成 python jdtls

1 jdtls得写全路径
2 改了还是不行
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/8f5e8c79-162c-478c-915c-02c532c1e6f7)
3 这个命令在终端直接执行是没问题的
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/1bd345e9-9e81-4a98-826c-5d0515dc81bd)

**Comment by manateelazycat** [comment]
我推送了一个补丁 https://github.com/manateelazycat/lsp-bridge/commit/7528ce445a06882df4b6e38468cb343afe23f29e ， 添加了 jdtls_windows.json, 你可以更新试一下。

不过最好有啥环境变量能够替换那个 D:\\xxx 的路径， 要不你一更新 jdtls, 这个配置就失效了。

**Comment by heheda123123** [comment]
> 我推送了一个补丁 [7528ce4](https://github.com/manateelazycat/lsp-bridge/commit/7528ce445a06882df4b6e38468cb343afe23f29e) ， 添加了 jdtls_windows.json, 你可以更新试一下。
> 
> 不过最好有啥环境变量能够替换那个 D:\xxx 的路径， 要不你一更新 jdtls, 这个配置就失效了。

还是不行，会自动应用吗？
我也手动设置了下lsp-bridge-jdtls-default-file的值，还是不行
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/74916ab4-6638-46e0-b30c-ab7675cee070)

**Comment by manateelazycat** [comment]
看看 `*lsp-bridge*` buffer有没有什么报错？

**Comment by heheda123123** [comment]
> 看看 `*lsp-bridge*` buffer有没有什么报错？

空白的没内容，只有message显示
```
[LSP-Bridge] Error: can’t find command ’jdtls’ to start LSP server jdtls (c:/temp/xx.java), disable lsp-bridge-mode.
```

**Comment by manateelazycat** [comment]
你更新后重启Emacs了吗？

**Comment by heheda123123** [comment]
重启了的，刚刚又重启了还是这样
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/87c7b5b5-6461-468d-94f8-cd2eace934b8)

**Comment by manateelazycat** [comment]
在 ipython 中执行

import platform
platform.system().lower()

看看你返回的是什么？ 着两行代码是用于判断操作系统平台的

**Comment by heheda123123** [comment]
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/087c9a54-8f8b-48cb-9647-3bfa708e6556)
windows

**Comment by heheda123123** [comment]
我这里加了一句输出看看，提示server_comamnd_path为空
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/11a67cf4-f8e1-4040-8691-0800f37d7170)
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/2f10fa72-2070-4124-aac6-3d5c211b7b95)

**Comment by manateelazycat** [comment]
你在 https://github.com/manateelazycat/lsp-bridge/blob/e118b8e6fbd286e641c31183995e3c4e98750cd7/lsp_bridge.py#L774 这里打印一下 print(lang_server_info_path) 看看返回的是啥？

**Comment by heheda123123** [comment]
> 你在
> 
> https://github.com/manateelazycat/lsp-bridge/blob/e118b8e6fbd286e641c31183995e3c4e98750cd7/lsp_bridge.py#L774
> 
> 这里打印一下 print(lang_server_info_path) 看看返回的是啥？

走到上面if那条路径去了
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/53362b1d-f6bd-43b0-9a6a-f4ffc4f8c62b)

**Comment by manateelazycat** [comment]
你把 .cache 目录下的 jdtls.json 内容粘贴一下

**Comment by heheda123123** [comment]
可以了，
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/cdb1b348-8bef-4928-8607-30f5a30f1fd7)

应该是cache造成的原因，我直接把.cache/lsp-bridge-jdtls删了就可以了

**Comment by heheda123123** [comment]
感谢大佬
