### ISSUE TITLE
当用evil-escape退出编辑状态时，lsp-bridge的补全弹窗不会自动消失

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#668]
我使用了evil-escape，并把按键设置为kj
当在insert模式下触发了补全，输入kj退出到normal模式下，补全弹窗仍然存在。
这个问题属于lsp-bridge处理的范畴嘛？

**Comment by manateelazycat** [comment]
我不用evil，不知道怎么解决

**Comment by 50ways2sayhard** [comment]
试试加上这行
```emacs-lisp 
(add-to-list 'lsp-bridge-completion-stop-commands #'evil-escape)
```

**Comment by heheda123123** [comment]
> 试试加上这行
> 
> ```emacs-lisp
> (add-to-list 'lsp-bridge-completion-stop-commands #'evil-escape)
> ```

还是不行，另外这样写也不行
```
(add-to-list 'lsp-bridge-completion-stop-commands "evil-escape")
```

**Comment by heheda123123** [comment]
这样可以了
```
(add-to-list 'evil-normal-state-entry-hook #'acm-hide)
```

**Comment by heheda123123** [comment]
额，不行，不能这样改，改了确实就不正常
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/68bab953-74ad-4280-b1ba-52fbb3b9ba39)

**Comment by heheda123123** [comment]
始终用esc退出就行了，算是一种解决方案
