### ISSUE TITLE
设置 lsp-bridge-find-def-fallback-function 无效

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#669]
安装dumb-jump之后，配置lsp-bridge-find-def-fallback-function
```
(use-package dumb-jump
  :ensure t
  :config
  (add-hook 'xref-backend-functions #'dumb-jump-xref-activate)
  )

(add-to-list 'load-path "~/emacs-plugin/lsp-bridge")
(require 'lsp-bridge)
(setq acm-enable-doc nil)
(setq lsp-bridge-find-def-fallback-function #'xref-find-definitions)
(global-lsp-bridge-mode)
```
打开`emacs`源码，找到`start-process`函数的定义，光标移动到`make-process`处
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/b87f9e87-8a68-42ed-91be-50f798068557)
调用`lsp-bridge-find-def`没反应，调用`xref-find-definitions`能直接跳到make-process的定义如下
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/f475eac4-0e9e-433f-9b28-900a842af46c)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs/blob/432da6cc4903ddcd2636cb280b69aa0920830305/site-lisp/config/init-lsp-bridge.el#L101

**Comment by heheda123123** [comment]
用猫哥配置里`lsp-bridge-jump`这个函数是可以的

**Comment by manateelazycat** [comment]
我写了一个补丁 https://github.com/manateelazycat/lsp-bridge/commit/9d62ea2089890236e0663a3e4d55f2bf031fffb7 ， lsp-bridge 提供对 elisp 各种符号的定义跳转， dumb-jump 去掉吧， 这玩意基本没啥用。
