### ISSUE TITLE
php代码格式化存在问题

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#673]
```
<?php
if(isset($_GET['id']))
{
    header("Content-type:text/html;charset=utf-8");
    $db = mysqli_connect("localhost:3307","root","123456","demo");
    if(!$db){
        echo "鏁版嵁搴撻摼鎺ュけ璐ワ紒";
        exit();
    }
    $id=addslashes($_GET['id']);
    $sql="SELECT * FROM user WHERE id='$id' LIMIT 0,1";
    $result=mysqli_query($db,$sql);
    $row = @mysqli_fetch_array($result);

if($row)
{
    echo 'Your Login name:'. $row['user'];
    echo "<br>";
    echo 'Your Password:' .$row['passwd'];
}
else
{
    echo mysqli_error($db);
}
    mysqli_close($db);
}

```
语法服务器使用intelephense，格式化之后存在很多语法问题，不知道这个是上游intelephense的问题还是lsp-bridge的问题
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/f791fbf3-26f1-4ced-85aa-f2693b8ebe3e)

**Comment by heheda123123** [comment]
同样的代码，试了下在vscode中开启intelephense之后，格式化是正常的。
而且不只是这段代码，随便找一段php代码，格式化都会乱掉

**Comment by heheda123123** [comment]
不过我在linux下执行会提示`current server not support code format`

**Comment by manateelazycat** [comment]
如果有这个提示，就是lsp server没有代码格式化这个能力

**Comment by heheda123123** [comment]
1 vscode上的intelephense支持格式化，官网也显示支持格式化功能。刚刚试了下lsp-mode，是可以正常格式化的
2 windows上没提示这个，直接进行了错误的格式化

**Comment by manateelazycat** [comment]
更新吧， 这个问题已经修复了。

https://github.com/manateelazycat/lsp-bridge/commit/b1de2e6ea18288cdc04a6e2f85d13006ec6e2356

原因是别的LSP Server返回的 code format 列表数据是升序的， 所以 lsp-bridge 需要把列表颠倒过来再格式化， PHP 的 LSP Server返回的格式化数据本身就是降序的， 再颠倒就会出现问题。

**Comment by heheda123123** [comment]
牛哇，试了下完美解决
