### ISSUE TITLE
在windows上revert-buffer-with-coding-system之后导致语言服务器退出

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#674]
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/fa3571a7-9315-47b5-a41b-26d5d13ba8e7)
如图，文件打开之后默认是gbk，文件名包含中文，使用revert-buffer-with-coding-system设置为utf-8之后，
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/a361f72f-b24e-41d0-aac3-338e0157456f)

在`*lsp-bridge*`中会看到这种提示
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/fd904352-16c6-4d38-ba0e-00a2af63ee76)
不过补全这些功能还是正常的，使用上没啥变化

**Comment by manateelazycat** [comment]
没有gbk的环境

**Comment by heheda123123** [comment]
windows上这样配置后就不会出现这种情况了
https://emacs-china.org/t/2023-windows/24920
