### ISSUE TITLE
C++ 文件的补全出现 *延迟*

### ISSUE THREAD

**Issue by AllTheLife** [manateelazycat/lsp-bridge#681]
如 GIF，`lsp-bridge` 在补全时，出现了 **延迟**

并非说前端卡住，前端非常流畅，而是提供的补全内容刷新得比较慢，可以看到，当输入完 `print` 后，acm的内容仍停留在 `p` 的补全项上。

- 在测试时， 我参照 [优化 Python 性能](https://github.com/manateelazycat/lsp-bridge/wiki/%E4%BC%98%E5%8C%96-Python-%E6%80%A7%E8%83%BD) 分析了一下性能剖析日志，发现python端动作非常迅速，所有操作在 34 ms 内就完成了。

- 我还发现 lsp-bridge 在为 elisp 提供补全时，acm内容刷新得很丝滑🤔

因此我推断（可能不对），问题是出在 lsp-bridge 与 lsp Server 之间的信息传递上。本来想着自己解决，无奈能力有限，只好来求助大佬，麻烦大佬花时间看看，帮忙解决一下🙏

![GIF](https://raw.githubusercontent.com/AllTheLife/logs/main/Peek%202023-07-17%2015-50.gif)

---

[Logs](https://raw.githubusercontent.com/AllTheLife/logs/main/a.txt)

#### 环境
- archlinux 最新版
- dwm 桌面环境
- ccls 与 clangd 后端均有此问题
- emacs 30 最新版
- lsp-bridge 最新版

**Comment by manateelazycat** [comment]
打开log选项会影响补全性能，平常用的时候不要打开 lsp-bridge-enable-log

**Comment by manateelazycat** [comment]
emacs -Q对比测试过了吗？

**Comment by AllTheLife** [comment]
测试过了，GIF就是emacs -Q时录的

**Comment by manateelazycat** [comment]
我这边测试没有延迟， 我看你gif也没有延迟啊。

**Comment by AllTheLife** [comment]
第一遍打得快了不太明显，后面几遍可以看出来，就是已经打完 `prin` 了，补全还是停留在 `p` 上

![GIF](https://raw.githubusercontent.com/AllTheLife/pictures/main/2023-07-18_10-08.png)

**Comment by manateelazycat** [comment]
我没法重现，早上试了很多遍，都是实时更新的

**Comment by AllTheLife** [comment]
那大佬能给什么调试建议吗？我尝试一下自己解决 thx

**Comment by manateelazycat** [comment]
打印 python 端process_response 的时间 https://github.com/manateelazycat/lsp-bridge/blob/master/core/handler/completion.py 

然后再看 elisp 端 lsp-bridge-completion--record-items  的调用时间

看看这两个时间对比，如果延迟明显，有可能有三个原因：
 
1. lsp server原因，就是慢
2. python端代码没有调用 lsp-bridge-completion--record-items
3. elisp 端调用了 lsp-bridge-completion--record-items ， 但是acm-update 没更新补全菜单

顺着上面三种可能原因耐心打print语句吧

**Comment by AllTheLife** [comment]
我拿远古版本（22年6月）的试了一下，发现没有这个问题🤔

我再调试看看

**Comment by manateelazycat** [comment]
你尝试把 (add-to-list 'candidates v t) 换成 (progn (add-to-list 'candidates v t)) 呢？

**Comment by manateelazycat** [comment]
> 谢谢大佬的帮助，我在对比以往提交时，找到了转折点：2022年 10月 21日 51d4ac 的提交
> 
> 在该次提交中，修改了 acm/acm-backend-lsp.el，与当前提交相比的diff见下
> 
> ```diff
> modified   acm/acm-backend-lsp.el
> @@ -124,22 +124,5 @@
>        (dolist (server-name acm-backend-lsp-server-names)
>          (when-let* ((server-items (gethash server-name acm-backend-lsp-items)))
>            (maphash (lambda (k v)
> +                     (add-to-list 'candidates v t))
> -                     (let ((candidate-label (plist-get v :label)))
> -                       (when (or (string-equal keyword "")
> -                                 (acm-candidate-fuzzy-search keyword candidate-label))
> -
> -                         ;; Adjust display label.
> -                         (plist-put v :display-label
> -                                    (cond ((equal server-name "文")
> -                                           (plist-get (plist-get v :textEdit) :newText))
> -                                          ((> (length candidate-label) acm-backend-lsp-candidate-max-length)
> -                                           (format "%s ..." (substring candidate-label 0 acm-backend-lsp-candidate-max-length)))
> -                                          (t
> -                                           candidate-label)))
> -
> -                         ;; FIXME: This progn here is to workaround invalid-function error for macros that have function bindings
> -                         ;; References: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46958
> -                         (progn
> -                           (plist-put v :backend "lsp")
> -                           (add-to-list 'candidates v t)))))
>                     server-items))))
> 
>      ;; NOTE:
> ```
> 
> 照着 diff 反向更改后就不会出现延迟了
> 
> 好奇为什么会这样呢？thinking

你能进一步删除diff代码， 来帮忙确定到底是哪一行导致的吗？

我看了 diff, 基本上就是 python 端重构后的废代码， 不会导致菜单延迟。

**Comment by AllTheLife** [comment]
看了一下，是

``` diff
modified   acm/acm-backend-lsp.el
@@ -124,5 +124,9 @@
       (dolist (server-name acm-backend-lsp-server-names)
         (when-let* ((server-items (gethash server-name acm-backend-lsp-items)))
           (maphash (lambda (k v)
-                     (add-to-list 'candidates v t))
-                   server-items))))
+                     (let ((candidate-label (plist-get v :label)))
+                       (when (or (string-equal keyword "")
+                                 (acm-candidate-fuzzy-search keyword candidate-label))
+
+                         (add-to-list 'candidates v t))))
+                     server-items))))

     ;; NOTE:
     ;; lsp-bridge has sort candidate at Python side,
```
这个补丁就能生效

是
``` lisp
(when (or (string-equal keyword "")
                                (acm-candidate-fuzzy-search keyword candidate-label))
```
起了作用

**Comment by manateelazycat** [comment]
我在 cpp 文件没有复现， 但是 rust 复现了。

我推送了一个补丁 https://github.com/manateelazycat/lsp-bridge/commit/4758674e21daef8a277286384457bc7adcd2029a ， 应该好了。

**Comment by AllTheLife** [comment]
抱歉，今天比较忙，刚刚试了一下，好像还是不太行 :smiling_face_with_tear:

**Comment by manateelazycat** [comment]
> 抱歉，今天比较忙，刚刚试了一下，好像还是不太行 🥲

你重启了吗？

**Comment by manateelazycat** [comment]
最好给我一个完整的代码， 让我可以稳定复现一下。

**Comment by AllTheLife** [comment]
是用 emacs -Q 测试的（应该可以吧？）

我这边只要是需要与lsp server配合的就会卡 :smiling_face_with_tear:

**Comment by manateelazycat** [comment]
给一份最小代码，还有你 lsp server 版本和emacs的版本。

**Comment by AllTheLife** [comment]
- clangd 15.0.7-9
- rust-analyzer 20230717-1
- emacs-git 30.0.50.167028-1

c++
``` c++
#include <bits/stdc++.h>
using namespace std;

int main() {
  printf("Hello world!");
}
```

rust 在更新后无法补全, `*lsp-bridge*` 与 `*Messages*` 均无报错

**Comment by manateelazycat** [comment]
无法重现

**Comment by AllTheLife** [comment]
抱歉，我把原来的删掉重新clone了一份，发现好了

可能是我在之前 pull 的时候误执行了什么操作 :smiling_face_with_tear:

感谢大佬的修复 :smiling_face_with_three_hearts:

**Comment by AllTheLife** [comment]
乌龙了 :sweat:，加载配置时把lsp-bridge指向了我打过补丁的目录

大佬能解释一下下面这个补丁为何不行吗？

``` diff
modified   acm/acm-backend-lsp.el
@@ -124,5 +124,9 @@
       (dolist (server-name acm-backend-lsp-server-names)
         (when-let* ((server-items (gethash server-name acm-backend-lsp-items)))
           (maphash (lambda (k v)
-                     (add-to-list 'candidates v t))
-                   server-items))))
+                     (let ((candidate-label (plist-get v :label)))
+                       (when (or (string-equal keyword "")
+                                 (acm-candidate-fuzzy-search keyword candidate-label))
+
+                         (add-to-list 'candidates v t))))
+                     server-items))))

     ;; NOTE:
     ;; lsp-bridge has sort candidate at Python side,
```

这个卡端在我这边仍然比较明显，可能是大佬的电脑太好了，察觉不到（？）

任何语言的hello world文件都可以复现

**Comment by manateelazycat** [comment]
这个补丁是在elisp过滤的，补全项多了就会卡顿。

最新版已经在python端过滤掉了。

**Comment by AllTheLife** [comment]
那奇了怪了🤔

我这边elisp端过滤可以解决问题，但Python端就不行

是不是elisp端的过滤还做了什么另外的事情？

**Comment by AllTheLife** [comment]
@manateelazycat 我看了一下，https://github.com/manateelazycat/lsp-bridge/commit/4758674e21daef8a277286384457bc7adcd2029a 在python端过滤是不是就无法用orderless进行选择了？

**Comment by manateelazycat** [comment]
lsp-bridge 有 acm-filter , 不需要啥orderless

**Comment by manateelazycat** [comment]
> 乌龙了 sweat，加载配置时把lsp-bridge指向了我打过补丁的目录
> 
> 大佬能解释一下下面这个补丁为何不行吗？
> 
> ```diff
> modified   acm/acm-backend-lsp.el
> @@ -124,5 +124,9 @@
>        (dolist (server-name acm-backend-lsp-server-names)
>          (when-let* ((server-items (gethash server-name acm-backend-lsp-items)))
>            (maphash (lambda (k v)
> -                     (add-to-list 'candidates v t))
> -                   server-items))))
> +                     (let ((candidate-label (plist-get v :label)))
> +                       (when (or (string-equal keyword "")
> +                                 (acm-candidate-fuzzy-search keyword candidate-label))
> +
> +                         (add-to-list 'candidates v t))))
> +                     server-items))))
> 
>      ;; NOTE:
>      ;; lsp-bridge has sort candidate at Python side,
> ```
> 
> 这个卡端在我这边仍然比较明显，可能是大佬的电脑太好了，察觉不到（？）
> 
> 任何语言的hello world文件都可以复现
> 
> 之前是我疏忽了，还请大佬再看一下pray

你最好更新到最新版， 打印看看 candidates 到底是啥？ 我真的不知道为啥你的环境会多出这些多余的候选词。

**Comment by AllTheLife** [comment]
> 你最好更新到最新版， 打印看看 candidates 到底是啥？ 我真的不知道为啥你的环境会多出这些多余的候选词。

我比对了一下两个 candidates，发现是一样的，没有多余的呀

**Comment by AllTheLife** [comment]
大佬，鄙人不才，有了一个猜想，如有错误，还请大佬纠正：

lsp-bridge 的 Python 端是异步的，在输入快了的时候可能会在短时间内向服务器发送多个请求，在请求返回准备显示时会杂糅在一起，导致会掺杂着很多落后的候选词，进而导致 *延迟*。此时如果在elisp端过滤可以被发现，而如果在Python端过滤，则会因为各个进程是独立的而过滤不出来。这就造成了这个奇怪的局面。大佬的电脑配置可能比较高，代码运行效率高，就不会受到这种困扰。

**Comment by AllTheLife** [comment]
所以大佬能不能考虑一下加个变量来控制是在elisp端过滤还是在python端过滤？

To fix this issue?

**Comment by manateelazycat** [comment]
> @manateelazycat 所以大佬能不能考虑一下加个变量来控制是在elisp端过滤还是在python端过滤？
> 
> To fix this issue?

elisp端过滤会影响性能，我们要知道为啥你的环境在最新版依然不能被python过滤掉多余的候选词。

**Comment by manateelazycat** [comment]
> @manateelazycat 大佬，鄙人不才，有了一个猜想，如有错误，还请大佬纠正：
> 
> * lsp-bridge 的 Python 端是异步的，在输入快了的时候可能会在短时间内向服务器发送多个请求，在请求返回准备显示时会杂糅在一起，导致会candidates中掺杂着很多落后的候选词，进而导致 _延迟_。
> * 此时如果在Python端过滤，则会因为各个进程是独立的而过滤不出来；但如果在elisp端过滤，由于各个补全候选项并在一起，则可以筛去不匹配的。这就造成了这个奇怪的局面。大佬的电脑配置可能比较高，代码运行效率高，就不会受到这种困扰。
> 
> 晚生愚笨，阅历浅薄，面对问题不够灵活，还望大佬多多见谅🙏

第一个问题不会有，只有最后一个请求才会显示，以前多个请求都会抛弃。

如果你elisp确实有多余候选词，需要在 https://github.com/manateelazycat/lsp-bridge/blob/e959f3dd930dadb8b929a2ff5e93bb547e5ddb52/core/handler/completion.py#L110

前后打印，看看为啥这个过滤函数没生效？

**Comment by AllTheLife** [comment]
打印了一下，发现生效了，在Python端并未出现多余的候选词，这让我猜测 elisp 端 **其实并没有多余的候选词**

于是我在 `acm-backend-lsp-candidates` 函数的末尾处添加了 `(message "1")`，发现所谓的多余的候选词其实是因为该函数运行多次造成的

例如我敲下 `pr`，则 `acm-backend-lsp-candidates` 会运行8次，其中三次中candidates为空，三次中candidates为`p`的菜单，两次为`pr`的菜单。这些菜单混在一起，给人一种产生了多余候选词的假象。

请问这是正常现象吗🤔

**Comment by manateelazycat** [comment]
你这个问题我的机器没法重现， 如果 Python 端没有问题， 确实有可能是 Elisp 端的问题， 我现在没法重现。

这个问题要花时间研究， 我最近在带家人休假， 要半个月以后才有时间研究。

如果你这段时间发现线索， 也欢迎留言。

**Comment by AllTheLife** [comment]
猫大辛苦了💐，在外还及时修bug

刚刚调试了一下，找到了只能在elisp端过滤的原因：

- 在python端过滤是根据 prefix 来过滤的，prefix是在触发补全时传递过去的`p`，而并不是最新的`pr`
- 在elisp端过滤时，是根据当前的keyword来过滤的，当前keyword是及时获取的，当输入完了`pr`后就会更新成`pr`，而非原来传递给python的`p`
所以它们过滤的区别在于根据的keyword不同，只要python端的keyword是即时获取的，就可以成功过滤

当然，这只是指标不治本的做法，我觉得根源应该还是上面说的重复调用的问题，但那个太复杂了，我还要再排查几天（马上要开学了，不一定能排查出来），所以先把当前的线索汇报一下

**Comment by manateelazycat** [comment]
lsp-bridge 设计之初就考虑到多个LSP请求的问题，不管是现在 elisp 端多次重复调用还是 python 端多个线程竞争返回的原因， lsp-bridge 设计成当补全候选词不是最新版本的时候就丢弃。

我觉得根本原因不是 prefix, 而是在你的电脑上， 第一次补全( `p` 前缀）比第二次补全 (`pr` 前缀）在Python端计算的更快， 这样第一次补全就调用了 lsp-bridge-completion--record-items ， 从而让你看到这些本应该抛弃的候选词。

我推送了 https://github.com/manateelazycat/lsp-bridge/commit/8b760af676773a207130ec5870e4ae253b582a08 补丁， 添加了一个 version 的参数给 completion.py , 多个补全线程在计算完结果后， 都用 self.version 和 self.file_action.version (这是最新实时的文件版本）对比一下， 如果版本不对就不调用 lsp-bridge-completion--record-items

理论上应该从根源上解决了问题， 但也许依然没有解决你的问题， 只能靠你继续反馈了， 我白天要开长途， 只能晚上回复了。

**Comment by AllTheLife** [comment]
依然没有解决这个问题😪，我都有点想重装系统了，就怕是硬件太弱的问题，重装也解决不了

试了一下在python端获取最新prefix，因为每次都要用elisp来获取，所以导致速度更慢了，甚至不如在elisp端过滤快

我再找找别的解决办法

**Comment by manateelazycat** [comment]
> acm-backend-lsp-candidates

你把 https://github.com/manateelazycat/lsp-bridge/blob/ba344368b4c669584a5adf63557754070b161e56/acm/acm.el#L439 这一行注释看一看， 看看会不会降低 acm-backend-lsp-candidates 调用次数？

**Comment by AllTheLife** [comment]
有一点点效果🤔，调用次数从八次落到了6次，每次按键将会使会函数被调用三次。

**Comment by manateelazycat** [comment]
我晚上在酒店理了一下逻辑， 应该是这样的：

我的电脑比较快， 所以每次LSP Server计算都非常快， 即使acm-backend-*-candidates 计算多次都不会发生 issue 的情况， 因为在我的电脑上acm-backend-lsp-items总是最新的。

在比较慢的电脑上， 理论上会发生这种情况： LSP server 计算很慢， 导致两次LSP Server计算之间， 其他补全后端比较快， 按照 lsp-bridge 的设计， 任何后端有数据更新后都可以随时调用 lsp-bridge-try-completion 函数， lsp-bridge-try-completion 函数会触发 acm-update 和 acm-backend-*-candidates 函数来重新计算所有后端的候选词， 但是这时候新的LSP补全候选词还没有返回新的候选词， 就会发生 issue 所说的 LSP 候选词和输入前缀不匹配的问题。

https://github.com/manateelazycat/lsp-bridge/commit/2801130a8632b334156af4c16e12c17685ef85c0 这个补丁的作用是给每个补全后端都引入缓存机制， 这样可以保证任何后端有新版补全数据时都可以实时更新 acm 补全菜单， 同时也不会导致其他后端重复计算。 这个补丁本质是进一步提升了 lsp-bridge 的性能。

要真正修复issue， 还需要 https://github.com/manateelazycat/lsp-bridge/commit/22428ddbf2a75f60db1b547ee85b308caacab347 这个补丁， 这个补丁的作用就是在 Elisp 端根据输入前缀过滤候选词， 因为根本原因还是 LSP Server 比其他补全后端的速度慢， 在 LSP Server 返回新的候选词结果之前， lsp-bridge Python 端没法介入， 只能在 Elisp 端处理。

你更新到最新版， 这个issue应该会被彻底修复。

**Comment by AllTheLife** [comment]
大佬太强了！这个问题解决了！🎆🎆🎆
