### ISSUE TITLE
Error running timer ‘acm-template-candidate-update’

### ISSUE THREAD

**Issue by Joxos** [manateelazycat/lsp-bridge#682]
# System
wsl 2 arch linux
# Lsp-bridge version
a3298566119606f84b640f767da6b4d535830d9c (Mon Jul 17 19:35:32 2023 +0800)
# Language Server
Jedi&Clangd (seems not to be their bugs since the messages are the same)
# Lsp-bridge Config (Tested with emacs -Q)
```elisp
(use-package markdown-mode
  :straight t
  :mode ("README\\.md\\'" . gfm-mode)
  :init (setq markdown-command "multimarkdown"))
(add-to-list 'load-path "~/.emacs.d/lsp-bridge/")
(use-package yasnippet
  :straight t
  :demand t
  :hook (after-init . delete-selection-mode)
  :config
  (require 'yasnippet)
  (yas-reload-all)
  (add-hook 'prog-mode-hook #'yas-minor-mode)
  (add-hook 'org-mode-hook #'yas-minor-mode))
(require 'lsp-bridge)
(setq lsp-bridge-python-lsp-server "jedi")
;; (setq acm-backend-lsp-enable-auto-import nil)
;; (define-key lsp-bridge-mode-map (kbd "RET") 'newline)
(global-lsp-bridge-mode)
```
# *Message*
```Error running timer ‘acm-template-candidate-update’: (wrong-number-of-arguments (((alpha . 0.9) (c2 . "#AAAAAA") (c1 . "unspecified-bg") t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8))) 0)```
# *lsp-bridge*
`Send textDocument/didChange notification to 'jedi' for project test.py
ERROR:epc:ReturnError([Symbol('wrong-number-of-arguments'), [[[Symbol('alpha'), Symbol('.'), 0.9], [Symbol('c2'), Symbol('.'), '#AAAAAA'], [Symbol('c1'), Symbol('.'), 'unspecified-bg'], True], [Symbol('r'), Symbol('g'), Symbol('b')], [Symbol('format'), '#%02x%02x%02x', [Symbol('ash'), Symbol('r'), -8], [Symbol('ash'), Symbol('g'), -8], [Symbol('ash'), Sy\
mbol('b'), -8]]], 0])`

**Comment by manateelazycat** [comment]
I think something wrong at https://github.com/manateelazycat/lsp-bridge/blob/a3298566119606f84b640f767da6b4d535830d9c/acm/acm-frame.el#L283

Can you tell me the value of below expression? 

```
(if (or force (equal (face-attribute 'acm-frame-default-face :background) 'unspecified))
                                 (face-attribute 'default :background)
                               (face-attribute 'acm-frame-default-face :background))
```

**Comment by Joxos** [comment]
I'm afraid that my emacs can't find `force`.

![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/339dfeb6-a600-455d-a69a-f9cc33b2c47f)

Perhaps I ignored sth, could you just explain it a little bit more clearly?

**Comment by AllTheLife** [comment]
Maybe U should print it in the function body, not in the scratch buffer.

`force` is an argument of `acm-frame-init-colors`

**Comment by manateelazycat** [comment]
> I'm afraid that my emacs can't find `force`.
> 
> ![image](https://user-images.githubusercontent.com/37507136/254240217-339dfeb6-a600-455d-a69a-f9cc33b2c47f.png)
> 
> Perhaps I ignored sth, could you just explain it a little bit more clearly?

Try 

```
(if (or (equal (face-attribute 'acm-frame-default-face :background) 'unspecified))
                                 (face-attribute 'default :background)
                               (face-attribute 'acm-frame-default-face :background))
```

**Comment by Joxos** [comment]
The value is `unspecified-bg`.

![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/8b1bfbc5-28d1-4264-93a2-0ca2fe9c8b4c)

![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/04871f70-6570-4f6b-a94d-47a796076f6c)

**Comment by manateelazycat** [comment]
What is value of `(face-attribute 'acm-frame-default-face :background)` ? And value of `(face-attribute 'default :background)`?

**Comment by Joxos** [comment]
Did you mean that i just put these in the function like this?

![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/00123fdd-4b0f-4357-a8b9-5bf0d8b56756)

It goes to

![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/df52d8ce-271c-4870-a295-bcf940ab2c25)

**Comment by Joxos** [comment]
![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/7e2805a1-a4aa-49a9-9cbc-a09c819023e8)

**Comment by Joxos** [comment]
![image](https://github.com/manateelazycat/lsp-bridge/assets/37507136/03935471-0a1d-4e65-978c-fa0733329c7b)

**Comment by manateelazycat** [comment]
I believe something wrong in your Emacs theme that throw unspecified-bg color

**Comment by Joxos** [comment]
Could you tell me your theme so that i can have a try on it?

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs
