### ISSUE TITLE
当调用注释函数时，诊断信息不会更新

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#683]
使用`-Q`测试
随便找一段python代码，在开头写上`import html`，因为只导入了没有使用会出现诊断信息，然后`M-x`直接调用`comment-line`把这行注释了，会发现如图诊断信息会一直存在。
同样调用其他类似的功能，比如`evilnc-comment-or-uncomment-lines`也是这样
但是如果手动在这一行开头加`#`，诊断信息就没了
估计是调用这些函数注释代码时没有向后端发送代码变更的请求
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/bd4936a8-29f1-47d4-8db7-28029013489b)

**Comment by manateelazycat** [comment]
已经修复了。
