### ISSUE TITLE
Issue with `acm-candidate-match-function` and `acm-lsp-candidate-min-length`

### ISSUE THREAD

**Issue by djs42012** [manateelazycat/lsp-bridge#684]
Hello,

Kudos on such a wonderful package.

There are two things which I am struggling to understand.

1) `acm-candidate-match-function` appears not to respect my configuration

In my config I've added:

```lisp
(after! acm
  (setq acm-candidate-match-function 'orderless-regexp))
```
Which does set the variable, but the completion style does not change at all.  For example, am trying to import from `'@herocions/react/20/solid'`and I would like to just be able to prompt by typing `icon`, to see the list of all icons, but I end up getting none because no exports actually begin with `icon`. I thought this is something orderless matching would address, but I tried every option for the variable and could not discern and different behavior. This is what leads me to the second point of confusion

2)  I assumed that since `acm-backend-lsp-candidate-min-length` is set to `0` that I would be able to just scroll through all of the options, but I am finding that I am not offered completion until I type the first character.

Am I missing anything with these two variables?

**Comment by manateelazycat** [comment]
You should use acm-filter M-u when acm popup menu.
