### ISSUE TITLE
lsp-bridge-get-project-path-by-filepath 没有生效

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/lsp-bridge#685]
如图定义了函数
```
(defun lsp-bridge-get-project-path-by-filepath (filename)
  (interactive)
  (expand-file-name (locate-dominating-file filename ".myproject")))
```
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/08748a4f-e428-4819-8201-7484d1295f82)

在`C:\Users\Administrator\temp\xx` 中创建文件`.myproject`
在`C:\Users\Administrator\temp\xx\kk`下创建`xx.py`文件
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/fe534bd2-a271-46da-a3ab-ffcc941351ea)

打开这个`xx.py`，手动执行函数
```
(lsp-bridge-get-project-path-by-filepath "xx.py")
(lsp-bridge-get-project-path-by-filepath ".")
```
都返回了.myproject文件存在的路径
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/938d2fa4-6485-4254-b3ca-0aa87d9621b7)

但是打开这个`xx.py`，`lsp-bridge`还是显示进入了单文件模式
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/ea87a48d-1464-4564-a3d4-2b12ef355692)

**Comment by manateelazycat** [comment]
这里的filename会传递文件的路径，你要测试全路径返回得目录是否是对的

**Comment by heheda123123** [comment]
> 
传全文件路径也这样
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/069f9f53-fb7f-465a-a37b-00d294b595b8)
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/c7c42125-101e-48cc-9616-5f1ffd452e3b)

**Comment by heheda123123** [comment]
好像是因为并没有调用这个函数，我在函数里加个message，打开一个py文件，并没有触发执行产生message
![image](https://github.com/manateelazycat/lsp-bridge/assets/97490782/dff78927-1bcd-4f6b-aea9-09e4f1e4b9a5)

**Comment by manateelazycat** [comment]
Python默认用的多服务器， 多服务器应该定制 lsp-bridge-get-multi-lang-server-by-project

**Comment by heheda123123** [comment]
可能我没有说清楚我的问题。现在`lsp-bridge`只把包含git文件的目录当作项目，但是有些源码没git文件，每次都要手动给他们创建一个git仓库。我就想自己定义一个标志代表这个目录是一个项目。类似于`projectile`里面放一个`.projectile`就代表这个目录是一个项目。
`lsp-bridge-get-multi-lang-server-by-project` 这个只是自定义语言服务器，应该解决不了这个问题吧

**Comment by manateelazycat** [comment]
lsp-bridge-get-project-path-by-filepath 是一个变量， 不是一个函数， 应该像下面这样来处理。

https://github.com/manateelazycat/lazycat-emacs/blob/db17495af970a6c3736c58a6bee27ef01af55daa/site-lisp/config/init-lsp-bridge.el#L113

**Comment by heheda123123** [comment]
> lsp-bridge-get-project-path-by-filepath 是一个变量， 不是一个函数， 应该像下面这样来处理。
> 
> https://github.com/manateelazycat/lazycat-emacs/blob/db17495af970a6c3736c58a6bee27ef01af55daa/site-lisp/config/init-lsp-bridge.el#L113

谢谢猫哥，这样定义解决我的问题了
```
(setq lsp-bridge-get-project-path-by-filepath
      (lambda (filepath)
        (when (locate-dominating-file filepath ".myproject")
	      (expand-file-name (locate-dominating-file filepath ".myproject")))))
```
