### ISSUE TITLE
Rust auto import 会把已有的 import 语句弄乱

### ISSUE THREAD

**Issue by HarumiKiyama** [manateelazycat/lsp-bridge#689]
### 问题描述
自动补全的时候，会把目前没有 import 进来的函数或者结构自动 import 进来，如果这时候已经 import 了同一目录下的函数或者结构
则会把原 import 语句弄乱掉。
原始的 `main.rs` 文件如下
```rust
use std::path::Path;

fn main{

    println!("Hello, world!");
}

```
自动 import 了 PathBuf 之后如下

```rust
use stdpaPath;path:{Path, PathBuf}:

fn main{
    let x = PathBuf("/");
    println!("Hello, world!");
}

```

### Emacs 配置文件
```elisp
(add-to-list 'load-path "/home/harumi/projects/lsp-bridge")
(package-initialize)

(require 'lsp-bridge)

(global-lsp-bridge-mode)
```

### Rust项目
使用 `cargo init test_lsp` 创建一个初始项目， 编辑其中的 `src/main.rs` 文件

### 日志输出
设置 `(setq lsp-bridge-enable-log t)` 之后接受到了大量的日志，无法正常使用 rust-analyzer 进行补全。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/d14083218a413c319084ab59b6792d6c6ab96bde

已经修复了， 重构引入的 bug
