### ISSUE TITLE
Issues with lsp-headerline-breadcrumb-mode Display

### ISSUE THREAD

**Issue by Jhonathan-Pedroso** [manateelazycat/lsp-bridge#691]
Hello,

I've been using the LSP-Bridge package for Emacs and I've come across an issue when trying to use the lsp-headerline-breadcrumb-mode.

When I enable lsp-headerline-breadcrumb-mode, instead of getting a breadcrumb trail showing the context within the file structure, all I see is a black shadow at the top of the buffer where the breadcrumb path should be.

I'm not sure if this is a problem with my configuration or if it's an issue with lsp-bridge itself. For comparison, when I use lsp-mode and enable lsp-headerline-breadcrumb-mode, I can see the file path breadcrumb as expected.

Do you have any suggestions on how to troubleshoot this, or could there be a potential issue with lsp-bridge's implementation of lsp-headerline-breadcrumb-mode? I'm looking forward to hearing your insights.

Thanks for your work on this package, it is an amazing experience!

**Comment by manateelazycat** [comment]
lsp-headerline-breadcrumb-mode is design for lsp-mode, I believe it can't works with lsp-bridge.

I don't like breadcrumb feature.

Anyway, if some developer implement breadcrumb feature for lsp-bridge, I will merged it.
