### ISSUE TITLE
Does lsp-bridge support hover-highlight feature? 

### ISSUE THREAD

**Issue by wd** [manateelazycat/lsp-bridge#694]
like this feature from lsp-mode
https://github.com/emacs-lsp/lsp-mode/blob/master/examples/sym_highlight.gif
https://github.com/emacs-lsp/lsp-mode/blob/master/examples/symbol-highlights.gif

**Comment by manateelazycat** [comment]
https://github.com/wolray/symbol - overlay is enough

**Comment by wd** [comment]
okay, the link is: https://github.com/wolray/symbol-overlay
