### ISSUE TITLE
Optionally distribute the Python files as a installable package?

### ISSUE THREAD

**Issue by rirze** [manateelazycat/lsp-bridge#696]
Hi,

As far I can tell, there's not an easy way to use virtual environments to employ the Python code in this library. If that's wrong, please correct me and ignore the rest of this issue.

Typically, I let this library use my global Python runtime and libraries, but it's a dependency hell waiting to happen. For example, latest Python release is 3.11 but PyPy only supports 3.10. My system is currently running at 3.11 but I would really prefer to run `lsp-bridge` within its own venv to gain the speed improvements of PyPy on 3.10. 

Distributing these files as a package would also enable using existing Python tooling such as `pipx` to isolate `lsp-bridge`'s dependencies from other packages'. 

Hopefully this makes sense as to why packaging the Python files a package would alleviate these issues. If you have a better solution, I would love to hear it.

**Comment by manateelazycat** [comment]
Maybe you can try https://github.com/manateelazycat/lsp-bridge/wiki/Python%20virtualenv

lsp-bridge use python multi-thread, python 3.11 is fast enough, same as pypy
