### ISSUE TITLE
Can't detect project root directory

### ISSUE THREAD

**Issue by damanis** [manateelazycat/lsp-bridge#698]
Single file mode works properly.
I try to set `(setq lsp-bridge-get-project-path-by-filepath (lambda (fname) (shell-command-to-string (concat "bash_script " fname))))`. The bash_script output is the path of existing directory, for example `/home/user/dir1`.
Problem: lsp-bridge init fails with error `no file or directory /home/user/dir1`.

**Comment by manateelazycat** [comment]
What's is content of bash_script?

**Comment by damanis** [comment]
For example:
```
#!/bin/bash
file=$(readlink -m $1)
echo "/$(echo $file | cut -d '/' -f 2,3,4)"
```

**Comment by manateelazycat** [comment]
(setq lsp-bridge-enable-log t)

then paste content of `*lsp-bridge*` buffer to me, thanks.

**Comment by damanis** [comment]
@manateelazycat 
I found the problem: bash script must use `echo -n` instead of `echo`.
Thank you for help (`*lsp-bridge*` helped).
