### ISSUE TITLE
Error: can't find command 'gopls' to start LSP server

### ISSUE THREAD

**Issue by pandaye** [manateelazycat/lsp-bridge#699]
I'm confident that I've already installed `gopls`, and the executable's path is in the `exec-path` of Emacs, but I still can't use lsp-bridge. Is additional configuration required for the path?
```
[LSP-Bridge] Error: can’t find command ’gopls’ to start LSP server gopls (/home/bogon/repos/awesomeGo/main.go), disable lsp-bridge-mode.
```
`exec-path` in Emacs：
```
> C-h v exec-path RET
```
```
exec-path is a variable defined in ‘C source code’.

Its value is
("/home/pandaye/lib/go/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin")
```
`gopls` path
```bash
$ which gopls
```
```
/home/pandaye/lib/go/bin/gopls
```
my config：
```emacs-lisp
(add-to-list 'exec-path "/home/pandaye/lib/go/bin")
(add-to-list 'load-path "~/.emacs.d/pkg/lsp-bridge")
(require 'lsp-bridge)
(global-lsp-bridge-mode)

```

**Comment by manateelazycat** [comment]
search goals in readme

**Comment by pandaye** [comment]
It hasn't taken full effect; there are two scenarios:
1. Starting Emacs from the command line： WORKS
2. Launching directly from the desktop： GET ERR

Also, I'm curious to know why it needs to be in ~/.local/bin?

**Comment by manateelazycat** [comment]
Because lsp-bridge backend is write by Python, Python search gopls from system bin directory.

**Comment by pandaye** [comment]
Got it, thank you. By the way, I wanted to ask if there are any plans to add a configuration option, or if it's possible to directly use Emacs's exec-path?

**Comment by manateelazycat** [comment]
> Got it, thank you. By the way, I wanted to ask if there are any plans to add a configuration option, or if it's possible to directly use Emacs's exec-path?

I have push new commit https://github.com/manateelazycat/lsp-bridge/commit/0f74bbf9d9497da005c4beddaf4193d4f780195f

That merged emacs' exec-path to Python's os.environ["PATH"]

You can try again after upgrade to newest version.
