### ISSUE TITLE
Is there support for LSP extensions, such as those provided by rust-analyzer?

### ISSUE THREAD

**Issue by Kenneth-Mata** [manateelazycat/lsp-bridge#703]
[Relevant link](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md)

**Comment by manateelazycat** [comment]
which protocol ？

**Comment by Kenneth-Mata** [comment]
jsonrpc still, but they use keys that are not part of the spec

**Comment by manateelazycat** [comment]
why a lsp client should support non-standard part?

if do, why need lsp?

**Comment by Kenneth-Mata** [comment]
To take full advantage of the lsp, is not as if they don't still have all the other default characteristics, however I understand how it can be unreasonable because it requires per language accomodations, it wasn't a demand, just an inquiry.
