### ISSUE TITLE
Cannot open load file: No such file or directory, acm-frame

### ISSUE THREAD

**Issue by knarkzel** [manateelazycat/lsp-bridge#704]
When I try installing `lsp-bridge`, I get no such file or directory `acm-frame`. I tried using it locally as well, but got same error. I'm on the latest emacs:
```
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
```
```elisp
(use-package lsp-bridge
  :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"))
```
```
⛔ Error (use-package): lsp-bridge/:catch: Cannot open load file: No such file or directory, acm-frame
```

**Comment by naoking158** [comment]
@knarkzel You need to specify a `:files` directive, e.g., `:files (:defaults "*.py" "acm/*" "core/*")`.

See `:files` section in below URL for more detail.
https://github.com/radian-software/straight.el#the-recipe-format

**Comment by knarkzel** [comment]
I will try that, thanks for the tip.

**Comment by knarkzel** [comment]
Are there other files I need? When running with `lsp-bridge`, I get errors like these:
```
Error in post-command-hook (lsp-bridge-monitor-post-command): (void-variable acm-backend-tabnine-cache-candiates)
```
After disabling `acm-enable-tabnine`, I get this:
```
Error in post-command-hook (lsp-bridge-monitor-post-command): (void-variable acm-backend-path-cache-candiates)
```
And when disabling `acm-enable-path`, I get same error message.

**Comment by mumu-lhl** [comment]
Try deleting the .elc and .eln files and disabling byte compile and native compile for lsp-bridge.

**Comment by knarkzel** [comment]
Nice, that actually fixed it. I deleted these folders:
- `~/.emacs.d/eln-cache`
- `~/.emacs.d/repos/lsp-bridge`
- `~/.emacs.d/straight/build-lsp-bridge`


Then used following configuration for `use-package` with `straight`:

```elisp
(use-package lsp-bridge
  :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge" :files (:defaults "*.py" "acm/*" "core/*") :build (:not compile))
  :init
  (global-lsp-bridge-mode))
```
