### ISSUE TITLE
(rust-analyzer) Disable inlay hints/type info?

### ISSUE THREAD

**Issue by jfaz1** [manateelazycat/lsp-bridge#712]
First, great job on this project, it's by far the fastest LSP client I've used! 

That being said, I'd like to disable type information/parameter hints, e.g. the gray text in the following image:

![image](https://github.com/manateelazycat/lsp-bridge/assets/56184947/228f0483-6383-4d63-a095-5828255a2ca0)

I've already set `lsp-bridge-user-langserver-dir` to a folder with its own `rust-analyzer.json` in there but it doesn't seem to be working. This is a feature in various LSP servers (e.g. C++), and in eglot for example you can do the following to disable it: `(add-hook 'eglot-managed-mode-hook (lambda () (eglot-inlay-hints-mode -1)))`.

Two questions:
- Do you think this feature should be enabled or disabled by default? If we disable it by default that'll (obviously) solve the issue for me :stuck_out_tongue: 
- Is it worth adding an `inlay-hint-mode` to `lsp-bridge` and use that to handle it per LSP server like eglot does?

Thanks!

**Comment by manateelazycat** [comment]
Hi, lsp-bridge haven't implement inlay hints highlight feature.

Can you use emacs -Q for test?

I guess you forgot turn off eglot/lsp-mode?

**Comment by manateelazycat** [comment]
@jfaz1 lsp-bridge newest version has implement inlay hint info, you can disable it by set `lsp-bridge-enable-inlay-hint` to nil.
