### ISSUE TITLE
请问如何在mode-line中显示诊断错误的数量？

### ISSUE THREAD

**Issue by stackcats** [manateelazycat/lsp-bridge#713]

**Comment by manateelazycat** [comment]
我平常不用 mode-line， 欢迎发送PR

**Comment by liuyinz** [comment]
@stackcats use [flymake-bridge](https://github.com/liuyinz/flymake-bridge)

**Comment by manateelazycat** [comment]
I just push commit https://github.com/manateelazycat/lsp-bridge/commit/1f763d25b0b417874d0f25bc9ca501d0e97da3a3

to add variable lsp-bridge-diagnostic-count, you can show lsp-bridge-diagnostic-count in mode-line.

Sorry, I don't use mode-line, any PR are welcome! ;)

**Comment by hyphenlee** [comment]
@liuyinz 亲测好用
