### ISSUE TITLE
lsp-bridge 不停地启动服务

### ISSUE THREAD

**Issue by AllTheLife** [manateelazycat/lsp-bridge#714]
今天更新了一下，发现如果在init时加载lsp-bridge，那么打开一个文件后，不停地移动光标，则会导致lsp-bridge不停地启动服务，消耗大量内存

回溯了一下，发现是 https://github.com/manateelazycat/lsp-bridge/commit/4045030476f98dab86ae239f0e5c1d05e9a2200f 导致的

已用 emacs -Q 测试过，麻烦大佬修复一下

环境
- Emacs 30
- Archlinux
- lsp-bridge 最新版
- dwm

**Comment by manateelazycat** [comment]
不会啊，你怎么重现的，我没有遇到过呀

**Comment by AllTheLife** [comment]
1. `git clone https://github.com/manateelazycat/lsp-bridge/ ~/lsp-bridge`
2. 
``` bash
echo "(add-to-list 'load-path \"~/lsp-bridge\")
(add-to-list 'load-path \"~/.emacs.d/site-lisp/extensions/yasnippet/\")
(add-to-list 'load-path \"~/.emacs.d/site-lisp/extensions/markdown-mode\")
(require 'yasnippet)
(yas-global-mode 1)

(require 'lsp-bridge)
(global-lsp-bridge-mode)
"  >> lsp-bridge-start.el
```
3. ~Emacs，启动！~ `emacs -q -l lsp-bridge-start.el ~/.emacs.d/init.el`
4. 不断地 `C-n` `C-p`
5. 问题出现

感觉我的环境被我折腾得比较特殊（捂脸），好多奇奇怪怪的bug会出现

**Comment by manateelazycat** [comment]
我确实没法重现

**Comment by AllTheLife** [comment]
Thanks anyway，我再看看吧

请问当初删掉`lsp-bridge-is-starting`这个变量是出于什么考虑呢？

**Comment by manateelazycat** [comment]
因为hola-layer加入后lsp-bridge就启动不了了。
