### ISSUE TITLE
no candidate popup shows up

### ISSUE THREAD

**Issue by braineo** [manateelazycat/lsp-bridge#715]
It has been a while since I updated lsp bridge. After I pulled 79a6609, diagnosis still works but auto completion stops working

`*lsp bridge*` buffer kept printing `ERROR:epc:ReturnError([Symbol('void-variable'), Symbol('acm-backend-path-cache-candiates')])` on receiving candidates from lsp

I took a brief look at the code, it seemed the variable was not used anywhere except

```lisp
;; lsp-bridge/acm/acm-backend-path.el:99

(acm-with-cache-candidates
   acm-backend-path-cache-candiates
   (when acm-enable-path
     acm-backend-path-items)))
```

I confirmed that a329856 was a working version

**Comment by mumu-lhl** [comment]
Wait for #716 to merge and pull it, then delete the elc and eln files related to lsp-bridge

**Comment by manateelazycat** [comment]
已经修复了。
