### ISSUE TITLE
how to disable status line on hover doc

### ISSUE THREAD

**Issue by shinhs0506** [manateelazycat/lsp-bridge#718]
as title

[](url)
![lsp-brirddge](https://github.com/manateelazycat/lsp-bridge/assets/51249639/162f7e99-bc0c-406c-9b58-fc7ede02e854)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/e37e962d108889fbba93c926788766f73aa54e6a/acm-frame.el#L182

mode-line has disable in acm frame.

Please use `emacs -Q` test.

**Comment by manateelazycat** [comment]
I can't reproduce this, please use emacs -Q to test it.

Please re-open this issue if you still have problem use emacs -Q.
