### ISSUE TITLE
python utf-8编码含中文导致补全不起作用

### ISSUE THREAD

**Issue by lynnux** [manateelazycat/lsp-bridge#72]
终于重现中文函数名问题了，环境win7 python3.8，要求打开的py文件事先含中文，然后补全完全不起作用，lsp bridge buffer报错：
```
--- Send notification: initialized

--- Send notification: workspace/didChangeConfiguration
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\lsp-bridge\core\lspserver.py", line 229, in lsp_message_dispatcher
    self.handle_send_notification(*message["content"])
  File "c:\Users\Administrator\Desktop\lsp-bridge\core\lspserver.py", line 488, in handle_send_notification
    self.send_did_open_notification(self.first_file_path)
  File "c:\Users\Administrator\Desktop\lsp-bridge\core\lspserver.py", line 260, in send_did_open_notification
    "text": f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 81: illegal multibyte sequence

--- Recv notification: window/logMessage
```
定位到代码：
![图片](https://user-images.githubusercontent.com/367894/168422256-2d72418e-5629-4898-8964-e7b893fb717b.png)
如果新建一个文件，然后写入中文是可以正常补全的。如果文件内容已存在中文再打开，那么上面send_did_open_notification里open就会出错，py用gbk编码去解码utf-8编码失败，然后导致这个线程挂了所以就没有补全了？
我太菜了不知道咋解决呀，看eglot的`eglot--signal-textDocument/didOpen` > `eglot--TextDocumentItem`是直接从emacs获取内容，emacs当然能处理编码，但python的话我也不太熟等大佬解决了
另外，py这边直接open没考虑编码的还有几处：
![图片](https://user-images.githubusercontent.com/367894/168422537-6d89642f-2573-40f0-b742-dc6e82adcefd.png)

**Comment by manateelazycat** [comment]
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 81: illegal multibyte sequence

我没有Windows, 但是强烈建议你让你的系统默认使用 utf-8 编码，不想再和Windows编码做斗争。

你可以尝试在 open(file, encoding='UTF-8') 这种方式看看能不能解决你的问题。

如果不行，我建议你换支持 utf-8 的操作系统，个人精力有限，不想去为兼容性花时间。

**Comment by zy9306** [comment]
试下 open(filepath, encoding="utf-8") 吧，我的 windows 能复现你的情况，加了之后就好了

**Comment by lynnux** [comment]
新提交一个pr可以解决这个问题。只是将就够用，能识别utf-8(include bom)，更多编码可能就需要第三方库了如chardet。

**Comment by manateelazycat** [comment]
> 试下 open(filepath, encoding="utf-8") 吧，我的 windows 能复现你的情况，加了之后就好了

@lynnux 这种方法在你的系统上不行吗？

**Comment by lynnux** [comment]
> 

可以，但是这就限定了文件编码必须是utf-8啊。这win7 python3.8看来是默认open用gbk编码了，windows上cpp开发尤其是msvc默认编码就不是utf-8的。
刚才试了`open(filepath, encoding="utf-8")`打开一个gbk编码的py文件提示：`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 54: invalid continuation byte`
然后又测试了下`tokenize.open`，也提示`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 54: invalid continuation byte`，我去，看来pr没解决问题啊，对gbk没用。汗~~

**Comment by manateelazycat** [comment]
> > 
> 
> 可以，但是这就限定了文件编码必须是utf-8啊。这win7 python3.8看来是默认open用gbk编码了，windows上cpp开发尤其是msvc默认编码就不是utf-8的。 刚才试了`open(filepath, encoding="utf-8")`打开一个gbk编码的py文件提示：`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 54: invalid continuation byte` 然后又测试了下`tokenize.open`，也提示`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 54: invalid continuation byte`，我去，看来pr没解决问题啊，对gbk没用。汗~~
> 
> 要不上第三方chardet自动识别编码？ 还有个symbol rename也是要open操作文件的，估计也会有编码问题。

你都用Emacs了，为啥不能强制编码 utf-8 ? 整个世界都在用 utf-8, 为啥要折腾 gdk 呢？

**Comment by manateelazycat** [comment]
> chardet

chardet 这个库只是概率，不要期望它能解决所有编码问题。

还是我的建议，默认用 utf-8 编辑文件，Emacs可以在Windows平台强制用 utf-8 打开的。
