### ISSUE TITLE
Are there any plans to separate the python LSP client into a library?

### ISSUE THREAD

**Issue by aspizu** [manateelazycat/lsp-bridge#720]
It would be nice if the python LSP client could be used stand-alone.

**Comment by manateelazycat** [comment]
I haven't time do that.

Anyway, you can read my blog https://manateelazycat.github.io/2022/05/12/lsp-bridge/ to know how to write a LSP client.

You need use Google translate to read my blog. ;)

**Comment by aspizu** [comment]
Thank you.
