### ISSUE TITLE
Code lens support

### ISSUE THREAD

**Issue by ezemtsov** [manateelazycat/lsp-bridge#721]
Does lsp-bridge in current state support code lens?
If not, is it a planned feature?

It's quite useful for frameworks like F# where majority of people rely on type inference

**Comment by manateelazycat** [comment]
Sorry, I haven't time on it.

Any PR are welcome. ;)

**Comment by ezemtsov** [comment]
Closing the issue as there's no plan to implement it for now

**Comment by manateelazycat** [comment]
@ezemtsov Maybe you want is lsp-bridge-peek ;)
