### ISSUE TITLE
Support passing environment onto lsp server

### ISSUE THREAD

**Issue by Eising** [manateelazycat/lsp-bridge#723]
Hi,

With some of the other emacs lsp implementations, the local environment is passed on to the LSP server.
In my example, I use an .envrc file to set my PYTHONPATH in a project. This should be passed on the pylsp through the emacs equivalent envrc module. This works with eglot and emacs-lsp.

Would it be possible to make this work with lsp-bridge too?

**Comment by manateelazycat** [comment]
I don't quite understand what you mean, you mean all environment variables that Emacs can recognize are passed to the lsp server?

**Comment by manateelazycat** [comment]
Python will pass env to lsp server default.

Please let me know if you still have issue.

**Comment by Eising** [comment]
Hi, sorry for missing your reply.

I did some testing and indeed my environment was there in the `lspserver.py` script.

Oddly enough, the LSP itself is not picking up the $PYTHONPATH env variable I had set, and I haven't been able to find out why.

**Comment by manateelazycat** [comment]
Did you try pyright ?
