### ISSUE TITLE
lsp-bridge-find-def 能不能检查隔壁的窗口就是要跳转的目标窗口？

### ISSUE THREAD

**Issue by getong** [manateelazycat/lsp-bridge#727]
我刚才试过lsp跳转，如果目标文件就是在隔壁窗口的文件，就直接跳转到隔壁窗口文件，而不是重新打开一个新的buffer。

就是 lsp-ui-peek--goto-xref-other-window 这样的效果。

**Comment by manateelazycat** [comment]
最近比较忙， 可能要过段时间才有空。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/a6b83b6fa35f352d08b073ff2a8843b1bf011b34

已经加了一个选项， 你设置一下 lsp-bridge-find-def-select-in-open-windows 选项就好了。
