### ISSUE TITLE
lsp-bridge-popup-documentation 只显示部分文档

### ISSUE THREAD

**Issue by spcmxxd** [manateelazycat/lsp-bridge#730]
![image](https://github.com/manateelazycat/lsp-bridge/assets/119666897/fe5469b8-1b14-4eaf-8331-bd031121f3de)

MacOS 13.3, Emacs 29.1

使用 lsp-bridge-popup-documentation 命令查看函数文档时，只显示部分文档

**Comment by manateelazycat** [comment]
有滚动按键的，看文档吧
