### ISSUE TITLE
Windows安装的python不一定含有python3.exe

### ISSUE THREAD

**Issue by WoofZJ** [manateelazycat/lsp-bridge#732]
从python.org下载exe安装的python，解释器只有python.exe（3.11、3.12）
![image](https://github.com/manateelazycat/lsp-bridge/assets/138768364/c3596432-fc56-445e-b864-198c024a6052)

[这里](https://github.com/manateelazycat/lsp-bridge/blob/31281b0e884ee019b12f1f1346fa77b8125b84d2/lsp-bridge.el#L323C62-L323C62)
会导致lsp-bridge找不到解释器（即使python.exe存在于path中）

![image](https://github.com/manateelazycat/lsp-bridge/assets/138768364/f20a103d-a1e3-486b-b4ac-c004c808a84e)
![image](https://github.com/manateelazycat/lsp-bridge/assets/138768364/287eaa0a-adcb-40a6-abd5-f3058f7dd7dc)

需要手动加个python3别名才能正常运行

![image](https://github.com/manateelazycat/lsp-bridge/assets/138768364/d239836c-d3d3-489e-87ea-67ae501020c3)
![image](https://github.com/manateelazycat/lsp-bridge/assets/138768364/13e31d1e-423e-4f31-892e-5883acbcf02a)

**Comment by manateelazycat** [comment]
更新最新版试一下吧。
