### ISSUE TITLE
Way to use tabnine as the default language server for all supported files?

### ISSUE THREAD

**Issue by fktpp2022** [manateelazycat/lsp-bridge#733]
I am used to use company-tabnine as my default completer for all kind of files. The thing has an advantage of not need to install and maintain all kinds of language server by hand.

Is it possible to make lsp-bridge work like this:?

1. install and enable lsp-bridge
2. enable tabnine
3. make tabnine as the default lsp server for all type of files.

**Comment by manateelazycat** [comment]
I guess you just need add target mode in lsp-bridge-default-mode-hooks ?

**Comment by fktpp2022** [comment]
I can not find a good hook for fundamental modes, and generic-x modes. I am now live with following code snip:

`(require 'lsp-bridge)

(define-globalized-minor-mode lsp-bridge-global-mode lsp-bridge-mode lsp-bridge-mode-on)

(defun lsp-bridge-mode-on ()
  (interactive)

  (when (and (lsp-bridge--not-mind-wave-chat-buffer)
	     (lsp-bridge--not-acm-doc-markdown-buffer))
    (lsp-bridge-mode 1)))


(lsp-bridge-global-mode t)
`

**Comment by fktpp2022** [comment]
After this change, I got lsp-bridge-mode enabled every where. But when there's a mode that have a predefined language-server failed to started. Tabnine will not work either.

e.g. Say I opened a file with .sh extsion, and lsp-bridge will try to launch `bash-language-server`. But I don't have it, then lsp-bridge will be disabled. And I can not get completion from Tabnine in this file.

**Comment by manateelazycat** [comment]
I will write some code in this weekend with Chinese time. ;)

**Comment by manateelazycat** [comment]
Hi @fktpp2022 

I just commit https://github.com/manateelazycat/lsp-bridge/commit/64f3ad34be4f2248b3a6bc9db1fe6256ab56f271 , can you update to newest version and try?

You can enable lsp-bridge-mode in any mode, and turn on option `acm-enable-tabnine`, TabNine and other non-lsp backend still can works even lsp server command not install.

![截图 2023-10-20 21-04-36](https://github.com/manateelazycat/lsp-bridge/assets/237487/6d8eab62-087d-43c5-b6af-5c601c96026f)

**Comment by fktpp2022** [comment]
I have to say, it works great!!!
