### ISSUE TITLE
Typescript/eslint help please

### ISSUE THREAD

**Issue by claidler** [manateelazycat/lsp-bridge#734]
I'm struggling to get typescript and eslint errors to be checked on my system. It seems typescript errors are showing up, but eslint ones are not and I'm not sure why. 
Could you please give me some steps to debug this issue? I've installed vscode-langservers-extracted globally - I thought that would be enough?
Are there any checks I can do to figure out the issue?
Flycheck has a function to call to check for setup issues, which I find very useful.
I'm new to emacs, FYI. I've tried it 3 times now, and have been using it for around a month at this point and enjoying it. This package is fantastic. Thank you for your work.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge#report-bug

**Comment by claidler** [comment]
Yeah I think related to this:
https://github.com/volta-cli/volta/issues/1119
I'll try removing Volta for nvm

**Comment by claidler** [comment]
actually this setting is for if an installed eslint can't be detected
