### ISSUE TITLE
如何在编辑本地文件的同时使用远程lsp server？

### ISSUE THREAD

**Issue by Yatogaii** [manateelazycat/lsp-bridge#735]
比如我本地有一个main.c，我想使用服务器A上的clangd来补全，如何配置呢？

**Comment by manateelazycat** [comment]
你直接把文件上传到服务器a上，lspbridge支持远程编辑和补全

**Comment by manateelazycat** [comment]
从LSP协议的设计上， LSP Server必须跟源代码文件在一个地方才行。

本地 lsp server 支持本地源代码， 远程 lsp server 支持远程源码， 这样才行， 要不是 lsp server 没法支持跨域分析大量文件。
