### ISSUE TITLE
TypeError("unhashable type: 'list'") when opening file with recentf

### ISSUE THREAD

**Issue by triHims** [manateelazycat/lsp-bridge#740]
Emacs 28.2
python3.11 system. Trying to work with javascript typescript react project.

`Eval in Emacs: (lsp-bridge--first-start '53595)
ERROR:epc:TypeError("unhashable type: 'list'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/himanshu/.local/lib/python3.11/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/himanshu/.local/lib/python3.11/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/himanshu/.local/lib/python3.11/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
                           ^^^^^^^^^^^
  File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/lsp_bridge.py", line 756, in _do
    getattr(getattr(self, obj_name), name)(*args, **kwargs)
  File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/core/search_file_words.py", line 43, in index_files
    self.search_files.add(filepath)
TypeError: unhashable type: 'list'
Eval in Emacs: (message '"[LSP-Bridge] Start LSP server (javascript) for /run/media/himanshu/New_Volume/Projects/Python/gig-enrich-data-apollo-storeleads/automation-dashboard...")
Eval in Emacs: (message '"[LSP-Bridge] Start LSP server (javascript) for /run/media/himanshu/New_Volume/Projects/Python/gig-enrich-data-apollo-storeleads/automation-dashboard with 'project' mode, enjoy hacking!")
`

**Comment by manateelazycat** [comment]
can you give me code to test this issue? thanks

**Comment by triHims** [comment]
I get this error when ever lsp-bridge starts

**Comment by triHims** [comment]
More errors from the same library 
`ERROR:epc:TypeError('SearchFileWords.close_file() takes 2 positional arguments but 3 were given')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/himanshu/.local/lib/python3.11/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/himanshu/.local/lib/python3.11/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/himanshu/.local/lib/python3.11/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
                           ^^^^^^^^^^^
  File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/lsp_bridge.py", line 756, in _do
    getattr(getattr(self, obj_name), name)(*args, **kwargs)
TypeError: SearchFileWords.close_file() takes 2 positional arguments but 3 were given`

**Comment by manateelazycat** [comment]
> More errors from the same library `ERROR:epc:TypeError('SearchFileWords.close_file() takes 2 positional arguments but 3 were given') ERROR:epc:Unexpected error Traceback (most recent call last): File "/home/himanshu/.local/lib/python3.11/site-packages/epc/handler.py", line 242, in _handle reply = handler(uid, *args) ^^^^^^^^^^^^^^^^^^^ File "/home/himanshu/.local/lib/python3.11/site-packages/epc/utils.py", line 51, in new_method ret = method(self, *args, **kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/himanshu/.local/lib/python3.11/site-packages/epc/handler.py", line 265, in _handle_call return ['return', uid, func(*args)] ^^^^^^^^^^^ File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/lsp_bridge.py", line 756, in _do getattr(getattr(self, obj_name), name)(*args, **kwargs) TypeError: SearchFileWords.close_file() takes 2 positional arguments but 3 were given`

What value of `buffer-file-name` in https://github.com/manateelazycat/lsp-bridge/blob/61b2bcb841c1e1f14aafdb9b9371fe1613aa4f63/lsp-bridge.el#L1070 ?

**Comment by triHims** [comment]
`
#("/run/media/himanshu/New_Volume/Projects/Python/StartPanel/Proximity/CreateProximity.jsx" 0 34
  (face ido-vertical-first-match-face)
  34 35
  (face
   (ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-match-face))
  35 164
  (face ido-vertical-first-match-face)
  164 165
  (face
   (ido-vertical-first-match-face ido-vertical-match-face ido-vertical-first-match-face))
  165 167
  (face
   (ido-vertical-first-match-face ido-vertical-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-match-face ido-vertical-first-match-face ido-vertical-match-face ido-vertical-first-match-face))
  167 168
  (face
   (ido-vertical-first-match-face ido-vertical-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-first-match-face ido-vertical-match-face ido-vertical-first-match-face)))
`

**Comment by triHims** [comment]
If you could guide me on where should i start to chase with recentf issue ?

**Comment by manateelazycat** [comment]
Looks some plugin of your emacs  attach face property to var buffer-file-name, I have push commit https://github.com/manateelazycat/lsp-bridge/commit/2ec86505ac04d50db8efd97ff95ec9c0dcc9ba36

You can update to newest and try again. ;)

**Comment by triHims** [comment]
Affirmative . 
The issue is now fixed.
Thank you very much

**Comment by manateelazycat** [comment]
You're welcome, enjoy lsp-bridge. ;)

**Comment by triHims** [comment]
Hey i get similar error when restarting lsp server 
    self.search_files.add(filepath)
TypeError: unhashable type: 'list'
Maybe unsanitized file is passed to this function too.

**Comment by manateelazycat** [comment]
> Hey i get similar error when restarting lsp server self.search_files.add(filepath) TypeError: unhashable type: 'list' Maybe unsanitized file is passed to this function too.

Can you add `(print "**** ", filepath)` before self.search_files.add(filepath), then paste log here, I need confirm filepath content before send fix patch.

**Comment by triHims** [comment]
thanks will do

**Comment by triHims** [comment]
['/run/media/himanshu/New_Volume/Projects/Python/gig-enrich-data-apollo-storeleads/app/schedular/storeleads_scrap_schedular/dropcontact_helper.py', 0, 39, [Symbol('face'), Symbol('ido-vertical-first-match-face')], 39, 42, [Symbol('face'), [Symbol('ido-vertical-first-match-face'), Symbol('ido-vertical-first-match-face'), Symbol('ido-vertical-match-face'), Symbol('ido-vertical-match-face'), Symbol('ido-vertical-match-face'), Symbol('ido-vertical-first-match-face')]], 42, 143, [Symbol('face'), Symbol('ido-vertical-first-match-face')]]

**Comment by manateelazycat** [comment]
@triHims I have push https://github.com/manateelazycat/lsp-bridge/commit/881b0ef6da0b6641c170eb29aa69f378538904b5 , you can try it .

**Comment by triHims** [comment]
Affermative , works nice.
Thank you very much.
