### ISSUE TITLE
Huge memory consumption when doing package upgrade

### ISSUE THREAD

**Issue by fktpp2022** [manateelazycat/lsp-bridge#742]
When doing package update, my laptop was frozen because some abnormal memory consumption. It turns out to be the lsp-bridge python server that is holding too much memory. And it will not release the memory after package upgrade is done, until I killed the emacs process by `M-x kill-emacs` command.

Way to reproduce:

1. Setup lsp-bridge
2. M-x list-packages
3. U (mark upgradeable packages, magit on melpa is frequently upgrades nowadays)
4. x (perform the upgrade)
5. Wait for memory to be consumed by the lsp-bridge python server.

**Comment by manateelazycat** [comment]
What's name of upgrade package?

**Comment by manateelazycat** [comment]
why its a bug of lsp-bridge？

**Comment by fktpp2022** [comment]
maybe lsp-bridge should ignore the buffers that package

**Comment by fktpp2022** [comment]
reopen, for I closed it by mistake

**Comment by manateelazycat** [comment]
I don't use magit or melpa, I use git submodule package my Emacs plugin.

PR are welcome if you know something wrong in lsp-bridge.

**Comment by manateelazycat** [comment]
My suggestion, execute lsp-bridge-kill-process before magit operation, execute lsp-bridge-restart-process after magit finish.

**Comment by manateelazycat** [comment]
I don't use magit, and I won't fix this, I even think it's not bug of lsp-bridge.

Sorry.
