### ISSUE TITLE
Javascript react completions stop working; Error: missing 1 required positional argument: 'version'

### ISSUE THREAD

**Issue by triHims** [manateelazycat/lsp-bridge#744]
Hi ,
When working with javascript react project i am facing the problem that after sometime , lsp does not provide any completions definitions or diagnostics.
I have to run lsp-bridge-restart-process to run it properly again.

How should i debug this ?
i use lsp-bridge-complete-manually
and call lsp-bridge-popup-complete-menu everytime i need completions.

**Comment by web10crown** [comment]
@triHims can you provide a screenshot please

**Comment by triHims** [comment]
Here are more details .
This problem start after i get this error in the log.
Traceback (most recent call last):
  File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/lsp_bridge.py", line 490, in event_dispatcher
    getattr(self, func_name)(*func_args)
  File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/lsp_bridge.py", line 741, in _do
    action.call(name, *args)
  File "/home/himanshu/.config/emacs/custom-packages/lsp-bridge/core/fileaction.py", line 163, in call
    getattr(self, method)(*args, **kwargs)
TypeError: FileAction.try_completion() missing 1 required positional argument: 'version'

**Comment by triHims** [comment]
@web10crown 
i do not know if screenshot will convey the issue properly .
here is the screen cast of the issue 
[](https://streamable.com/og2m8n)

**Comment by triHims** [comment]
My lisp is not very good but it seems we are not passing version here . 
https://github.com/manateelazycat/lsp-bridge/blob/0b30d95c6de95b150d93ecee325b95e04ff09e46/lsp-bridge.el#L1164

**Comment by manateelazycat** [comment]
@triHims I have commit https://github.com/manateelazycat/lsp-bridge/commit/b4c386747008b2a581787e55a7524c1cacf9b898

Can you upgrade to newest version and test again? Thanks.

**Comment by triHims** [comment]
Perfect thanks
