### ISSUE TITLE
plistp does not exist in emacs 28.3 

### ISSUE THREAD

**Issue by triHims** [manateelazycat/lsp-bridge#746]
plist used here https://github.com/manateelazycat/lsp-bridge/blob/b4c386747008b2a581787e55a7524c1cacf9b898/lsp-bridge-code-action.el#L354
does not exist in 28.3
https://github.com/emacs-mirror/emacs/blob/a44d906740f0d8b2b1f1b4db4f1cce88f4832692/lisp/subr.el#L3747
If possible please replace it.
This breaks code actions for me.
Thanks.

**Comment by triHims** [comment]
maybe this will work 
(generated by chatgpt)
(defun my-plistp (object)
  (and (listp object)
       (cl-every #'keywordp object)
       (cl-evenp (length object))))

**Comment by manateelazycat** [comment]
Update to newest version, and try agian. ;)

**Comment by triHims** [comment]
nice.

**Comment by triHims** [comment]
I am enjoying this plugin more and more.
