### ISSUE TITLE
omnisharp autocomplete not working properly

### ISSUE THREAD

**Issue by serezlan** [manateelazycat/lsp-bridge#747]
Hi,

I'm interested in lsp-bridge after watching the presentation. So far I found that the autocomplete response is quite fast and I enjoy it.
However I found problem which prevent me from using it in my daily workflow.

Provblem:

Autocomplete not working after on some scenario.

Steps to reproduce:

- create empty console project
- open Program.cs 
- on the top file, type "using System."
Expected behavior:

- popup appears with list of suggestions

Actual behavior:

- no suggestion appear

System:

- ubuntu 22.04
- emacs 28.2
- omnisharp-roslyn dotnet-core v 1.39.102

If you need another information, please let me know.

Thx

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge#report-bug

**Comment by serezlan** [comment]
Hi,

this is my lsp-bridge output. 
I cut some in the middle to make it brief.
It appears it tried to scan and open every csproj in my  drive. Is this normal?

Also found this in messages buffer. Not sure if it's related

or: Wrong type argument: lsp-bridge-epc-manager, nil

**Comment by manateelazycat** [comment]
where is output log?

did you test with emacs -Q ?

**Comment by serezlan** [comment]
it's working after using "emacs -q"
I think there are conflict with my existing config.

However I still found problem that the autocomplete suggestion is not shown.
using simple console app I type this line:

Console.WriteLine("foo");


Both "Console" and "WriteLine" suggestion are not shown but the log has them sent by omnisharp.
[lsp-bridge.zip](https://github.com/manateelazycat/lsp-bridge/files/13194301/lsp-bridge.zip)
b

**Comment by manateelazycat** [comment]
From log content, Console not return completion is lsp server not response when you type "Console", I don't know why omnishapre lsp server don't return completion result to lsp-bridge.

**Comment by serezlan** [comment]
I tried another experiment and found these lines log 

Line 1023310

"Item1": 61,
            "Item2": 48,
            "$$__handler_id__$$": "7595a31e-7b8c-4800-99b6-525e06a92148"
         }
      },
      {
         "label": "WriteLine",
[lsp-bridge-2.zip](https://github.com/manateelazycat/lsp-bridge/files/13197737/lsp-bridge-2.zip)

         "kind": 2,
         "detail": "",
         "in

cmiiw, that is omnisharp response for the completion request.

**Comment by manateelazycat** [comment]
lsp-bridge has support csharp-ls, csharp-ls is better way, you can try it. ;)

**Comment by serezlan** [comment]
* Autocopletion not working properly

Hi,

I revisit lsp-bridge today and still found autocompletion not working as expected.
I use both omnisharp-dotnet and csharp-ls with similar result. The latter give slightly better result occasionally.
The test is run with simple hello world program to minimize variables.
Is there additional config that I missed?

** Correct candidate is not the first  choice
for example I type "Cons"  the the first suggestion is "char ". The correct suggestion is not at first choice.
** None of the completion is correct
For example, I type certain variable "delt". I expect to have "delta" as main suggestion but none of the suggestions is valid.

My active modes are:

Minor modes enabled in this buffer: Auto-Save Font-Lock Lsp-Bridge
Undo-Tree

The major mode is C#//l mode defined in csharp-mode.el:

I attached *lsp-bridge* output and my sample project.
Please let me know if there's anything else needed to debug this issue.
It'll be great if I can use lsp-bridge to access my project remotely.

Thx.
[sample-project.zip](https://github.com/user-attachments/files/18219135/sample-project.zip)
[lsp-bridge.zip](https://github.com/user-attachments/files/18219137/lsp-bridge.zip)

**Comment by manateelazycat** [comment]
I have check your lsp-bridge.txt, I saw completion response at line 19956, I guess you turn on option lsp-bridge-enable-log that cause lsp-bridge too slow?

Can you turn off option lsp-bridge-enable-log (set it to nil), and try again?

Sorry, I haven't omnisharp env to test your project.

**Comment by serezlan** [comment]
I don't understand.. I had it turned off earlier with same result :) 
anyway.. it's working fine now. Much smoother even on my old laptop.
thx
