### ISSUE TITLE
changeWorkingDirectory: inappropriate type (Not a directory)

### ISSUE THREAD

**Issue by Doodler8888** [manateelazycat/lsp-bridge#748]
I'm  trying to use lsp-bridge with haskell, but i have this error:

*_[LSP-Bridge] Error on initialize: *"file path"*: changeWorkingDirectory: inappropriate type (Not a directory)_*

I have zero experience with haskell and emacs, but i've also tried to use lsp-mode, eglot and neovim's built-in lsp client on the same haskell projects/files and everything works correctly. I've also tried to use lsp-bridge with a go project. Again, everything was fine. In every instance 'haskell-language-server-wrapper' was attached. 

I'm using the latest emacs version.
This is the current configuration:

  ```
  (use-package lsp-bridge
    :elpaca '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"
			:files (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
			:build (:not compile))
    :init
    (global-lsp-bridge-mode))

  (use-package haskell-mode)
  (use-package go-mode)
  (use-package markdown-mode
    :ensure t
    :mode ("README\\.md\\'" . gfm-mode)
    :init (setq markdown-command "multimarkdown")
    :bind (:map markdown-mode-map
	  ("C-c C-e" . markdown-do)))

  (use-package yasnippet
    :config
    (yas-global-mode 1))

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge#report-bug

**Comment by manateelazycat** [comment]
![截图 2023-10-24 00-48-15](https:github.com/manateelazycat/lsp-bridge/assets/237487/29e9e77c-786d-461e-a15a-420a0ea50671)

This is because the Haskell LSP Server does not support single-file mode, and in order for lsp-bridge to work, you should put the Haskell project into the git project, and when lsp-bridge recognizes the root of git, it will work automatically
