### ISSUE TITLE
Copilot problems with copilot-node-server

### ISSUE THREAD

**Issue by Moerliy** [manateelazycat/lsp-bridge#749]
Copilot isn't working for me. My guess is its a problem with the copilot-node-serve npm packaga. 

The message I get displayed in the \*lsp-bridge\* buffer:
```

--- [22:34:00.543649] Send initialize request (21862) to 'copilot' for project copilot_backend

--- [22:34:00.543798] Send setEditorInfo request (54216) to 'copilot' for project copilot_backend

--- [22:34:00.543854] Send signInInitiate request (55509) to 'copilot' for project copilot_backend
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/copilot-node-server/copilot/dist/agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.0

--- [22:34:00.572896] LSP server 'copilot' exited with code 1
b''

```

**Comment by manateelazycat** [comment]
@kongds Can you help to answer this issue? Thanks. ;)

**Comment by kongds** [comment]
It looks like you npm can't find copilot.
Do you install copilot via `npm install -g copilot-node-server`?

**Comment by Moerliy** [comment]
> Do you install copilot via `npm install -g copilot-node-server`?

Yes. And in the terminal I can use copilot-node-server like expected. 
'copilot-node-server --version' works for an example.

**Comment by kongds** [comment]
Can you find directory `copilot-node-server` in global root (base) directory (return in `npm root -g`)?
``` bash
npm root -g
ls `npm root -g`/copilot-node-server
```

**Comment by Moerliy** [comment]
Hmm ok. I just tried it on another machine and it worked. I will investigate and come back to it when I can play around with my broken one.

**Comment by Moerliy** [comment]
All righ. The problem was pnpm and me having it aliased to npm. After I installed the npm module with the real /bin/npm it worked. Thanks for the quick help.
