### ISSUE TITLE
Question: can `lsp-bridge` show the function's `arguments` and `return type` in completion menu?

### ISSUE THREAD

**Issue by eval-exec** [manateelazycat/lsp-bridge#761]
For example, I typed `n.che`:
![image](https://github.com/manateelazycat/lsp-bridge/assets/46400566/89cb9e4e-0bd6-4564-a280-5f5416f2f047)

The lsp-bridge currently suggested:
`checked_add(...)                                             Method`, which is exactly what I want.

However I would like it to be displayed as:
`checked_add(&self, duration: Duration) -> Option<Instant>    Method`.

Is it possible for the lsp-bridge to achieve this?

**Comment by manateelazycat** [comment]
Please add (message "%s" candidates) in function lsp-bridge-completion--record-items

I suspect that the only "..." in candidate returned by the lsp server, 
and not include function arguments.

Or it's rust lsp server default value, I remember Java lsp server will include function argument in candidate.

**Comment by eval-exec** [comment]
When I type `checked_add`I got this:
```
evil-forward-char: End of line
((:key checked_add(…)_fn(&self, Duration) -> Option<Instant> :icon method :label checked_add(…) :display-label checked_add(…) :deprecated nil :insertText nil :insertTextFormat 2 :textEdit (:range (:start (:line 11 :character 5) :end (:line 11 :character 15)) :newText checked_add($0)) :sortText ffffffef :server rust-analyzer :backend lsp :additionalTextEdits nil))
((:key checked_add(…)_fn(&self, Duration) -> Option<Instant> :icon method :label checked_add(…) :display-label checked_add(…) :deprecated nil :insertText nil :insertTextFormat 2 :textEdit (:range (:start (:line 11 :character 5) :end (:line 11 :character 16)) :newText checked_add($0)) :sortText ffffffef :server rust-analyzer :backend lsp :additionalTextEdits nil))
Saving file /tmp/rust-playground/at-2023-11-03-160621/src/main.rs...
```

**Comment by manateelazycat** [comment]
@eval-exec I have push https://github.com/manateelazycat/lsp-bridge/commit/2d6ca132623b7fa514819e65a7d1d524fea4b7bb

You can update to newest version and try again. ;)

**Comment by eval-exec** [comment]
Thank you, it's awesome.
![image](https://github.com/manateelazycat/lsp-bridge/assets/46400566/87cfa3b6-e344-4bd6-adcc-58c789ebc5ce)

Can I modify the value of `display_label_max_length` to prevent truncation of the candidates?  (The second candidates was truncated

**Comment by manateelazycat** [comment]
I have push https://github.com/manateelazycat/lsp-bridge/commit/2b453025a8f9f8721eb70f573f70219474a1a680

A patch for Rust fn detail.
