### ISSUE TITLE
Import and format via gopls and hooks

### ISSUE THREAD

**Issue by diegostamigni** [manateelazycat/lsp-bridge#770]
Hello there,

I'm testing the switch from `lsp-mode` to `lsp-bridge` but I can't seem to find a way to achieve (when using `go-mode` and `gopls`) to perform `gopls.completeUnimported` and `gopls.staticcheck ` plus formatting (via `lsp-organize-imports` and `lsp-format-buffer`).

This is the code I _used_ to have for lsp-mode:
```elisp
(add-hook 'go-mode-hook #'lsp-deferred)
(defun lsp-go-install-save-hooks ()
  (add-hook 'before-save-hook #'lsp-format-buffer t t)
  (add-hook 'before-save-hook #'lsp-organize-imports t t))
(add-hook 'go-mode-hook #'lsp-go-install-save-hooks)
(lsp-register-custom-settings
 '(("gopls.completeUnimported" t t)
   ("gopls.staticcheck" t t)))
```

Is there a way to achieve the same/similar with `lsp-bridge`?

**Comment by manateelazycat** [comment]
I just commit https://github.com/manateelazycat/lsp-bridge/commit/0d7f6c540da60414c549ee157462f5077f6edc51

If you want format code, please use `lsp-bridge-code-format`, lsp-bridge use `lsp-bridge-code-action` execute code action, include source.organizeImports

**Comment by manateelazycat** [comment]
Please re-open issue if still have problem.
