### ISSUE TITLE
Error running timer ‘lsp-bridge-diagnostic-show-tooltip’: (beginning-of-buffer)

### ISSUE THREAD

**Issue by AllTheLife** [manateelazycat/lsp-bridge#771]
在开启 `lsp-bridge-enable-hover-diagnostic` 写C++代码时，如果出现了error，将光标移动到出现error的地方，会报错：
```
Error running timer ‘lsp-bridge-diagnostic-show-tooltip’: (beginning-of-buffer)
```

已用 emacs -Q 测试

## 最小配置
``` elisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/extensions/markdown-mode")
(add-to-list 'load-path "~/.emacs.d/site-lisp/extensions/yasnippet")
(add-to-list 'load-path "~/.emacs.d/site-lisp/extensions/lsp-bridge")
(require 'yasnippet)
(yas-global-mode)
(require 'lsp-bridge)
(global-lsp-bridge-mode)
(setq lsp-bridge-enable-hover-diagnostic t)
```

**Comment by manateelazycat** [comment]
最新版已经修复了， 请升级吧。

原因是 https://github.com/manateelazycat/lsp-bridge/commit/9174c62390860c8a80564f5994699ec2724f6956 这个补丁引起的， 因为原来诊断信息跳转的时候， 太靠近窗口边缘会导致tooltip挡住产生错误代码的地方。

**Comment by AllTheLife** [comment]
@manateelazycat  大佬，这个问题修复后，每次弹出 tooltip 时，光标都会跳到文件末尾

https://github.com/manateelazycat/lsp-bridge/commit/9174c62390860c8a80564f5994699ec2724f6956 这个补丁的 `scroll-down-line` 是不是应该也裹在 `save-excursion` 里啊

**Comment by manateelazycat** [comment]
有截图吗

**Comment by AllTheLife** [comment]
emacs -Q 时表现为屏幕不断滚动

![Peek 2023-11-11 13-20](https://github.com/manateelazycat/lsp-bridge/assets/87554738/0ac79be6-903b-4c39-9e39-94562be888cd)

**Comment by AllTheLife** [comment]
> 有截图吗

@manateelazycat emacs -Q 时表现为屏幕不断滚动

![Peek 2023-11-11 13-20](https://github.com/manateelazycat/lsp-bridge/assets/87554738/0ac79be6-903b-4c39-9e39-94562be888cd)

**Comment by manateelazycat** [comment]
再更新看看

**Comment by AllTheLife** [comment]
好耶，谢谢大佬修好了，现在变得和往常一样非常好用了 👏👏
