### ISSUE TITLE
新提交版本回车缩进没用了

### ISSUE THREAD

**Issue by ipyffor** [manateelazycat/lsp-bridge#781]
新提交版本回车缩进没用了，切换回838212a45772a4987d2d3fe1c8ece1fab78c79af版本正常，不知道是哪一次提交导致的

**Comment by ipyffor** [comment]
python诊断信息会提示SyntaxError: unindent does not match any outer indentation level

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/d25a63a1e7cca38fc931bb6ddb52acf590912685

跟这个补丁有关， 因为 electric-indent-mode 打开会导致补全列表错误。

建议用其他插件实现回车缩进的功能。
