### ISSUE TITLE
How to disable corfu, company, lsp-mode, eglot, etc. when lsp-bridge is activated?

### ISSUE THREAD

**Issue by maikol-solis** [manateelazycat/lsp-bridge#786]
Hi! 

In the README appears this note:

> When using lsp-bridge, please first disable other completion plugins, such as lsp-mode, eglot, company, corfu, etc. lsp-bridge provides a complete solution from the completion backend, completion frontend to multi-backend integration.

However, I couldn't figure it out yet how to disable corfu (in my case) when lsp-bridge is active. 

For example, in a LaTeX file, I have this behavior:

![image](https://github.com/manateelazycat/lsp-bridge/assets/4078489/6515e2ae-d2d3-4c96-9e7b-8fdde2967bbd)

Please illustrate me the correct mechanism for deactivating those other modes. Perhaps you could consider adding those explanations to improve the README. 

Thanks for your assistance.

Best

**Comment by manateelazycat** [comment]
just remove Corfu or disable Corfu mode，you should ask corfu author

**Comment by maikol-solis** [comment]
Hi! 

Yes, the thing is that I don't want to disable corfu at all because it's useful for the minibuffer or plain text files.  

I tried this, but it didn't work. 

```elisp 
(add-hook! 'lsp-bridge-mode-hook (lambda () (corfu-mode -1)))
```

I am unsure if I am missing something.

Thanks again. 

Best.

**Comment by manateelazycat** [comment]
I don't know how to mix corfu and lsp-bridge, sorry

best way is develop completion backend in lsp-bridge, then disable corfu completelly

**Comment by manateelazycat** [comment]
Please ask in corfu github, I don't know how to disable corfu, sorry.

**Comment by maikol-solis** [comment]
Thanks! Just for reference, I posted a question in the Corfu repo: 

https://github.com/minad/corfu/discussions/388

Best.
