### ISSUE TITLE
ERROR:epc:ReturnError

### ISSUE THREAD

**Issue by LeoGitHuber** [manateelazycat/lsp-bridge#789]
More details:
```
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])
search_list error: elisp not exist in backend_dict.
```
Environment: ArchLinux, Emacs 30.05

**Comment by manateelazycat** [comment]
能说一下重现步骤吗？我可能要到周末才有时间看呢

**Comment by LeoGitHuber** [comment]
使用 `emacs -q` debug，然后正常地把 `lsp-bridge` 导入，此时在 `Elisp` 文件中启用 `lsp-bridge-mode`，就会在 `*lsp-bridge*` 这个 buffer 中出现以上提到的字段信息，同时补全弹窗没有正常出现。

**Comment by manateelazycat** [comment]
你尝试按照 README 的方式使用 (global-lsp-bridge-mode) 了吗？

**Comment by LeoGitHuber** [comment]
试了也不行，`global-lsp-bridge-mode` 也会报错；另外，发现如果只是出现`search_list error: elisp not exist in backend_dict.` 这个信息会大概率出现，如果出现了，补全弹窗是不会弹出的；`ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])` 这个信息必出现。

**Comment by maikol-solis** [comment]
> This message will appear with a high probability. If it does, the completion pop-up window will not pop up; `ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])`This message must appear.

I'm having the same issue here #787

**Comment by manateelazycat** [comment]
> 试了也不行，`global-lsp-bridge-mode` 也会报错；另外，发现如果只是出现`search_list error: elisp not exist in backend_dict.` 这个信息会大概率出现，如果出现了，补全弹窗是不会弹出的；`ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('stringp'), []])` 这个信息必出现。

更新到最新版再尝试一下。

**Comment by LeoGitHuber** [comment]
刚刚拉取了最新版，这些报错照常出现。

**Comment by manateelazycat** [comment]
> 使用 `emacs -q` debug，然后正常地把 `lsp-bridge` 导入，此时在 `Elisp` 文件中启用 `lsp-bridge-mode`，就会在 `*lsp-bridge*` 这个 buffer 中出现以上提到的字段信息，同时补全弹窗没有正常出现。

为什么要在 elisp 中开启 lsp-bridge-mode？

(global-lsp-bridge-mode) 这个函数会在 elisp 文件中自动打开 lsp-bridge.

**Comment by manateelazycat** [comment]
你是怎么安装 lsp-bridge 的？ git clone 还是其他方式？

**Comment by LeoGitHuber** [comment]
我是通过 `git clone` 安装 lsp-bridge 这个包的，我配置文件中使用的是 `(global-lsp-bridge-mode)` 启用 lsp-bridge 的。

**Comment by LeoGitHuber** [comment]
> > 使用 `emacs -q` debug，然后正常地把 `lsp-bridge` 导入，此时在 `Elisp` 文件中启用 `lsp-bridge-mode`，就会在 `*lsp-bridge*` 这个 buffer 中出现以上提到的字段信息，同时补全弹窗没有正常出现。
> 
> 为什么要在 elisp 中开启 lsp-bridge-mode？
> 
> (global-lsp-bridge-mode) 这个函数会在 elisp 文件中自动打开 lsp-bridge.

之前测试时没有用 `(global-lsp-bridge-mode)` 这个函数，而是直接在 Elisp 文件中使用 `lsp-bridge-mode` 启用，不过这次测试使用了 `(global-lsp-bridge-mode)` 报错。

**Comment by manateelazycat** [comment]
我目前没法重现，如果有更多线索欢迎提供

**Comment by manateelazycat** [comment]
应该是调用 https://github.com/manateelazycat/lsp-bridge/blob/1b3b50ed380f6d8ab7442e410ad83acffd584bed/lsp-bridge.el#L1559 函数的时候， 接着调用了 https://github.com/manateelazycat/lsp-bridge/blob/1b3b50ed380f6d8ab7442e410ad83acffd584bed/core/search_list.py#L47 这个函数。

在 https://github.com/manateelazycat/lsp-bridge/blob/1b3b50ed380f6d8ab7442e410ad83acffd584bed/core/search_list.py#L47 这个函数中， 如果发现 elisp 不在 self.backend_dict 字典中就会报 search_list error

如果出现 elisp 不在字典中的情况， 应该是 https://github.com/manateelazycat/lsp-bridge/blob/1b3b50ed380f6d8ab7442e410ad83acffd584bed/lsp-bridge.el#L1548 这个函数并没有正常调用导致的。

你可以在 https://github.com/manateelazycat/lsp-bridge/blob/1b3b50ed380f6d8ab7442e410ad83acffd584bed/lsp-bridge.el#L1541 函数中添加一些 message 信息， 看看是什么判断条件没有满足？

**Comment by LeoGitHuber** [comment]
定位到问题了，是在 `lsp-bridge.el` 的 1579 行，`(buffer-list)` 返回的 `buffer` 可以不存在 `buffer-file-name`，如果使用 `substring-no-properties` 处理这个 `nil` 会报错，我修改这个后，报错不出现了，也能正常工作了。

**Comment by LeoGitHuber** [comment]
抱歉，不会像你一样引用文件具体的位置，只能这么描述了。

**Comment by manateelazycat** [comment]
最新版我修复了其他issue类似问题，可以更新最新版试一下吗

**Comment by LeoGitHuber** [comment]
已经更新最新版，发现你也注意到类似的问题了，但是上面提到的位置没有修复 `buffer-file-name` 这个问题，所以还是报错。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/7abcf56f919dc95321e5a092e3c9f89bde792d17

再更新一下吧。

**Comment by LeoGitHuber** [comment]
问题完全解决，感谢。
