### ISSUE TITLE
emacs29.1 ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'") ERROR:epc:Unexpected error

### ISSUE THREAD

**Issue by chenzhaobo** [manateelazycat/lsp-bridge#791]
fedora39环境，python3.12，emacs 29.1
lsp代码是最新clone下来的
我的配置和报错如图
![图像_2023-11-22_124613617](https://github.com/manateelazycat/lsp-bridge/assets/15965505/a79d870b-5d23-4213-b599-99fec8e77e7d)

`AttributeError: 'Symbol' object has no attribute 'value'
ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/chenzhaobo/.local/lib/python3.12/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/chenzhaobo/.local/lib/python3.12/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
            ^^^^^^^^^^^^^`

我在pip安装依赖的时候碰到过一个问题，安装sexpdata包的时候报错了
![图像_2023-11-22_124752229](https://github.com/manateelazycat/lsp-bridge/assets/15965505/1aa901d7-07ba-4938-b40d-d2a453135263)
![image](https://github.com/manateelazycat/lsp-bridge/assets/15965505/5c4c6bef-dc88-42cc-8f27-147140b536a3)

最后我用
`pip3 install --prefer-binary sexpdata
`
安装的二进制包，显示安装是成功的
![image](https://github.com/manateelazycat/lsp-bridge/assets/15965505/ea16b082-e61f-44f9-b2fa-c8a2daee4c8a)

**Comment by manateelazycat** [comment]
Looks sexpdata something wrong in Fedora.

It's not bug of lsp-bridge, please check your enviroment.
