### ISSUE TITLE
How to use TabNine Pro in lsp-bridge?

### ISSUE THREAD

**Issue by jackjackk** [manateelazycat/lsp-bridge#792]
First of all, thanks for this package! Great work.

Second, how can I use my credentials to be able to use TabNine Pro, and how to make sure I am using the pro version instead of the free one?

**Comment by manateelazycat** [comment]
I remember TabNine has a hint, when you type some keyword in Emacs, it will popup config page in browser to fill credentials.

You need check TabNine document.

**Comment by manateelazycat** [comment]
We haven't TabNine Pro account
