### ISSUE TITLE
lsp-bridge-mode is not enabled automatically on C++

### ISSUE THREAD

**Issue by damanis** [manateelazycat/lsp-bridge#807]
For JavaScript files lsp-bridge-mode enabled automatically when file loaded. For C++ files it is not activated until `lsp-bridge-mode` command called manually.
The lsp-bridge version is latest for `8ec922088`.
The configuration is minimal according `Installation` section step 5:
```
(add-to-list 'load-path "<path-to-lsp-bridge>")
(require 'yasnippet)
(yas-global-mode 1)
(require 'lsp-bridge)
(global-lsp-bridge-mode)
(setq lsp-bridge-get-project-path-by-filepath ...)
```

**Comment by manateelazycat** [comment]
You need write CMakeLists.txt like below:

[CMakeLists.txt](https://github.com/manateelazycat/lsp-bridge/files/13648510/CMakeLists.txt)

**Comment by manateelazycat** [comment]
You need enable option lsp-bridge-enable-log, then https://github.com/manateelazycat/lsp-bridge/blob/dfc5c3210ec1d6c421ef38e51e30f568ad4a3a54/lsp-bridge.el#L1188 will print which predicate is wrong.

**Comment by damanis** [comment]
@manateelazycat 
Currently it not reproduced, I will try again and notify you if it causes.
Is there easy way to save log directly to file?
