### ISSUE TITLE
c++在函数有多个重载的情况下无法在下方显示参数信息

### ISSUE THREAD

**Issue by ipyffor** [manateelazycat/lsp-bridge#809]
c++在函数有多个重载的情况下无法在下方显示参数信息请问是设置问题还是没有实现

**Comment by ipyffor** [comment]
函数唯一的时候能显示且能展开模板功能，有多个重载就没反应

**Comment by manateelazycat** [comment]
给一下测试的代码和重新步骤吧

**Comment by ipyffor** [comment]
![OUTPUT](https://github.com/manateelazycat/lsp-bridge/assets/47955238/508ea510-0e86-468f-ab8b-9707b1bf8946)
好像就一些函数补全之后没有展开参数，补全之后下方也没显示当前输入参数

**Comment by ipyffor** [comment]
[test.tar.gz](https://github.com/manateelazycat/lsp-bridge/files/13701104/test.tar.gz)

**Comment by manateelazycat** [comment]
更新到最新版还是有这个问题？

**Comment by ipyffor** [comment]
还是有

**Comment by manateelazycat** [comment]
![截图 2024-08-13 03-13-03](https://github.com/user-attachments/assets/4bce98dd-262f-4a81-9b24-556aa72cce7f)

我晚上测试了一下， 两个eye函数都可以显示呀， 我不太明白你这个issue的目标是什么？

**Comment by ipyffor** [comment]
我发的图也是eye函数也是正常的，还发了另外一个函数create没展开，也不现实签名

**Comment by ipyffor** [comment]
是调用的问题，类方法create不能这样调用，但是lsp能显示补全
