### ISSUE TITLE
能不能加两个命令，拷贝hover，拷贝inlayhint信息？

### ISSUE THREAD

**Issue by getong** [manateelazycat/lsp-bridge#810]
通过`lsp-bridge-popup-documentation`命令获取到变量类型，但只能看，不能拷贝，能不能加个命令拷贝这个变量类型信息？
另外能不能当前inlay hint信息？

顺便问一下
```
(defcustom lsp-bridge-popup-documentation-buffer " *lsp-bridge-hover*"
```
这个多余的空格是不是导致buffer会随时删除，感觉有点像是大拇指多敲了个空格，但不确定。

**Comment by manateelazycat** [comment]
在emacs中开头多余一个空格的buffer都会被emacs认为是临时隐藏buffer，只处理信息，但不在buffer list中操作和显示。

**Comment by manateelazycat** [comment]
这两个需求我觉得很简单，你可以尝试写一下补丁吧，锻炼一下自己。

**Comment by getong** [comment]
我试试
