### ISSUE TITLE
Supported python language servers not listed in docstring

### ISSUE THREAD

**Issue by doolio** [manateelazycat/lsp-bridge#811]
https://github.com/manateelazycat/lsp-bridge/blob/b526ed024f1dac9283256785f5082b2cc66cca66/lsp-bridge.el#L419-L425

L420: `pyright-background-analysis` and `ruff` are missing

Suggest to reword as follows (note the separation into two lines and the removal of `'):

"Default LSP server for Python.
Possible choices are pyright, pyright-background-analysis, jedi, python-ms, pylsp, and ruff." 

L424: `pyright-background-analysis_ruff` is missing

Suggest to reword as follows (note the separation into two lines and the removal of `'):

"Default Multi LSP server for Python.
Possible choices are pyright_ruff, pyright-background-analysis_ruff, jedi_ruff, python-ms_ruff, and pylsp_ruff."

**Comment by manateelazycat** [comment]
Can you give me a PR? thanks. ;)
