### ISSUE TITLE
Code format error in multi lsp server for python

### ISSUE THREAD

**Issue by 101scholar** [manateelazycat/lsp-bridge#814]
If I use ruff as backend, code formatting is OK. But if I use both pyright and ruff as backend, when calling `lsp-bridge-code-format`, it says "Current server not support code format."

FYI, I think ruff is activated since the message buffer prints `[LSP-Bridge] Start LSP server (pyright, ruff) for ... with ’project’ mode, enjoy hacking!`.

**Comment by manateelazycat** [comment]
The default value of lsp-bridge-python-multi-lsp-server is pyright-background-analysis_ruff, config at https://github.com/manateelazycat/lsp-bridge/blob/bc687cdc1814493d1d024ab984aa13f7b177c421/langserver/pyright-background-analysis.json#L1

I have test it, works fine.
