### ISSUE TITLE
acm补全窗口在退出insert state后仍然存在

### ISSUE THREAD

**Issue by norris-young** [manateelazycat/lsp-bridge#815]
我用的[meow](https://github.com/meow-edit/meow), 在输入比较快的时候退出insert state后补全窗口会一直停留在一个位置不动了. 不知道用evil的用户是否有出现类似问题, acm现在是不是目前对这块没有特别处理? 用原生emacs输入的应该不会有这个问题.

**Comment by manateelazycat** [comment]
我不用meow，可以去emacs-china网站搜索一下

**Comment by norris-young** [comment]
找到解决方案了
```lisp
(advice-add #'meow-insert-exit :after #'acm-hide)
```

**Comment by norris-young** [comment]
> 我不用meow，可以去emacs-china网站搜索一下

找到解决方案了
```lisp
(advice-add #'meow-insert-exit :after #'acm-hide)
```
