### ISSUE TITLE
希望可以增加配置标准库的tags文件

### ISSUE THREAD

**Issue by donaldsdlo** [manateelazycat/lsp-bridge#816]
是否可以通过ctags将标准库或者其他第三方库，先生成一个 tags文件，然后再通过dir env来设置需要加载哪些 tags 文件，然后补全的时候同时查询 标准库以及第三方库的tags文件以及项目中的tags文件

**Comment by manateelazycat** [comment]
已经有citre后端了，citre支持ctags
