### ISSUE TITLE
Use file-local no-byte-compile and no-native-compile variables

### ISSUE THREAD

**Issue by phil-s** [manateelazycat/lsp-bridge#823]
Looking at the readme, there are strong warnings to *not* allow byte- or native-compilation; but even though Emacs has provisions for enforcing this, they don't appear to be used.

You should add file-local `no-byte-compile` and/or `no-native-compile` variables to each library which must not be compiled in those ways.

**Comment by manateelazycat** [comment]
Can you help provide PR ? Thanks

**Comment by phil-s** [comment]
Not currently, as I don't know which elisp files are affected by the issue.

(I don't even understand the reason why elisp compilation is a problem for this project -- I'm not currently using it, and was just looking in passing and the readme warning jumped out at me as being very odd when that could be enforced.)

The change would simply be along these lines:

```diff
-    -*- lexical-binding: t; -*-
+    -*- lexical-binding: t; no-byte-compile: t; no-native-compile: t; -*-
```
