### ISSUE TITLE
Auto-import broken for duplicate names

### ISSUE THREAD

**Issue by runekaagaard** [manateelazycat/lsp-bridge#826]
When using pyright lsp server to auto-import a name that exists in multiple files only the last candidate is shown. This is due to the "detail" key of the response always being "Auto-import" and thus the candidate key being "MyThing_Auto-import" for all the candidates.

This little change in the `process_response` method in completion.py works for me:

```python
import hashlib

if self.file_action.enable_auto_import:
    candidate["additionalTextEdits"] = item.get("additionalTextEdits", [])
    key += "_".join(
        hashlib.md5(x["newText"].encode('utf-8')).hexdigest()
        for x in candidate["additionalTextEdits"])
    candidate["key"] = key
```

**Comment by manateelazycat** [comment]
can you send test code to me?

**Comment by runekaagaard** [comment]
Sure, you can try to import the symbol `MyThing` in the file `d.py` from this repo:

https://github.com/runekaagaard/lspb-example

It should show MyThing from `a.py`, `b.py` and `c.py`.

**Comment by manateelazycat** [comment]
How to operate? Can you tell me the steps to reproduce?

**Comment by runekaagaard** [comment]
Sure, go to d.py and type `MyThing` on an empty line. I only shows the completion for one of a, b or c but should show all three.

**Comment by manateelazycat** [comment]
I typed MyThing, but there was no completion menu. Can you share your lsp-bridge configuration?

**Comment by runekaagaard** [comment]
Hmmm, that's very standard. You are probably missing pyright?

```
pip install pyright
# or
npm install -g pyright
```

**Comment by manateelazycat** [comment]
![截图 2024-01-12 20-26-22](https://github.com/manateelazycat/lsp-bridge/assets/237487/deb33629-7c49-481b-a224-1bced309b140)
![截图 2024-01-12 20-26-30](https://github.com/manateelazycat/lsp-bridge/assets/237487/888ed0c6-35fb-4fe0-8b00-9e39fbda8f90)

I guess because ```lsp-bridge-python-multi-lsp-server "pyright-background-analysis_ruff"``` ?

Which python lsp server did you use?

**Comment by runekaagaard** [comment]
I use pyright and have no special configuration related to that, LSPB picks it up automatically.

**Comment by manateelazycat** [comment]
Can you send a PR ?  I'm happy merge it if logic is okay.

**Comment by runekaagaard** [comment]
https://github.com/manateelazycat/lsp-bridge/pull/829
