### ISSUE TITLE
Duplicate, Using code actions freezes emacs

### ISSUE THREAD

**Issue by Kenneth-Mata** [manateelazycat/lsp-bridge#827]
Using the ``lsp-bridge-code-action`` while having ``lsp-bridge-code-action-enable-popup-menu`` enabled will cause emacs to freeze, it will not respond to keyboard input (but mouse input, at least on wayland) will still work

I tried using this configuration 

``` lisp
(setq package-enable-at-startup nil)
(setq straight-check-for-modifications nil)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(use-package straight
  :config
  (setopt straight-use-package-by-default t))
(use-package yasnippet :config (yas-global-mode 1))
(use-package yasnippet-snippets)
(use-package markdown-mode)
(use-package lsp-bridge
  :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"
						 :files (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
						 :build (:not compile))
  :init
  (global-lsp-bridge-mode)
  :config
(setopt lsp-bridge-enable-log t)  
(setopt lsp-bridge-python-command "/home/kenneth/.conda/envs/py_env/bin/python"))
```

[Screencast_20240111_181830-1.webm](https://github.com/manateelazycat/lsp-bridge/assets/92641443/3ad2b099-81dc-49f9-a4d0-56ac85464e04)

This is the lsp-bridge buffer after the code action

![Screenshot_20240111_182200](https://github.com/manateelazycat/lsp-bridge/assets/92641443/66559c6f-9193-455a-9770-36b79c4e5097)

It was previously mentioned [here](https://github.com/manateelazycat/lsp-bridge/issues/711l)

I'm not very knowledgeable in either elisp or python, but i think this is worth mentioning, or disabling the popup by default / removing the option if it doesn't work properly.

**Comment by Kenneth-Mata** [comment]
Tried with a different language, it also happens with gopls

[Screencast_20240111_184822.webm](https://github.com/manateelazycat/lsp-bridge/assets/92641443/31ca01c2-e147-4374-aa64-062ba9b91589)

The lsp-bridge buffer

![Screenshot_20240111_185024](https://github.com/manateelazycat/lsp-bridge/assets/92641443/38779254-e1f9-4c2b-bd7a-a7a59249135a)

**Comment by manateelazycat** [comment]
can you send example code to me?

**Comment by Kenneth-Mata** [comment]
``` c
#include <stdio.h>
/* ANSI C doesn't require int to be the return of the main function*/
main() {
	float fahr, celsius, upper, lower, step;
	step = 20;
	upper = 500;
	lower = 0;

	fahr = lower;
	printf("%s", "Fahrenheit to Celsius Table\n");
	while (fahr <= upper) {
		celsius = (5.0 / 9.0) * (fahr - 32);
		printf("%6.2d   %9.1f\n" ,fahr, celsius);
		fahr = fahr + step;
	}
}
```

This is from the C Programming Book 2nd, clangd will highlight that %6.2d should be %6.2f, but freeze after selecting the fix

**Comment by manateelazycat** [comment]
I used the above code to test locally. The code action ran normally and there was no freezing problem. Please use emacs -Q to load only lsp-bridge for testing to eliminate the influence of other plug-ins.

**Comment by Kenneth-Mata** [comment]
``` lisp
(add-to-list 'load-path "/home/kenneth/.config/emm/lsp-bridge")

(require 'yasnippet)
(yas-global-mode 1)

(require 'lsp-bridge)
(global-lsp-bridge-mode)

(setopt lsp-bridge-enable-log t)
(setq lsp-bridge-python-command "/home/kenneth/.conda/envs/py_env/bin/python")

```

i tried with this configuration, directly download the lsp-bridge repo and still got the freezing behavior

![Screenshot_20240112_122143](https://github.com/manateelazycat/lsp-bridge/assets/92641443/49ebfa21-62f8-444d-8014-f2de590a634f)


I'll try to replicate this behavior on a VM and/or my windows machine

**Comment by kuba-orlik** [comment]
I can also confirm this behavior. It happens only in graphical mode, not in `-nw` mode. It seems it has to do more with showing/hiding the action popup than with applying the action itself, as when I `C-g` to hide the popup, the freeze still occurs

**Comment by manateelazycat** [comment]
> I can also confirm this behavior. It happens only in graphical mode, not in `-nw` mode. It seems it has to do more with showing/hiding the action popup than with applying the action itself, as when I `C-g` to hide the popup, the freeze still occurs. This happens in Wayland and in XOrg. I'm using pgtk emacs我也可以确认这种行为。它仅发生在图形模式下，而不发生在`-nw`模式下。看起来它必须在显示/隐藏操作弹出窗口方面做更多的事情，而不是应用操作本身，因为当我`Cg`隐藏弹出窗口时，冻结仍然发生。这种情况发生在 Wayland 和 XOrg 中。我正在使用 pgtk emacs

(setq pgtk-wait-for-event-timeout 0) 

Will fix your problem?

**Comment by manateelazycat** [comment]
> > I can also confirm this behavior. It happens only in graphical mode, not in `-nw` mode. It seems it has to do more with showing/hiding the action popup than with applying the action itself, as when I `C-g` to hide the popup, the freeze still occurs. This happens in Wayland and in XOrg. I'm using pgtk emacs我也可以确认这种行为。它仅发生在图形模式下，而不发生在`-nw`模式下。看起来它必须在显示/隐藏操作弹出窗口方面做更多的事情，而不是应用操作本身，因为当我`Cg`隐藏弹出窗口时，冻结仍然发生。这种情况发生在 Wayland 和 XOrg 中。我正在使用 pgtk emacs
> 
> (setq pgtk-wait-for-event-timeout 0)
> 
> Will fix your problem?

@kuba-orlik Can you help to test this solution? Thanks

**Comment by kuba-orlik** [comment]
I've just tested it and unfortunately it does not solve this problem

**Comment by manateelazycat** [comment]
It's looks like pgtk branch bug, I haven't use pgtk, can't help you.
