### ISSUE TITLE
C++ 补全snippet indent问题

### ISSUE THREAD

**Issue by zijianyue** [manateelazycat/lsp-bridge#845]
for的snippet补全，如下图所示，上面的写法}的indent位置错误，下面的写法indent位置正确
<img width="433" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/0a8a79ad-58b2-4500-8db4-b9736f778070">

**Comment by manateelazycat** [comment]
这个 snippet 本身的内容是对的吗？

**Comment by zijianyue** [comment]
本身内容是对的，clangd提供的
<img width="591" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/96403e04-8db4-4810-9fe8-421e708502c1">
我看它缩进成这样的原因 应该是for (range-declaration : range-expression)这个内容导致的，因为保持这个内容不变的话，我用TAB键去缩进‘}’也是在错误的位置上动不了，但是我如果把for (range-declaration : range-expression)改成正确的语法，比如for (auto& it : edgeSet.GetAllEdges())这样，再用TAB去缩进'}'就正常了。
但是lsp-mode的snippet补全在处理这个case时是正确的，如下图所示，回车补全候选，‘}’ 缩进位置就是对的
<img width="527" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/f1f95c8b-1da2-4a45-9b7b-03fb723eefaa">
<img width="382" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/0dad5813-6d43-49d0-a40e-07d095d633f3">

**Comment by manateelazycat** [comment]
你试过 emacs -Q 只加载 lsp-bridge 做过对比测试吗？

**Comment by zijianyue** [comment]
刚刚试了一下，也有同样的问题
<img width="476" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/216a4894-5419-438b-9799-408e6fcb395f">

**Comment by manateelazycat** [comment]
emacs -Q 可以测试一下 lsp-mode 吗？ 因为 lsp-bridge 的snippet展开是 yasnippet 的函数去展开的。

我估计是 yasnippet 配置不同造成的。

我晚上有空也验证一下。

**Comment by zijianyue** [comment]
lsp-mode的结果
<img width="430" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/967dd454-6dff-4347-aed3-85bfc12aff11">

配置如下
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/lsp-mode-20240130.1829")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/dash-20240103.1301")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/f-20231219.750")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/s-20220902.1511")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/ht-20230703.558")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/lv-20200507.1518")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/markdown-mode-20240107.831")
(add-to-list 'load-path "/home/gezijian/.emacs.d/elpa/spinner-1.7.4")
(add-to-list 'load-path "/home/gezijian/.emacs.d/site-lisp/company-mode")
(add-to-list 'load-path (concat user-emacs-directory "site-lisp/other"))
(require 'company)
(require 'yasnippet)
(require 'lsp-mode)
(require 'lsp-completion)
(global-company-mode t)
(yas-global-mode t)

启动lsp-mode后还要开启一下lsp-completion-mode

**Comment by manateelazycat** [comment]
研究了一下 lsp-mode, 需要移植 https://github.com/emacs-lsp/lsp-mode/pull/1939/files 这个补丁到 lsp-bridge 中。

lsp-mode 在展开 snippet 后， 接着对展开的 snippet 进行了格式化操作。

**Comment by manateelazycat** [comment]
我看了 lsp-mode 的方法， 写的太绕了。

https://github.com/manateelazycat/lsp-bridge/commit/6c064de79c9e13f2a075a19d2e2450ec8d00aefe 这个补丁应该修复了这个问题：
1. 展开 snippet 之间记录当前光标的缩进值
2. 展开 snippet 后， 跳转到 yas-snippet-end， 并让 snippet 最后一行的缩进和第一行缩进一致
