### ISSUE TITLE
刚启动时多次编辑仅发送一次 `didChange` 导致文档不同步

### ISSUE THREAD

**Issue by zerolfx** [manateelazycat/lsp-bridge#87]
https://github.com/manateelazycat/lsp-bridge/blob/master/test/test_completion.py

把测试中的 `(sleep-for 5)` 去掉之后会导致测试无法通过。根据日志，发现打开文件后连续进行两次编辑，只有第一次发送了 `didChagne` 请求，于是 lsp 眼中的文档不一致，补全错误。

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/lsp-bridge/pull/93
