### ISSUE TITLE
How can i make it work with emacs-direnv?

### ISSUE THREAD

**Issue by spl3g** [manateelazycat/lsp-bridge#870]
I am using NixOS with direnv with emacs-direnv to manage my lsp servers per project. But the lsp-bridge does not see lsp executables even though eshell sees them.

**Comment by manateelazycat** [comment]
I don't use NixOS, don't know how to fix it, any PR are welcome. ;)

**Comment by 2403772980ygy** [comment]
I guess just restarting the server process is enough when switching environments. direnv-mode sets the path the environment variables for subprocesses of emacs, which should work fine for cases like this.

**Comment by xinyifly** [comment]
I'm using NixOS 24.05 and confirm that lsp-bridge works correctly with `envrc-mode` .

It's seems that lsp-bridge initiate lsp server on first lsp related command invoke. Thus it doesn't really need a `lsp-deferred` command like in `lsp-mode`

**Comment by sggutier** [comment]
I have a very silly workaround that somehow works: if you simply wrap your lsp binary with a script that sets up direnv, it works. I've been using that solution after having a lot of issues with actually using direnv mode. Note that I don't have `direnv-mode` installed on my Emacs, so you might need to modify it. For gopls for instance, my script looks like

```bash
#!/usr/bin/env bash

direnv allow
eval "$(direnv export bash)"

exec <path-to-gopls>/gopls -mode=stdio -rpc.trace
```
