### ISSUE TITLE
Is it possible to use ACM with Orderless component separator like in Corfu?

### ISSUE THREAD

**Issue by artemkovalyov** [manateelazycat/lsp-bridge#884]
I haven't found in the docs how to achieve completion in a buffer by separating input in several Ordereless fields/segments similar to Corfu. It immensely helps with narrowing down completion candidates in LISP for example.  Is that possible? In one of the talks about `lsp-bridge` it was mentioned that Corfu was an inspiration but it was enhanced by removing CAPF-related APIs.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/bdb63a289dd9f36936309c3698845379ba347a9e/acm/acm.el#L229
