### ISSUE TITLE
lsp-bridge-workspace-list-symbols 查询结果集，如果是以 jdt:// 开始，无法正常跳转

### ISSUE THREAD

**Issue by bbenchen** [manateelazycat/lsp-bridge#886]
lsp-bridge-workspace-list-symbols 查询的结果中，如果location是以jdt://开始，无法正确跳转

https://github.com/manateelazycat/lsp-bridge/blob/935f7181102182045ba7d203d22a4d717bcd127d/lsp-bridge.el#L2290

这里未正确处理 jdt 协议

**Comment by manateelazycat** [comment]
给测试代码吧

**Comment by bbenchen** [comment]
[mybatis-flex](https://github.com/mybatis-flex/mybatis-flex)

输入Clone后，返回结果如下：

![image](https://github.com/manateelazycat/lsp-bridge/assets/2104470/d6c9d208-cffa-4e0a-b9fb-5335cbfec268)

**Comment by bbenchen** [comment]
我将 `lsp-bridge-workspace--list-symbols` 中 find-file 处代码修改成下面的代码，jdtls 给出的提示是：`[LSP-Bridge] No definition found.`

`
(cond ((string-prefix-p "jdt://" symbol-file)
       (lsp-bridge-call-file-api "jdt_uri_resolver" symbol-file symbol-position))
      (t
       (find-file symbol-file)
       (goto-char (acm-backend-lsp-position-to-point symbol-position))))
`

**Comment by bbenchen** [comment]
在执行 `lsp-bridge-call-file-api` 时，使用 `url-encode-url` 函数将 `symbol-file` 转义处理一下，就可以正常跳转了
`lsp-bridge-workspace--list-symbols` 最终代码以下：
```
(defun lsp-bridge-workspace--list-symbols (info)
  (if (zerop (length info))
      (message "LSP server did not return any symbols.")
    (let* ((symbols (mapcar #'lsp-bridge-workspace-transform-info info))
           (match-symbol (completing-read "Workspace symbol: " symbols))
           (match-info (seq-filter (lambda (i) (string-equal match-symbol (lsp-bridge-workspace-transform-info i))) info)))
      (when match-info
        (let* ((symbol-info (plist-get (car match-info) :location))
               (symbol-file (lsp-bridge-pick-file-path (format "%s" (plist-get symbol-info :uri))))
               (symbol-position (plist-get (plist-get symbol-info :range) :start)))
          (cond ((string-prefix-p "jdt://" symbol-file)
                 (lsp-bridge-call-file-api "jdt_uri_resolver" (url-encode-url symbol-file) symbol-position))
                (t
                 (find-file symbol-file)
                 (goto-char (acm-backend-lsp-position-to-point symbol-position)))))))))
```

**Comment by manateelazycat** [comment]
发个补丁吧，谢谢

**Comment by bbenchen** [comment]
@manateelazycat OK

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/d9c976c4cb7ac5af1f79ff570b7c9a689aa2bc39

这个补丁已经修复了。
