### ISSUE TITLE
在latex启动lsp-bridge-mode后只能补全yasnippet中的模板，不能连接latex lsp服务器

### ISSUE THREAD

**Issue by Elonisme** [manateelazycat/lsp-bridge#894]
在latex启动lsp-bridge-mode后只能补全yasnippet中的模板，不能连接latex lsp服务器texlab
![image](https://github.com/manateelazycat/lsp-bridge/assets/87638888/a3ab73e9-c7f3-4721-976d-7de31b453b6f)

手动启动lsp-bridge-mode， message显示如下：
![image](https://github.com/manateelazycat/lsp-bridge/assets/87638888/250b9456-889c-4096-be18-c1f3dfd12fb5)

这是配置
![image](https://github.com/manateelazycat/lsp-bridge/assets/87638888/e56a90d9-878c-4845-a78a-e4a67990c050)

texlab版本如下：
![image](https://github.com/manateelazycat/lsp-bridge/assets/87638888/baba4b0b-9446-464e-bf47-a64f414c59f7)

不清楚是不是依赖的问题

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/de8f8447a65198206c38ec9aa3792c8f3b9c9c1f

尝试更新到最新版看看

**Comment by Elonisme** [comment]
> [de8f844](https://github.com/manateelazycat/lsp-bridge/commit/de8f8447a65198206c38ec9aa3792c8f3b9c9c1f)
> 
> 尝试更新到最新版看看

更新后，问题解决
