### ISSUE TITLE
lsp-bridge-find-def not working with remote

### ISSUE THREAD

**Issue by leath-dub** [manateelazycat/lsp-bridge#895]
when I run `lsp-bridge-find-def` in remote file it tries to go to a file in my local file system: not the remote. For example if I run it on a class `A` it trys to got to /usr/include/xxxx.h on my local file system not the remote file system. I am accessing the remote file using `lsp-open-remote-file`.

**Comment by manateelazycat** [comment]
@norris-young Can you help take a look at this issue? thank you for your time ;)

**Comment by leath-dub** [comment]
> Can you add some log in function `lsp-bridge-define--jump` ?
> 
> I guess something wrong to make code not execute
> 
> https://github.com/manateelazycat/lsp-bridge/blob/22d0623378e77c8d20f1f5f8598ccf62bcf63e51/lsp-bridge.el#L1955

Sorry not using emacs anymore.

**Comment by norris-young** [comment]
> @norris-young Can you help take a look at this issue? thank you for your time ;)

@manateelazycat @leath-dub 
Sorry for late reply. `lsp-bridge-enable-with-tramp` need to be set to `nil` which is default `t` if you want to use `lsp-bridge-open-remote-file` instead of opening with tramp. Maybe we need to add this limitation info to the `README`.

**Comment by manateelazycat** [comment]
> lsp-bridge-open-remote-file

Done 

https://github.com/manateelazycat/lsp-bridge/commit/ee43c6caf78bd8ec851859e0dd690aa646231591
