### ISSUE TITLE
能加入mojo支持吗？

### ISSUE THREAD

**Issue by xep007** [manateelazycat/lsp-bridge#904]
能加入mojo支持吗？

**Comment by xep007** [comment]
vscode上可以支持，不够好像还没独立的mojo-lsp-server。对了，我居然忘了这一茬。

**Comment by manateelazycat** [comment]
有独立的 lsp sever , 支持比较好做， 没有的话， 我自己也不熟悉 mojo, 只能希望社区大佬的贡献了， 我个人精力极度有限， 尽情谅解。

**Comment by xep007** [comment]
谢谢manateelazycat,是我孟浪了。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/2370f61ae296913a5f66bc6cba921f5e7e63fe73

我推送了补丁， 我的系统没法安装 mojo, 你可以用 modular install mojo-lsp-server, 然后再尝试最新版看看能否工作？

**Comment by xep007** [comment]
可以用。就是找不到一个好的mojo-mode.el。

**Comment by manateelazycat** [comment]
mojo-hl
