### ISSUE TITLE
enabling lsp-bridge breaks syntax highlighting

### ISSUE THREAD

**Issue by Cadair** [manateelazycat/lsp-bridge#905]
Hello,

I am running doom emacs, with lsp-bridge enabled. If I include lsp-bridge in my config when I edit files in python-mode (and maybe others, but I mainly use python) the syntax highlighting goes completely insane until I re-run `M-x python-mode`.

I know this is a terrible bug report, but any suggestions on how I can get you more information would be helpful, I don't really know where to start.

Thanks!

**Comment by manateelazycat** [comment]
Can you give me a minimal reproducible configuration, minimal test code, and a stable reproducible method?

I don't use Doom Emacs

**Comment by Cadair** [comment]
Hi! Thanks for getting back to me, I have started trying to build a docker contain which can reproduce the issue here: https://github.com/Cadair/lsp-bridge-doom-debugging/

unfortunately I haven't managed to reproduce the syntax highlighting bug because I get this error on load when I unclude by lsp-bridge module:

```
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8$
  (closure (t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8)))()                                           
  apply((closure (t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8))) nil)                                  
  acm-frame-color-blend("unspecified-bg" "#AAAAAA" 0.9)                                                                       
  (set-face-background 'acm-frame-default-face (acm-frame-color-blend default-background blend-background (if is-dark-mode 0.$
  (progn (set-face-background 'acm-frame-default-face (acm-frame-color-blend default-background blend-background (if is-dark-$
  (if (or force (equal (face-attribute 'acm-frame-default-face :background) 'unspecified)) (progn (set-face-background 'acm-f$
  (let* ((is-dark-mode (string-equal (acm-frame-get-theme-mode) "dark")) (blend-background (if is-dark-mode "#000000" "#AAAAA$
  acm-frame-init-colors(t)                                                                                                    
  acm-reset-colors(doom-one t)                                                                                                
  apply(acm-reset-colors (doom-one t))                                                                                        
  load-theme(doom-one t)                                                                                                      
  (progn (load-theme doom-theme t))                                                                                           
  (if (and doom-theme (not (custom-theme-enabled-p doom-theme))) (progn (load-theme doom-theme t)))                           
  doom-init-theme-h()                                                                                                         
  run-hooks(after-init-hook delayed-warnings-hook)                                                                            
  command-line()                                                                                                              
  normal-top-level()    
```

Do you have any thoughts on what could be causing that?

**Comment by manateelazycat** [comment]
This is a problem with the theme. Please change the theme and test again.

**Comment by clementpoiret** [comment]
@manateelazycat sorry to reopen this issue, but I don't want to open a new one, as I face this exact same bug.
I don't think it is theme related as I do not have this issue with the "normal" lsp-mode. This issue occured after the installation of "lsp-bridge".

Here is my very basic config: https://github.com/clementpoiret/emacs-config/tree/main

Thanks for your time!

**Comment by clementpoiret** [comment]
Another config (from someone else) having the syntax-highlightning bug: https://github.com/ryan4yin/nix-config/commit/11bbedcde766aed538c703b8bd21ba436044c85a

**Comment by manateelazycat** [comment]
> @manateelazycat sorry to reopen this issue, but I don't want to open a new one, as I face this exact same bug. 很抱歉重新打开此问题，但我不想打开新问题，因为我面临着完全相同的错误。 I don't think it is theme related as I do not have this issue with the "normal" lsp-mode. This issue occured after the installation of "lsp-bridge". 我不认为这与主题相关，因为我在“正常”lsp 模式下没有这个问题。安装“lsp-bridge”后出现此问题。
> 
> Here is my very basic config: https://github.com/clementpoiret/emacs-config/tree/main这是我非常基本的配置：https://github.com/clementpoiret/emacs-config/tree/main
> 
> Thanks for your time!谢谢你的时间！

It's a theme problem, you need give me theme you use, not config.

I haven't time to debug your config

**Comment by clementpoiret** [comment]
I use catppuccin mocha: https://github.com/catppuccin/emacs
What's your theme? I would happily try with it to see if I have the same problem.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-theme

**Comment by manateelazycat** [comment]
I have push new patch https://github.com/manateelazycat/lsp-bridge/commit/92d58ff0fb938ced513d690e0daadef74737e5d4 try to fix this issue.
