### ISSUE TITLE
Pop up buffer stuck on screen

### ISSUE THREAD

**Issue by abdalazizrashid** [manateelazycat/lsp-bridge#908]
Sometimes the mini buffer gets stuck on the screen and can't be closed unless start a new frame.
<img width="1397" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/33545649/2364d103-479b-434d-b156-6a81a701aaaf">

**Comment by manateelazycat** [comment]
emacs -Q for compare test

**Comment by abdalazizrashid** [comment]
Not sure how to reproduce it, I think it some kind of interaction with helm

**Comment by manateelazycat** [comment]
Ok, please re-open issue if you have reproduce step.
