### ISSUE TITLE
No signature help when using lsp-bridge within org babel source block

### ISSUE THREAD

**Issue by nujabse** [manateelazycat/lsp-bridge#909]
Although `lsp-bridge` can provide nice code completions in org babel source code blocks, it can not show signature help when it is ued within org babel source blocks, calling `lsp-bridge-signature-help-fetch` does not show signature help, either.

- `emacs -Q` test configuration:
```elisp
(require 'yasnippet)
(yas-global-mode 1)
(require 'markdown-mode)
(require 'lsp-bridge)
(setq lsp-bridge-enable-org-babel t)
(setq lsp-bridge-org-babel-lang-list '("python") )
(global-lsp-bridge-mode)
```
- Org mode code sample to reproduce:
```
#+begin_src python :results output
print('Hello, world')
#+end_src

```
- Expected behaviour:
 Show signature help for function at point (`print`) in the minibuffer.

**Comment by manateelazycat** [comment]
@kongds Can you help add this feature? Thanks.

**Comment by manateelazycat** [comment]
Please update to newest version, has fixed it.

**Comment by nujabse** [comment]
Thank you for the quick fix! Really appreciate your help, it now works flawlessly.
