### ISSUE TITLE
安装说明中是否可以增加spacemacs？

### ISSUE THREAD

**Issue by sandao** [manateelazycat/lsp-bridge#914]
看到说明里面有Doom的使用说明；可否增加spacemacs的？自己配置一直出错；语言是C#

**Comment by manateelazycat** [comment]
SpaceEmacs估计不行吧， 它内置了 compnay 和 lsp-mode 这些插件， 冲突太大了。

抱歉。

**Comment by sandao** [comment]
好的；感谢解答；
