### ISSUE TITLE
提供选中区域格式化的功能

### ISSUE THREAD

**Issue by zijianyue** [manateelazycat/lsp-bridge#916]
能否提供一个支持选中区域格式化的功能，目前只找到lsp-bridge-code-format，会对整个文件格式化，局部格式化一是更快，二是有时候不想改动其他位置的格式，以免代码差异过多，不便查看修改记录

**Comment by manateelazycat** [comment]
我看了看 LSP 的协议 https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions

目前 LSP 协议还不支持指定区域格式化， 因为格式化的调整有可能会调整换行的情况， 目前也没法通过对比LSP Server返回的信息， 在Elisp端精确控制格式化区域。

**Comment by manateelazycat** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rangeFormatting

**Comment by zijianyue** [comment]
我用的后端是clangd 18.1，选中区域执行 lsp-bridge-code-format，报错
[LSP-Bridge] Current server not support range format

**Comment by manateelazycat** [comment]
那就是clangd lsp server不支持局部格式化这个功能

**Comment by zijianyue** [comment]
> 那就是clangd lsp server不支持局部格式化这个功能
通过lsp-mode的诊断来看clangd应该是有这个功能的
<img width="780" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/264c4347-2b36-4fb7-834f-8804ddbf2f11">

**Comment by manateelazycat** [comment]
我推送了 https://github.com/manateelazycat/lsp-bridge/commit/dd700106341012e9858d9d764b5f49327df91433

这是补丁解决不同LSP Server range format返回格式不一致的问题， pyright/ruff 返回的是 documentRangeFormattingProvider/rangesSupport, clangd 返回的是 documentRangeFormattingProvider

**Comment by zijianyue** [comment]
太好了，现在正常工作了
