### ISSUE TITLE
Idea: Support lsp progress?

### ISSUE THREAD

**Issue by eval-exec** [manateelazycat/lsp-bridge#922]
I believe it would be nice if the lsp-bridge could display lsp progress in the modeline, similar to the example shown in https://github.com/linrongbin16/lsp-progress.nvim.

Reference:
- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress

**Comment by manateelazycat** [comment]
I'll make it happen in a while. I've been a little too busy lately.

**Comment by manateelazycat** [comment]
Can you give me some code to test workDoneProgress? Thanks.

**Comment by eval-exec** [comment]
> Can you give me some code to test workDoneProgress? Thanks.

You can try this rust repo:
`git clone --depth=1 https://github.com/BurntSushi/ripgrep`

**Comment by manateelazycat** [comment]
@eval-exec 

I have push https://github.com/manateelazycat/lsp-bridge/commit/c767902cc6b9e60ad4c8dca15ddbecef44cb496b to support workDoneProgress protocol.

Control by option acm-backend-lsp-show-progress , when acm-backend-lsp-show-progress is t, show progress in minibuffer.

I use my awesome-tray, not use modeline, any PR about modeline are welcome! ;)

**Comment by eval-exec** [comment]
Great job on implementing support for the workDoneProgress protocol! Thank you! :blue_heart: 

> I use my awesome-tray, not use modeline, any PR about modeline are welcome! ;)

Now I can use the following spinner characters to display the status of WorkDoneProgress:
;; spinner = {"⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"},

**Comment by manateelazycat** [comment]
Enjoy it.
