### ISSUE TITLE
使用lsp-bridge-semantic-tokens-global-scope-face后，C++中的宏和函数的颜色无法区分开

### ISSUE THREAD

**Issue by zijianyue** [manateelazycat/lsp-bridge#934]
(setq-default lsp-bridge-semantic-tokens-type-modifier-faces
                                                    [("globalScope" . lsp-bridge-semantic-tokens-global-scope-face)])

<img width="269" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/703a197f-972b-419e-98c6-1c0756816900">
关闭后可以区分开
<img width="267" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/fee127e6-3996-4edf-81be-2b7ec3009e36">

**Comment by manateelazycat** [comment]
我这个补丁 https://github.com/manateelazycat/lsp-bridge/commit/1d164e64fc9507b3ceb9bd8bb446b284f60e412b 改了一下默认的值， 原来只是加粗

**Comment by zijianyue** [comment]
能否改成在原有face基础上叠加上加粗的效果？而不是覆盖掉原来的face，比如一个global function，原本是金色的，期望变成加粗的金色，而不是global的macro, function等等都只能统一用一个face，就无法区分开了。
下图是你的补丁的最新效果：
<img width="279" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/cdf80edd-3595-449a-a27f-360943ec96f6">

**Comment by manateelazycat** [comment]
自己自定义吧

**Comment by xhcoding** [comment]
@zijianyue 
默认 modifier 的 face 会覆盖掉原来的 face ，可以使用组合模式，这样就能实现 globalScope 的 face 叠加到原来的 face 上

```
  (setq lsp-bridge-semantic-tokens-apply-modifiers 'combine)
```
![image](https://github.com/manateelazycat/lsp-bridge/assets/30917129/6e44f309-2896-4a72-aaaf-d5d638112880)

**Comment by manateelazycat** [comment]
> @zijianyue 默认 modifier 的 face 会覆盖掉原来的 face ，可以使用组合模式，这样就能实现 globalScope 的 face 叠加到原来的 face 上
> 
> ```
>   (setq lsp-bridge-semantic-tokens-apply-modifiers 'combine)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/30917129/329838363-6e44f309-2896-4a72-aaaf-d5d638112880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDU0MjgsIm5iZiI6MTcxNTUwNTEyOCwicGF0aCI6Ii8zMDkxNzEyOS8zMjk4MzgzNjMtNmU0NGYzMDktMjg5Ni00YTcyLWFhYWYtZDVkNjM4MTEyODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA5MTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMzQ4ZGZiYTkyYTg3MWVlZjM1YTc0NDYxNDZkNDlmOWM2MTJjOTE4OGRkOTViMTQ3YWViODQ1NDU4YzRhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBulLMT3eRRRDhLgMZd_-rSclaDVH9JYUHJoYaVed_s)

大佬， combine 是不是一个更好的默认值？

**Comment by xhcoding** [comment]
我觉得可以改成 combine

**Comment by zijianyue** [comment]
赞！

**Comment by zijianyue** [comment]
我有个疑问，比如我想将readonly的函数变成const的颜色（添加以下配置），就不适用combine了，这时候期望用override
(setq-default lsp-bridge-semantic-tokens-type-modifier-faces
                                                        [("globalScope" . lsp-bridge-semantic-tokens-global-scope-face)
                                                         ("readonly" . lsp-bridge-semantic-tokens-enum-member-face)])
期望的效果，来自lsp-mode，readonly的函数打了const标记
<img width="383" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/937629b5-1b06-4073-b366-dc2731eebfe8">
<img width="179" alt="image" src="https://github.com/manateelazycat/lsp-bridge/assets/6119928/047bc580-3cc6-4750-9985-3bc184f43724">

**Comment by manateelazycat** [comment]
@zijianyue 麻烦重新提一个issue， 我好追踪新的问题
