### ISSUE TITLE
Rust中函数名不显示

### ISSUE THREAD

**Issue by devbins** [manateelazycat/lsp-bridge#935]
Rust中调用函数，只显示签名，不显示函数名，Python正常
<img width="558" alt="Screenshot 2024-05-07 at 23 21 59" src="https://github.com/manateelazycat/lsp-bridge/assets/8175896/dd91bfd5-7670-490e-93d5-f8bcd295f62d">

**Comment by manateelazycat** [comment]
这个补丁引起的 https://github.com/manateelazycat/lsp-bridge/pull/928

我推送了修复补丁 https://github.com/manateelazycat/lsp-bridge/commit/b00ffd36ce147c13a9cbb6dda75f10fc112d2279

既保证了 https://github.com/manateelazycat/lsp-bridge/pull/928 的优化预期， 又避免这个问题。

![截图 2024-05-08 01-43-06](https://github.com/manateelazycat/lsp-bridge/assets/237487/9459c4c7-f1a8-4686-b608-c46f3285c343)

![截图 2024-05-08 01-43-20](https://github.com/manateelazycat/lsp-bridge/assets/237487/6fb247a0-17be-4a90-87eb-36320cd02f91)
