### ISSUE TITLE
C++自己写的头文件函数名不显示，标准库可以

### ISSUE THREAD

**Issue by devbins** [manateelazycat/lsp-bridge#936]
之前Rust函数名不显示的问题解决了，我又发现C++调用自己写的头文件中的函数，不显示函数名，标准库可以

<img width="541" alt="Screenshot 2024-05-09 at 22 53 33" src="https://github.com/manateelazycat/lsp-bridge/assets/8175896/93002565-6802-465c-a02f-e3b31c74a3f6">

调用标准库函数
<img width="529" alt="Screenshot 2024-05-09 at 22 53 21" src="https://github.com/manateelazycat/lsp-bridge/assets/8175896/f3a6d508-13ef-47e0-8d60-875233802c46">

test.h
```c
#ifndef _TEST_H
#define _TEST_H

void init();

#endif /* _TEST_H */
```

main.cpp
```c
#include <test.h>
#include <iostream>

int main(int argc, char *argv[])
{
  ini
    return 0;
}

```

**Comment by manateelazycat** [comment]
你把你的整个工程目录都上传一下吧， 我看看能否重现。

**Comment by devbins** [comment]
> 你把你的整个工程目录都上传一下吧， 我看看能否重现。

代码上传到 https://github.com/devbins/lsp-cpp 了，大佬有空试试

**Comment by devbins** [comment]
> 你把你的整个工程目录都上传一下吧， 我看看能否重现。

代码上传到 https://github.com/devbins/lsp-cpp 了，大佬有空试试

**Comment by manateelazycat** [comment]
只需要这两个文件吗？ 不需要其他的 compile_commands.json 啥的吗？

**Comment by devbins** [comment]
> 只需要这两个文件吗？ 不需要其他的 compile_commands.json 啥的吗？

不需要

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/b8768c4a76525d82360d124c829774acd26634c3 修复了， 感谢反馈
