### ISSUE TITLE
Incorrect response to `window/workDoneProgress/create`

### ISSUE THREAD

**Issue by mhanberg** [manateelazycat/lsp-bridge#938]
https://github.com/manateelazycat/lsp-bridge/blob/b8768c4a76525d82360d124c829774acd26634c3/core/lspserver.py#L733

Unless it is responding with an error, the only valid response is `null`.

The code linked above seems to be responding with an empty object.

Also, if you don't support this request, you can declare the window.workDoneProgress client capability as false, then the server should not even request it (if it does, the server should be fixed).

**Comment by knarkzel** [comment]
Changing to this gets rid of error message for `nextls`:
```py
self.sender.send_response(message["id"], None) 
```

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/c4b9ac3617ca8072ff77b1440b628e382188d6ff

Has fixed, thanks for report. ;)
