### ISSUE TITLE
补全自动修改窗口位置

### ISSUE THREAD

**Issue by lizqwerscott** [manateelazycat/lsp-bridge#940]
当开启 lsp-bridge-enable-inlay-hint 后，在 rust 下， 补全会自动将当前行设置为窗口第一行
系统: Arch Linux
测试代码:
``` elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/") t)
(package-initialize)

(add-to-list 'load-path "~/.emacs.d/site-lisp/lsp-bridge")

(require 'yasnippet)
(yas-global-mode 1)
(require 'lsp-bridge)
(setq lsp-bridge-enable-inlay-hint t)
(global-lsp-bridge-mode)

(require 'rust-mode)
```
rust 代码:
``` rust
fn main() {
    println!("Hello, world!");
}
```
问题：
补全之前:
![inlay1](https://github.com/manateelazycat/lsp-bridge/assets/28244403/fd1f2b2a-c3eb-4251-a535-0d5a69248848)
补全之后:
![inlay2](https://github.com/manateelazycat/lsp-bridge/assets/28244403/5fac2507-a19c-4435-b62d-95b80c949768)

**Comment by manateelazycat** [comment]
我刚才试了， 没有这种现象， 请用 emacs -Q 排除你的配置， 感谢你的反馈。

**Comment by lizqwerscott** [comment]
刚刚我重新编译了 Emacs，发现最新的 Emacs 30 master 不存在此问题。而当使用 Arch Linux 源内附的 Emacs 29.3-3 时，则会遭遇该状况。@manateelazycat，在您进行测试时，采用了哪个 Emacs 版本呢？

**Comment by manateelazycat** [comment]
我是git版本
