### ISSUE TITLE
vue模式下跳转定义文件，第二次就失败了

### ISSUE THREAD

**Issue by getong** [manateelazycat/lsp-bridge#959]
报错信息
```
--- [17:41:55.007569] Recv textDocument/definition response (3203) from 'volar' for project 
File App.vue opened again before close.
File App.vue opened again before close.
```
- [ ] 第一次跳转的时候，能找到对应的文件；但第二次以及以后的跳转，都失败了，这个是跟vue的模式有关，有多个language server
- [ ] 报错有两次，应该报错一次就足够了

**Comment by manateelazycat** [comment]
提供一下测试代码和重现步骤吧，谢谢

**Comment by getong** [comment]
https://github.com/getong/typescript_workspace_example/blob/c90e68a5d994db79957f7d476853b754c0f40d6c/vue_basic_counter_ts_example/src/App.vue#L11-L12
有两个click属性，在第一个click使用`lsp-bridge-find-def` 能跳转。
切换到另外click再使用`lsp-bridge-find-def` ， 就出现上面的bug

**Comment by manateelazycat** [comment]
我刚刚测试了一下， 感觉是 volar 的问题呀， volar 在第二次发送 find define 消息的时候确实返回 []

**Comment by manateelazycat** [comment]
我试了其他语言的服务器， 比如 Python 的 pyright ， 没有遇到这个问题， Python默认也是多服务器
