### ISSUE TITLE
使用最新代码（commitid: 1f47c8fb），js 无法补全

### ISSUE THREAD

**Issue by ringawho** [manateelazycat/lsp-bridge#967]
大佬，今天 pull 了最新代码后出现一个问题，您有时间的话可以看一下。js-ts-mode 中使用 lsp-bridge，选中候选项然后回车会报错，无法补全，我确认了下是最新的 commit 有关，回退上一个没有这个问题。另外 python (pyright) 没有问题

commit：1f47c8fbf4b145e4f8b42dc1aebf096e4cd159f9

server：typescript-language-server

mac emacs-plus 30.0.50

![image](https://github.com/manateelazycat/lsp-bridge/assets/18455821/a86511ad-2e9b-43f1-aebe-d96187723da9)

**Comment by manateelazycat** [comment]
最新的补丁已经 revert 了， 感谢反馈
