### ISSUE TITLE
刚装上，同时出现了 YASnippet 和  lsp 的补全列表，怎么去选中 YASnippet 的候选项了

### ISSUE THREAD

**Issue by yufengwang** [manateelazycat/lsp-bridge#969]
![image](https://github.com/manateelazycat/lsp-bridge/assets/12859005/07fe8f81-68a4-49dd-96aa-3840bd37bc1d)

默认按 return 或 tab 选中的是 lsp 的候选列表，不是 YASnippet 的

**Comment by manateelazycat** [comment]
看readme，禁用其他补全插件

**Comment by yufengwang** [comment]
这俩一起用的时候，怎么选中 YASnippet 的候选项了
