### ISSUE TITLE
Probably a typo in multiserver/qmlls_javascript.json

### ISSUE THREAD

**Issue by siguma0013** [manateelazycat/lsp-bridge#970]
Maybe the value for key "document_symbol", "workspace_symbol", "semantic_tokens", "semantic_tokens" in multiserver/qmlls_javascript.json is a typo and "qmlls" is correct, is it?

![2024-06-16 03 44 25 github com 37accd1eda73](https://github.com/manateelazycat/lsp-bridge/assets/5283539/de012c4a-bf31-4dfe-b967-a13f1236a3d7)

**Comment by manateelazycat** [comment]
Has fixed by https://github.com/manateelazycat/lsp-bridge/commit/152431c0b1d731d0302e1849690e2361f3caf7c1

Thanks for report.
