### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by TESTSIGNUP123** [manateelazycat/lsp-bridge#972]
懒猫大佬 问一下你这个LSP-bridge 没有上传elpa上 ，后续你如果更新了 此mode 我该如何更新

**Comment by manateelazycat** [comment]
https://manateelazycat.github.io/2018/10/07/why-not-melpa/

https://manateelazycat.github.io/2022/05/21/emacs-plugin/

请阅读上面的回答。

**Comment by TESTSIGNUP123** [comment]
谢谢 表示 多多少少有点 不会此插件   lsp-mode我也装了
但是 还是有有点懵
