### ISSUE TITLE
How can I detect if ACM menu is active when hitting Tab?

### ISSUE THREAD

**Issue by aguynamedben** [manateelazycat/lsp-bridge#974]
Thank you for providing this package, it's incredible.

Which function or variable can I use to detect it if the ACM menu is currently showing? I'm trying to use lsp-bridge alongside [copilot.el](https://github.com/copilot-emacs/copilot.el) and mimic tab completion in VS Code:

1. If the ACM menu is showing and I hit Tab, take the ACM completion
2. Otherwise, take the copilot.el completion

However I'm unable to determine a variable or function I can use from acm that will tell me if it's currently showing or not.

I've tried these 4 conditions, but they all seem to return false even when I'm hitting Tab while the ACM menu is open.

## Attempt 1
```elisp
(if (acm-frame-visible-p acm-menu-frame)
    (progn
      (message "Using lsp-bridge completion - old")
      (acm-complete))
  (progn
    (message "Using copilot.el completion - old")
    (copilot-accept-completion)))
```

Result: Uses copilot

## Attempt 2
```elisp
(if (lsp-bridge-completion-ui-visible-p)
  (progn
    (message "Using lsp-bridge completion - old2")
    (acm-complete))
  (progn
    (message "Using copilot.el completion - old2")
    (copilot-accept-completion)))
```

Result: Uses copilot

## Attempt 3
```elisp
(if (and acm-mode acm-menu-candidates)
  (progn
    (message "Using lsp-bridge completion - old2")
    (acm-complete))
  (progn
    (message "Using copilot.el completion - old2")
    (copilot-accept-completion)))
```

Result: Uses copilot

## Attempt 4
```elisp
(if (frame-visible-p acm-menu-frame)
  (progn
    (message "Using lsp-bridge completion - old2")
    (acm-complete))
  (progn
    (message "Using copilot.el completion - old2")
    (copilot-accept-completion)))
```

Result: Uses copilot

Checking if `acm-menu-candidates` is nil seems to "works" the first time, but that variable stays populated after the ACM menu is hiding. Also, I tried `if (and (fboundp 'lsp-bridge-completion-ui-visible-p) (funcall 'lsp-bridge-completion-ui-visible-p))` but that also seems to return nil even when I'm hitting tab and the ACM menu is open.

Maybe this is a race condition? Do you have any suggestions or docs on how to conditionally handle Tab?

**Comment by manateelazycat** [comment]
I have try below code, works fine

```
(run-with-timer 5 nil (lambda ()
                        (when (acm-frame-visible-p acm-menu-frame)
                          (message "acm frame is show"))))
````

**Comment by manateelazycat** [comment]
It cannot be reproduced. If there is any problem, please reopen the issue. Thank you.
