### ISSUE TITLE
lsp-bridge-open-remote-file not working and all problems

### ISSUE THREAD

**Issue by Anoncheg1** [manateelazycat/lsp-bridge#978]
1) Behavior is not predictable. It is trying all hosts in .ssh/config after a big lag in a very stupid fashion.
2) lsp-bridge-open-remote-file asks for ip:path and don't allow Host:path (as in README.md have been told)
3) yasnippet is not mandatory dependency for Eglot, why it is mandatory here?
4) No guide for creation of encrypted connection to remote server with SSH without direct access to remote host ports.
5) How to specify host and ports for lsp server and lsp-bridge server?
6) syntax highlighting is broken after (require 'lsp-bridge or yasnippet)
7) no error messages, just  "updating info... skip call find_define." "updating info... skip call change_cursor." ... etc in *Messages*.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/issues/966

**Comment by manateelazycat** [comment]
LSP server will return code template, it's need yasnippet to parse template

**Comment by manateelazycat** [comment]
Please provide a separate issue for each issue，
Don't merge them all together that issue cannot be tracked.
