### ISSUE TITLE
lsp-bridge-peek-mode with errors

### ISSUE THREAD

**Issue by gchape** [manateelazycat/lsp-bridge#979]
The following error occurs when I try to activate peek-mode.  
```
Lsp-Bridge-Peek mode enabled in current buffer
Error in post-command-hook (lsp-bridge-peek--show): (wrong-type-argument integerp nil)
```

Error causes the cursor to freeze, and it accumulates with each movement: `Wrong type argument: integerp, nil [10 times]`

**Comment by manateelazycat** [comment]
M-x toggle-debug-on-error

And paste `*backtrace*` content to me, thanks!

**Comment by gchape** [comment]
`Debugger entered--Lisp error: (wrong-type-argument integerp nil)
  nth(nil nil)
  (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
  (if (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree)) (if (nth 5 (nth (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree)) lsp-bridge-peek-symbol-tree)) (progn (setq already-changed nil) (if (or (< (+ num (nth 5 ...)) 0) (> (+ num (nth 5 ...)) (1- (length ...)))) nil (let* ((c (nthcdr 5 ...))) (setcar c (+ num (nth 5 ...)))) (setq already-changed t)) (if already-changed nil (if (< (+ num (nth 5 ...)) 0) (progn (let* (...) (setcar c ...)) (setq already-changed t)))) (if already-changed nil (if (> (+ num (nth 5 ...)) (1- (length ...))) (let* ((c ...)) (setcar c 0)))) (setq lsp-bridge-peek-selected-symbol (nth (nth 5 (nth (nth 3 ...) lsp-bridge-peek-symbol-tree)) (nth 4 (nth (nth 3 ...) lsp-bridge-peek-symbol-tree)))) (setq lsp-bridge-peek--content-update t))))
  lsp-bridge-peek-tree-change-branch(-1)
  lsp-bridge-peek-tree-next-branch()
  funcall-interactively(lsp-bridge-peek-tree-next-branch)
  command-execute(lsp-bridge-peek-tree-next-branch)
`

**Comment by gchape** [comment]
`Debugger entered--Lisp error: (wrong-type-argument integerp nil)
  nth(nil nil)
  (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
  (if (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
      (if (nth 5 (nth (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
                     lsp-bridge-peek-symbol-tree))
          (progn
            (setq already-changed nil)
            (if (or (< (+ num (nth 5 ...)) 0)
                    (> (+ num (nth 5 ...)) (1- (length ...))))
                nil
              (let* ((c (nthcdr 5 ...)))
                (setcar c (+ num (nth 5 ...))))
              (setq already-changed t))
            
            (if already-changed
                nil
              (if (< (+ num (nth 5 ...)) 0)
                  (progn
                    (let* (...) (setcar c ...))
                    (setq already-changed t)))))
          
          (if already-changed
              nil
            (if (> (+ num (nth 5 ...)) (1- (length ...)))
                (let* ((c ...))
                  (setcar c 0))))
          
          (setq lsp-bridge-peek-selected-symbol
                (nth (nth 5 (nth (nth 3 ...) lsp-bridge-peek-symbol-tree))
                     (nth 4 (nth (nth 3 ...) lsp-bridge-peek-symbol-tree))))
          
          (setq lsp-bridge-peek--content-update t)))
  
  lsp-bridge-peek-tree-change-branch(-1)
  lsp-bridge-peek-tree-next-branch()
  funcall-interactively(lsp-bridge-peek-tree-next-branch)
  command-execute(lsp-bridge-peek-tree-next-branch)
`

**Comment by gchape** [comment]
Debugger entered--Lisp error: (wrong-type-argument integerp nil)
  nth(nil nil)
  (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
 ```
 (if (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
      (if (nth 5 (nth (nth 3 (nth lsp-bridge-peek-selected-symbol lsp-bridge-peek-symbol-tree))
                     lsp-bridge-peek-symbol-tree))
          (progn
            (setq already-changed nil)
            (if (or (< (+ num (nth 5 ...)) 0)
                    (> (+ num (nth 5 ...)) (1- (length ...))))
                nil
              (let* ((c (nthcdr 5 ...)))
                (setcar c (+ num (nth 5 ...))))
              (setq already-changed t))
            
            (if already-changed
                nil
              (if (< (+ num (nth 5 ...)) 0)
                  (progn
                    (let* (...) (setcar c ...))
                    (setq already-changed t)))))
          
          (if already-changed
              nil
            (if (> (+ num (nth 5 ...)) (1- (length ...)))
                (let* ((c ...))
                  (setcar c 0))))
          
          (setq lsp-bridge-peek-selected-symbol
                (nth (nth 5 (nth (nth 3 ...) lsp-bridge-peek-symbol-tree))
                     (nth 4 (nth (nth 3 ...) lsp-bridge-peek-symbol-tree))))
          
          (setq lsp-bridge-peek--content-update t)))
```
  
  lsp-bridge-peek-tree-change-branch(-1)
  lsp-bridge-peek-tree-next-branch()
  funcall-interactively(lsp-bridge-peek-tree-next-branch)
  command-execute(lsp-bridge-peek-tree-next-branch)

**Comment by AllTheLife** [comment]
I guess this error is caused by `lsp-bridge-peek-define--return` receiving too many arguments

I pushed https://github.com/manateelazycat/lsp-bridge/pull/982 to try to fix this, and it worked on my computer. I hope it solves your problem.

Have fun :)
