### ISSUE TITLE
completion not working on windows with doomemacs

### ISSUE THREAD

**Issue by Yousuf28** [manateelazycat/lsp-bridge#986]
Thanks for the package, Its really fast.
I have used lsp-bridge before for python in my old windows laptop. I got new windows laptop and set up the same way.
I got following error

``` 
error: Wrong type argument: lsp-bridge-epc-manager, nil
```
And it does not suggest autocomplete in python.
I have tried fresh doomemacs installation and still got the same error.
Would appreciate any help.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge#report-bug

**Comment by Yousuf28** [comment]
@manateelazycat Thanks for pointing me in right direction. So what happened is that I have msys2 installed and another version of python installed  using msys2. Rather than starting windows main python, emacs was starting msys2 python. Now I remove the PATH of msys's /usr/bin from my $PATH variable and everything working fine.
