### ISSUE TITLE
Rust mode does not show expected  diagnostic info

### ISSUE THREAD

**Issue by HarumiKiyama** [manateelazycat/lsp-bridge#990]
#  Emacs config
```elisp
(package-initialize)
(add-to-list 'load-path "~/.emacs.d/elpa/lsp-bridge")
(require 'yasnippet)
(yas-global-mode 1)
(require 'lsp-bridge)
(setq lsp-bridge-enable-log nil)
(global-lsp-bridge-mode)
```
# rust main.rs
```rust
fn test(x :i32){
    
}

fn main() {
    println!("Hello, world!");
}

```
It suppose to show diagnostic on `fn test(x :i32){` for not used variable x, and not used function test, But not.
Use `rust-analyzer` directly in terminal, `rust-analyzer diagnostics test_rust/main.rs ` got response: 

 Diagnostic { code: RustcLint(“unused_variables”), message: “unused variable”, range: FileRange { file_id: FileId(11), range: 8…9 }, severity: Warning, unused: false, experimental: true, fixes: Some([Assist { id: AssistId(“unscore_unused_variable_name”, QuickFix), label: “Rename unused x to _x”, group: None, target: 8…9, source_change: Some(SourceChange { source_file_edits: {FileId(11): (TextEdit { indels: [Indel { insert: “_x”, delete: 8…9 }] }, None)}, file_system_edits: , is_snippet: false }), trigger_signature_help: false }]), main_node: Some(InFileWrapper { file_id: FileId(11), value: SyntaxNodePtr { kind: IDENT_PAT, range: 8…9 } }) }

**Comment by manateelazycat** [comment]
rust lsp server 确实没有返回诊断信息， 和rust命令行效果不一样

**Comment by HarumiKiyama** [comment]
> rust lsp server 确实没有返回诊断信息， 和rust命令行效果不一样

I have figured out finally. In langserver/rust-analyzer.json got 
```json
    "checkOnSave": {
      "enable": true,
      "allTargets": true,
      "features": "all",
      "invocationLocation": "root",
      "invocationStrategy": "once"
    }
```
so, `rust-analyzer` will not use `cargo check` to get the  extra diagnostics info.

I'm not sure why checkOnSave was disabled.

**Comment by manateelazycat** [comment]
默认打开了 https://github.com/manateelazycat/lsp-bridge/commit/82580331a736290f106f455efda130ecf56ad5b4

主要是被开发者关闭的， https://github.com/manateelazycat/lsp-bridge/commit/7c4c7926cda7830113a49cd274c62aa620d34050

众口难调哇
