### ISSUE TITLE
Win10行安装后报错： No compression program defined

### ISSUE THREAD

**Issue by nasoundead** [manateelazycat/lsp-bridge#992]
配置如下：
(use-package lsp-bridge
  :straight '(lsp-bridge :type git :host github :repo "manateelazycat/lsp-bridge"
            :files (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
            :build (:not compile))
  :init
  (global-lsp-bridge-mode))

已知7z.exe在PATH目录下。
从这个讨论组来的：https://emacs-china.org/t/lsp-bridge-dz/26474/14。问题没人回复，求助下大佬。

**Comment by manateelazycat** [comment]
不用windows，没法帮你，抱歉
