### ISSUE TITLE
completion word from a file

### ISSUE THREAD

**Issue by Yousuf28** [manateelazycat/lsp-bridge#996]
Let's say I  have a file with some words in each line e.g.
Banana
Mango
Apple
Is it possible get completion suggestion in a specific major mode from that file?

Similar to following one?

https://github.com/hlissner/emacs-company-dict/tree/master

Thanks

**Comment by manateelazycat** [comment]
Should write new backend like https://github.com/manateelazycat/lsp-bridge/blob/023924926ae6adfbcf5458c350b90dea7c05d51b/core/search_sdcv_words.py#L1

**Comment by manateelazycat** [comment]
@Yousuf28 You can give me your dict file, I will try to show some example

**Comment by Yousuf28** [comment]
Here is one dictionary.
https://github.com/redguardtoo/emacs.d/blob/e9c656592d5ad89ee008764903972d0aeda2339b/misc/english-words.txt

**Comment by manateelazycat** [comment]
why not use lsp-bridge-toggle-sdcv-helper ？
