### ISSUE TITLE
basedpyright_ruff issue

### ISSUE THREAD

**Issue by nohzafk** [manateelazycat/lsp-bridge#997]
devcontainer-feature-emacs-lsp-bridge now supports using the system Python if it's avaible, instead of using python from nix.

This is python lsp working inside a container, I want to report and discuss an issue here, to see if anyone else has the same problem when using python lsp locally.

When usign **basedpyright** as the language server, it works fine

However, when I switch to using **basedpyright_ruff**, the popup menu occasionally fails to appear, and Ruff displays errors throughout the code. I suspect this might be due to Ruff LSP performing too aggressively (it's incredibly fast), while basedpyright is comparatively slower.

Has anyone else experienced a similar issue?

Using basedpyright is good, but basedpyright_ruff sometimes has trouble (it is not consistently working)

<img width="397" alt="Screenshot 2024-07-25 at 5 11 08 PM" src="https://github.com/user-attachments/assets/4432e26f-d27d-4e6a-b824-2ff3594f18f6">

**Comment by manateelazycat** [comment]
不在容器内，在本地也会发生错误？
