### ISSUE TITLE
dart中import无法补全库名称

### ISSUE THREAD

**Issue by DanielLiuCD** [manateelazycat/lsp-bridge#998]
我目前使用的是emacs29.4, 大部分都是正常，但是dart的库文件无法补全。我尝试了lsp-mode可以成功补全。尝试修改过dart的json文件，但是没有效果

**Comment by manateelazycat** [comment]
需要给测试代码， 如果 lsp-mode 可以补全成功， 最好把对应的日志发送过来会有帮助， 一般都是给 LSP Server 配置的 init 消息没有配置对， 或者对 workspace/configuration 消息的回应不对。

**Comment by DanielLiuCD** [comment]
> 需要给测试代码， 如果 lsp-mode 可以补全成功， 最好把对应的日志发送过来会有帮助， 一般都是给 LSP Server 配置的 init 消息没有配置对， 或者对 workspace/configuration 消息的回应不对。

[helper.tar.gz](https://github.com/user-attachments/files/16394383/helper.tar.gz)

这下面的是lsp-bridge buffer输出内容：
`
--- [00:33:47.971704] Recv textDocument/signatureHelp response (42038) from 'dart-analysis-server' for project helper

--- [00:33:48.246376] Send textDocument/didChange notification to 'dart-analysis-server' for project helper

--- [00:33:48.249110] Send textDocument/didChange notification to 'dart-analysis-server' for project helper

--- [00:33:48.250756] Recv window/workDoneProgress/create request (49) from 'dart-analysis-server' for project helper

--- [00:33:48.250891] Send response to server request 49 to 'dart-analysis-server' for project helper

--- [00:33:48.251194] Recv dart/textDocument/publishClosingLabels notification from 'dart-analysis-server' for project helper

--- [00:33:48.251483] Recv $/progress notification from 'dart-analysis-server' for project helper

--- [00:33:48.255653] Recv dart/textDocument/publishClosingLabels notification from 'dart-analysis-server' for project helper

--- [00:33:48.256818] Recv $/progress notification from 'dart-analysis-server' for project helper

--- [00:33:48.354119] Send textDocument/completion request (31507) to 'dart-analysis-server' for project helper

--- [00:33:48.355392] Recv textDocument/completion response (31507) from 'dart-analysis-server' for project helper

--- [00:33:48.355427] Got completion candidates (0) from 'dart-analysis-server' for file helper.dart

--- [00:33:48.355440] Record completion candidates (0) from 'dart-analysis-server' for file helper.dart

--- [00:33:48.755489] Send textDocument/signatureHelp request (17569) to 'dart-analysis-server' for project helper

--- [00:33:48.756579] Recv textDocument/signatureHelp response (17569) from 'dart-analysis-server' for project helper

--- [00:33:49.468292] Send textDocument/formatting request (20808) to 'dart-analysis-server' for project helper

--- [00:33:49.470593] Send textDocument/didSave notification to 'dart-analysis-server' for project helper

--- [00:33:49.472226] Recv window/showMessage notification from 'dart-analysis-server' for project helper

--- [00:33:49.472402] Recv textDocument/formatting response (20808) from 'dart-analysis-server' for project helper

--- [00:33:49.583233] Recv window/workDoneProgress/create request (50) from 'dart-analysis-server' for project helper

--- [00:33:49.583700] Send response to server request 50 to 'dart-analysis-server' for project helper

--- [00:33:49.584760] Recv $/progress notification from 'dart-analysis-server' for project helper

--- [00:33:49.585224] Recv $/progress notification from 'dart-analysis-server' for project helper

--- [00:33:54.440051] Recv window/workDoneProgress/create request (51) from 'dart-analysis-server' for project helper

--- [00:33:54.440155] Send response to server request 51 to 'dart-analysis-server' for project helper

--- [00:33:54.440425] Recv $/progress notification from 'dart-analysis-server' for project helper

--- [00:33:54.440580] Recv $/progress notification from 'dart-analysis-server' for project helper
`

**Comment by DanielLiuCD** [comment]
> > 需要给测试代码， 如果 lsp-mode 可以补全成功， 最好把对应的日志发送过来会有帮助， 一般都是给 LSP Server 配置的 init 消息没有配置对， 或者对 workspace/configuration 消息的回应不对。
> 
> [helper.tar.gz](https://github.com/user-attachments/files/16394383/helper.tar.gz)
> 
> 这下面的是lsp-bridge buffer输出内容： ` --- [00:33:47.971704] Recv textDocument/signatureHelp response (42038) from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.246376] Send textDocument/didChange notification to 'dart-analysis-server' for project helper
> 
> --- [00:33:48.249110] Send textDocument/didChange notification to 'dart-analysis-server' for project helper
> 
> --- [00:33:48.250756] Recv window/workDoneProgress/create request (49) from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.250891] Send response to server request 49 to 'dart-analysis-server' for project helper
> 
> --- [00:33:48.251194] Recv dart/textDocument/publishClosingLabels notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.251483] Recv $/progress notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.255653] Recv dart/textDocument/publishClosingLabels notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.256818] Recv $/progress notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.354119] Send textDocument/completion request (31507) to 'dart-analysis-server' for project helper
> 
> --- [00:33:48.355392] Recv textDocument/completion response (31507) from 'dart-analysis-server' for project helper
> 
> --- [00:33:48.355427] Got completion candidates (0) from 'dart-analysis-server' for file helper.dart
> 
> --- [00:33:48.355440] Record completion candidates (0) from 'dart-analysis-server' for file helper.dart
> 
> --- [00:33:48.755489] Send textDocument/signatureHelp request (17569) to 'dart-analysis-server' for project helper
> 
> --- [00:33:48.756579] Recv textDocument/signatureHelp response (17569) from 'dart-analysis-server' for project helper
> 
> --- [00:33:49.468292] Send textDocument/formatting request (20808) to 'dart-analysis-server' for project helper
> 
> --- [00:33:49.470593] Send textDocument/didSave notification to 'dart-analysis-server' for project helper
> 
> --- [00:33:49.472226] Recv window/showMessage notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:49.472402] Recv textDocument/formatting response (20808) from 'dart-analysis-server' for project helper
> 
> --- [00:33:49.583233] Recv window/workDoneProgress/create request (50) from 'dart-analysis-server' for project helper
> 
> --- [00:33:49.583700] Send response to server request 50 to 'dart-analysis-server' for project helper
> 
> --- [00:33:49.584760] Recv $/progress notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:49.585224] Recv $/progress notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:54.440051] Recv window/workDoneProgress/create request (51) from 'dart-analysis-server' for project helper
> 
> --- [00:33:54.440155] Send response to server request 51 to 'dart-analysis-server' for project helper
> 
> --- [00:33:54.440425] Recv $/progress notification from 'dart-analysis-server' for project helper
> 
> --- [00:33:54.440580] Recv $/progress notification from 'dart-analysis-server' for project helper `


https://github.com/user-attachments/assets/8125d705-a05d-45d6-9960-f6611af9096d

**Comment by manateelazycat** [comment]
已经修复了 https://github.com/manateelazycat/lsp-bridge/commit/22685dbd2c4e1d2d4903d191d077069cd3aded40

lsp-bridge 默认是不允许在字符串里面补全的， 避免用户写字符串的时候干扰用户， 但是 dart 的 import 语法是在字符串中的， 所以会导致无法补全。

感谢反馈。

**Comment by DanielLiuCD** [comment]
> 已经修复了 [22685db](https://github.com/manateelazycat/lsp-bridge/commit/22685dbd2c4e1d2d4903d191d077069cd3aded40)
> 
> lsp-bridge 默认是不允许在字符串里面补全的， 避免用户写字符串的时候干扰用户， 但是 dart 的 import 语法是在字符串中的， 所以会导致无法补全。
> 
> 感谢反馈。

能告诉我你如何查找问题的过程吗？我也想尝试修复使用过程中的问题

**Comment by manateelazycat** [comment]
打开日志 (setq lsp-bridge-enable-log t)， 当 lsp-bridge 不能正常工作的时候， 通过日志 `*lsp-birdge*` buffer 可以看到为什么不工作的原因。

**Comment by DanielLiuCD** [comment]
gdb在macbook m3上无法安装，请问是否有办法将gdb修改为lldb

**Comment by manateelazycat** [comment]
源代码搜索gdb吧，我不用mac
